shader-slang/slang

.github/workflows/windows-selfhosted.yml, deps/target-deps.json, github_test.sh, source/core/slang-process.h, source/core/unix/slang-unix-process.cpp, source/core/windows/slang-win-process.cpp, source/slang/slang-check-decl.cpp, source/slang/slang-check-overload.cpp, source/slang/slang-emit-glsl.cpp, source/slang/slang-ir-inline.cpp, source/slang/slang-ir-lower-buffer-element-type.cpp, source/slang/slang-ir-specialize-resources.cpp, tests/bugs/ray-query-in-generic.slang, tests/expected-failure-linux.txt, tests/hlsl-intrinsic/shader-execution-reordering/hit-object-make-hit.slang.1.expected, tests/hlsl-intrinsic/shader-execution-reordering/hit-object-output.slang.1.expected, tests/hlsl-intrinsic/shader-execution-reordering/hit-object-reorder-thread.slang.1.expected, tests/hlsl-intrinsic/shader-execution-reordering/hit-object-trace-motion-ray.slang.1.expected, tests/hlsl-intrinsic/shader-execution-reordering/hit-object-trace-ray.slang.1.expected, tools/gfx-unit-test/copy-texture-tests.cpp, tools/gfx-unit-test/shader-cache-tests.cpp, tools/slang-test/slang-test-main.cpp, tools/slang-test/test-context.h, tools/slang-unit-test/unit-test-lock-file.cpp, tools/slang-unit-test/unit-test-persistent-cache.cpp, tools/slang-unit-test/unit-test-translation-unit-import.cpp
GLSL does not allow copying these objects. To work around with this limitation, we always make `RayQuery` type appear as `__ref` parameter (if not defined, automatically inserts the qualifier). Then we translate all `__ref` parameters to GLSL with the `spirv_by_reference` qualifier.
Also in this PR:
- Update slang-llvm.
- Run tests in parallel, fix multiple unit tests that writes files such that they use a process-id dependent filename to avoid conflicts.
- Simplify the texture copy unit tests to not test on all formats to save time.
=> Fix GLSL code gen around RayQuery and HitObject types.

source/slang/hlsl.meta.slang, source/slang/slang-ast-expr.h, source/slang/slang-ast-iterator.h, source/slang/slang-ast-type.cpp, source/slang/slang-ast-type.h, source/slang/slang-check-expr.cpp, source/slang/slang-check-impl.h, source/slang/slang-diagnostic-defs.h, source/slang/slang-emit-c-like.cpp, source/slang/slang-emit-c-like.h, source/slang/slang-emit-glsl.cpp, source/slang/slang-emit-glsl.h, source/slang/slang-emit-hlsl.cpp, source/slang/slang-emit-hlsl.h, source/slang/slang-ir-specialize-resources.cpp, source/slang/slang-lower-to-ir.cpp, source/slang/slang-parser.cpp, tests/bindings/hlsl-to-vulkan-shift-rw-structured.hlsl, tests/hlsl-intrinsic/shader-execution-reordering/hit-object-assign.slang, tests/hlsl-intrinsic/shader-execution-reordering/hit-object-make-hit.slang, tests/hlsl-intrinsic/shader-execution-reordering/hit-object-make-miss.slang, tests/hlsl-intrinsic/shader-execution-reordering/hit-object-make-nop.slang, tests/hlsl-intrinsic/shader-execution-reordering/hit-object-output.slang, tests/hlsl-intrinsic/shader-execution-reordering/hit-object-reorder-thread.slang, tests/hlsl-intrinsic/shader-execution-reordering/hit-object-trace-motion-ray.slang, tests/hlsl-intrinsic/shader-execution-reordering/hit-object-trace-ray.slang, tests/language-feature/non-copyable-return.slang, tests/pipeline/ray-tracing/trace-ray-inline.slang.hlsl
Use destination driven lowering to get rid of temp var copies when working with functions that returns a non-copyable object.
Fixes HitObject API issues on Vulkan.
Added lowering logic for functions that return non-copyable objects:
```
NonCopyable myFunc(T x, U y);
```
Lowers into
```
void myFunc(T x, U y, __ref NonCopyable __return_val);
```
Assignments and initializations are handled accordingly to generate callsites that match this function signature.
Returns are lowered into writes into the `__return_val` parameter.
The `__return_val` parameter is also made available for functions that return non-copyable objects in user code, so it is valid to write:
```
NonCopyable myFunc()
{
__return_val = otherFunc();
// do some other things before returning
...
}
```
With this changes, we can …
=> Proper lowering of functiosn that returns NonCopyable values.

source/slang/slang-check-overload.cpp, source/slang/slang-diagnostic-defs.h, tests/diagnostics/param-mutation.slang, tests/diagnostics/param-mutation.slang.expected
#3067 added checking such that an error is produced if a [mutating] method is called on an `in` parameter.
The change was added to make it an error on 'NonCopyable' types, but was also an error on copyable types too. This change makes it an error on NonCopyable type as was the original intention, and a warning otherwise. The NonCopyable scenario is not triggerable currently as NonCopyable types are also implicitly passed as `ref`. The support for emitting an error is left here though as that behavior might change.
=> Make a warning if a [mutating] method is called on an in param.

docs/command-line-slangc-reference.md, source/compiler-core/slang-dxc-compiler.cpp, source/core/slang-file-system.h, source/slang/slang-compiler.cpp, source/slang/slang-compiler.h, source/slang/slang-options.cpp, source/slang/slang-repro.cpp, source/slang/slang-repro.h
The motivation here is when using a repro which requires access to includes to complete, which weren't captured. For example if using implicit `NVAPI`, the NVAPI header includes are inserted into downstream output. The option allows specifying a falback directory or disabling (if fallback isn't required). This could also allow splitting a repro.
* Put repro options into repro category
* Added `-repro-fallback-directory` option
* Support `none:` and `default:` special directories
=> Add -repro-fallback-directory option

source/slang/slang-ast-support-types.h, source/slang/slang-check-constraint.cpp, source/slang/slang-check-conversion.cpp, source/slang/slang-check-impl.h, source/slang/slang-check-overload.cpp, tests/language-feature/overload-resolution.slang
Our existing overload resolution logic does not respect the l-value-ness of implicit conversions, this leads to issues such as:
```
int f(inout int a, int b) {...}
int f(inout uint a, uint b) {...}
uint a = 0;
int b =  1;
f(a, b);
```
Because it is cheaper to cast `uint` to `int`, our resolution logic will pick the first overload which leads to a surprising l-value cast.
To address this issue, we must propagate the l-value-ness of parameter types to various places of our overload resolution logic and add an extra cost whenever an implicit cast on l-value is ocurred. This will allow the compiler to pick the second overload.
Note that we need to handle the generic case as well:
```
T f<T:BuiltinIntegerType>(inout T a, T b) {...}
uint a = 0;
int b =  1;
f(a, b); // should resolve to T<uint> …
```
=> Incur l-value conversion cost during overload resolution.

source/slang/hlsl.meta.slang, source/slang/slang-ast-modifier.h, source/slang/slang-check-expr.cpp, source/slang/slang-check-modifier.cpp, source/slang/slang-language-server-ast-lookup.cpp, source/slang/slang-language-server-semantic-tokens.cpp, source/slang/slang-language-server.cpp, source/slang/slang-parser.cpp, tests/diagnostics/vk-bindings.slang.expected, tests/spirv/spirv-instruction.slang
Fix highlighting issues around attributes that are qualified with `::`, e.g. `[[vk::attributeName]]`.
Fix a type checking crash causing https://github.com/shader-slang/slang-vscode-extension/issues/5
Fix spirv wave intrinsics.
=> Fix attribute highlighting + language server crash.

prelude/slang-torch-prelude.h
Otherwise, this can lead to undetected scenarios where the strides are incorrect for non-scalar types (`float2`, `float3`, etc..)
Users must call `tensor = tensor.contiguous()` on the inputs to avoid this error.
=> Add check for contiguous tensors

source/slang/slang-emit-spirv.cpp, tests/expected-failure.txt
Still TODO: emit a diagnostic when a use of a memoized value precedes its definition.
=> Memoize types in spirv asm blocks

source/slang/core.meta.slang, source/slang/slang-emit-c-like.cpp, source/slang/slang-ir-address-analysis.cpp, source/slang/slang-ir-autodiff-fwd.cpp, source/slang/slang-ir-autodiff-unzip.cpp, source/slang/slang-ir-autodiff.cpp, source/slang/slang-ir-check-differentiability.cpp, source/slang/slang-ir-constexpr.cpp, source/slang/slang-ir-inst-defs.h, source/slang/slang-ir-insts.h, source/slang/slang-ir-link.cpp, source/slang/slang-ir-peephole.cpp, source/slang/slang-ir-pytorch-cpp-binding.cpp, source/slang/slang-ir-sccp.cpp, source/slang/slang-ir-simplify-cfg.cpp, source/slang/slang-ir-ssa-register-allocate.cpp, source/slang/slang-ir-util.cpp, source/slang/slang-ir-validate.cpp, source/slang/slang-ir.cpp, source/slang/slang-ir.h, tests/autodiff/modify-vector-param.slang
- Make dynamic cast transparent through `IRAttributedType`.
- Handle vector type in `castHostToCUDAType`.
- Fix bug in tuple type marshaling.
- Place cuda kernels in `extern "C"` block to get rid of CUDA<->C++ linkage issue.
=> Various slangpy fixes.

source/slang/slang-emit.cpp, source/slang/slang-ir-autodiff-fwd.cpp, source/slang/slang-ir-autodiff-rev.cpp, source/slang/slang-ir-inline.cpp
#3217 causes a performance regression.
This change reverts the change to do pervasive inlining, instead it checks if the callee has fwd_diff and bwd_diff insts and don't inline if they have those insts during `performPreAutoDiffInlining` to avoid the problem that the autodiff pass cannot handle a function  that has unprocessed fwd_diff or bwd_diff insts.
=> Revert inlining change in #3217.

source/slang/slang-ast-base.cpp, source/slang/slang-ast-builder.cpp, source/slang/slang-compiler.h
Multhreading is discussed in [docs](https://github.com/shader-slang/slang/blob/master/docs/api-users-guide.md#multithreading).
The epoch id broke the behavior though because the model allowed for a global session to be used from different threads, but it could only be used exclusively by one at a time. The epoch was being held in a thread local variable, which meant if the a compilation moved to a different thread the epoch would become that which was associated with that thread, which is likely inconsistent with the epochs set.
=> Fix for threading issues around global session & epoch ids.

source/slang/slang-ast-base.cpp, source/slang/slang-serialize-ast.cpp, source/slang/slang-serialize-container.cpp, source/slang/slang.cpp
Previously these tests were failing...
tests/serialization/serialized-module-test.slang
tests/serialization/extern/extern-test.slang
The issue is around the thread_local mechanism holding the current ASTBuilder. This wasn't being setup for a couple of scenarios that were being hit. The fix is to setup the thread_local for these scenarios using `SetASTBuilderContextRAII `
The other problem was around embed-stdlib. There the problem was that the sharedASTBuilder was being destroyed before the ASTBuilder on the Session. This led to a dangling pointer being accessed by the dtor of ASTBuilder. The fix was just to destroy the ASTBuilder before anything else.
=> Fix for epoch/ASTBuilder* nullptr issue

source/slang/slang-ir.cpp
A `[NoSideEffect]` callee isn't movable, but it should be safe to move `[ReadNone]` callees.
=> Fix `isMovableInst`.

source/slang/hlsl.meta.slang, source/slang/slang-emit-c-like.cpp, source/slang/slang-emit-c-like.h, source/slang/slang-emit-glsl.cpp, source/slang/slang-emit-spirv.cpp, source/slang/slang-intrinsic-expand.cpp, source/slang/slang-ir-glsl-legalize.cpp, source/slang/slang-ir-inst-defs.h, source/slang/slang-ir-lower-buffer-element-type.cpp, source/slang/slang-ir-specialize-target-switch.cpp, source/slang/slang-ir-spirv-legalize.cpp, source/slang/slang-ir-util.cpp, tests/vkray/closesthit.slang, tests/vkray/entry-point-params.slang, tests/vkray/intersection.slang, tests/vkray/raygen.slang
Add intrinsics for ray tracing API.
Translate StorageClass for ray payload, callable payload, shader record and hit object atttributes.
Replace the target_intrinsic expansion logic of "XC", "XP" and "XH" with an actual `IROp_GetVulkanRayTracingPayloadLocation` instruction and handle it during legalization passes.
=> [Direct SPIRV]: ray tracing pipeline intrinsics.

source/slang/hlsl.meta.slang, source/slang/slang-compiler.h, source/slang/slang-emit-spirv-ops.h, source/slang/slang-emit-spirv.cpp, source/slang/slang-ir-inst-defs.h, source/slang/slang-ir-insts.h, source/slang/slang-ir-lower-buffer-element-type.cpp, source/slang/slang-ir-simplify-for-emit.cpp, source/slang/slang-ir-specialize-resources.cpp, source/slang/slang-ir-specialize-resources.h, source/slang/slang-ir-spirv-legalize.cpp, source/slang/slang-ir.cpp, source/slang/slang-spirv-val.cpp, tests/cross-compile/rw-buffer.slang, tests/hlsl-intrinsic/shader-execution-reordering/hit-object-assign.slang, tests/hlsl-intrinsic/shader-execution-reordering/hit-object-make-hit.slang, tests/hlsl-intrinsic/shader-execution-reordering/hit-object-make-miss.slang, tests/hlsl-intrinsic/shader-execution-reordering/hit-object-make-nop.slang, tests/hlsl-intrinsic/shader-execution-reordering/hit-object-output.slang, tests/hlsl-intrinsic/shader-execution-reordering/hit-object-reorder-thread.slang, tests/hlsl-intrinsic/shader-execution-reordering/hit-object-trace-motion-ray.slang, tests/hlsl-intrinsic/shader-execution-reordering/hit-object-trace-ray.slang, tests/spirv/bool-vector.slang, tools/gfx/d3d12/d3d12-shader-object.cpp
Fixes #3238.
Fixes #3253.
- Specialize all resource uses to get rid of image type mismatch issues.
- Inline global values at function-local use sites.
- float != lowers to FUnordNotEqual instead of FOrdNotEqual.
- Marshal bool vector type to uint vectors.
- Add intrinsics for ShaderExecutionReordering and Buffer/RWBuffer.
- Fix out-of-bound write in d3d shader object implementation when handling root parameters.
=> Add SPIRV intrinsics for ShaderExecutionReordering and RW/Buffer.

source/slang/slang-check-decl.cpp, source/slang/slang-emit-glsl.cpp, source/slang/slang-emit-spirv.cpp, source/slang/slang-ir-array-reg-to-mem.cpp, source/slang/slang-ir-glsl-legalize.cpp, source/slang/slang-ir-spirv-legalize.cpp, source/slang/slang-ir-util.cpp, source/slang/slang-ir-util.h, source/slang/slang-lower-to-ir.cpp, tests/spirv/mutating-method-syn.slang, tools/gfx/vulkan/vk-api.h, tools/gfx/vulkan/vk-device.cpp
- Properly synthesize mutating conformance methods from non-mutating implementations.
- Infer image type for arrays of images.
- Keep `GetVulkanPayloadLocation` insts instead of replacing them with the literal location in order to keep the original global variable definition alive.
=> More direct-SPIRV fixes.

source/core/slang-string-util.cpp, source/core/slang-string-util.h, source/slang/slang-check-expr.cpp, source/slang/slang-ir-check-differentiability.cpp, source/slang/slang-ir-util.h, source/slang/slang-ir.cpp, source/slang/slang-language-server-completion.cpp, source/slang/slang-language-server.cpp, source/slang/slang-language-server.h, tests/diagnostics/property-readonly-lvalue.slang
- Fix emitElementAddr() on attributed/rate types.
- Add diagnostic on using a read-only property as l-value.
- Properly recognize differentiablity of a custom provided derivative function referenced via `fwd_diff(f)` or `bwd_diff(f)`.
- Perform `${workspaceFolder}` macro replacement in clang-format-location settings in language server.
=> Small type system fixes.

source/slang/core.meta.slang, source/slang/slang-ast-base.cpp, source/slang/slang-ast-base.h, source/slang/slang-ast-builder.h, source/slang/slang-ast-decl-ref.cpp, source/slang/slang-ast-type.cpp, source/slang/slang-ast-type.h, source/slang/slang-check-constraint.cpp, source/slang/slang-check-decl.cpp, source/slang/slang-check-expr.cpp, source/slang/slang-check-impl.h, source/slang/slang-diagnostic-defs.h, source/slang/slang-emit-spirv.cpp, source/slang/slang-ir-inst-pass-base.h, source/slang/slang-ir-insts.h, source/slang/slang-ir.cpp, source/slang/slang-lower-to-ir.cpp, source/slang/slang-mangle.cpp, source/slang/slang-parser.cpp, source/slang/slang-syntax.cpp, source/slang/slang-syntax.h, tests/language-feature/generics/generic-interface-1.slang, tests/language-feature/generics/iarray.slang
Add the `IArray<T>` interface to stdlib to allow writing generic functions on array-like types.
`Array`, `vector` and `matrix` types are modified to implement `IArray`.
Major changes in this PR are:
- Enabling `subscript` operators in interfaces
- Allow generic type argument inference to structurally match base types, so that functions like `void test<T>(IArray<T> array)` can be called with `test(Array<float,3>())`, although `Array<float,3>` can't structurally match `IArray<T>`, we should still be able to infer `T` because `Array<float,3>:IArray<float>`.
=> Add `IArray`.

source/slang/slang-ir-autodiff-fwd.cpp, source/slang/slang-ir-autodiff-fwd.h, source/slang/slang-ir-autodiff-transpose.h, source/slang/slang-ir-util.cpp, source/slang/slang-ir-util.h, tests/autodiff/no-diff-out.slang
The problem we are fixing here is that if we have a block accepting a phi parameter that is `no_diff`, and the block that computes the phi argument is differentiable, then after forward-mode transcription we could end up with a `branch` inst with a diff argument into a block that doesn't have a phi parameter.
The fix is to check the differentiability of the phi parameter type and provide the argument accordingly.
=> Fix crash when writing to `no_diff` out parameter.

source/slang/slang-check-decl.cpp, source/slang/slang-check-impl.h, source/slang/slang-diagnostic-defs.h, tests/autodiff/custom-derivative-generic.slang
- Add support for using `[*DerivativeOf()]` on a member function of a generic type to refer to another member function of the same type as the original function.
- Add diagnostic on trying to refer a member function of a different outer generic type in [*DerivativeOf] attribute.
- Add diagnostic on trying to use a member function of a different type as the derivative of some non-static member function.
- Add diagnostic on trying to use [*Derivative] attribute on a member function of a differentiable type. This is not allowed because there is no way to specify the transformed `this` parameter.
=> Add more diagnostics on invalid custom derivative use.

source/slang/slang-check-decl.cpp, source/slang/slang-check-expr.cpp, source/slang/slang-diagnostic-defs.h, source/slang/slang-emit-spirv-ops.h, source/slang/slang-emit-spirv.cpp, source/slang/slang-ir-glsl-legalize.cpp, source/slang/slang-language-server-ast-lookup.cpp, source/slang/slang-language-server-semantic-tokens.cpp, source/slang/slang-language-server.cpp, source/slang/slang-lower-to-ir.cpp, source/slang/slang-parser.cpp, tests/autodiff/derived-interface.slang, tests/diagnostics/interfaces/mutating-impl-of-non-mutating-req.slang.expected, tests/hlsl-intrinsic/image-swizzle-write.slang
- Diagnose when a method supposed to implement an interface requirement isn't marked as differentiable when the requirement is.
- Improve diagnostics on non-matching interface implementations to point to the mismatched implementation method instead of the inheritance decl, when the potential satisfying method is non-ambiguous.
- Lower an associatedtype declref from an interface into an `IRAssocType` even if the associated type is defined in the base interface to prevent ICE.
- Fixed a regression on GLSL/SPIRV image subscript swizzle write legalization.
- Improved language server highlighting and hinting around constructors and `this` expr.
- Fixed a language server crashing issue.
- Allow simplified generics syntax on constructors: `__init<T:IFoo>(T obj);`.
=> Fix ICE when lowering an associatedtype declref from an derived interface.

prelude/slang-cuda-prelude.h, source/compiler-core/slang-nvrtc-compiler.cpp
Hi Slang team! This merge request contains a few attempts to fix things I noticed while looking at the generated CUDA code for a `WaveActiveSum()` operation.
* Fixes mask ambiguity between the mask used for getting the lane index from `threadIdx.x` and the fast-path mask for a full mask of threads.
`SLANG_CUDA_WARP_MASK` (31) was used in two places: as the mask used in `_getLaneId()`:
```cuda
__forceinline__ __device__ uint32_t _getLaneId()
{
// ...
return threadIdx.x & SLANG_CUDA_WARP_MASK;
}
```
and as the test for the fast-path in `_waveCalcPow2Offset()`:
```cuda
__inline__ __device__ int _waveCalcPow2Offset(WarpMask mask)
{
// This should be the most common case, so fast path it
if (mask == SLANG_CUDA_WARP_MASK)
{
return SLANG_CUDA_WARP_SIZE; // nbickford note: This is 32
}
...
}
``` …
=> CUDA: Fixes for NVRTC 12.x and warp mask ambiguity; adds CC 8.x warp reduction intrinsics.

source/slang/slang-emit-spirv.cpp, source/slang/slang-ir-glsl-legalize.cpp, source/slang/slang-ir-inst-defs.h, source/slang/slang-ir-insts.h, source/slang/slang-ir-spirv-legalize.cpp, source/slang/slang-ir-translate-glsl-global-var.cpp, tests/glsl/flat-in-float.slang, tests/spirv/array-resource.slang
- Fix dropped `flat` qualifier when converting glsl global input.
- Fix spirv emit logic for unsized resource array parameters.
Fixes #3333.
=> GLSL/SPIRV Fixes.

source/slang/slang-options.cpp, tests/spirv/multi-entrypoint.slang
=> Allow whole program compile when using direct spirv backend.

source/slang/slang-ast-support-types.h, source/slang/slang-ast-val.cpp, source/slang/slang-ast-val.h, source/slang/slang-check-constraint.cpp, source/slang/slang-check-decl.cpp, source/slang/slang-check-impl.h, source/slang/slang-check-overload.cpp, source/slang/slang-check-resolve-val.cpp, tests/diagnostics/bad-operator-call.slang, tests/language-feature/generics/generic-overload-disambiguation.slang, tests/language-feature/generics/vector-generic.slang
Allow overload resolution to prefer generics with more specialized constraints.
Allow type inference to work when passing a scalar argument to a generic vector parameter.
=> Improve generic type argument inference.

source/slang/core.meta.slang, source/slang/glsl.meta.slang, source/slang/hlsl.meta.slang, source/slang/slang-check-modifier.cpp, tests/diagnostics/groupshared-local.slang, tests/diagnostics/int-texture-sample.slang
=> Define `Texture::Sample` for float element types only.

source/slang/hlsl.meta.slang, tests/cross-compile/vk-texture-indexing.slang
By updating the hlsl meta intrinsic for spirv path. Decorating the index that is input to NonUniformResourceIndex was getting removed by spirv-opt, when inlining as the decoration was applied to the function parameter. Thus the implementation was modified by introducing OpCopyObject that copies the object inside the function body of the meta builtin "NonUniformResourceIndex" and the decoration is applied to the result of OpCopyObject. With this approach SPIRV-OPt Inliner propagates decoration correctly.
=> Fix nonuniform decoration on direct-to-spirv backend path. (#3338)

source/slang/hlsl.meta.slang, source/slang/slang-emit.cpp, source/slang/slang-spirv-val.cpp, source/slang/slang-spirv-val.h
of result of OpLoad instruction was missing. This resulted in an incomplete OpLoad instruction getting generated causing spirv-val to report failure.
Also added dumping of spirv disassembly right after unoptimized spirv emission.
Fixes bug #3359
=> Fix the intrinsic expansion of ObjectToWorld3x4 in spirv_asm. Data type

source/slang/slang.cpp
Fix issue with entry point result not being available via `spGetEntryPointCodeBlob` if defined in a serialized module.
=> Fix inconsistency around entryPointCount, if entry point is defined in serialized module.

docs/design/stdlib-intrinsics.md, source/slang/hlsl.meta.slang
Adding float3 HitTriangleVertexPositions(uint) to slang stdlib to support GLSL gl_HitTriangleVertexPositionsEXT builtin variable under extension of GL_EXT_ray_tracing_position_fetch.
This function support emitting GLSL code and spir-V directly.
=> Support for gl_HitTriangleVertexPositionsEXT (#3405)

deps/target-deps.json
Update slang-glslang library download URL to the latest version (v13.0.0.x-h)
=> Update slang-glslang library

tests/vkray/anyhit.slang, tests/vkray/closesthit.slang
Add test to closesthit.slang to test the slang
stdlib API: HitTriangleVertexPosition.
The new test will add the checking for extension declaration, built-in declaration, and built-in variable access.
=> Add test to closesthit shader

docs/user-guide/02-conventional-features.md
Depending on the target language, sizeof(bool) changes. 
HLSL and GLSL users will be familiar, but it might strike CUDA-to-slang users (like myself) as odd that sizeof(bool) differs from C/C++ host languages and is 4 bytes rather than 1.  
Made a small change to the docs to clarify what users can expect sizeof(bool) to be.
=> Updated docs to detail specifics of sizeof(bool)

source/slang/slang-diagnostic-defs.h, source/slang/slang-ir-glsl-legalize.cpp, source/slang/slang-ir-layout.cpp, tests/spirv/std140-layout.slang
1. Fix GLSL legalization that produces insts with wrong type (missing ptr type).
2. Fix diagnostic id conflict.
3. Fix std140 layout logic, size of `float3` should be 12.
=> Bug fixes for the direct spirv backend.

source/slang/hlsl.meta.slang, tests/vkray/rayquery-closesthit.slang
Add a member function to RayQuery<RAY_FLAG> class
GetIntersectionTriangleVertexPositions to support the GLSL built-int rayQueryGetIntersectionTriangleVertexPositionsEXT.
Also add new test file under tests/vkray/rayquery-closesthit.slang to test this functionality.
=> Add support for rayQueryGetIntersectionTriangleVertexPositionsEXT

docs/user-guide/06-compiling.md
The user guide refers to `SlangComPtr`, but the type is actually called `ComPtr` and resides in the `Slang` namespace.
=> Correctly refer to ComPtr type in documentation

tools/gfx/vulkan/vk-device.cpp
I'd like to use Vulkan's printf feature in Falcor, which requires a couple small changes to the GFX backend. 
I tested these with one of the internal GFX examples, and the printf output for Vulkan backends now seems to correctly appear.
=> Add Vulkan printf support to GFX

source/slang/hlsl.meta.slang, source/slang/slang-emit-cpp.cpp, source/slang/slang-emit-glsl.cpp, source/slang/slang-ir-byte-address-legalize.cpp, source/slang/slang-ir-inst-defs.h, source/slang/slang-ir-layout.cpp, source/slang/slang-ir-lower-append-consume-structured-buffer.cpp, source/slang/slang-ir-lower-buffer-element-type.cpp, source/slang/slang-ir-specialize.cpp, source/slang/slang-ir.h, tests/doc/doc.slang.expected, tests/spirv/scalar-structured-buffer.slang
Fixes #3534.
This change adds a second optional type parameter to `[RW|Append|Consume|RasterizerOrdered]StructuredBuffer`, so that you can use:
```
StructuredBuffer<float3, ScalarDataLayout> scalarBuffer;
StructuredBuffer<float3, Std430DataLayout> std430Buffer;
StructuredBuffer<float3, Std140DataLayout> std140Buffer;
```
to define buffers with explicit vulkan layouts.
By default, `StructuredBuffer<float3>` maps to `StructuredBuffeR<float3, DefaultDataLayout>` that has target dependent layout, which means natural storage layout on d3d, and std430 on Vulkan.
=> Add per-buffer data layout control.

docs/user-guide/05-capabilities.md, source/compiler-core/slang-diagnostic-sink.cpp, source/core/slang-string-util.cpp, source/slang/slang-ast-decl.h, source/slang/slang-capabilities.capdef, source/slang/slang-check-decl.cpp, source/slang/slang-diagnostic-defs.h, source/slang/slang-lower-to-ir.cpp, source/slang/slang-parser.cpp, source/slang/slang-syntax.cpp, source/slang/slang-syntax.h, source/slang/slang-workspace-version.cpp, tests/diagnostics/extension-visibility.slang.expected, tests/diagnostics/generic-type-inference-fail.slang.expected, tests/language-feature/capability/capability3.slang, tests/language-feature/capability/capability4.slang
- Allow adding `[require]` attributes to module declarations.
- Add `__require_capability` decl that can be placed inside functions to introduce additional requirements for inference.
- Include requirements from `this` parameter in inference.
=> Improve Capability System

build/visual-studio/gfx-unit-test-tool/gfx-unit-test-tool.vcxproj, build/visual-studio/gfx-unit-test-tool/gfx-unit-test-tool.vcxproj.filters, source/slang/slang-check-decl.cpp, source/slang/slang-check-expr.cpp, source/slang/slang-diagnostic-defs.h, source/slang/slang-mangle.cpp, tools/gfx-unit-test/gfx-test-util.h, tools/gfx-unit-test/link-time-constant.cpp, tools/gfx-unit-test/link-time-constant.slang
This change adds the ability to provide link-time constants to specialize a precompiled module.
First, a module can declare link time constants with something like:
```
extern static const bool turnOnFeature;
extern static const float  value;
// use these values just as normal uniform parameters.
```
Next, the user can create a composite component type from this module, and another module that defines the value of these constants.
The other module can be defined as:
```
export static const bool turnOnFeature = true;
export static const float value = 1.0;
```
Then when asked to generate final code for the linked module, the compiler will plug in these link time constants to generate the specialized module.
Added a unit test for this usage: `gfx-unit-test-tool/linkTimeConstantVulkan`, …
=> Support link-time constants.

source/slang/slang-stdlib-textures.cpp, source/slang/slang-stdlib-textures.h
=> Fix incorrect spirv intrinsics for RWTexture.GetDimensions.

build/visual-studio/gfx-unit-test-tool/gfx-unit-test-tool.vcxproj, build/visual-studio/gfx-unit-test-tool/gfx-unit-test-tool.vcxproj.filters, slang.h, source/slang/slang-ast-base.h, source/slang/slang-ast-decl.h, source/slang/slang-check-decl.cpp, source/slang/slang-check-expr.cpp, source/slang/slang-check-impl.h, source/slang/slang-check-shader.cpp, source/slang/slang-compiler.cpp, source/slang/slang-compiler.h, source/slang/slang-module-library.cpp, source/slang/slang-parser.cpp, source/slang/slang-serialize-ast-type-info.h, source/slang/slang-serialize-container.cpp, source/slang/slang-serialize-container.h, source/slang/slang-serialize-factory.cpp, source/slang/slang-serialize-factory.h, source/slang/slang-serialize-types.h, source/slang/slang-serialize.cpp, source/slang/slang-serialize.h, source/slang/slang-syntax.h, source/slang/slang.cpp, tools/gfx-unit-test/gfx-test-util.cpp, tools/gfx-unit-test/gfx-test-util.h, tools/gfx-unit-test/precompiled-module-2.cpp, tools/gfx-unit-test/precompiled-module-imported.slang, tools/gfx-unit-test/precompiled-module-included.slang, tools/gfx-unit-test/precompiled-module.cpp, tools/gfx-unit-test/precompiled-module.slang
This PR addes support for serializing/deserializing checked modules (that contains AST+IR) from the `ISession` API, and allows `import` to find and load serialized modules.
This will allow our users to get rid of run-time Slang type checking cost by moving them to an offline build process.
The key change here is that we need a better handling of `Val` deserialization so the deserialized  module can have globally deduplicated `Val` objects that shares the deduplication dictionary with the currently loaded modules. To implement this, we separated out the logic of `Val` serialization/deserialization to be lazy/on-demand and bottleneck Val deserialization through `ASTBuilder::getOrCreateImpl`.
=> Support loading serialized modules.

CMakeLists.txt, cmake/SlangTarget.cmake, docs/building.md, source/slang/CMakeLists.txt
This adds an option to cmake that allows to build and link a static version of the slang library.
The resulting `slang.lib` is about 1 GB in size in debug, which is a bit on the larger side but I don't know why.
=> cmake: option to build a static library version of slang

build/visual-studio/gfx-unit-test-tool/gfx-unit-test-tool.vcxproj, build/visual-studio/gfx-unit-test-tool/gfx-unit-test-tool.vcxproj.filters, source/core/slang-list.h, source/slang/slang-ast-decl.cpp, source/slang/slang-ast-decl.h, source/slang/slang-ast-dump.cpp, source/slang/slang-ast-support-types.h, source/slang/slang-check-conformance.cpp, source/slang/slang-check-decl.cpp, source/slang/slang-check-impl.h, source/slang/slang-check-modifier.cpp, source/slang/slang-diagnostic-defs.h, source/slang/slang-lower-to-ir.cpp, source/slang/slang-parser.cpp, tests/diagnostics/incomplete-type.slang, tools/gfx-unit-test/link-time-type.cpp
This PR enables link time specialization, such that the following use case will work:
```
// module ifoo:
interface IFoo { [mutating] void setValue(float v); float getValue(); }
// module1:
import ifoo;
extern struct Foo : IFoo;
[numthreads(1,1,1)]
void computeMain(uniform RWStructuredBuffer<float> buffer)
{
Foo foo;
foo.setValue(3.0);
buffer[0] = foo.getValue();
}
// module2:
import ifoo;
export struct Foo : IFoo
{
float val;
[mutating] void setValue(float v) { val = v; }
float getValue() { return val + 1.0; }
};
```
The user can now compile these modules separately, and link these three modules together to produce a specialized shader.
An `extern` struct type is now treated as "incomplete" type. And "incomplete" type cannot be used in global buffers (e.g. ConstantBuffer) so they can't …
=> Support link time type specialization.

source/slang/slang-ast-decl.h, source/slang/slang-check-decl.cpp, source/slang/slang-check-impl.h, source/slang/slang-diagnostic-defs.h, source/slang/slang-lower-to-ir.cpp, source/slang/slang-parser.cpp, tools/gfx-unit-test/link-time-type.cpp
This changes add the following convenience syntax:
```
struct Foo : IFoo = FooImpl;
```
Which creates a wrapper type `Foo` around `FooImpl`:
```
// expands to:
struct Foo:IFoo
{
FooImpl inner;
void ifoo_method() { inner.ifoo_method(); }
// other ifoo requirement wrappers...
}
```
This can be used with link time specialization to do things like:
```
// module common
interface IMaterial {}
struct ClothMaterial : IMaterial {}
struct DiffuseMaterial : IMaterial {}
// module shading
import common;
extern struct Material : IMaterial;
void main()
{
Material m;
m.compute(...);
}
// module specialization_arg:
export struct Material : IMaterial = ClothMaterial;
```
=> Add wrapper type syntax for link time specialization.

source/slang/slang-check-shader.cpp, source/slang/slang-emit-spirv.cpp, source/slang/slang.cpp, tests/bugs/gh-3601.slang, tests/spirv/namespace-texture-array.slang, tests/spirv/pointer-bug.slang
Fix issues with pointers.
Fix an issue that causes global parameters defined in namespaces to miss layout.
Fixes #3595.
Fixes #3600.
Fixes #3601.
Fixes #3605.
=> Fix SPIRV lowering issue.

build/visual-studio/generate-capabilities/generate-capabilities.vcxproj, build/visual-studio/gfx-unit-test-tool/gfx-unit-test-tool.vcxproj, build/visual-studio/gfx-unit-test-tool/gfx-unit-test-tool.vcxproj.filters, build/visual-studio/platform-test/platform-test.vcxproj, build/visual-studio/platform-test/platform-test.vcxproj.filters, build/visual-studio/slang-capability-generator/slang-capability-generator.vcxproj, build/visual-studio/slang-capability-generator/slang-capability-generator.vcxproj.filters, slang.h, source/compiler-core/slang-source-loc.cpp, source/compiler-core/slang-source-loc.h, source/core/slang-io.cpp, source/core/slang-io.h, source/slang/slang-compiler.h, source/slang/slang-serialize-container.cpp, source/slang/slang-serialize-container.h, source/slang/slang-serialize-types.h, source/slang/slang.cpp, tools/gfx-unit-test/precompiled-module-cache.cpp
This change adds an `CompilerOptionName::UseUpToDateBinaryModule` compiler option that will make the compiler verify the up-to-date-ness of the sources and compiler options used to compile the binary module before loading and reusing it. If the module is no longer up-to-date, the loadModule attempt will fail and the compiler will continue the search of the module from other directories that may contain the source.
Also adds a `ISession::isBinaryModuleUpToDate` function to for applications to query if an existing binary module is up-to-date.
Closes #3565.
=> Add API for querying and reusing precompiled binary modules.

CMakeLists.txt
Hi Slang team!
At the moment, ToT generates the following when running `cmake --preset vs2022; cmake --build --preset release --target slang-bootstrap` to build the slang-bootstrap target using CMake on Windows:
```output
slang-check-expr.obj : error LNK2019: unresolved external symbol "bool __cdecl Slang::lookupGLSLstd450(struct Slang::Un
ownedStringSlice const &,enum GLSLstd450 &)" (?lookupGLSLstd450@Slang@@YA_NAEBUUnownedStringSlice@1@AEAW4GLSLstd450@@@Z
) referenced in function "public: void __cdecl <lambda_95ea3229cd43cabe2973e50266723bf3>::operator()<class <lambda_95ea
3229cd43cabe2973e50266723bf3>,class Slang::SPIRVAsmOperand>(class <lambda_95ea3229cd43cabe2973e50266723bf3> const &,cla
ss Slang::SPIRVAsmOperand &)const " (??$?RV<lambda_95ea3229cd43cabe2973e50266723bf3>@@VSPIRVAsmOpe …
```
=> Fixes building slang-bootstrap by linking with slang-lookup-tables

prelude/slang-cuda-prelude.h
Hi Slang team! This merge request modifies the CUDA prelude so that `nvcc` can compile code that uses it when `SLANG_CUDA_ENABLE_HALF` is defined and set to 1.
I've attached a repro case; `test-half-vector-calc.bat` transpiles `tests/compute/half-vector-calc.slang` to a CUDA source file using
```
slangc -target cuda ../../../tests/compute/half-vector-calc.slang -o half-vector-calc.slang.cuh
```
and then compiles the result to a `.cubin` using the following support file:
```cuda
// half-vector-calc.cu
#define SLANG_CUDA_ENABLE_HALF 1
#include "half-vector-calc.slang.cuh"
```
and the command line
```
nvcc half-vector-calc.cu --cubin --output-file half-vector-calc.cubin
```
Currently, this generates a lot of errors, originating in two places:
* `SLANG_MAKE_VECTOR()` is only defined if …
=> CUDA prelude: Fixes compilation when using `SLANG_CUDA_ENABLE_HALF` without NVRTC

source/slang/slang-lower-to-ir.cpp
Work-around for an issue #3628
This commit allows __init() functions in stdlib to be decleared without "[__unsafeForceInlineEarly]" or "[ForceInline]".
We need to find a proper solution for the issue later.
=> WAR for ForceInline not working issue in stdlib

tools/gfx/vulkan/vk-buffer.cpp, tools/gfx/vulkan/vk-device.cpp, tools/gfx/vulkan/vk-texture.cpp
Uses `VK_KHR_external_memory_fd` on Linux to shared memory.
=> Add support for shared resources on vulkan/linux

source/slang/slang-check-expr.cpp, tests/bugs/gh-3643.slang
=> Allow non-static const to be considered compile-time constant.

source/slang/slang-options.cpp, tests/diagnostics/vk-bindings.slang
=> [slangc] generate an error when `-entry` is not specified for targets that require them.

build/visual-studio/slang/slang.vcxproj, build/visual-studio/slang/slang.vcxproj.filters, slang.h, source/core/slang-uint-set.cpp, source/core/slang-uint-set.h, source/slang/core.meta.slang, source/slang/hlsl.meta.slang, source/slang/slang-ast-modifier.h, source/slang/slang-check-modifier.cpp, source/slang/slang-diagnostic-defs.h, source/slang/slang-emit.cpp, source/slang/slang-ir-entry-point-uniforms.cpp, source/slang/slang-ir-inst-defs.h, source/slang/slang-ir-insts.h, source/slang/slang-ir-uniformity.cpp, source/slang/slang-ir-uniformity.h, source/slang/slang-lower-to-ir.cpp, source/slang/slang-options.cpp, source/slang/slang-parser.cpp, tests/language-feature/dynamic-uniform/dynamic-uniform-1.slang
This changes implements an experimental uniformity analysis pass to diagnose warnings on places where a dynamic uniform is expected but the compiler cannot prove it is dynamic uniform.
Uniformity analysis must be explicitly enabled with the `-validate-uniformity` compiler option.
- Added `dynamic_uniform` modifier that can be placed on function parameters, variables and struct fields.
- Added `[NonUniformReturn]` modifier to mark a function that returns non uniform values (mostly used for intrinsics).
- Implemented a data-flow pass to warn in places where dynamic uniform is expected but cannot be proved.
Example:
```csharp
//DIAGNOSTIC_TEST:SIMPLE(filecheck=CHECK): -target hlsl -entry main -profile cs_6_0 -validate-uniformity
RWStructuredBuffer<int> output;
void …
```
=> Uniformity analysis.

slang.h, source/slang/slang-ast-modifier.h, source/slang/slang-ast-val.cpp, source/slang/slang-ast-val.h, source/slang/slang-check-conformance.cpp, source/slang/slang-check-conversion.cpp, source/slang/slang-check-decl.cpp, source/slang/slang-check-expr.cpp, source/slang/slang-check-impl.h, source/slang/slang-check-modifier.cpp, source/slang/slang-check-overload.cpp, source/slang/slang-check-stmt.cpp, source/slang/slang-check-type.cpp, source/slang/slang-compiler.h, source/slang/slang-diagnostic-defs.h, source/slang/slang-ir-insts.h, source/slang/slang-ir.cpp, source/slang/slang-language-server.cpp, source/slang/slang-lower-to-ir.cpp, source/slang/slang-options.cpp, source/slang/slang-reflection-api.cpp, source/slang/slang-type-layout.cpp, source/slang/slang.cpp, tests/diagnostics/unsized.slang, tools/gfx-unit-test/link-time-constant.cpp, tools/gfx-unit-test/link-time-constant.slang
- Add `ISession::loadModuleFromSourceString(char* name,char* path,char* src,IBlob** diagnostic)` for convenience.
- Allow `loadModuleFromSource` to accept a nullptr `path` or `name`, in which case we synthesize a digest from source to use as name or path.
- Allow link-time constants to be used as array sizes or in `[numthreads]`.
Closes #3709.
Closes #3710.
Closes #3711.
Closes #3712.
=> Link-time constant and linkage API improvements.

source/slang/slang-ast-decl.h, source/slang/slang-ast-val.cpp, source/slang/slang-ast-val.h, source/slang/slang-check-decl.cpp, source/slang/slang-check-shader.cpp, source/slang/slang-compiler.h, source/slang/slang-parameter-binding.cpp, source/slang/slang-reflection-api.cpp, source/slang/slang-type-layout.h, source/slang/slang.cpp, tools/gfx-unit-test/link-time-constant.cpp, tools/gfx-unit-test/link-time-type.cpp
- Fix method synthesis logic for static differentiable methods.
- Support link-time constants in thread group size reflection.
Closes #3735.
Closes #3736.
=> Link-time specialization fixes.

docs/user-guide/08-compiling.md, slang.h, source/slang/slang-compiler-options.cpp, source/slang/slang-emit-spirv.cpp, source/slang/slang-emit.cpp, source/slang/slang-hlsl-to-vulkan-layout-options.cpp, source/slang/slang-hlsl-to-vulkan-layout-options.h, source/slang/slang-ir-glsl-legalize.cpp, source/slang/slang-ir-inst-defs.h, source/slang/slang-ir-insts.h, source/slang/slang-ir-vk-invert-y.cpp, source/slang/slang-ir-vk-invert-y.h, source/slang/slang-options.cpp, tests/cross-compile/geometry-decoration-ordering.slang, tests/spirv/geometry-decoration-ordering.slang, tests/spirv/rcp-w-fragment.slang
Closes #3732.
Also it appears that 
`OpExecutionMode %main InputPoints` must appear before `OpExecutionMode %main OutputVertices 4` and `OutputTriangleStrip` in the SPIRV for the shader to work properly, despite no validation rules states so. This PR fixes the problem and always emit input execution modes before output execution modes for geometry shaders.
Fixes #3733.
=> Add `-fvk-use-dx-position-w` and fix ExecutionMode ordering for geometry shaders.

source/slang/glsl.meta.slang, source/slang/slang-check-decl.cpp, source/slang/slang-check-shader.cpp, source/slang/slang-ir-propagate-func-properties.cpp, source/slang/slang-ir-util.cpp, tests/glsl/storage-buffer-side-effect.slang
Fixes #3746.
Fixes reflection on storage buffers.
Add gl_NumWorkGroup and gl_WorkGorupSize builtins.
Fix implicit `uniform` logic for glsl mode.
=> Fix side effect checking around storage buffer type.

CMakeLists.txt, premake5.lua, tools/gfx/cuda/cuda-base.h, tools/gfx/cuda/cuda-buffer.cpp, tools/gfx/cuda/cuda-command-queue.cpp, tools/gfx/cuda/cuda-device.cpp, tools/gfx/cuda/cuda-helper-functions.cpp, tools/gfx/cuda/cuda-helper-functions.h, tools/gfx/cuda/cuda-shader-object.cpp
This PR removes slang gfx's dependency to `cudart`. All CUDA calls are now done through the CUDA driver API.
This will allow a future change that loads the CUDA driver API dynamically, removing the build dependency to the CUDA SDK.
=> [gfx] use CUDA driver API

build/visual-studio/slang/slang.vcxproj, build/visual-studio/slang/slang.vcxproj.filters, source/slang/slang-diagnostic-defs.h, source/slang/slang-emit-spirv.cpp, source/slang/slang-emit.cpp, source/slang/slang-ir-check-unsupported-inst.cpp, source/slang/slang-ir-check-unsupported-inst.h, source/slang/slang-ir-spirv-legalize.cpp, source/slang/slang-ir-util.cpp, source/slang/slang-ir-util.h, tests/bugs/gh-3780.slang, tests/bugs/gh-3781.slang, tests/bugs/gh-3783.slang, tests/cross-compile/array-of-buffers.slang, tests/diagnostics/recursion.slang, tests/spirv/scalar-buffer-packing.slang
Fixes #3780.
Fixes #3781.
Fixes #3783.
Fixes #3779.
=> Fix SPIRV for mesh shaders, checks for invalid target code&recursion.

source/slang/hlsl.meta.slang, source/slang/slang-ast-modifier.h, source/slang/slang-ir-spirv-legalize.cpp, source/slang/slang-preprocessor.cpp, tests/spirv/vk-buffer-pointer-1.slang, tests/spirv/vk-buffer-pointer.slang
Closes #3489.
Not implemented in this PR:
1. Alignment is accepted, but not translated to SPIRV. All pointers will have aligmments that are derived from the type.
2. static_pointer_cast does not verify sub-type relationship.
=> Partially implement vk_buffer_ref proposal.

source/slang/core.meta.slang, source/slang/hlsl.meta.slang, source/slang/slang-ast-support-types.h
Adding constructor for matrix that takes a partial matrix and a vector.
For example, "mat4x4 var = mat4x4(mat3x4, vec4)".
Adding implicit cast from vector<T,1> to T.
transpose(matrix<T,R,C>) had ambigous calls when T is int, because there
are definition for __BuiltinIntegerType and __BuiltinLogicalType. "int"
couldn't be resolved properly. In order to resolve the issue,
__BuiltinLogicalType got [OverloadRank(-1)], which gives
__BuiltinIntegerType a higher chance to be used.
=> Changes to make UE TSR working with Slang.

source/slang/slang-emit-spirv.cpp, source/slang/slang-ir-glsl-legalize.cpp, source/slang/slang-ir-translate-glsl-global-var.cpp, tests/spirv/mesh-primitive.slang
Fixes #3826.
Also fixes a problem where `Flat` decoration is missing when a struct field or input parameter is declared as `nointerpolation`.
=> Fix missing PerPrimitive decoration in mesh shader output.

source/slang/slang-ir-sccp.cpp, source/slang/slang-ir.h, tests/bugs/gh-3637.slang
In constant folding of a right shift operation,slang always uses signed interger as the operand no matter the input source code is signed or unsigned, this could causes sign-extending issue if the input source is unsigned integer with highest bit set to 1.
Fix the issue by checking the original type of the input and use the unsigned type if the input is unsigned.
=> Fix the sign-extending issue in right shift

source/slang/slang-parser.cpp
Our decl parsing func is assumed to always return a non-null ast node upon successful parse.
The parseTransparentBlockDecl directly inserts the parsed decls in to the current parent isntead of constructing a new decl, so it was returning null. The problem with that is the calling function `ParseDeclWithModifiers` will see it as failed and continue to try fallback parsing logic, resulting wrong parsing behavior.
The fix here is to have `parseTransparentBlockDecl` return an EmptyDecl instead.
=> Fix parsing issue around __transparent_block.

README.md
Adds tables to README.md for quick reference of which platforms and targets are supported. Links to detailed information in user guide.
Bug Id: shader-slang/slang #3667
=> Update README.md with tables for platform & target support

source/slang/slang-ast-support-types.h, source/slang/slang-check-decl.cpp, source/slang/slang-check-expr.cpp, source/slang/slang-check-impl.h, source/slang/slang-lookup.cpp, source/slang/slang-lookup.h, source/slang/slang-parser.cpp, tests/bugs/gh-3845-2.slang, tests/bugs/gh-3845.slang
Fixes #3845.
The change here is to extend decl lookup functions to take a `declToExclude` parameter that excludes the specified decl from lookup result.
Before we check the type of `typedef Foo Foo`, we will set the typedef decl itself to be excluded from lookup, so that when we check the type expr of `Foo`, we won't mistakenly use the typedef itself as its own type.
=> Fix lookup to prevent finding `typedef` itself.

source/slang/slang-check-decl.cpp, tests/bugs/gh-3824.slang
Expand on #3848 to allow the variables, struct fields and function parameters to be named the same as their types.
The fix is the same: exclude the current var/param decl from the lookup when checking its type.
Fixes #3824.
=> Allow var/param names to be the same as type name.

source/slang/slang-emit-spirv.cpp, source/slang/slang-ir-insts.h, source/slang/slang-ir-layout.cpp, source/slang/slang-ir.cpp, tests/bugs/gh-3825.slang
In '-emit-spirv-directly' mode, slang generates the incorrect stride for unsized array in `OpDecorate` instructions.
The root cause of this issue is that `emitOpDecorateArrayStride` will only take a 32-bit integer as the stride value, however, we define the IRSizeAndAlignment::kIndeterminateSize as the size for the unsized array, which is a 64-bit integer. So it will be 0 when converted to 32-bit.
The easiest fix for this issue is to change
IRSizeAndAlignment::kIndeterminateSize to a 32-bit integer.
=> Fix incorrect SPV stride for unsized array

source/slang/slang-emit-spirv.cpp, tests/pipeline/rasterization/mesh/primitive-output.slang
[Follow capabilities as per SPIR-V specification](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#_capability) CullPrimitiveEXT should require `SPV_EXT_mesh_shader`, currently the code requires `SPV_NV_mesh_shader`.
Addresses https://github.com/shader-slang/slang/issues/3863
=> Correctly emit `SPV_EXT_mesh_shader` for when `CullPrimitiveEXT` is used - resolves #3863

source/slang/slang-ir-peephole.cpp, tests/language-feature/types/is-on-type.slang
Closes #3861.
The cause is that we are using both `kIROp_TypeType` and `kIROp_TypeKind` to represent the type of an inst that represents a type. This needs to be clean up separately so that we unify them into a single opcode.
=> Fix peephole optimization of `TypeEquals`.

source/slang/slang-check-expr.cpp, tests/language-feature/extensions/ptr-extension.slang, tests/language-feature/extensions/ptr-extension.slang.expected
Closes #3868.
When looking up members of a pointer type, we will automatically dereference the pointer and lookup in the pointee type instead.
However when the lookup is static, such as when the user is doing (Ptr<T>::member), we shouldn't be doing this implicit deref step, and instead need to lookup in the Ptr type itself.
=> Fix static member lookup in pointer types.

source/slang/core.meta.slang, source/slang/slang-ast-val.cpp, source/slang/slang-check-decl.cpp, source/slang/slang-check-expr.cpp, source/slang/slang-check-impl.h, tests/language-feature/enums/enum-generic-arg.slang
The main change here is to allow constant folding to preserve the enum types from enum case values, and to allow constant propagation logic to identify the binary operator overloads.
=> Allow enum values to be used as generic arguments.

source/slang/slang-emit-spirv.cpp, tests/spirv/depth-replacing-none.slang
#3884 was not completely fixed by #3885. This enhances the emit logic further.
=> Not emit DepthReplacing when frag shader uses SV_Position.

source/slang/slang-ast-stmt.h, source/slang/slang-check-impl.h, source/slang/slang-check-stmt.cpp, source/slang/slang-diagnostic-defs.h, tests/diagnostics/switch-duplicate-case.slang, tests/diagnostics/switch-multiple-defaults.slang
The change looks for duplicate default cases in a switch statement, and flag them as invalid
=> Fix assertions due to malformed switch statements

source/slang/slang-emit-spirv.cpp, tests/pipeline/rasterization/mesh/mesh-PerPrimitiveEXT.slang
=> Add decoration PerPrimitiveEXT when a mesh output variable is decorated with PrimitiveID

README.md
Add CTS status badge to README.
Our CTS is schedule as nightly run, and currently there is no passive notification for developers about the status, for now we just add the status to our README badge as a notification.
=> Add CTS status badge to README

build/visual-studio/slang-unit-test-tool/slang-unit-test-tool.vcxproj, build/visual-studio/slang-unit-test-tool/slang-unit-test-tool.vcxproj.filters, slang.h, source/slang/slang-check-impl.h, source/slang/slang-compiler.cpp, source/slang/slang-compiler.h, source/slang/slang.cpp, tools/slang-unit-test/unit-test-find-check-entrypoint.cpp
Our COM based API has provided a `IModule::findEntryPointByName` method that can return
an `IEntryPoint` from an `IModule`.
However, this function only works when the entrypoint is decorated with the `[shader]` attribute.
If not, the function returns nullptr.
This changes adds `IModule::findAndCheckEntryPoint` so that if the function is not decorated
with [shader], we will call `findAndValidateEntryPoint` to find and validate the entrypoint function
on demand.
The work here is just to set up the FrontEndCompileRequest and FrontEndEntryPointRequests
so that the checking logic and be invoked.
Closes #3882.
=> Allow COM based API to discover and check entrypoints without [shader] attribute.

source/slang/glsl.meta.slang, source/slang/hlsl.meta.slang, source/slang/slang-check-modifier.cpp, source/slang/slang-ir-inst-defs.h, source/slang/slang-ir-translate-glsl-global-var.cpp, tests/spirv/subgroup-size-2.slang, tests/spirv/subgroup-size.slang
Instead of relying on the WorkgroupSize SPIRV built-in, which has been deprecated and superseded with a dedicated execution mode in spirv 1.6 (which we are not targeting), we simply resolve the workgroup size from the `[numthreads]` decoration and substitute it into the user code.
Fixes #3910.
=> Properly compile `gl_WorkgroupSize`.

build/visual-studio/slang/slang.vcxproj, build/visual-studio/slang/slang.vcxproj.filters, source/slang/slang-emit.cpp, source/slang/slang-ir-variable-scope-correction.cpp, source/slang/slang-ir-variable-scope-correction.h
In the IR optimization pass, we turn all the loop to do-while loop form. But in the do-while loop form, the loop body block is dominating the blocks after the loop break block. This assumption is fine for SPIRV and IR code, however, it's incorrect for all the other language target (e.g. c/c++/cuda/glsl/hlsl) because the instructions defined in the loop body is invisible from outside of the loop. Therefore, when translating to other textual language, there could be issue for the variables scope.
To fix this issue, we first detect the instructions that are defined inside the loop block, then check if these instructions are used after the break block. If so, we duplicate these instructions right before their users such that we can make those instructions available globally.
=> WIP: Fix the variable scope issue (#3838)

.github/actions/common-setup/action.yml
The timestamped caches were filling up the 10GB max cache size, removing the timestamps allows older ones to be overwritten instead
=> Disable sccache timestamps

source/slang/slang.cpp
Fix the issue that 'spGetDependencyFilePath' will report "unknown" for the source code is from string. We only reported valid file path when the source code is file a file, so we change that to report a valid file name even when the source code is from the string.
=> Fix the issue that 'spGetDependencyFilePath' report 'unknown' (#3927)

source/slang/slang-ir-validate.cpp, source/slang/slang-lower-to-ir.cpp, tests/bugs/gh-3930.slang
The lowering logic for do-while loops is making an incorrect assumption that the current insert location is still the same block after lowering an expression. However this is not true with the recent short circuiting operator work. Lowering exprs can lead to new block being created, and the insert loc can be changed to a different loc.
This change fixes the logic to not make this assumption, and adds an IR validation logic to guard against this type of IR error.
This fixes a reported crash.
Closes #3930.
=> Fix IR lowering bug of do-while loops.

source/slang/hlsl.meta.slang, tests/hlsl-intrinsic/atomic/atomic-intrinsics-64bit.slang
Resolves #3951
This adds a few atomic functions for SM6.6.
The spec can be found from here:
https://microsoft.github.io/DirectX-Specs/d3d/HLSL_SM_6_6_Int64_and_Float_Atomics.html
=> Support 64bit HLSL atomic functions

build/visual-studio/gfx-unit-test-tool/gfx-unit-test-tool.vcxproj, build/visual-studio/gfx-unit-test-tool/gfx-unit-test-tool.vcxproj.filters, slang.h, source/core/slang-array.h, source/slang/slang-check-conformance.cpp, source/slang/slang-check-decl.cpp, source/slang/slang-check-impl.h, source/slang/slang-parameter-binding.cpp, source/slang/slang-reflection-api.cpp, source/slang/slang-type-layout.cpp, source/slang/slang-type-layout.h, tools/gfx-unit-test/uint16-buffer.slang, tools/gfx-unit-test/uint16-structured-buffer.cpp, tools/gfx/d3d12/d3d12-device.cpp, tools/gfx/d3d12/d3d12-resource-views.cpp, tools/gfx/d3d12/d3d12-resource-views.h, tools/gfx/d3d12/d3d12-shader-object-layout.cpp, tools/gfx/d3d12/d3d12-shader-object-layout.h, tools/gfx/d3d12/d3d12-shader-object.cpp
Fixes #3952.
When binding a buffer resource to a StructuredBuffer parameter in D3D12, we need to specify an element stride. This stride can be derived from Slang's reflection info.
This change changes the logic in resource buffer view creation and binding, so that when binding a buffer to a buffer entry, we will create a specialized descriptor with the stride info, and cache the descriptor on the buffer view object.
=> [GFX] Fix d3d12 buffer view creation logic for StructuredBuffers.

source/slang/hlsl.meta.slang, source/slang/slang-ir-autodiff-fwd.cpp
Fixes #3969 
NonUniformResourceInfo instruction is applied as a Decoration on the backing resource. With the following shader, this is applied to the Function Call.
```
vRadiance.rgb *= g_bindless_Texture2D [NonUniformResourceIndex (light.m_nCookie_nLuminaireType_nPathTraceFlags.x)].SampleLevel(g_Sampler, vUv, 0.0).rgb;
```
as shown below:
```
{145371}	let  %1826	: Int	= nonUniformResourceIndex(%1789)
{177146}	let  %1828	: Vec(Float, 4 : Int)	= call %SampleLevel(%1826, %gx5FCookieSampler, %1827, 0 : Float)
```
This patch ForceInlines SampleLevel intrinsic function call so that the Decoration is correctly applied on the resource.
=> ForceInline SampleLevel to allow decorations to be applied

build/visual-studio/slang/slang.vcxproj, build/visual-studio/slang/slang.vcxproj.filters, source/slang/slang-emit-metal.cpp, source/slang/slang-emit-metal.h, source/slang/slang-emit-spirv.cpp, source/slang/slang-emit.cpp, source/slang/slang-ir-wrap-global-context.cpp, source/slang/slang-ir-wrap-global-context.h, source/slang/slang-ir.h, tests/metal/simple-compute.slang
The goal here is to workaround Metal's language rule that disallows global variables and global parameters.
In Metal, all shader parameters must be defined as entry point parameter, and all global scope variables are restricted to be compile-time constants.
To solve this problem and compile ordinary HLSL/Slang shaders to metal, we need to take two steps:
1. Turn all global parameters into entry point parameters + global variables.
2. Turn all global variables into an explicit context parameter for each function.
In the first step, we create a function parameter in each entry point for each global parameter. And we also create a global variable that the entry point function initializes as the first thing. After this step, there will be no more global parameters, but there will be global …
=> Metal: rewrite global variables as explicit context.

slang.h, source/slang/slang-check-decl.cpp, source/slang/slang-check-impl.h, source/slang/slang-check-shader.cpp, source/slang/slang-options.cpp, tests/language-feature/capability/capability1.slang, tests/language-feature/capability/capability2.slang, tests/language-feature/capability/capability3.slang, tests/language-feature/capability/capability4.slang
`-ignore-capabilities` flag allows ignoring capability incompatibilities/discontinuity errors/warnings. We still process capabilities (needed for stdlib).
Added to capability tests to ensure everything is working as intended. More will be added in the full stdlib capabilities implementation.
(fixes #3985)
Fixes #3978.
=> Add slangc flag to `-ignore-capabilities`

source/core/slang-test-tool-util.cpp
If Slang is installed using CMake install command, preludes are no longer in `... /prelude` (arbitrary depth), but in `../include` relative to the `slangc` executable.
This fix add search for preludes in `../include` relative to the `slangc` executable.
=> Fix for preludes being always embedded for cpp and cuda targets

source/slang/slang-ir-insts.h, source/slang/slang-ir-specialize.cpp, tests/bugs/gh-3935.slang
Resovles an issue #3935
Slang had to fold the generic arguments after specialization.
=> Support arithmetics on generic arguments

build/visual-studio/compiler-core/compiler-core.vcxproj, build/visual-studio/compiler-core/compiler-core.vcxproj.filters, slang.h, source/compiler-core/slang-artifact-desc-util.cpp, source/compiler-core/slang-downstream-compiler-util.cpp, source/compiler-core/slang-gcc-compiler-util.cpp, source/compiler-core/slang-metal-compiler.cpp, source/compiler-core/slang-metal-compiler.h, source/core/slang-type-text-util.cpp, source/slang/slang-capabilities.capdef, source/slang/slang-compiler.cpp, source/slang/slang-compiler.h, source/slang/slang-emit-c-like.cpp, source/slang/slang-ir-link.cpp, source/slang/slang-options.cpp, source/slang/slang-profile-defs.h, source/slang/slang-type-layout.cpp, source/slang/slang.cpp, tests/metal/simple-compute.slang, tools/slang-test/slang-test-main.cpp, tools/slang-test/test-context.h
This adds `metallib` target, which will make slang emit metal source, then invoke metal compiler to generate the metalib file.
This allows us to filecheck disassembled metallib in our tests.
Closes #3967.
=> Add metal downstream compiler + metallib target.

slang.h, source/slang/slang-emit-c-like.cpp, source/slang/slang-emit-c-like.h, source/slang/slang-emit-hlsl.cpp, source/slang/slang-options.cpp, tests/language-feature/no-hlsl-pack-constant-buffer-elements.slang
Added a flag that prevents packing of elements in cbuffers into ParameterGroup structs, and instead emits them directly into the resulting cbuffer. Addresses #3992.
Also added a small test verifying the flag. All tests pass locally.
=> Flag to prevent packing of cbuffer elements in HLSL backend.

deps/target-deps.json, github_build.sh
Update the dependency file to use the latest release version for slang-llvm and slang-glslang where we added a new Linux release to support the older version of Glibc-2.27.
Fix a type in github.sh for the glibc compatible option input for premake5.lua.
=> Update the dependency file

source/slang/slang-check-decl.cpp, tests/language-feature/struct-field-initializers/struct-field-initializer-shadowed-member.slang
Use memberExpr instead of varExpr, this is to allow proper resolution of a this->member with the same name as a local var to enable proper init creation when shadowing a variable name.
fixes #4007
=> Fix variable shadowing use with constructor's

source/slang/slang-check-decl.cpp, source/slang/slang-check-overload.cpp
Fix the issue (#3999).
For a function is defined as extern and export at the same time, don't report error, we can use the 'export' function to overload the 'extern' function.
=> Do not diagnose error when a symbols is defined as 'extern' and 'export'

source/compiler-core/slang-metal-compiler.cpp, source/slang/slang-check-decl.cpp, source/slang/slang-compiler.h
Adding "override" keywords for member functions whereever they need. The compiler warning was visible on CI build but not visible on local visual studio build.
=> Silent compiler warning about missing override keywords

source/slang/slang-ir-constexpr.cpp, tests/bugs/gh-3834.slang, tests/glsl-intrinsic/intrinsic-texture.slang
Closes #3834
The issue was that "const" variables inside of generic functions became non-const variables.  This issue prevented some of GLSL texture functions from being called inside of generic functions.
`propagateConstExpr()` was iterating global functions excepts generic functions. This commit includes generic functions and resolves the issue.
=> Keep const-ness in generic functions

source/slang/glsl.meta.slang, tests/bugs/gh-4031.slang
Fixes #4031
Each component of unpackU/Snorm4x8 had to be masked for 8bits.
=> Fix unpackUnorm4x8 and unpackSnorm4x8

source/slang/slang-mangle.cpp
Do not mange the name of identifiers decorated by "__extern_cpp".
For a slang files that are included by the library module and entry point module, slang could generated two different mangled names for the same functions, because the function with a struct parameter will make the mangled function name contains the file name. Therefore, we allow using "__extern_cpp" on such struct, such that no file name is associated in the mangled name.
=> Do not mangle the name of identifiers when __extern_cpp is added

source/slang/core.meta.slang, source/slang/diff.meta.slang, source/slang/glsl.meta.slang, source/slang/hlsl.meta.slang
Partially resolves #3906
Most but not all __target_intrinsics are replaced with __target_switch. All __specialize_for_target are replaced with __target_switch.
This change is mostly processed by a temporary c++ program mechanically. Because the change is already too big, the remaining __target_intrinsics will be replaced later in another commit.
=> Replace __target_intrinsics and __specialize_for_target, part 1

slang.h, source/slang/slang-check-impl.h, source/slang/slang-options.cpp, source/slang/slang.cpp
Add option -disable-short-circuit to disable short circuit for logic operators && and ||. Also, disable the short circuit by default in the stdlib.
=> Add option -disable-short-circuit

source/slang/core.meta.slang, source/slang/slang.cpp
Do not use "&&" to implement the intrinsic kIROp_And, instead define a 'and' function in stdlib. So it will be up to us to determine whether we want to use 'short-circuit' behavior in stdlib.
=> Change stdlib to not depend on short-circuit

source/slang/slang-check-shader.cpp, source/slang/slang-compiler.cpp, source/slang/slang-compiler.h, source/slang/slang.cpp
Fixes https://github.com/shader-slang/slang/issues/3979
We weren't able to reproduce the completely silent error with the latest top-of-tree Slang. In general, a silent error points to an internal error, and should be referred to the compiler team. Diagnostic messages from compiler errors due to incorrect input code are currently reported by `slangtorch` on stdout.
Tthis PR fixes the `[numthreads]` problem which assumed that any method with `[numthreads]` is necessarily a compute shader entry point. We no ignore that classification for CUDA-related targets ('cuda', 'ptx', and 'torch-binding').
=> Avoid classifying methods with `[numthreads]` as entry points for CUDA-related targets

source/slang/slang-ir.cpp, source/slang/slang-ir.h
Adds a member dump() to IRInst that can writes the immediate value or IR
inst value to stdout to help with debugging
=> Adds functionality to dump IR to stdout

source/slang/core.meta.slang, source/slang/slang-check-modifier.cpp, source/slang/slang-syntax.h
Currently we only allow variable, struct, and function as the target for the user-defined attribute, this change adds the function parameter to the target as well.
=> Add ParamDecl as the attribute target (#4055)

source/slang/slang-ir-lower-buffer-element-type.cpp, source/slang/slang-ir-util.cpp, tests/spirv/large-struct-pack.slang, tests/spirv/large-struct-ptr.slang, tests/spirv/large-struct.slang, tools/render-test/render-test-main.cpp, tools/render-test/shader-input-layout.cpp, tools/render-test/shader-input-layout.h
The problem of long compile time is due to our `lower-buffer-element-type` pass is emitting expanded/unrolled instructions to pack/unpack each element in an array.
We fix this problem by emitting a loop to copy the array when the array is bigger than a threshold, instead of just emit raw insts that processes each element.
Fixes #4038.
=> SPIRV: Fix performance issue when handling large arrays.

source/slang/glsl.meta.slang, source/slang/slang-compiler-options.cpp, source/slang/slang-ir-insert-debug-value-store.cpp, source/slang/slang-ir-insts.h, source/slang/slang-ir-util.cpp, source/slang/slang-ir-util.h, source/slang/slang-ir.cpp, source/slang/slang.cpp, tests/autodiff/struct-this-parameter.slang, tests/autodiff/was/warped-sampling-1d.slang, tests/bugs/stk-chk.slang, tests/glsl-intrinsic/intrinsic-basic.slang, tests/ir/loop-dce.slang, tools/render-test/options.cpp, tools/render-test/options.h, tools/render-test/render-test-main.cpp, tools/render-test/slang-support.cpp
This change is to prevent generating debugValue inst on types that may cause complications during future lowering passes to avoid crashing the compiler.
Currently we are avoiding generating debug inst for existential typed values, because the existence of the debug value inst can lead to generation of dynamic dispatch logic. We don't want debug symbols to trigger that because it will result in slower code and triggers crashes due to corner cases that cannot be handled by our dynamic dispatch passes.
Fixes #4070.
=> Fix compile failures when using debug symbol.

source/slang/slang-compiler.h, source/slang/slang-options.cpp, source/slang/slang.cpp
In current implementation, the some options will be to added to the target that is only specified by command line "-target". But if user specifies the target by just using slang API, e.g. 'spAddCodeGenTarget', those options will be missed.
To fix the problem, we copy the default target's options to the code-gen target's option set. The default target will only be useful when there is no target specified in the command line.
=> Copy default target's optionSet to code-gen target's optionSet

source/slang/slang-parser.cpp
This is causing a failure of gfx-smoke test under debug configuration.
The assert is out of date and no longer needed because we already have a centralized validation check on what modifiers are allowed on what decls in `isModifierAllowedOnDecl`.
Fixes #3953.
=> Delete out-of-date assert.

tests/reflection/attribute.slang, tests/reflection/attribute.slang.expected, tools/slang-reflection-test/slang-reflection-test-main.cpp
The reflection test doesn't print the user attributes decorating for the variables, only types. Therefore, add the print for user attributes of variables.
=> Fix reflection-test issue (#4082)

source/slang/glsl.meta.slang, source/slang/hlsl.meta.slang, tests/cross-compile/fmod.slang, tests/glsl-intrinsic/intrinsic-basic.slang
The default implementation of fmod was doing "Modulo" operation when "fmod" in HLSL should do "remainder" operation.
=> Fix fmod behavior targetting GLSL and SPIR-V

source/slang/slang-check-modifier.cpp, tests/reflection/attribute.slang, tests/reflection/attribute.slang.expected
The syntax like:
[__AttributeUsage(_AttributeTargets.Var)]
[__AttributeUsage(_AttributeTargets.Param)]
struct DefaultValueAttribute
{
int iParam;
};
is allowed.
For user-defined attribute, we can specify more attribute targets on the attribute declaration. So one attribute can be used in more than one situations.
=> Allow multiple _AttributeTargets for attribute declaration

source/slang/core.meta.slang, source/slang/slang-lower-to-ir.cpp, source/slang/slang-parser.cpp, tests/spirv/ptr-subscript.slang
Fixes #4029.
The main change here is to make `__subscript` a generic on `T:__BuiltinIntegerType`, and allow parser to accept generic __subscript decls.
=> Fix `Ptr::__subscript` to accept any integer index.

source/slang/hlsl.meta.slang
=> Don't bottleneck Wave intrinsics through `WaveMask*` for spirv.

source/slang/slang-emit-metal.cpp, source/slang/slang-emit-metal.h, source/slang/slang-ir-explicit-global-context.cpp, source/slang/slang-ir-insts.h, tests/metal/groupshared.slang
This change extends the explicit context pass to handle groupshared variables differently, such that they are allocated first in the entry point as a local variable, and then its pointers are passed in the global context object.
For example,
```
groupshared int data[3];
void test()
{
int a = data[2];
}
void main()
{
test();
}
```
Is emitted as:
```
struct KernelContext
{
array<int,3> threadgroup* data;
};
void test(KernelContext thread* ctx)
{
int a =  (*ctx->data)[[2];
}
void main()
{
threadgroup array<int,3> data;
KernelContext ctx;
ctx.data = &data;
test(&ctx);
}
```
Closes #4045.
=> Support groupshared variables for Metal.

build/visual-studio/slang/slang.vcxproj, build/visual-studio/slang/slang.vcxproj.filters, premake5.lua, source/slang-capture-replay/capture_utility.cpp, source/slang-capture-replay/capture_utility.h, source/slang-capture-replay/slang-filesystem.cpp, source/slang-capture-replay/slang-filesystem.h, source/slang-capture-replay/slang-global-session.cpp, source/slang-capture-replay/slang-global-session.h, source/slang-capture-replay/slang-session.cpp, source/slang-capture-replay/slang-session.h, source/slang/CMakeLists.txt, source/slang/slang-api.cpp
- Add global session, filesystem, and session capture interface classes: GlobalSessionCapture for IGlobalSession FileSystemCapture for ISlangFileSystemExt SessionCapture for ISession
- Add environment variables to enable it The 2 variables are SLANG_CAPTURE_LAYER and SLANG_CAPTURE_LOG_LEVEL
SLANG_CAPTURE_LAYER:
In slang_createGlobalSession(), after the compiling/loading stdlib,
we will check the capture environment variable, if it's set to 1,
we will create a GlobalSessionCapture object and return to user
code.
SLANG_CAPTURE_LOG_LEVEL: This is to set the log level, user can
choose the loglevel to debug. (We can remove this when the feature
is fully implemented).
- Update premake file to add the capture/replay source folder
=> capture/replay: interface implementation 1

source/slang/slang-ir-spirv-legalize.cpp, tests/bugs/gh-4131.slang
Fixes #4131.
The issue is that if `NonUniformResourceIndex()` is not decorating a diverging resource handle, we should ignore and remove it instead of leaving the inst in the IR module after legalization.
=> Fix NonUniformResourceIndex legalization for SPIRV.

source/slang/slang-ir-obfuscate-loc.cpp
Slang crashes during obfuscation because of referencing the nullptr pointer. Add the checking.
In addition, above situation happens when user provide an empty slang shader with '-obfuscate' option, we shouldn't do anything in that case.
So add an early return in obfuscateModuleLocs if no IR code is actually generated.
=> Fix crash in obfuscation

source/slang/hlsl.meta.slang, source/slang/slang-ir-spirv-legalize.cpp, tests/spirv/image-atomic-array-2.slang, tests/spirv/image-atomic-array.slang
Also Add glsl/spirv intrinsic for 64 bit `InterlockedAdd`.
Fixes #4121.
Fixes #4120.
=> Fix legalization of `kIROp_GetLegalizedSPIRVGlobalParamAddr`.

slang.h, source/core/slang-performance-profiler.cpp, source/slang/slang-lower-to-ir.cpp, source/slang/slang-options.cpp, tests/autodiff/path-tracer/pt-loop.slang, tests/autodiff/reverse-while-loop-2.slang, tests/cross-compile/loop-attribs.slang, tests/ir/loop-inversion.slang
In PerformanceProfiler::getProfiler() we return a static object for the profiler implementation, this is not thread-safe, so change it to thead_local.
There is still some visual artifacts when using slang as the shading language. We don't know the root cause yet, but found out it's related to our loop inversion algorithm. So stage this feature for now, and turn it into an internal option and default off. We will re-enable it after more investigation on this optimization.
File an new issue 4151 to track it.
=> Fix race-condition and visual artifacts issues

.github/workflows/falcor-test.yml, examples/autodiff-texture/main.cpp, examples/ray-tracing-pipeline/main.cpp, examples/ray-tracing/main.cpp, slang-gfx.h, tools/gfx-unit-test/buffer-barrier-test.cpp, tools/gfx-unit-test/nested-parameter-block.cpp, tools/gfx/d3d12/d3d12-command-encoder.cpp, tools/gfx/d3d12/d3d12-device.cpp, tools/gfx/d3d12/d3d12-resource-views.cpp, tools/gfx/d3d12/d3d12-resource-views.h, tools/gfx/d3d12/d3d12-shader-object.cpp, tools/gfx/gfx.slang, tools/gfx/vulkan/vk-command-encoder.cpp, tools/gfx/vulkan/vk-device.cpp, tools/render-test/render-test-main.cpp
- Change `BufferRange` to a range of bytes
- Remove `IResourceView::Desc::bufferElementSize`
- Create D3D12 buffer view descriptors on demand
- Use D3D12 buffer view descriptor with zero struct stride for `ClearUnorderedAccessViewUint/Float`
=> [gfx] specify resource view buffer range in bytes

source/slang/hlsl.meta.slang, source/slang/slang-capabilities.capdef, source/slang/slang-emit-metal.cpp, source/slang/slang-stdlib-textures.cpp, source/slang/slang-stdlib-textures.h, tests/bindings/multi-file-shared.slang, tests/metal/texture.slang
This commit is to implement texture functions for Metal target.
The following functions are implemented and tested.
- GetDimensions()
- CalculateLevelOfDetail()
- CalculateLevelOfDetailUnclamped()
- Sample()
- SampleBias()
- SampleLevel()
- SampleCmp()
- SampleCmpLevelZero()
- Gather()
- SampleGrad()
- Load()
Metal has limited support for the texture functions compared to HLSL.
- LOD is not supported for 1D texture,
- Depth textures are limited to 2D, 2DArray, Cube and CubeArray textures.
- "Offset" variants are limited to 2D, 2DArray, 2D-Depth, 2DArray-Depth and 3D textures.
The functions that cannot be implemented for Metal should properly be handled by the capability system later.
=> Implement texture functions for Metal target

CMakeLists.txt
This CL contains changes to CMakeLists.txt that enables the examples to run from within Visual Studio when using CMake generated solution. Previously the working directory was set to examples/<example name> and which resulted in an invalid path in the generated project files. Additionally, the assets (shaders, images, models) were not in location that was accessible to the executable when ran from within Visual Studio.
- Changed examples to use ${CMAKE_BINARY_DIR}/${dir} instead of ${dir} if generator is MSVC.
- Add custom target to assets (shaders, images, models, etc) to example subdir under ${CMAKE_BINARY_DIR}
- Add dependency to copy prebuilt binaries if building examples in MSVC so DirectX shader signing doesn't fail
- Changed copy-prebuilt-binaries to use copy_if_different to avoid …
=> Fixes running examples from generated SLN

source/slang/core.meta.slang, source/slang/hlsl.meta.slang, source/slang/slang-ast-modifier.h, source/slang/slang-emit-c-like.cpp, source/slang/slang-emit-c-like.h, source/slang/slang-emit-glsl.cpp, source/slang/slang-emit-metal.cpp, source/slang/slang-emit-metal.h, source/slang/slang-emit-spirv-ops.h, source/slang/slang-emit-spirv.cpp, source/slang/slang-emit.cpp, source/slang/slang-ir-byte-address-legalize.cpp, source/slang/slang-ir-byte-address-legalize.h, source/slang/slang-ir-inst-defs.h, source/slang/slang-ir-insts.h, source/slang/slang-ir-spirv-legalize.cpp, source/slang/slang-ir.cpp, tests/hlsl/raster-order-resource.slang, tests/metal/byte-address-buffer.slang
Also fixes the byte address buffer logic for metal.
- RasterizerOrdered buffers and textures are now supported on the spirv and metal backend.
- [RW][RasterizerOrdered]ByteAddressBuffer types are now supported on the metal backend.
=> RasterizerOrder resource for spirv and metal.

docs/user-guide/03-convenience-features.md
add member init expr and additional constructor logic to the docs.
Updates 03-convenience-features.md
fixes: [#2031](https://github.com/shader-slang/slang/issues/2031)
=> Add member init expressions and constructor logic to docs

source/slang/slang-check-decl.cpp, tests/language-feature/capability/intrinsic-texture-ignore-capability.slang
This is done for compile performance if chosen 
note: this may break code down the line, currently works since nothing depends on the capabilities pass in any meaningful way.
=> `-ignore-capabilities` now skips the capability pass 100%

build/visual-studio/slang/slang.vcxproj, build/visual-studio/slang/slang.vcxproj.filters, source/slang-capture-replay/capture_utility.h, source/slang-capture-replay/slang-composite-component-type.cpp, source/slang-capture-replay/slang-composite-component-type.h, source/slang-capture-replay/slang-entrypoint.cpp, source/slang-capture-replay/slang-entrypoint.h, source/slang-capture-replay/slang-filesystem.cpp, source/slang-capture-replay/slang-global-session.cpp, source/slang-capture-replay/slang-module.cpp, source/slang-capture-replay/slang-module.h, source/slang-capture-replay/slang-session.cpp, source/slang-capture-replay/slang-session.h, source/slang-capture-replay/slang-type-conformance.cpp, source/slang-capture-replay/slang-type-conformance.h, source/slang/slang-compiler.h, source/slang/slang.cpp
Add `ModuleCapture` class for capturing `IModule`
- The `IModule` can only be created from -- `ISession::loadModule` -- `ISession::loadModuleFromIRBlob` -- `ISession::loadModuleFromSource` -- `ISession::loadModuleFromSourceString` so, we create the `ModuleCapture` at those methods in `SessionCapture` class. We use a hash map to store a map from `IModule` to `ModuleCapture` to avoid creating new `ModuleCapture` when there is already an old one.
- In `SessionCapture::getLoadedModule`, we will assert on not finding a `ModuleCapture` instance.
Add `EntryPointCapture` class for capturing `IEntryPoint`.
- The `IEntryPoint` can only be created from: -- `IModule::findEntryPointByName` -- `IModule::findAndCheckEntryPoint` so, we create the `EntryPointCapture` at those methods in `ModuleCapture`. …
=> capture/relay: Add capture interface classes

CMakeLists.txt, CONTRIBUTION.md
This commit increases the minimum CMake version from 3.20 to 3.25.
I was trying to see if I can lower it to 3.16, but I found that we are currently using CMake feature that requires a version 3.25 not 3.20.
This finding is not new. I made a similar change to CMakePresets.json a few days ago. At that time, I didn't realize that the same change had to be made for CMakeList.txt as well.
=> Increase CMake version requirement from 3.20 to 3.25

docs/user-guide/toc.html
Adding (limited) to the header in a previous doc change broke the link.
=> Fix pointers link in userguide

docs/user-guide/03-convenience-features.md
Make the example shown for pointers something that would compile. Don't redefine pNext and do define MyType.
=> Fix pointer example

docs/user-guide/toc.html, source/slang/hlsl.meta.slang, tests/bugs/gh-4200.slang
[docs do not talk about this behavior](https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/sm5-object-texture2dms-sampleoperatorindex), but DXC still allows it.
If no sample is set with a `Texture(.*)MS[]` operation, set sample to 0.
Fixes: #4200
=> If no sample is set with a `Texture(.*)MS[]` operation, set sample to 0.

slang-gfx.h, tools/gfx/d3d12/d3d12-command-encoder.cpp, tools/gfx/d3d12/d3d12-shader-table.cpp, tools/gfx/d3d12/d3d12-shader-table.h, tools/gfx/renderer-shared.cpp, tools/gfx/renderer-shared.h, tools/gfx/vulkan/vk-command-encoder.cpp, tools/gfx/vulkan/vk-shader-table.cpp
Breaking change:
The ABI around gfx shader table creation is changed. Users of gfx will need to rebuild from source after upgrading.
There are no breaking changes in Slang.
=> Add support for callable shaders in gfx

.github/workflows/vk-gl-cts-nightly.yml
Stage some known failure test cases, will enable them back when the fix is merged.
The failure tests can be checked in
https://github.com/shader-slang/VK-GL-CTS/blob/main/test-lists/slang-waiver-tests.xml
TODO:
Change the schedule to per-PR, will change it back when it's ready to merge.
=> CTS: stage some known failure tests for now

tools/slang-test/options.cpp, tools/slang-test/options.h
When slang-test.exe ran with a file name doesn't exactly match character-by-character, those tests don't run.
This commit alters the file name given from the command-line and it will behave in a more expected way.
- "./" are removed.
- "../" gets removed along with its parent directory name.
- Back-slash characters will be converted to slash on Windows.
=> Simplify test file names for slang-test

source/core/slang-std-writers.cpp, source/slangc/main.cpp
When memory leak is detected, this commit will dump the information about the memory leak. This feature is available only in Debug build on Windows platform.
Also note that the message will not be printed on the client applications that use slang.dll, because the printing happens as a part of slangc.exe not slang.dll.
I found a bug that Slang::StdWriters was closing `stdout` and `stderr` in its destructor, which prevented Crt functions to print the messages to `stdout` and `stderr`.
=> Print memory leak info in Debug build of slangc.exe

source/compiler-core/slang-diagnostic-sink.cpp, source/slang/hlsl.meta.slang, source/slang/slang-artifact-output-util.cpp, source/slang/slang-ast-support-types.h, source/slang/slang-check-conversion.cpp, source/slang/slang-check-decl.cpp, source/slang/slang-check-impl.h, source/slang/slang-check-inheritance.cpp, source/slang/slang-emit.cpp, source/slang/slang-ir-autodiff-fwd.cpp, source/slang/slang-ir-ssa-simplification.cpp, source/slang/slang-options.cpp, source/slangc/main.cpp, tests/bindings/multiple-parameter-blocks.slang, tests/language-feature/extensions/extension-method-simple.slang, tests/slang-extension/atomic-float-byte-address-buffer-cross.slang
1. Add caching for implicit conversion overload resolution results.
2. Handle invalidation of type checking cache upon extension registration more gracefully.
3. Add a setting to `simplifyIR` to disable `redundancyRemoval` pass (still enabled by default).
=> Improve compile time performance.

source/slang/slang-lower-to-ir.cpp, tests/language-feature/interfaces/zero-init-interface.slang
`default(IFoo)` should lower into a `DefaultConstruct : IFoo` inst instead of `MakeStruct : IFoo` for our passes to handle it correctly to produce valid HLSL output.
Closes #3831.
=> Fix a bug on default initialization of interface typed value.

build/visual-studio/slang/slang.vcxproj, build/visual-studio/slang/slang.vcxproj.filters, source/slang/slang-diagnostic-defs.h, source/slang/slang-ir-operator-shift-overflow.cpp, source/slang/slang-ir-operator-shift-overflow.h, source/slang/slang-lower-to-ir.cpp, tests/diagnostics/warning_operator_left_shift_overflow.slang
Closes #3944
For the given type of the left side operand to `operator<<` is not big enough for the right side operand, print a warning that the result will be always zero.
=> Print warning when operator<< shifting too much

examples/hello-world/main.cpp
This CL fixes a typo in the profile string for the hello-world example. Currently `"glsl440"` is passed into `findProfile()` resulting in a return value of `SLANG_UNKNOWN_PROFILE` since format of the profile name is incorrect. The correct profile name is `glsl_440`, therefore the string passed into `findProfile()` should be `"glsl_440"` which results in valid profile value.
=> Fixes incorrect profile string in hello-word example

slang.h, source/core/slang-performance-profiler.cpp, source/core/slang-performance-profiler.h, source/slang/slang-api.cpp, source/slang/slang-compiler.h, source/slang/slang.cpp
Add serial time measurement
Add profiler to measure lots of stages in slang compilation, and it can accumulate the time spent in each thread in multi-threads case and finally report a serial timing info.
=> Add APIs to get profile of compile time

source/core/slang-performance-profiler.cpp
Use memcpy to replace strncpy_s in SlangProfiler::SlangProfiler to fix the error in Windows.
=> Use memcpy to replace strncpy_s

source/core/core_lldb.py
This adds an initial set of LLDB formatters for the following slang core types:
- `Slang::String`
- `Slang::UnownedStringSlice`
- `Slang::RefPtr`
- `Slang::ComPtr`
- `Slang::Array`
- `Slang::List`
- `Slang::ShortList`
Note: I've tested these both in XCode and VS Code on macOS. For VS Code I recommend to use the `vscode-lldb` extension (https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb). The debugger in the `ms-vscode.cpptools` extension is buggy and will freeze often (independent of the formatters).
=> initial set of lldb formatters

source/slang/slang-compiler.cpp
When compile a library module with other slang module together, if that library module already contains entry points, during the front-end process, we could add the entry points in library module again when scanning all the translation units. This will cause an issue that we will call linkIR twice on the exactly same entry point, and it will downgrade our performance heavily.
So, we will add a check in _discoverEntryPoints(), where if the entry points were added before, don't discover them again.
=> Avoid duplicating entry points in library

source/core/slang-string.h
Make `String::trim` remove carriage return and newline characters equal to what `String::trimStart` and `String::trimEnd` do.
=> make String::trim consistent with String::trimStart/trimEnd

docs/user-guide/a1-02-slangpy.md
I guess it did not like the space between backtits and "Python"
=> Fix python syntax highlighting in slangpy chapter

source/slang/glsl.meta.slang, source/slang/hlsl.meta.slang
When SPIR-V uses operators whose name has a keyword, "Implicit", they require calling a function "__requireComputeDerivative()".
When it uses "Explicit", the function doesn't need to be called.
=> Remove unnecessary call to __requireComputeDerivative

tools/slang-capability-generator/capability-generator-main.cpp
fixes: #4293
Currently the code does:
```
void inclusiveJoinConjunction(CapabilitySharedContext& context, CapabilityConjunction& c, List<CapabilityConjunction>& toAddAfter)
{
if (c.isImpossible())
return;
for (auto& conjunction : conjunctions)
{
if (c.implies(conjunction))
return;
}
```
This is incorrect because it means that "if the set we are going to add is a super set of an element, don't add it". This does not make sense since inclusive join is meant to be 'additive' of super sets.
Correct behavior code:
```
void inclusiveJoinConjunction(CapabilitySharedContext& context, CapabilityConjunction& c, List<CapabilityConjunction>& toAddAfter)
{
if (c.isImpossible())
return;
for (auto& conjunction : conjunctions)
{
if (conjunction.implies(c))
return;
}
```
This is correct behavior because …
=> Capabilities System: Inclusive join logic bug

docs/cuda-target.md, docs/doc-system.md, docs/faq.md, examples/autodiff-texture/draw-quad.slang, examples/autodiff-texture/reconstruct.slang, examples/autodiff-texture/train.slang, examples/gpu-printing/printing.slang, examples/model-viewer/shaders.slang, examples/shader-toy/example-effect.slang, examples/shader-toy/shader-toy.slang
Improve consistency of formatting in example shaders and remove trailing spaces in documentation files. Fix minor typos.
=> Improve documentation and example formatting consistency

source/slang/slang-emit-spirv.cpp
If we have `GetElement(vector, index)` where `index` is a `GlobalValueRef(IntLit)`, we still want to generate OpCompositeExtract instead of `OpVectorExtractDynamic`.
=> Small SPIRV emit cleanup around vector element extract.

tests/glsl-intrinsic/intrinsic-texture.slang
This commit adds a functional test to GLSL texture functions. It appears that the testing frameworkd doesn't work for combined sampler for "shadow" and "buffer".
=> Adding functional test for GLSL texture functions

source/slang/slang-diagnostic-defs.h, source/slang/slang-emit-metal.cpp, source/slang/slang-emit-metal.h, source/slang/slang-ir-inst-defs.h, source/slang/slang-ir-insts.h, source/slang/slang-ir-metal-legalize.cpp, tests/metal/stage-in-2.slang, tests/metal/stage-in.slang, tests/metal/system-val-conversion.slang
Add legalization logic to translate HLSL SV semantic to metal system values attributes.
If the declared HLSL parameter has type that is different from the Metal spec-defined type, we will insert conversion logic at the beginning of the entry point.
Also fixes the handling of stage-in parameters with user defined semantics. We shouldn't flatten the members of a struct-typed stage in parameter if the parameter has explicit user semantic.
Closes #4288.
=> Metal system value overhaul.

source/slang/slang-parser.cpp
=> Disallow certain types of decls in `interface` to provide better diagnostic message.

slang-gfx.h, source/compiler-core/slang-metal-compiler.cpp, tools/gfx/metal/metal-buffer.h, tools/gfx/metal/metal-command-buffer.cpp, tools/gfx/metal/metal-command-buffer.h, tools/gfx/metal/metal-command-encoder.cpp, tools/gfx/metal/metal-command-encoder.h, tools/gfx/metal/metal-device.cpp, tools/gfx/metal/metal-framebuffer.cpp, tools/gfx/metal/metal-framebuffer.h, tools/gfx/metal/metal-helper-functions.h, tools/gfx/metal/metal-pipeline-state.cpp, tools/gfx/metal/metal-pipeline-state.h, tools/gfx/metal/metal-render-pass.cpp, tools/gfx/metal/metal-render-pass.h, tools/gfx/metal/metal-shader-program.cpp, tools/gfx/metal/metal-shader-program.h, tools/gfx/metal/metal-swap-chain.cpp, tools/gfx/metal/metal-swap-chain.h, tools/gfx/metal/metal-texture.h, tools/gfx/metal/metal-util.cpp, tools/gfx/metal/metal-util.h, tools/gfx/metal/metal-vertex-layout.cpp, tools/gfx/metal/metal-vertex-layout.h, tools/gfx/vulkan/vk-fence.cpp
Adds support for basic Metal graphics pipelines.
Resource binding for different shader stages is not handled correctly yet. But otherwise, this should support most of gfx API for graphics pipelines, framebuffers etc.
The swapchain is implemented using extra backbuffer images, doing an extra copy to the Metal renderable on present. This is to support the current API of gfx, which needs explicit access to the backbuffer images. Metal doesn't support this natively.
=> [gfx] Metal graphics support

source/slang/hlsl.meta.slang, source/slang/slang-check-expr.cpp, source/slang/slang-check-impl.h, source/slang/slang-diagnostic-defs.h, source/slang/slang-emit-glsl.cpp, source/slang/slang-emit-spirv.cpp, source/slang/slang-ir-glsl-legalize.cpp, source/slang/slang-ir-inst-defs.h, source/slang/slang-ir-insts.h, tests/diagnostics/get-vertex-attribute.slang, tests/spirv/get-vertex-attribute.slang
=> Fix `GetAttributeAtVertex` for spirv and glsl targets.

tools/gfx/vulkan/vk-api.h, tools/gfx/vulkan/vk-device.cpp
This will be a source of a validation layer warning since 2 of the same extension is enabled.
=> Remove duplicate `VkPhysicalDeviceComputeShaderDerivativesFeaturesNV` extension structure in vk-api.h

source/slang/glsl.meta.slang, source/slang/hlsl.meta.slang, tests/diagnostics/int-texture-sample.slang, tests/glsl-intrinsic/intrinsic-texture.slang
Closes #4196
This commit re-enables the ability to sample from an integer typed texture for GLSL functions while keeping it unavailable for HLSL target.
The type constrains for the GLSL texture functions are changed from __BuiltinFloatingPointType to __BuiltinArithmeticType, which may cause a trouble if the user shader implemented based on __BuiltinFloatingPointType.
=> Support integer typed textures for GLSL

source/slang/slang-emit-metal.cpp, tests/metal/byte-address-buffer.slang, tests/metal/texture.slang
This commit adds testing for Metal texture functions with the following six types that the document says supported:
- float
- half
- int32_t
- uint32_t
- int16_t
- uint16_t
=> Metal: Support and test integer type textures

source/slang/hlsl.meta.slang, source/slang/slang-compiler.cpp, source/slang/slang-diagnostic-defs.h, source/slang/slang-emit-spirv.cpp, source/slang/slang-ir-glsl-legalize.cpp, source/slang/slang-ir-inst-defs.h, source/slang/slang-ir-specialize-target-switch.cpp, source/slang/slang-parameter-binding.cpp, tests/spirv/tessellation.slang
Closes #4332.
The main task here is to properly lower `InputPatch<T>` and `OutputPatch<T>` to array types in SPIRV, and to combine both the hull shader and the patch constant function into a single entrypoint for SPIRV.
A hull shader in the form of:
```
struct HullInput { float3 inElement; }
struct ConstantOutput { float factor[4] : SV_TessFactor; }
struct HullOutput { float3 outElement; }
ConstantOutput constantFunc(InputPatch<HullInput, N> inPatch, OutputPatch<HullOutput, N> outPatch)
{
// compute tess factor
}
[patchconstantfunc("constantFunc")]
HullOutput hull(InputPatch<HullInput, N> patch, int i : SV_OutputControlPointID)
{
// compute outElmeent
} 
```
should be transformed to:
```
in float3 inElement[N];
out float3 outElement[N];
void hull()
{
// compute outElement (original hull …
```
=> SPIRV backend: add support for tessellation stages.

source/slang/slang-ir-lower-optional-type.cpp, tests/bugs/optional-generic.slang, tests/bugs/optional.slang
=> Fix crash when using optional type in a generic.

source/slang/slang-ir-explicit-global-context.cpp, tests/glsl/matrix-mul.slang
fixes: #4377
Decorations were not expected as an input, this causes a crash since there is no 'context pointer' for a decoration use site.
Previously `layout(location = 0) in highp vec4 a_position;` caused a crash, now it does not.
=> Fix cuda/cpp/metal crash when using GLSL shader inputs

build/visual-studio/slang/slang.vcxproj, build/visual-studio/slang/slang.vcxproj.filters, source/core/slang-stream.h, source/slang-capture-replay/api_callId.h, source/slang-capture-replay/capture-manager.cpp, source/slang-capture-replay/capture-manager.h, source/slang-capture-replay/output-stream.cpp, source/slang-capture-replay/output-stream.h, source/slang-capture-replay/parameter-encoder.cpp, source/slang-capture-replay/parameter-encoder.h, source/slang-capture-replay/slang-global-session.cpp, source/slang-capture-replay/slang-global-session.h
Add infrastructure for output stream
This is the interface to record the method and parameter, and also
provide functionality to write all the serialized data into file.
Add capture manager:
Capture manager is associated to global session object, it will
provide the functionality to actual record all the APIs.
Implement some of parameter encoder functions.
=> capture/replay: implement infrastructure for capture

source/slang/slang-ir-metal-legalize.cpp, source/slang/slang-parameter-binding.cpp, source/slang/slang-parameter-binding.h, tests/metal/sv_target.slang
=> [Metal] Support SV_TargetN.

source/slang/slang-diagnostic-defs.h
=> Make unknown attributes a warning instead of an error.

source/slang/hlsl.meta.slang, source/slang/slang-emit-glsl.cpp, source/slang/slang-emit-spirv.cpp, source/slang/slang-profile.cpp, source/slang/slang-profile.h, tests/gpu-feature/texture/query/footprint/nv-shader-texture-footprint-simple.slang, tests/gpu-feature/texture/query/footprint/nv-shader-texture-footprint.slang, tests/hlsl-intrinsic/ray-tracing/rt-pipeline-intrinsics-ahit.slang, tests/hlsl-intrinsic/ray-tracing/rt-pipeline-intrinsics-chit.slang, tests/hlsl-intrinsic/ray-tracing/rt-pipeline-intrinsics-int.slang, tests/hlsl-intrinsic/ray-tracing/rt-pipeline-intrinsics-miss.slang, tests/hlsl-intrinsic/ray-tracing/rt-pipeline-intrinsics-rgen.slang, tests/vkray/anyhit.slang, tests/vkray/callable.slang
fixes: #4001
1. Added direct-spirv tests for 'raytracing' and 'texture-footprint'
2. Fixed bug with texture-footprint using direct-spirv path
3. Changed when we emit raytracing/rayquery extensions with backends (to reduce 'incorrect' extension emitting)
Note: 
1. `tests/hlsl-intrinsic/ray-tracing/rt-pipeline-intrinsics-ahit.slang` checks for the following code:
```
// SPIRV-DAG: OpTerminateRayKHR
// SPIRV-DAG: OpIgnoreIntersectionKHR
```
This code is checked using `DAG` since the used `OpBranch` has varying ordering when emitted by direct-spirv versus glslang-spirv.
=> Improve Direct SPIRV Backend Test Coverage & Fix Associated Bug

source/slang/hlsl.meta.slang, tests/bugs/buffer-swizzle-store.slang, tests/metal/texture.slang
fixes: #4405
The change modifies stdlib to ensures all metal texture `read`/`sample` uses swizzle their `vector<T,4>` output into the same parent element type of __TextureImpl<T>
1. Added test cases to texture.slang to cover all types.
=> Metal: Implement fix for non vector4 texture Load/Sample

source/slang/hlsl.meta.slang, source/slang/slang-emit-c-like.cpp, source/slang/slang-emit-metal.cpp, source/slang/slang-ir-inst-defs.h, tests/bugs/atomic-coerce.slang, tests/compute/atomics-buffer.slang, tests/compute/atomics-groupshared.slang, tests/compute/atomics.slang, tests/metal/atomic-intrinsics.slang
This commit adds a support for the atomic intrinsics in Metal.
Metal requires the first argument for the atomic functions to be an atomic data type. This implementation rely on the fact that we can do a C-style type casting from a regular data type to an atomic data type.
=> Support atomic intrinsics for Metal

source/slang/glsl.meta.slang, source/slang/hlsl.meta.slang, tests/compute/texture-subscript-multisample.slang
Close #4427
We had the postfix order wrong for the keyword MS. This commit changes the incorrect name Texture2DArrayMS to Texture2DMSArray.
=> Fix Texture2DMSArray

source/slang/glsl.meta.slang, source/slang/hlsl.meta.slang, tests/hlsl-intrinsic/countbits.slang
Fixes #4439
Adds vector type overloads for the `countbits` intrinsic.
=> Extend `countbits` intrinsic for vector types

.github/workflows/release-linux-glibc-2-17.yml
Forget to enable asserts upload in #4496.
=> Enable upload asset for old glibc build

docs/design/coding-conventions.md
Put space between control-flow and `(`. This is a default formatting setting of Visual Studio 2019 and 2022. And we have been writing the code in this style for a while.
=> Update the coding convention document.

source/slang/hlsl.meta.slang, tests/hlsl-intrinsic/texture/partial-resident-texture.slang
Closes #4438
Closes #4445
Closes #1712
Related to #4495
This commit implements "CheckAccessFullyMapped()" for HLSL target. All of other "status" variants for Sample/Load are limited to HLSL by the capability system, because they not properly implemented yet.
=> Implement CheckAccessFullyMapped

source/slang/slang-parser.cpp, tests/bugs/gh-4457.slang
When a local variable is declaraed, a scope(::) was not properly parsed for its type name. This commit fixes it.
Close #4457
=> Parse scope for local variable declaration

CMakeLists.txt
This commit changes the working directory setting for slangc.exe in Visual Studio Debugging from "build" directory to the root of the repository.
It is often the case that the users debug slang shaders under "tests" directory, and the working directory needs to be manually changed to the root directory of the repository.
=> Set debug working directory for slangc.exe

prelude/slang-torch-prelude.h, source/slang/slang-ir-pytorch-cpp-binding.cpp
This avoids a problem with broadcasted tensors. Our tensor-view platform is designed to allow unrestricted access to tensor memory, while broadcasted tensors were designed for 'read-only' use-cases. Trying to write into a broadcasted tensor needs re-allocation, which Slang is not designed to do.
For now, we enforce contiguity on tensors with any 0 strides.
In the future, we will introduce a ConstTensorView object to allow such tensors to be used as an input.
This patch also propagates name-hint information through structs & arrays of tensors, to allow sensible names for the error messages (before this the error messages were temporary inst numbers, which is nearly impossible to debug)
Resolves a part of #3855 (will open a new issue for ConstTensorView if necessary)
This is a potentially …
=> Error out when constructing tensor views from tensors with 0 stride.

source/slang/hlsl.meta.slang, tests/hlsl/texture-sample-operator.slang
Fixes #4497
Includes a test to ensure the generated code has the appropriate functions for all targets.
=> Support HLSL `.sample` operators for MS textures

source/slang/slang-emit-glsl.cpp, tests/compute/byte-address-buffer-array.slang
In StructuredBuffer::Load(), we allow any type of integer as the input. However, when emitting glsl code,
StructuredBuffer::Load(index)
will be translated to the subscript index of the buffer, e.g. buffer[index], however, glsl doesn't allow 64bit integer as the subscript.
So the easiest fix is to convert the index to integer when emitting glsl.
=> Fix the type error in kIROp_RWStructuredBufferLoad

source/slang/core.meta.slang, tests/bugs/gh-4434.slang, tests/bugs/gh-4441.slang, tests/bugs/gh-4531.slang, tests/bugs/gh-4533.slang
=> Add vector overloads for or and and

source/slang/slang-check-decl.cpp, source/slang/slang-language-server-document-symbols.cpp, source/slang/slang.cpp
Fix language server performance regression due to additional path search, we now always prefer to look at source modules instead of trying to search for binary modules first when in language server mode.
Fix a correctness issue where the synthesized constructor has invalid source loc info and caused visual studio code validation error.
Fixes #4560.
Fixes #4562.
=> Language server performance and document symbol fix.

source/slang/slang-emit-spirv.cpp, source/slang/slang-ir-util.cpp, source/slang/slang-ir-util.h, tests/bugs/gh-4556.slang
This fixes issue: #4556
In emitFloatCast function, we only considered the input type is float scalar or float vector, so if the input type is a float matrix type, it will crash.
We should also handle the float matrix type.
Also, we add some diagnose info to point out the source location where there is error happened, so in the future it's easier to tell us what happens.
=> Fix the issue in emitFloatCast

source/slang/hlsl.meta.slang, source/slang/slang-capabilities.capdef, tests/glsl-intrinsic/clock-read.slang
Close issue #4564.
This change adds the glsl intrinsic clock2x32ARB support.
Also define a cap: GL_ARB_shader_clock.
=> Add intrinsic for clock2x32ARB

tests/bindings/nested-parameter-block-2.slang
With this context filecheck can generate a better error when it fails
=> Neaten filecheck output for non-passing nested-parameter-block test

CMakeLists.txt, cmake/CompilerFlags.cmake, docs/building.md, source/slang/slang-emit-spirv.cpp, source/slang/slang-ir-glsl-legalize.cpp, source/slang/slang-ir-metal-legalize.cpp, source/slang/slang-ir-specialize-address-space.cpp, source/slang/slang-ir-specialize-address-space.h, source/slang/slang-ir-spirv-legalize.cpp, source/slang/slang-ir.h, tests/spirv/address-space-specialize.slang
Closes #4558.
Closes #4380.
This change uses the address space specialization pass to propagate address space to all pointer values, and specialize the callees with address spaces from the argument.
=> Specialize address space during spirv legalization.

CMakePresets.json, docs/building.md, source/slang/slang-check-conversion.cpp, tests/language-feature/interfaces/default-construct-conformance.slang
Closes #4464.
The problem here is that if we have a struct type without a ctor:
```
struct Foo : IInterface
{
}
```
And then if we return a default construct of `Foo` as an exsitential:
```
IInterface makeFoo()
{
return Foo();
}
```
We will translate `Foo()` call into an `InitializerListExpr` because `Foo` does not have a ctor.
However, when coercing `InitializerListExpr` to the return type `IInterface`, we are just directly producing an initializerListExpr for `IInterface`, which becomes `return IInterface{};`. This is obviously wrong because the type info is lost.
Instead we need to make sure not to go into `coerceInitializerListExpr` if the expr to be coerced is already a coerced initializer list (where the type is no longer `InitializerListType`).
=> Fix incorrect codegen when returning initializer list as existential value.

source/slang/slang-emit.cpp, tests/compute/struct-autodiff-default-init.slang
Fixes #4622
Problem:
Currently, if a decoration refers to its-parent through its operands we will have a recursive dependency and fail. The reason we encounter this problem is because autodiff decorations are not stripped if the autodiff -pass never runs. This happens due to the autodiff pass not running if we only have a `IRDerivativeMemberDecoration`.
Solution:
Start autodiff pass if we found a `IRDerivativeMemberDecoration`.
=> Start autodiff pass if `IRDerivativeMemberDecoration` is found

tools/gfx/d3d11/d3d11-shader-object.cpp, tools/gfx/metal/metal-command-buffer.h, tools/gfx/metal/metal-device.h, tools/gfx/metal/metal-pipeline-state.h, tools/gfx/metal/metal-shader-object.cpp, tools/gfx/metal/metal-shader-program.h
The cause of the test correctness issue in the offset computation when binding a shader object as a constant buffer leads to double counting of index offsets when a default constant buffer needs to be created for the entrypoint object.
The problem of the memory leak issue is that PipelineState and ShaderProgram should not store a storng reference back to device, because a device contains a pipeline state cache that stores a reference to all currently created pipeline states. Having PipelineState reference back a device leads to a cyclic reference preventing destruction of all objects.
Fixes #4545.
=> Fix gfx/metal uniform data binding and memory leaks.

source/slang/slang-emit.cpp, source/slang/slang-ir-legalize-is-texture-access.cpp, source/slang/slang-ir-legalize-is-texture-access.h, tests/hlsl-intrinsic/atomic/atomic-intrinsics.slang
Fixes: #4639
Currently we use 'simplify CFG' to remove unused blocks using `isTextureAccess` functions. This works because the code then uses the 'simplify SCCP' inside 'SimplifyIR' to remove all code associated with unused code blocks.
Due to reliance on 'SimplifyIR' this code does not work when using slang with a 'minimal optimization flag'. Calling 'simplify SCCP' directly solves this dependency.
=> SCCP instead of CFG to clear unused blocks using `isTextureAccess` with `static_assert`

source/slang/slang-check-decl.cpp, tests/compute/assoctype-nested-lookup.slang
This is a quick fix:  we weren't registering a synthesized constructor onto the witness table for dynamic dispatch.
Fixes: https://github.com/shader-slang/slang/issues/4637
=> Fix issue with synthesized `__init` methods not getting added to witness table

docs/design/autodiff/basics.md
Adjusted latex expressions to suit Github's quirky markdown system
Fixes #4381
=> Fix latex rendering errors in auto-diff docs

source/compiler-core/slang-lexer.cpp, tests/bugs/gh-4667.slang
closes https://github.com/shader-slang/slang/issues/4667
=> Correctly parse multiple escaped newlines

source/slang/slang-ir-use-uninitialized-values.cpp, tests/diagnostics/uninitialized-local-variables.slang, tests/hlsl-intrinsic/size-of/align-of-3.slang, tests/hlsl-intrinsic/size-of/size-of-3.slang
Addressed to #3832 
Fixes a bug in #4530 which results in the warning system ignoring uninitialized variables in nested scopes.
=> Fix bug with uninitiailized variable warnings in nested scopes

source/slang/slang-emit-spirv-ops-debug-info-ext.h, source/slang/slang-emit-spirv.cpp, tests/spirv/debug-type-pointer.slang
This change supports OpDebugTypePointer for a member variable whose type is a pointer type for the outer struct that hasn't been declared yet. It is done with new extension, "SPV_KHR_relaxed_extended_instruction", that comes with a new instruction, "OpExtInstWithForwardRefs".
Closes #4304
=> Support OpDebugTypePointer for struct member pointer

source/slang/slang-ast-decl.h, source/slang/slang-check-decl.cpp, source/slang/slang-diagnostic-defs.h, source/slang/slang-ir-inst-defs.h, source/slang/slang-ir-insts.h, source/slang/slang-ir-use-uninitialized-values.cpp, source/slang/slang-lower-to-ir.cpp, tests/compute/struct-default-init.slang, tests/diagnostics/uninitialized-fields.slang, tests/language-feature/struct-field-initializers/struct-field-initializer.slang
Addresses #4578 
Adds new tests in the file `tests/diagnostics/uninitialized-fields.slang`.
Warnings will look like the following:
```
.\tests\diagnostics\uninitialized-fields.slang(22): warning 41020: exiting constructor without initializing field 'next'
__init(int v, Simple* ptr)
^~~~~~
.\tests\diagnostics\uninitialized-fields.slang(39): warning 41020: exiting constructor without initializing field 'another_field'
return;
^~~~~~
.\tests\diagnostics\uninitialized-fields.slang(60): warning 41021: default initializer for 'Implicit' will not initialize field 'a'
int a;
^
.\tests\diagnostics\uninitialized-fields.slang(63): warning 41021: default initializer for 'Implicit' will not initialize field 'c'
int c;
^
```
New decorations:
* ConstructorDecoration: indicates whether an IRFunc is a …
=> Warnings for uninitialized fields in constructors

source/slang/slang-mangle.cpp, tests/diagnostics/illegal-func-decl-module.slang, tests/diagnostics/illegal-func-decl.slang
During our name mangling, we should add the direction of the parameter in the name, otherwise it could have the name collision which will result in invalid code generation:
e.g.
// in slang-module.slang
export func(float a) { ...}
// in test.slang
extern func(inout float a);
when we compile test.slang, slang will pass a pointer type to the 'func', however, in the slang-module.slang, `func` expects a value instead of pointer. This will lead the wrong spirv code.
So we should add the parameter direction into the mangle name such that above two symbols will have the different mangled names, and we will catch this during IR-link stage.
=> Fix the issue of name mangling

CMakeLists.txt
In the change:
2db15080 Move the file public header files to `include` dir (#4636)
we miss the installation of the public headers as they move to a new `include` folder, and cpack doesn't catch those automatically.
Therefore, add the install command to install those headers.
=> Install the missing public headers in release package

source/slang/slang-emit-spirv.cpp, tests/bindings/binding-spv-storage-class.slang
In
https://registry.khronos.org/vulkan/specs/1.3/html/chap37.html#VUID-StandaloneSpirv-DescriptorSet-06491
it states that
If a variable is decorated by DescriptorSet or Binding, the Storage class must be UniformConstant, Uniform and StorageBuffer.
So apply this rule to our emit-spirv logic.
=> Allow only specific spv storage classes for binding decoration

include/slang.h, source/compiler-core/slang-spirv-core-grammar.h, source/core/slang-performance-profiler.cpp, source/core/slang-performance-profiler.h, source/slang/slang-api.cpp, source/slang/slang-capability.h, source/slang/slang.cpp, source/slangc/main.cpp, tools/render-test/render-test-main.cpp, tools/slang-capability-generator/capability-generator-main.cpp, tools/slang-reflection-test/slang-reflection-test-main.cpp, tools/slang-spirv-embed-generator/spirv-embed-generator-main.cpp, tools/slang-test/slang-test-main.cpp, tools/slangd/main.cpp, tools/test-server/test-server-main.cpp
Closes #4208.
We have many global constants that holds heap allocated memory. This PR adds a `slang::shutdown()` API to clean them up.
This isn't strictly necessary to call from user code, but it gets rid of crt memory leak detection errors.
=> Cleanup global memory allocations on shutdown.

source/slang/slang-check-decl.cpp, tests/bugs/gh-4633.slang
Closes #4633.
Checking of initExpr should be left for a later checking pass.
=> Fix checking of var with matrix layout modifier.

source/slang/slang-ast-builder.h, source/slang/slang-ast-type.cpp, source/slang/slang-check-decl.cpp, tests/bugs/extended-type-in-param.slang
This PR includes two fixes. Closes #4699.
We need to make sure all extensions are discovered and registered before checking the function parameters, otherwise we will fail to recognize that a parameter type is valid due to missing knowledge about the type conformances brought in through extensions. This is done by slightly modifying `checkModuleDecl` to discover all extension decl and call ensureDecl on them before checking other decls.
When synthesizing the requirement for `IDifferentiable` inside an extension decl, we need to make sure the decl ref to the synthesized function/associated type contains a correct reference to the enclosing extension decl. This is done by calling `applyExtensionToDecl`.
=> Fix around extensions and `IDifferentiable` requirement synthesis. 

source/slangc/main.cpp
This commit makes the memory leaks harder to miss by triggering an assertion failure for memory leaks. It works only for Windows Debug build.
SLANG_ASSERT doesn't print the info where the assertion failure happens, for an unknown reason. Using the system assert as a workaround.
=> Fail assertion on debug build when memory leaks

source/slang/slang-ir-inst-defs.h, source/slang/slang-ir-use-uninitialized-values.cpp, tests/diagnostics/uninitialized-globals.slang
Fixes an undesired warning issued when using GLSL layout variables. The higher level problem is that the warning system was not skipping checks for input global variables.
=> Disable warnings for input global variables

docs/user-guide/02-conventional-features.md, source/slang/core.meta.slang, source/slang/slang-ast-support-types.h, source/slang/slang-check-conversion.cpp, source/slang/slang-diagnostic-defs.h, source/slang/slang-emit.cpp, source/slang/slang-ir-autodiff-fwd.cpp, source/slang/slang-ir-check-unsupported-inst.cpp, source/slang/slang-ir-inst-defs.h, source/slang/slang-ir-peephole.cpp, source/slang/slang-ir-specialize-arrays.cpp, source/slang/slang-ir-specialize-function-call.cpp, source/slang/slang-ir-specialize-function-call.h, source/slang/slang-ir.cpp, tests/language-feature/unsized-array.slang
Closes #4701.
This changes extends the function call specialization pass to be able to specialize the type of a parameter.
If we see a call with sized array arguments to an unsized array parameter, we will specialize the callee to take a sized array parameter instead. This allows us to implement `kIROp_GetArrayLength` opcode that returns the size of an array.
If we cannot optimize out GetArrayLength, we will diagnose an error. This will the case if the user calls GetArrayLength on an unsized array that cannot be resolved to a sized array during compilation.
=> Allow passing sized array to unsized array parameter.

source/slang/slang-emit-spirv.cpp, source/slang/slang-ir-util.cpp, tests/spirv/small-int-texture.slang
=> Fix SPIRV emit for small-integer texture types.

source/slang/slang-check-conversion.cpp, tests/bugs/assign-nullptr.slang
Fixes #4754
Changes:
* Currently the way we resolve `nullptr` produces invalid code-gen due to type-mismatching. Now we assign `nullptr` by using `DefaultConstructExpr` to assign a `nullptr`. This correctly assigns `nullptr` to the target `T*` type since the default of `T*` is `nullptr`.
=> Set `nullptr` to coerce into the default value of `T*` type

source/slang/slang-diagnostic-defs.h, source/slang/slang-emit.cpp, source/slang/slang-ir-check-shader-parameter-type.cpp, source/slang/slang-ir-check-shader-parameter-type.h, source/slang/slang-ir-insts.h, source/slang/slang-ir-legalize-types.cpp, source/slang/slang-ir.cpp, source/slang/slang-legalize-types.cpp, tests/bindings/nested-parameter-block-3.slang, tests/diagnostics/nested-constant-buffer-in-parameter-block.slang, tools/gfx/d3d12/d3d12-shader-object-layout.cpp, tools/gfx/d3d12/d3d12-shader-object-layout.h
On metal, we map `ParameterBlock<T>` to an argument buffer represented as `T constant *`.
This means that no type legalization should take place for `ParameterBlock<T>`.
However, this leads to a problem when the user has:
```
struct MyResourceTypes { Texture2D t; RWStructuredBuffer<uint> v; };
ParameterBlock<MyResourceTypes> gRes; // gRes is not legalized and translated to pointer as is.
void f(MyResourceTypes t) // `t` here is legalized out to individual resource typed parameters.
{
// ...
}
void main()
{
f(gRes); // we must handle this call correctly to deal with the fact that gRes is not legalized and f is legalized.
}
```
To make the above case work, this change extended the type legalization logic to allow a `LegalVal::Flavor::simple` legalVal to be coerced into a LegalType that is …
=> Fixes for Metal ParameterBlock support.

source/slang/slang-lower-to-ir.cpp, tests/language-feature/constants/static-const-in-generic-interface.slang, tests/language-feature/interfaces/generic-interface-conformance.slang, tools/slang-test/slang-test-main.cpp
Closes #4749.
The issue being fixed here is that when we lower a generic interface to IR, the function types aren't lowered from proper DeclRef with default substitute info, so they end up being direct `IRGeneric` insts, instead of a `specialize(IRGeneric, ...)` inst. This leads to incorrect interface types after specialization pass. The fix is simply lower the function types using a declref.
=> Fix IR lowering for generic interface types.

source/slang/slang-ir-reachability.cpp, source/slang/slang-ir-reachability.h, source/slang/slang-ir-use-uninitialized-values.cpp, source/slang/slang-lower-to-ir.cpp, tests/diagnostics/uninitialized-out-parameters.slang
Handles #4720 
Also adds a fix to skip generating IR for empty target switches. Previously this would result in generating an unreachable block, which would have necessitated special handling for target switches.
=> Warnings target switch intrinsic asm

source/slang/slang-check-decl.cpp, source/slang/slang-parser.cpp, tests/language-feature/enums/reference-previous.slang
=> Allow an enum case to reference a previously defined value.

source/compiler-core/slang-dxc-compiler.cpp
Some debug code was left in by accident which called DXC to disassemble the DXIL it produced.
=> Remove dxc disassemble debug code

source/core/slang-io.cpp, source/core/slang-io.h, source/slang-record-replay/record/output-stream.cpp, source/slang-record-replay/record/output-stream.h, source/slang-record-replay/record/record-manager.cpp, source/slang-record-replay/record/record-manager.h, source/slang-record-replay/record/slang-filesystem.cpp, source/slang-record-replay/replay/json-consumer.cpp, source/slang-record-replay/replay/json-consumer.h, source/slang-record-replay/replay/recordFile-processor.h, source/slang-record-replay/util/record-utility.cpp, tools/slang-replay/main.cpp
This is a first effort on reducing dependency on the std library, which is needed for #4784.
Usage of `std::string` is replaced with `Slang::String`.
Usage of `std::filesystem` is replaced with `Slang::String`, `Slang::File` and `Slang::Path` utilities.
`<filesystem>` is now only used in `slang-io.cpp` for `getRelativePath` and `createDirectoryRecursive` implementations. These should be replaced in future PRs.
=> Reduce dependency on std library

source/slang/core.meta.slang, source/slang/diff.meta.slang, source/slang/slang-ast-modifier.h, source/slang/slang-diagnostic-defs.h, source/slang/slang-emit-c-like.cpp, source/slang/slang-emit-spirv.cpp, source/slang/slang-ir-addr-inst-elimination.cpp, source/slang/slang-ir-autodiff-transcriber-base.h, source/slang/slang-ir-inst-defs.h, source/slang/slang-ir-insts.h, source/slang/slang-ir-use-uninitialized-values.cpp, source/slang/slang-lower-to-ir.cpp, source/slang/slang.cpp, tests/autodiff/reverse-inout-param-custom-derivative.slang, tests/bugs/gl-33-ext.slang, tests/bugs/optional.slang, tests/diagnostics/inout-never-written.slang, tests/hlsl-intrinsic/matrix-double.slang, tests/hlsl-intrinsic/size-of/align-of-3.slang, tests/hlsl-intrinsic/size-of/size-of-3.slang, tests/language-feature/struct-field-initializers/struct-field-no-initializer-complex-types.slang, tests/language-feature/unsized-array.slang, tests/pipeline/ray-tracing/trace-ray-inline.slang
Addresses #4698 as one approach to diagnose the potential problem.
A new intrinsic function `unmodified(inout T)` has been added to explicitly indicate that an `inout` variable will not be modified in the function.
This is only one way to address the specific validation error in #4698. In general it seems that DXC does some more extensive checks on actual struct fields (as opposed to observing arbitrary struct writes), so that will be the next step.
=> Warn when inout parameter is never written

source/compiler-core/slang-lexer.cpp, source/core/slang-char-encode.cpp, source/core/slang-char-encode.h, source/core/slang-char-util.h, source/core/slang-std-writers.cpp, source/slang/slang-language-server-document-symbols.cpp, source/slang/slang-language-server.cpp, source/slang/slang-workspace-version.cpp, source/slang/slang-workspace-version.h, tests/front-end/unicode-identifier.slang
Closes #4553.
The main fix here is to handle unicode utf8 bytes during lexing, and treat all unicode characters as a valid identifier character.
=> Support unicode identifier names.

source/slang/slang-emit-glsl.cpp, tests/bugs/gh-4818-1.slang, tests/bugs/gh-4818-2.slang
Fixes #4818
Emit memory qualifiers once when compiling to GLSL.
This is required because 2 of the same memory qualifiers on an object is a compile error
=> Emit memory qualifiers once when compiling to GLSL

CONTRIBUTION.md
This commit adds a quick build step for MacOS on CONTRIBUTION.md.
It is unclear what are the conditions that slang-llvm needs to be rebuilt locally. An issue is filed for it, #4812
=> Update build steps for MacOS

source/slang/slang-ir-use-uninitialized-values.cpp, tests/diagnostics/inout-never-written.slang
Noticed this when warnings are issued from #4823, so there are additional tests added to `inout-never-used.slang`.
Previously, the warnings were:
```
environment.slang(22): warning 41022: inout parameter 'seed' is never written to
public float3 environment_sample(StructuredBuffer <Environment_sample_data> sample_buffer, inout int seed)
^~~~~~~~~~~~~~~~~~
hit.slang(5): warning 41022: inout parameter 'seed' is never written to
float3 sample_lights(inout uint seed)
^~~~~~~~~~~~~
```
With this PR they should not be emitted.
=> Include inout cast operation as an aliasing instruction

source/slang/slang-syntax.cpp, tests/modules/compile.bat, tests/modules/environment.slang, tests/modules/hit.slang
=> Avoiding the use of the global AST builder in DeclRefType::create

source/slang/slang-check-expr.cpp, tests/bugs/gh-4863.slang
Closes #4863.
The fix here is to make sure we resolve overloaded exprs for call arguments.
=> Make sure to resolve overloaded expr for call args.

source/slang/slang-ast-synthesis.h
Fixes #4879
Track ContainerDecl with synthesized scope variable for `DifferentialType`
=> Track ContainerDecl with synthesized scope variable for `DifferentialType`

source/slang/slang-ir-use-uninitialized-values.cpp
Fixes #4878
Track uninitialized values of `Ptr<Specialize<T>>` inside type `T` without hang
Note: related to `tests/reflection/ptr/ptr-generic.slang`
=> Track uninitialized values of `Ptr<Specialize<T>>` inside type `T` without hang

source/slang/slang-doc-ast.cpp, source/slang/slang-doc-ast.h, source/slang/slang-doc-markdown-writer.cpp
Fixes #4888
Changes to exclude synthesized code from code-auto-documentation system
=> Exclude synthesized code from code auto documentation system

tests/bugs/gh-3087-multi-entry-point.slang, tests/bugs/gh-3087.slang
With the current SPIR-V, the test emits the following,
```
; Annotations
OpDecorate %8 Flat
; Types, variables and constants
%8 = OpVariable %_ptr_Input_int Input
```
With the latest SPIR-V, the same test emits the following with an additional comment,
```
; Annotations
OpDecorate %8 Flat
; Types, variables and constants
%8 = OpVariable %_ptr_Input_int Input ; Location 0, Flat
```
This results in a false failure where it is not a real failure.
=> Fix a false failure when using the latest SPIR-V

examples/cpu-hello-world/main.cpp, examples/example-base/example-base.cpp, examples/example-base/test-base.cpp, examples/example-base/test-base.h, examples/ray-tracing/main.cpp, examples/shader-object/main.cpp, source/slang-record-replay/record/slang-module.cpp, source/slang-record-replay/record/slang-module.h, source/slang-record-replay/record/slang-session.cpp, source/slang-record-replay/record/slang-session.h, source/slang-record-replay/replay/json-consumer.cpp, source/slang-record-replay/replay/parameter-decoder.h, source/slang-record-replay/replay/replay-consumer.cpp, source/slang-record-replay/replay/replay-consumer.h, source/slang-record-replay/replay/slang-decoder.cpp, tools/slang-unit-test/unit-test-record-replay.cpp
Migrate cpu-hello-world to new slang API and add it to slang-unit-test
Add 'shader-object' to slang-unit-test
Convert ray-tracing example into slang-unit-test
Fix bugs in record-replay layer:
- Wrong decode type in array size in specialize() call.
- Wrong decode type in 'getEntryPointHostCallable'.
- Mistakes in computing the output buffer size.
- When capture entrypoint, we should increase the reference count
for the allocated entrypoint recorder object, because that is
allocated by record layer, it should be owned by the layer, user
should not be able to free it.
=> Migrate examples

docs/user-guide/03-convenience-features.md, source/slang/core.meta.slang, source/slang/slang-check-decl.cpp, source/slang/slang-check-expr.cpp, source/slang/slang-check-impl.h, source/slang/slang-diagnostic-defs.h, source/slang/slang-parser.cpp, tests/language-feature/ifunc/diff-functor.slang, tests/language-feature/ifunc/functor.slang, tests/language-feature/ifunc/ifunc.slang
Partially address #4892.
This PR adds the syntax support for calling a functor directly with `operator ()`.
=> Add functor syntax support.

source/slang/slang-ir-use-uninitialized-values.cpp, tests/diagnostics/uninitialized-fields-delegated.slang, tests/diagnostics/uninitialized-fields.slang
=> Ignoring construct field warnings on delegatory methods

source/slang/core.meta.slang, source/slang/slang-check-overload.cpp, tests/language-feature/generics/variadic-partial-inference.slang
=> Fix partial inference of variadic generic functions.

tests/ir/factorial.slang, tests/ir/string-literal-hash-reflection.slang, tests/ir/string-literal.slang
A correct semantic name is SV_DispatchThreadID with "ID" not "Index". Those tests don't actually run and they haven't caused any problems yet.
=> Fix typo SV_DispatchThreadIndex

source/slang/core.meta.slang, source/slang/diff.meta.slang, source/slang/slang-ast-modifier.h, source/slang/slang-ir-autodiff.cpp, source/slang/slang-ir-inst-defs.h, source/slang/slang-ir-insts.h, source/slang/slang-lower-to-ir.cpp, tests/language-feature/generics/variadic-0.slang
Closes #4957.
This is to make sure we always remove the `export`/`keepalive` decorations on the builtin `NullDifferential` type regardless of whether autodiff pass is run. To make it easy to identify this type from the linked IR, we add a `[__AutoDiffBuiltin]` attribute so we can easily trigger the logic to remove `export` decoration when we see this decoration.
=> Make sure `NullDifferential` and its witness are removed after autodiff.

source/slang/core.meta.slang, source/slang/slang-ast-modifier.h, source/slang/slang-check-impl.h, source/slang/slang-check-modifier.cpp, source/slang/slang-emit-c-like.cpp, source/slang/slang-emit-c-like.h, source/slang/slang-emit-glsl.cpp, source/slang/slang-emit-glsl.h, source/slang/slang-emit-spirv-ops.h, source/slang/slang-emit-spirv.cpp, source/slang/slang-ir-inst-defs.h, source/slang/slang-ir-insts.h, source/slang/slang-ir-spirv-legalize.cpp, source/slang/slang-lower-to-ir.cpp, source/slang/slang-parameter-binding.cpp, source/slang/slang-parser.cpp, source/slang/slang-type-system-shared.h, tests/language-feature/zero-initialize/struct.slang, tests/spirv/specialization-constant.slang
This PR adds support for specialization constants in both spirv and glsl backends.
Speecialization constants can now be declared with:
```
[vk::specialization_constant]
const int specConst = 1; // implicit layout
[vk::constant_id(7)] // explicit layout
const int specConst = 1;
layout(constant_id = 9]
const int specConst = 1; // glsl flavor
```
Closes #3581.
=> Support specialization constants.

source/core/slang-io.cpp, source/core/slang-io.h, tools/slang-unit-test/unit-test-record-replay.cpp
We've implemented a function in slang-record-replay unit test to remove the non-empty directory, now move this function into slang `Path` namespace to make this function as an utility.
Close issue #4916
=> Add Path::removeNonEmpty() to remove non-empty dir

docs/user-guide/03-convenience-features.md, docs/user-guide/06-interfaces-generics.md, source/slang/slang-check-constraint.cpp, source/slang/slang-check-decl.cpp, source/slang/slang-check-inheritance.cpp, source/slang/slang-check-overload.cpp, source/slang/slang-diagnostic-defs.h, tests/diagnostics/interfaces/interface-extension.slang, tests/language-feature/extensions/extension-override.slang
With `extension<T:IFoo> T` supported, this PR disallows the ill-defined `extension IFoo` syntax.
This is a technically breaking change, but we must clean up this part of the language before more widespread use of this problematic feature.
Also added a test to make sure the overriding behavior of extensions are correct.
`extension IFoo {}` where `IFoo` is an interface type will now result in a compile time error. This kind of code should always be written as `extension<T:IFoo> T` in the future.
=> Fix extension override behavior, and disallow extension on interface types.

source/slang/slang-check-decl.cpp, source/slang/slang-check-overload.cpp, tests/bugs/gh-4467.slang
Closes #4467.
The problem revealed here is that in `ResolveInvoke` we are performing `openExistential` on arguments before resolving overloaded callees. This is needed in order to correctly resolve generic arguments for generic callees. However we can't always us the opened existential value as argument if the parameter is mutable.
So the fix here is to switch back to original argument expr after an overload candidate is picked and we can figure out the corresponding parameter is a mutable one.
=> Open existential on arguments after overload resolution.

source/slang/slang-ir-specialize-resources.cpp, tests/library/precompiled-module-library-resource.slang
fixes: #4989
Changes:
1. Before handing off to DCE an `oldFunc` which should be removed, clean up any leftover `IRKeepAliveDecoration` (else DCE won't remove our `oldFunc`s)
=> Fix resource specialization with `-embed-dxil`

source/slang/slang-check-decl.cpp, source/slang/slang-check-expr.cpp, source/slang/slang-check-impl.h, source/slang/slang-check-overload.cpp, source/slang/slang-language-server-semantic-tokens.cpp, source/slang/slang-language-server.cpp, tests/language-server/this-type-hover.slang
Closes #4981.
Fix a bug in language server that incorrectly highlights `This` type declref using the token length of the actual type name instead of just highlighting 4 characters.
The fix is to make sure the `name` field of constructed `DeclRefExpr` for the lookup result uses the `name` from the original `VarExpr` instead of the name from the referenced decl.
=> Preserve name in DeclRefExpr for correct highlighitng of `This`.

docs/user-guide/a2-target-specific-features.md, docs/user-guide/a3-01-reference-capability-profiles.md, docs/user-guide/a3-02-reference-capability-atoms.md, docs/user-guide/a3-reference.md, docs/user-guide/toc.html, external/CMakeLists.txt, source/slang/slang-capabilities.capdef, tools/slang-capability-generator/capability-generator-main.cpp, tools/slang-capability-generator/slang-capability-diagnostic-defs.h
Fixes: #4125
Unimplemented Considerations:
1. This PR does not add support to query all capability-atom's from a command-line option. It is understood that this might be desired, due to this, the logic to generate `docs\user-guide\a3-02-reference-capability-atoms.md` was made to be "command-line friendly" so minimal changes are needed to pipe our documentation into a command-line option if this change is to be added.
Changes:
1. Added a way to document atoms inside `.capdef`. Method to document is described under `source\slang\slang-capabilities.capdef`. The goal is to error if a public atom does not have any form of documentation to ensure we always have up-to-date documentation to guide user on what an atom is/does. 
* The following `.capdef` file syntax was added 
* /// [HEADER_GROUP] …
=> Document All Capability Atoms and Profiles

source/slang/slang-check-decl.cpp, source/slang/slang-emit-c-like.cpp, source/slang/slang-emit-c-like.h, source/slang/slang-emit-cuda.cpp, source/slang/slang-emit-cuda.h, source/slang/slang-emit-glsl.cpp, source/slang/slang-emit-glsl.h, source/slang/slang-emit-hlsl.cpp, source/slang/slang-emit-hlsl.h, source/slang/slang-emit-metal.cpp, source/slang/slang-emit-metal.h, source/slang/slang-type-layout.cpp, tests/compute/constant-buffer-memory-packing.slang, tests/language-feature/types/matrix-layout-uniform.slang
Closes #4873.
Also fixes incorrect metal constant buffer layout calculation revealed by a test.
=> Respect matrix layout in uniform and in/out parameters for HLSL target.

source/slang/slang-check-constraint.cpp, source/slang/slang-emit.cpp, source/slang/slang-ir-inst-defs.h, source/slang/slang-ir-insts.h, source/slang/slang-ir-specialize.cpp, tests/language-feature/generics/generic-return-type-requirement.slang, tests/language-feature/generics/nested-gen-value-param-inference-2.slang, tests/language-feature/generics/nested-gen-value-param-inference.slang, tests/language-feature/interfaces/default-construct-conformance.slang
Paritally addresses #5035.
This PR enhances our specialization logic so that functions that returns an existential value can now be specailized into a function that returns a concrete type. This avoid us generating unnecessary dynamic dispatch logic when the return type of the function is statically known.
=> Specialize existential return types when possible.

source/slang/slang-check-overload.cpp, tests/language-feature/overloaded-subscript.slang
Closing #5034.
Directly allowing defining `set` and `get` in different subscript decls and allow deferred overload resolution is tricky to support. However it is trivial to add a disambiguation rule to prefer the one with more complete accessors. This should allow example like #5034 to work, but in a slightly different way:
```
//TEST(compute):COMPARE_COMPUTE_EX(filecheck-buffer=CHECK):-slang -compute -shaderobj -output-using-type
//TEST(compute, vulkan):COMPARE_COMPUTE_EX(filecheck-buffer=CHECK):-vk -compute -shaderobj -output-using-type
// Test that we can disambiguiate subscript decls by prefering the candidate that contains a super set of
// accessors than the other candidates.
interface IBuf<T>
{
T read(int x);
}
interface IRWBuf<T> : IBuf<T>
{
[mutating]
void write(int x, T v);
} …
```
=> Disambiguate subscript decls by preferring the one with more accessors.

.gitignore
Following git-ignore rules are added to ignore VIM temporary files:
- *\~: Ignores all files ending with a tilde (~), which are Vim's backup files.
- .*.swp: Ignores Vim swap files, which have .swp extension.
- .*.swo: Ignores Vim swap files created when a .swp file already exists.
=> Git-ignore for VIM temporary files

source/slang/slang-check-overload.cpp, tests/bugs/overload-ambiguous.slang
This change fix the issue #4476.
When looking up the overloaded functions, we need to consider the declaration's distance to the global scope, and will prefer the farther one. The reason that this can work is because in overloaded resolution function `CompareLookupResultItems`, only valid candidates will be considered here, so farther to the global scope implies it's more closer to the callsite. And we really want to choose the one closer to the callsite.
=> Fix the issue in resolving the overload functions

source/slang-glslang/slang-glslang.cpp
The slang-glslang.cpp file was including private glslang headers, however they don't even seem to be necessary and can be safely removed. After this change, only the public glslang headers are used.
=> Remove includes of glslang private headers

include/slang.h, source/slang/hlsl.meta.slang, source/slang/slang-capabilities.capdef, tests/wgsl/math.slang, tools/slang-test/slang-test-main.cpp, tools/slang-test/test-context.h
This commit implements math related intrinsics and a few others for WGSL.
The implementation is based on the following doc,
https://www.w3.org/TR/WGSL
=> Implement math intrinsics for WGSL

source/slang/hlsl.meta.slang
Two WGSL functions have little different behavior compared to other shader languages: frexp and modf.  They return a struct to return two values.
For more details, see:
https://www.w3.org/TR/WGSL/#frexp-builtin
https://www.w3.org/TR/WGSL/#modf-builtin
=> Fix WGSL frexp and modf that returns a struct

source/slang/slang-check-overload.cpp, tests/bugs/overload-ambiguous-1.slang, tests/bugs/overload-ambiguous-2.slang, tests/bugs/overload-ambiguous.slang, tests/diagnostics/overload-ambiguous.slang
In the previous change of #5060, we propose a way to resolve the ambiguous call when considering the scope of a function.
But this rule should be considered as a low priority than "specialized candidate", aka. we should consider more "specialized candiate" first.
=> Lower the priority of looking up the rank of scope

source/slang/hlsl.meta.slang, source/slang/slang-capabilities.capdef
=> Add WGSL intrinsics for synchronization

tools/render-test/options.cpp, tools/render-test/options.h, tools/render-test/render-test-main.cpp, tools/render-test/shader-input-layout.cpp, tools/render-test/shader-renderer-util.cpp, tools/render-test/shader-renderer-util.h, tools/render-test/slang-support.cpp, tools/render-test/slang-support.h
- Update to latest version of `slang-rhi`.
- Refactor render test to new `slang-rhi` API.
=> refactor render test to use latest slang-rhi

source/slang/slang-check-decl.cpp, source/slang/slang-check-impl.h, source/slang/slang-diagnostic-defs.h, tests/diagnostics/generic-constraint-left-hand-side.slang
(This PR is based on top of PR #5111.)
Add validation on left hand side of type generic. For example, we need to diagnose an error for:
```
void foo<T>() where int : X {} // int cannot be left hand side of a generic constraint.
```
Closes #5113.
=> Add diagnostic to verify the left hand side of a generic constraint.

source/slang/hlsl.meta.slang, source/slang/slang-capabilities.capdef, source/slang/slang-emit-wgsl.cpp, source/slang/slang-stdlib-textures.cpp, source/slang/slang-stdlib-textures.h, tests/wgsl/texture.slang
This PR implements all of the texture intrinsics for WGSL except "Gather" and sampler-less.
They will be implemented in a separate PR.
A few things to note:
- texture sampling functions are available only for the fragment shader stage; not for compute
- WGSL doesn't have any functions similar to CalculateLevelOfDetail or CalculateLevelOfDetailUnclamped.
- WGSL doesn't have a function overlaoding for `textureSample` with "clamp" or "status" arguments.
- WGSL doesn't support Load operation with offset for texture_multisampled_XX and texture_storage_XX.
- WGSL supports only four types of depth textures: 2D, 2D_array, cube and cube_array.
- WGSL doesn't support "offset" variants for cube and cube_array.
=> WGSL implement texture intrinsics except gather and sampler-less

source/slang/slang-emit-c-like.cpp, source/slang/slang-emit-c-like.h, source/slang/slang-emit-wgsl.cpp, source/slang/slang-emit-wgsl.h, source/slang/slang-ir-wgsl-legalize.cpp, tests/language-feature/atomic-t/atomic-0.slang, tests/wgsl/inout.slang
This PR overhauls the logic of handling pointer dereference in WGSL backend.
Basically we treat WGSL as a target that doesn't support pointers, so we never emit any pointer logic for variable reference or structured buffer reference, i.e. no `*`, `&`, `->` etc. through out the emit logic like what we are doing for hlsl and glsl, except:
1. When emitting an `inout` parameter, emit it as `ptr<function, T> param`.
2. When referencing a `inout` parameter as operand, emit it as `(*param)` so the rest of logic won't need to deal with pointers.
3. When calling a function with an argument to an `inout` parameter, emit the argument as `&arg`.
Aside from call sites, we treat wgsl as a language that doesn't have pointers everywhere else. This should work exactly as WGSL expected, since pointers in …
=> Fix handling of pointer logic in wgsl backend.

source/slang/hlsl.meta.slang, source/slang/slang-stdlib-textures.cpp
Closes #5143
Recently there was a commit that changed the behavior of the memory pointer for WGSL.
This commit fixes some issues came up after the change.
=> Fix incorrect use of pointer in WGSL

external/CMakeLists.txt
- Add initial support for WebGPU using Google Dawn.
=> update slang-rhi with initial wgpu support

source/slang/slang-compiler.cpp, source/slang/slang-emit.cpp, source/slang/slang-ir-lower-combined-texture-sampler.cpp, source/slang/slang-ir-lower-combined-texture-sampler.h, source/slang/slang-type-layout.cpp, tests/wgsl/texture-sampler-less.slang
The implementation in hlsl.meta.slang for combined texture was already committed and it appears to be working fine.
The trouble was more on the layout rule where the synthesized textures and samplers were not getting the binding offset values correctly.
When the combined-texture is used, it is replaced with a texture and a sampler.
For WGSL, both cases get layout info as `LayoutResourceKind::DescriptorTableSlot`.
This is little different from how it is handled in HLSL where Texture got `LayoutResourceKind::ShaderResource` and Sampler got `LayoutResourceKind::SamplerState`
This commit also adds a new layout-rule for WGSL.
It is mostly identical to the layout-rule for GLSL.
The difference is that Combined-texture is handled little differently.
This is because for GLSL, there is an actual …
=> Implemented Combined-texture for WGSL

source/slang/hlsl.meta.slang
`$p` was incorrectly removed on the previous commit. This commit brings it back and fixes the problem.
This is to fix the regression on CI.
=> Fix the incorrect use of GLSL textureGather

CMakeLists.txt, CMakePresets.json, docs/building.md, include/slang.h, source/core/slang-io.cpp, source/slang/slang-ast-dump.cpp, source/slang/slang-parameter-binding.cpp, source/slang/slang-workspace-version.cpp, source/slang/slang-workspace-version.h
Add support for Wasm build target
=> Enable emscripten builds to compile slang.dll to WebAssembly.

source/slang/hlsl.meta.slang, source/slang/slang-intrinsic-expand.cpp, tests/wgsl/texture-gather.slang, tests/wgsl/texture-load.slang, tests/wgsl/texture.slang
This commit fixes a few issues with WGSL texture intrinsics.
- static_assert-s are corrected.
- Gather functions work properly with depth textures
- Load functions work properly with depth textures
=> WGSL texture support for depth and multisampled

source/slang/hlsl.meta.slang, source/slang/slang-emit-wgsl.cpp, tests/wgsl/texture-storage.slang
Closes #5082
This commit implements `texture_storage_Xd` in WGSL, which is similar to RWTextureXD in HLSL.
It is intresting that `texture_storage_Xd` doesn't take the shader type as its input argument at all.
Instead, it takes "texel format" enum value as its first template parameter, which can be found here:
https://www.w3.org/TR/WGSL/#storage-texel-formats
As an example, `texture_storage_2d<rg32uint, read_write>` expects vec4<u32> as a value type for `Load` and `Store`, where Z-component will be ignored and treated as zero and W-component will be treated always as 1.
WGSL requires `texture_storage_Xd` values to always be global variables and they cannot be passed into a function as a function argument.
=> Implement texture_storage_Xd in WGSL

.github/workflows/release.yml
This should prevent `slang-rhi` from linking dawn on aarch64 target platform when using cross-compilation.
=> export CMAKE_SYSTEM_PROCESSOR for cross compilation builds

.github/workflows/ci.yml, docs/building.md
Closes #5117
This adds a build step of WebAssembly version of Slang for all platforms and all configurations.
The new build step appears to take about double times of time compared to the regular Slang build step.
=> Add CI step to build WebAssembly version of Slang

.github/workflows/ci.yml
Closes #5195
Disable the building of slang-llvm when targeting wasm platform
=> Disable the building of slang-llvm when targeting wasm platform

.github/workflows/vk-gl-cts-nightly.yml
Closes #5161
This commit enables the workflow debug message for running VK CTS workflow.
Currently three CTS tests are causing a crash of deqp with an exit code 1. And when the debug message printing is enabled, this crash is no longer happening, which is unexpected. It seems like the issue is on the CI runner process rather than Slang, driver nor deqp.
We will keep the log message enabled not only to avoid the crash but also to see more information when things went wrong.
This commit also prints the last 1,000 lines of TestResults.qpa when deqp had a failing test or deqp was exited unexpectedly. This will help us to debug the problem faster.
=> Enable debug log for VK CTS workflow

source/slang/slang-check-expr.cpp, source/slang/slang-parser.cpp
As to why this ever worked in non-stdlib code, I still don't know
Fixes https://github.com/shader-slang/slang/issues/5191
=> SizeOfLikeExpr has type int

.github/actions/common-setup/action.yml
Closes https://github.com/shader-slang/slang/issues/5201
Currently ci.yml builds slang-llvm all the time for all platforms.
Because it takes too long, we store the output files in the cache.
If the cache server is too busy, slang-llvm will be rebuilt, which will take awhile, but it will eventually work out.
The problem is that git-clone was failing for cloning the LLMV repo.
This is a less expected result, because cloning a git repository normally don't fail.
We think that when the git-clone command is manually executed, there might be limit on the network connection based on IP or some sort.
We expect that this problem will be resolved if we use actions/checkout in the workflow.
Also this commit uses a forked repo of llvm under shader-slang
organization to avoid network traffic on the …
=> Checkout LLVM as a workflow action rather than git-clone command

source/slang/slang-check-decl.cpp
This change is a separate PR for the issue #5192.
The only reason we separate this from PR #5215 is we don't want to bloat the size this PR.
This change just refactor the logic of synthesizing the body of the constructor inside `SemanticsDeclBodyVisitor::visitAggTypeDecl`.
It makes the code more manageable and readable, and also remove some redundant logic and variable creation.
=> Refactor the code for synthesizing the body of constructor

source/slang/slang-emit-glsl.cpp, tests/bindings/hlsl-to-vulkan-global-binding.hlsl, tests/cross-compile/texture-load.slang
=> Use user defined type name in glsl buffer declarations.

source/slang/hlsl.meta.slang, source/slang/slang-emit-wgsl.cpp, tests/compute/byte-address-buffer.slang
=> WGSL: Enable load & store from byte-addressible buffers

CMakeLists.txt, CMakePresets.json, docs/building.md, source/compiler-core/slang-diagnostic-sink.cpp, source/slang-wasm/slang-wasm-bindings.cpp, source/slang-wasm/slang-wasm.cpp, source/slang-wasm/slang-wasm.h
This adds a target that builds slang-wasm.js and slang-wasm.wasm, which exposes a simplified WebAssembly interface on top of the native Slang API.
=> Add slang-wasm target

cmake/SlangTarget.cmake, source/slang-stdlib/CMakeLists.txt, source/slang/CMakeLists.txt
Install slang shared object when we build just the generators, this config is used for release builds where we need to build generators separately to accommodate cross compiling
=> Fix release build failure

source/slang/slang-emit-c-like.cpp, tools/slang-unit-test/unit-test-find-entrypoint-nested.cpp
When there is
```
[shader("compute")]
void inner() { ... }
[shader("compute")]
void outer() { inner(); }
```
And the user trys to compile `outer` to glsl, we are currently generating two functions named `main` in the output glsl because both functions are marked as entrypoint, and there is the logic to emit all entrypoints as `main`. This is wrong if a user-declared entrypoint isn't being selected as the entrypoint in the current compilation session.
=> Fix entrypoint naming in glsl backend.

CMakeLists.txt, source/core/slang-render-api-util.cpp, tools/render-test/slang-support.cpp, tools/slang-test/slang-test-main.cpp
D3D12Core.dll had been copied to a wrong directory and slang has been using D3D12Core.dll from the system directory, C:\windows\system32.
D3D12Core.dll has to be copied from `external/slang-binaries/bin/windows-x64` to `build/Release/bin/D3D12` not to `build/Release/bin`.
The same is true for the debug build and it had to be copied to `build/Debug/bin/D3D12` not `build/Debug/bin`.
It hasn't been a problem for Release build, because the debug-layer is not enabled for Release build and it didn't cause the version mismatching problem with D3D12SDKLayers.dll. The Release build was loaded from either `build/Release/bin` or from `C:\windows\system32`, and it didn't matter which one was used.
The Debug build, however, got into a problem where D3D12Core.dll was loaded from the system directory …
=> Fix D3D12Core.dll loading problem for debug build

CMakeLists.txt, cmake/FetchedSharedLibrary.cmake, cmake/GitHubRelease.cmake, cmake/GitVersion.cmake, docs/building.md
Improve error reporting when things go wrong.
Fall back by default to a non-llvm build
Closes https://github.com/shader-slang/slang/issues/5247
Tested sensible behavior with:
- `FETCH_BINARY_IF_POSSIBLE`, valid tag
- No errors or warnings, successful build with llvm
- `FETCH_BINARY_IF_POSSIBLE`, no valid tag
- Warning message, successful llvm build with slang-llvm from latest release
- `FETCH_BINARY_IF_POSSIBLE`, no valid tag, bad `SLANG_SLANG_LLVM_BINARY_URL` specified
- Warning message, successful no-llvm build
- `FETCH_BINARY_IF_POSSIBLE`, no valid tag, unable to fetch release information
- Warning message, successful no-llvm build
- `FETCH_BINARY`, valid tag
- No errors or warnings, successful build with llvm
- `FETCH_BINARY`, no valid tag
- Warning message, successful llvm build with …
=> Make slang-llvm fetching and failure more robust

tools/gfx/d3d12/d3d12-device.cpp
Correctly adjust WSize when accessing none-zero mip level of a 3D texture.
WSize is now calculated correctly by shifting down the depth. In theory WSize could probably be set to -1, however the mip0 case already works, so I see no reason to mess with it.
=> Fix UAV access for 3d texture mips

source/slang/core.meta.slang
Closes https://github.com/shader-slang/slang/issues/5308
=> Stdlib documentation for Atomic, Optional, Tuple

source/compiler-core/slang-spirv-core-grammar.cpp, tools/slang-lookup-generator/lookup-generator-main.cpp
Closes https://github.com/shader-slang/slang/issues/5350
This commit will handle the new JSON keyword "aliases" in SPIRV-Header grammar files.
"aliases" are used in two places: one for "opname" and another for "enumerants".
This commit itself wouldn't do anything until we integrate new commits from SPIRV-Header repo.
=> Recognize a new spirv header json grammar keyword "aliases"

source/slang/hlsl.meta.slang
=> Document bit operations

source/slang/slang-compiler.h, source/slang/slang-reflection-api.cpp, source/slang/slang.cpp, tools/slang-unit-test/unit-test-function-reflection.cpp
- Adds a check for methods that are already specialized.
- Fixes an issue where thread-local ast-builder is not available,  causing more complex specialization checks to crash
- Use the diagnostic sink to decide if the resolution was successful.
- Add some more cases to the reflection unit-tests
Fixes: https://github.com/shader-slang/slang/issues/5378
=> Fix several bugs with `specializeWithArgTypes()`

source/slang-wasm/slang-wasm-bindings.cpp, source/slang-wasm/slang-wasm.cpp, source/slang-wasm/slang-wasm.h
Also add a new interface to return spirv code which is binary,
because 'std::string ComponentType::getEntryPointCode' is not suitable for returning the binary data.
We use a more standard way that wrap the binary data by using emscripten::val as the return type.
=> wasm: Add compile target option when creating slang session

source/slang/slang-emit-spirv-ops-debug-info-ext.h, source/slang/slang-emit-spirv.cpp, source/slang/slang-ir-addr-inst-elimination.cpp, source/slang/slang-ir-insert-debug-value-store.cpp, source/slang/slang-ir-insts.h, source/slang/slang-ir-legalize-types.cpp, source/slang/slang-ir.cpp, source/slang/slang-lower-to-ir.cpp, tests/spirv/debug-type-pointer-2.slang, tests/spirv/debug-type-pointer.slang
Closes #5398.
Fix missing DebugLine before loop conditions.
Fix duplicate DebugEntryPoint declarations.
=> Use DebugDeclare instead of DebugValue.

.github/actions/common-setup/action.yml
Now that sccache isn't evicting llvm from the cache we should be able to fetch it from upstream again (and archive our fork)
I did however keep the behaviour of using github credentials to fetch llvm
=> Switch back to fetching upstream llvm project 

source/slang-wasm/slang-wasm-bindings.cpp, source/slang-wasm/slang-wasm.cpp, source/slang-wasm/slang-wasm.h, source/slang/slang.cpp
This is to support playground to query the defined entrypoints and their names.
=> More wasm binding for playground.

.github/actions/format-setup/action.yml, .github/workflows/format.yml, .github/workflows/slash-command-dispatch.yml, extras/formatting.sh
It now opens a PR against the target branch, rather than committing directly. this means we can give the bot far fewer permissions.
Also, it formats using the script in the destination branch, which by virtue of the actions being hosted in this repository is something we've signed off on, so we should be less concerned with the bot executing arbitrary code from a PR. The disadvantage of this is that one can't change external/formatting.sh and also call `/format` to apply these changes in the same pr
=> Improvements to formatting bot

source/slang/hlsl.meta.slang, tests/bugs/gh-5339.slang, tests/glsl-intrinsic/intrinsic-texture.slang
Closes https://github.com/shader-slang/slang/issues/5339
This commit changes to use `Offset` option on OpImageGather instruction when translating `textureGatherOffset` to SPIR-V code.
Interestingly GLSL allows the offset value to be a variable not constant just for the function `textureGatherOffset` while all other offset variants of texture sampling functions require the offset to be a constant value.
From a few experiments, I found that the spirv-optimizer changes `Offset` to `ConstOffset` if the offset is a compile-time value. I also found that when the offset value is zero, it changes to `None` with no offset value.
=> Use Offset instead of ConstOffset for GLSL function textureGatherOffset

CMakePresets.json, source/slang/slang-check-expr.cpp, tests/bugs/gh-5372.slang, tests/diagnostics/attribute-error.slang
Closes https://github.com/shader-slang/slang/issues/5372
When the expresion used as a switch-case labels is a type-casting from floating-point type to an integer type, the floating-point literal also need to be constant-folded.
=> Constant-fold for the type-casting in switch-case labels

source/slang-wasm/slang-wasm-bindings.cpp, source/slang-wasm/slang-wasm.cpp, source/slang-wasm/slang-wasm.h, source/slang/slang-check-decl.cpp
We add the functionalities to get the hashed string from shader code into our wasm binding code. This is key to support shader printf.
Also found a bug in the visibility the type generic, we forgot handling the type pack parameter.
=> Add function of getting hash string to wasm binding

examples/hello-world/main.cpp, include/slang.h, source/slang/slang-compiler-options.cpp, source/slang/slang-compiler-options.h, source/slang/slang-options.cpp
CompilerOptionName::EmitSpirvViaGLSL and CompilerOptionName::EmitSpirvDirectly options are not mutually exclusive, but due to compatible reason, we cannot delete those options. Instead, this change makes the effort to create a new option name EmitSpirvMethod, and we will turn those two options into the new one internally. Also, we put a priority implicitly on those two options, where EmitSpirvDirectly always win if it's set.
We have another location that can setup the same option, where is through SlangTargetFlags::SLANG_TARGET_FLAG_GENERATE_SPIRV_DIRECTLY.
We should definitely deprecate this flag to avoid more confusing. But for the same compatible reason, we cannot do that in this PR. Again, we will encourage people to not use this flag, but using the CompilerOptionName instead. In this …
=> Improve on spirv generation compile option

source/slang/slang-ast-support-types.h, tests/compute/unbounded-array-of-array-syntax.slang, tests/language-feature/overload-resolution-signed-unsigned.slang, tests/metal/atomic-texture-texture1d.slang
This is a breaking change, but the change is to make Slang's overload resolution aligned with C specification.
Basically, when there is a binary operator that takes (int, int) or (uint, uint), and the argument is of type (int, uint), the expected behavior is to convert the `int` to `uint` instead of the other way around.
Closes #5473.
=> Revert uint<->int implicit cast cost to prefer promotion to unsigned.

source/slang/slang-emit-c-like.cpp, source/slang/slang-emit-c-like.h, source/slang/slang-emit-wgsl.cpp, source/slang/slang-emit-wgsl.h, source/slang/slang-ir-wgsl-legalize.cpp, tests/compute/assoctype-lookup.slang, tests/compute/texture-simpler.slang, tests/wgsl/nested-varying-input.slang
Closes #5486
The return type of the entry-point needs to be legalized when targeting WGSL.
This commit flattens the nested-structs of the return type and the input parameters of the entry-point.
Most of code is copied from the legalization code for Metal. The following functions are exactly same to the implementation for Metal or almost same.
- flattenInputParameters() : 136 lines
- reportUnsupportedSystemAttribute() : 7 lines
- ensureResultStructHasUserSemantic() : 46 lines
- struct MapStructToFlatStruct : 176 lines
- flattenNestedStructs() : 95 lines
- maybeFlattenNestedStructs() : 42 lines
- _replaceAllReturnInst() : 19 lines
- _returnNonOverlappingAttributeIndex() : 16 lines
- _replaceAttributeOfLayout() : 23 lines
- tryConvertValue() : 41 lines
- legalizeSystemValueParameters() : 11 …
=> Legalize the Entry-point for WGSL

source/slang/slang-options.cpp
This slangc option internally uses an experimental Slang API interface. The feature is only at prototype-level completion, currently.
Fixes #5434
=> Mark -embed-downstream-ir as experimental

source/slang/slang-core-module-textures.cpp, tests/bugs/gh-5518.slang
This extension is only necessary when using texture functions on non-combined texture/samplers.
Fixes #5518
=> Require GL_EXT_samplerless_texture_functions only if needed

source/slang/slang-ir-link.cpp, source/slang/slang-ir-specialize.cpp
The first bug was introduced in b2ca2d5a4efeae807d3c3f48f60235e47413b559 and ran some code at scope exit that dereferenced a nullptr context.
The second bug was introduced in bea1394ad35680940a0b69b9c67efc43764cc194 and would cause the wrong mangled name to be used during specialization.
This closes #5516.
=> Fix two specialization bugs

source/slang/slang-emit.cpp, source/slang/slang-ir-defer-buffer-load.cpp, source/slang/slang-ir-defer-buffer-load.h, source/slang/slang-ir.cpp, tests/spirv/sb-load-2.slang, tests/spirv/sb-load.slang
=> Push buffer load to end of access chain.

source/slang/slang-ir-defer-buffer-load.cpp
This PR simplifies #5544 by not doing adhoc deduplication and instead rely on the existing redundancy removal pass to get rid of redundant FieldExtract/GetElement insts before deferring buffer loads.
=> Simplify defer buffer load.

source/slang/slang-compiler.cpp, source/slang/slang.cpp
=> Make `getDependencyFilePath` return most unique identity.

source/slang/slang-emit.cpp, source/slang/slang-ir-insts.h, source/slang/slang-ir-strip-default-construct.cpp, source/slang/slang-ir-strip-default-construct.h
Our auto-diff step currently emits a few 'raw' `OpDefaultConstruct` insts for intermediate data types, mostly to silence HLSL errors about uninitialized variables. This is a redundant inst, because our auto-diff pass will always make sure all generated fields are individually set.
Usually, these intermediate types are made up of zero-initializable types so they get lowered to `OpMakeStruct`, so targets like SPIRV where `OpDefaultConstruct` does not exist don't run into issues.
For some special types, it is not easy (or safe) to emit such zero initializers, so we will instead run a pass to remove `OpDefaultConstruct` for backends where it is not available (thankfully, these backends do not complain about uninitialized variables, so the code correctness is unaffected)
=> Remove 'raw' default construct insts for SPIRV emit

.gitignore, CMakePresets.json, source/compiler-core/slang-artifact-associated-impl.h, source/slang-record-replay/record/slang-module.h, source/slang/slang-ast-decl.h, source/slang/slang-ast-expr.h, source/slang/slang-ast-modifier.h, source/slang/slang-ast-support-types.h, source/slang/slang-ast-type.cpp, source/slang/slang-ast-val.cpp, source/slang/slang-check-decl.cpp, source/slang/slang-check-expr.cpp, source/slang/slang-compiler.h, source/slang/slang-ir-insts.h, source/slang/slang-ir.cpp, source/slang/slang-lower-to-ir.cpp, tools/slang-cpp-extractor/diagnostic-defs.h, tools/slang-cpp-extractor/parser.cpp
This change allows us to embed prebuilt core module in WebAssembly.
The main issue being fixed here is that some of our AST nodes contain fields of type `Index` or `UInt`, whose sizes are architecture dependent. This means that the serialized module produced from x64 build system won't correct load by the web assembly module, which is 32-bit. The fix is to get rid of these arch-dependent int types in AST nodes.
To prevent future regression, the slang-cpp-extract application is updated to report an error if it sees an AST node field is of such types.
=> Embed core module in wasm build.

source/slang/hlsl.meta.slang, tests/glsl/sampler-fetch.slang
=> Remove "GL_EXT_samplerless_texture_functions" from combined sampler funcs.

source/slang/slang-check-decl.cpp, tests/spirv/specialization-constant.slang
Closes [#5463](https://github.com/shader-slang/slang/issues/5463).
=> Fix specialization constant miscompile in glsl mode.

docs/user-guide/a2-03-wgsl-target-specific.md, docs/user-guide/a2-target-specific-features.md
Add some initial documentation of how WGSL is targeted by Slang.
Issue #5567
=> Document WGSL specific features

source/slang/hlsl.meta.slang, source/slang/slang-ir-wgsl-legalize.cpp, tests/wgsl/workgroup-uniform-load.slang
=> Fix wgsl legalization around __ref parameter.

tests/compute/texture-sampling-no-1d-arrays.slang
- Update Slang-RHI to get WGPU fixes
- Fix and enable WGPU texture sampling test
https://github.com/shader-slang/slang/issues/4943
=> Enable WGPU texture sampling test

docs/user-guide/03-convenience-features.md
slang extensions looks same as c# extension methods, not partial classes. Partial classes allow extending types to introduce more variables unlike slang extensions. And you cannot extend that types not partial to begin with. Where extension methods allows that. Also c# users that use extension methods much more  than partial types, probably.
=> [Docs] Extensions -  better wording for c# equivalent

.github/workflows/release-linux-glibc-2-17.yml, .github/workflows/release.yml, CMakeLists.txt, CMakePresets.json, docs/building.md
It seems that release workflows were unexpectedly broken when STDLIB was renamed to CORE_MODULE.
Changed the option default because I think it just makes more sense. Removed explicit calls to enable it. Fixed docs.
Should `SLANG_EMBED_CORE_MODULE_SOURCE` be disabled too? Does it do anything useful?
As reported in https://github.com/shader-slang/slang/issues/5631
NOTE: I haven't really tested it at this point, but should work.
=> Enable core module embedding by default in CMake.

docs/user-guide/toc.html
I believe this will fix the dead links that occurred because of sub section renames.
=> [Docs] fix spirv dead links on toc.html

source/slang/slang-check-shader.cpp, source/slang/slang-mangle.cpp, tests/bugs/dyn-dispatch-single-conformance.slang, tests/compute/dynamic-dispatch-13.slang, tests/compute/dynamic-dispatch-14.slang, tests/compute/dynamic-dispatch-15.slang, tests/compute/interface-assoc-type-param.slang, tests/language-feature/interfaces/empty-type-conformance.slang
Fixes #5629.
When we have a `StructuredBuffer<IFoo>` parameter, we shouldn't treat it as a statically specializable parameter because we never want to directly replace `IFoo` with any concrete type. Instead we want to always rely on the dynamic dispatch handling logic to insert proper header to maintain data layout consistency.
=> Don't treat StrcturedBuffer<IFoo> as a specializable param.

.github/actions/common-setup/action.yml, .github/workflows/falcor-compiler-perf-test.yml, .github/workflows/vk-gl-cts-nightly.yml
CI was previous using different versions in different jobs but all were old and using a version of Node that has been deprecated within the GitHub Actions infrastructure.
=> ci: Use v1.11 of the release-downloader action

examples/triangle/shaders.slang
Hi, I'm new here.
I was looking at the triangle sample and noticed that it declared a struct `Fragment` for the fragment shader output but didn't actually use it, so I decided to fix that.
Of course, I could have just deleted `Fragment`, but I chose to use it to demonstrate that we can use a custom struct for output.
=> Fix unused struct in  sample shader

prelude/CMakeLists.txt, prelude/slang-torch-prelude.h, tools/slang-embed/slang-embed.cpp
Related: https://github.com/shader-slang/slang-torch/issues/23
Our slang-torch repository keeps breaking due to relative paths being occasionally re-written (e.g. 
`#include "slang.h"` vs. `#include "../../include/slang.h"`), exacerbated by the fact that we don't have slang-torch on CI yet.
This PR adds an include directory to the slang-embed tool to avoid this issue in the future.
=> Fix issue with slang-embed & include ordering

cmake/SlangTarget.cmake
Closes https://github.com/shader-slang/slang/discussions/5632
This commit enables Link Time Code Generation, or LTCG for short, for the release builds.
Because "incremental" build is enabled, this ends up using "/LTCG:incremental" rather than the full "/LTCG". It is still expected to more performant than without any "/LTCG" at all.
In order to use the full LTCG, we will need to give up the incremental build option for the Release build. We will need to decide if we wants to do it later.
=> Enable Link-Time-Code-Generation for Release builds

docs/user-guide/09-targets.md, docs/user-guide/toc.html
=> Add WebGPU target doc

tests/compute/constexpr.slang, tests/metal/nested-struct-fragment-input.slang, tests/metal/nested-struct-fragment-output.slang, tests/metal/nested-struct-multi-entry-point-vertex.slang, tests/metal/no-struct-vertex-output.slang, tests/metal/sv_target-complex-1.slang, tests/metal/sv_target-complex-2.slang, tests/wgsl/semantic-coverage.slang, tests/wgsl/semantic-depth.slang, tests/wgsl/semantic-dispatch-thread-id.slang, tests/wgsl/semantic-group-id.slang, tests/wgsl/semantic-group-index.slang, tests/wgsl/semantic-group-thread-id.slang, tests/wgsl/semantic-instance-id.slang, tests/wgsl/semantic-is-front-face.slang, tests/wgsl/semantic-position.slang, tests/wgsl/semantic-sample-index.slang, tests/wgsl/semantic-vertex-id.slang
Closes https://github.com/shader-slang/slang/issues/5067
New tests, covering what's declared supported in the WGSL support docs
- tests/wgsl/semantic-coverage.slang
- tests/wgsl/semantic-depth.slang
- tests/wgsl/semantic-dispatch-thread-id.slang
- tests/wgsl/semantic-group-id.slang
- tests/wgsl/semantic-group-index.slang
- tests/wgsl/semantic-group-thread-id.slang
- tests/wgsl/semantic-instance-id.slang
- tests/wgsl/semantic-is-front-face.slang
- tests/wgsl/semantic-position.slang
- tests/wgsl/semantic-sample-index.slang
- tests/wgsl/semantic-vertex-id.slang
WGSL enabled existing tests:
- tests/compute/compile-time-loop.slang
- tests/compute/constexpr.slang
- tests/compute/discard-stmt.slang
- tests/metal/nested-struct-fragment-input.slang
- tests/metal/nested-struct-fragment-output.slang …
=> Test varying inputs and outputs for wgsl

source/slang/hlsl.meta.slang
In order to emit fast target implementations of some Metal-based functions (fmin(), fmax(), fmin3(), fmax3()) on all targets, remove some specification regarding the handling of NaNs, and also remove the enforcement of the specification.
These functions are now documented to be basically undefined now in the presence of NaN input, to make the common "is a number" case fast.
Also, clarify that powr() is undefined when given a non-positive base input value, allowing us to remove an additional abs() operation that was unnecessarily coercing results to be predictable on non-Metal targets.
Closes #5580
Closes #5581
Closes #5587
=> Core lib Metal math function fixes

source/slang/hlsl.meta.slang
Fix the regression from #5578.
=> Fix a regression that GL_EXT_samplerless_texture_functions is missing

include/slang.h
The macros SLANG_NO_INLINE, SLANG_FORCE_INLINE, SLANG_BREAKPOINT and SLANG_ALIGN_OF end up getting defined twice when using g++ or clang++ with the slang.h header on Windows.
Change the VC specific definitions to depend on SLANG_VC instead of SLANG_MICROSOFT_FAMILY.
Resolves #5765
=> Fix compiler warning when using slang.h with gcc/clang on Windows

CMakeLists.txt, cmake/LLVM.cmake, cmake/SlangTarget.cmake, source/slang-glslang/CMakeLists.txt, source/slang-rt/CMakeLists.txt, source/slang/CMakeLists.txt, source/slangc/CMakeLists.txt, tools/CMakeLists.txt
Closes https://github.com/shader-slang/slang/issues/5764
Also mention other installed targets in cmake config
Technically a breaking change if anyone is used to the `lib64` install location, but that never made it into a release
=> Remove duplicate call to install() for libslang

include/slang.h, source/core/slang-signal.cpp, source/core/slang-signal.h, source/slang/slang-api.cpp
This adds a public API function `getLastInternalErrorMessage` that can be used to access the message of the last raised internal signal. This allows API users to access the same error message that is also output for internal errors when running `slangc` and get some minimal hint at what error was raised.
=> Add API for getting last internal error message

source/slang/slang-parser.cpp, tests/diagnostics/nested-func.slang, tests/diagnostics/uninitialized-local-variables.slang
=> Report error on nested functions.

source/slang/slang-ast-modifier.h, source/slang/slang-check-modifier.cpp, source/slang/slang-ir-insts.h, source/slang/slang-ir.cpp, source/slang/slang-lower-to-ir.cpp, tests/bugs/gh-5781.slang, tests/language-feature/constants/max-iters-link-time-const.slang
Also allows MaxIters to take link time constants.
Closes #5781.
Closes #5770.
=> Fix crash during emitCast of attributed type, allow MaxIters to take linktime const.

source/slang/slang-ir-lower-buffer-element-type.cpp, tests/bugs/gh-3825.slang, tests/spirv/ptr-unsized-array-3.slang, tests/spirv/ptr-unsized-array-4.slang, tools/render-test/render-test-main.cpp
Closes #5351.
This change allows us to finally run executable tests for pointers.
=> Fix pointer offset logic and add executable tests.

source/slang/slang-check-conversion.cpp, source/slang/slang-check-decl.cpp, source/slang/slang-check-impl.h, tests/bugs/half-coercion.slang
=> Don't emit a warning when implicit casting from known in-range int lit to half.

tests/metal/nested-struct-fragment-input.slang, tests/metal/nested-struct-fragment-output.slang, tests/metal/nested-struct-multi-entry-point-vertex.slang, tests/metal/no-struct-vertex-output.slang, tests/metal/stage-in-2.slang, tests/metal/sv_target-complex-1.slang, tests/metal/sv_target-complex-2.slang
This commit enables existing tests for WGSL that are enabled for Metal regarding the Semantics.
Closes https://github.com/shader-slang/slang/issues/5502
=> Enable WGSL tests that works for Metal related to Semantics

source/slang/slang-emit-wgsl.cpp
Previously compiling a slang file with `RWTexture<float>` would fail silently and hang the playground. This changes the code to be closer to the `glsl` implementation and fixes the failure.
Still not exactly sure why the previous code didn't work but I think it had something to do with chaining the declarations in the if statement.
=> Fix wgsl float texture format inference silent failure

examples/example-base/example-base.h
On Discord, one of users reported that the error reporting logic encountered a buffer overrun when the error message is long.
https://discord.com/channels/1303735196696445038/1316453522493149236/1316453522493149236
The issue itself isn't Slang related but it will be better to have a more stable example.
Since I was not able to reproduce the issue, this is a speculative fix.
=> Use perfect forwardnig to preserve the parameters for log

cmake/FetchedSharedLibrary.cmake
CMAKE_SHARED_LIBRARY_PREFIX is still `lib` when compiling on linux, but the deps don't have that in them
=> Fix prebuilt dependencies filenames on non-windows platforms

CMakeLists.txt, cmake/CompilerFlags.cmake, docs/building.md
At the moment there's no way to easily disable this functionality 
(Happy that the linux support was so good until now that there was no call for this :D)
=> Add SLANG_ENABLE_DXIL

docs/user-guide/09-reflection.md, docs/user-guide/toc.html
The new version of the chapter is intended to
accompany the `reflection-api` example program,
and reflects (pun intended) the best practices
that the Slang project team wants to encourage
for interacting with the reflection API.
=> Update reflection API chapter in User Guide

source/slang/slang-parser.cpp
Close #5911.
In this issue, if we define the generic in source file 1, and import it into source file 2, then when parsing the reference of that generic in source file 2, we will not parse the generic directly, instead we have a logic to speculate it as generics first with a fake diagnostic sink, and if there is no error report, we will consider it as a actual generic and will parse it again.
In this logic, we will also disambiguate the expression based on the following token, but we didn't consider the token '[', so we will finally not treat the expression as generic.
The fix is just simply adding '[' .
=> Fix the parser issue for not recognize Generic<T>[N]

.github/workflows/ci-examples.sh
This helps to address issue #5520.
=> Fix issues reported by 'shellcheck'

docs/user-guide/a2-01-spirv-target-specific.md, docs/user-guide/a2-02-metal-target-specific.md, source/slang/glsl.meta.slang, source/slang/slang-emit-spirv.cpp, source/slang/slang-ir-glsl-legalize.cpp, source/slang/slang-ir-legalize-varying-params.h, source/slang/slang-ir-metal-legalize.cpp, source/slang/slang-ir-wgsl-legalize.cpp, source/slang/slang-language-server-completion.cpp, tests/glsl-intrinsic/system-values-draw-parameters.slang, tests/hlsl-intrinsic/system-values-draw-parameters.slang
Adds base vertex and base instance system value semantics that were introduced in [SM 6.8](https://microsoft.github.io/DirectX-Specs/d3d/HLSL_ShaderModel6_8.html#extended-command-information). Parallel implementations already exist on GLSL, SPIRV and Metal but not WGSL.
=> Add base vertex and base instance system values

docs/user-guide/02-conventional-features.md, docs/user-guide/06-interfaces-generics.md, docs/user-guide/07-autodiff.md, docs/user-guide/08-compiling.md, docs/user-guide/09-reflection.md, docs/user-guide/09-targets.md, docs/user-guide/10-link-time-specialization.md, docs/user-guide/a1-03-obfuscation.md, docs/user-guide/a1-04-interop.md, docs/user-guide/a2-01-spirv-target-specific.md
I have corrected a few minor typos in the user guide.
=> Fix tiny typos

source/core/slang-list.h, source/slang/slang-check-decl.cpp, source/slang/slang-syntax.cpp, source/slang/slang-syntax.h, tests/language-feature/interfaces/overloaded-associatedtype.slang
=> Fix witness lookup to prefer decls in the same parent as the inheritance decl.

source/slang/slang-ast-support-types.cpp, source/slang/slang-ast-support-types.h, source/slang/slang-capability.cpp, source/slang/slang-check-decl.cpp, source/slang/slang-check-impl.h, source/slang/slang-diagnostic-defs.h, tests/diagnostics/interfaces/mutating-impl-of-non-mutating-req.slang, tests/language-feature/interfaces/argument-direction-mismatch.slang, tests/language-feature/modules/wrapper-inout.slang, tests/language-feature/modules/wrapper-property.slang
Based on PR #5955.
Closes #5962.
=> Check mismatching method parameter direction against interface declaration.

source/slang/hlsl.meta.slang, source/slang/slang-emit-glsl.cpp, tests/spirv/u-to-accelstruct.slang
Closes [#5801](https://github.com/shader-slang/slang/issues/5801).
=> Add `RaytracingAccelerationStructure::__init(uint64_t)`.

source/slang/slang-check-expr.cpp, source/slang/slang-diagnostic-defs.h, tests/diagnostics/invalid-spv-obj.slang
Closes [#5753](https://github.com/shader-slang/slang/issues/5753).
=> Check for undefined %id in spirv_asm block.

source/slang/glsl.meta.slang
I checked the SPIR-V and GLSL output, both seem fine with this approach.
Closes #5946.
=> Add terminateRayEXT & ignoreIntersectionEXT to glsl.meta.slang

source/slang/slang.cpp
Hello,
I have been trying to use the Slang Compilation API in C# by interfacing with the COM-lite API.
I've been able to call the API functions by directly interfacing with the vtable in unsafe C#, but for my own sanity, I was trying to use the [source generated ComWrappers API](https://learn.microsoft.com/en-us/dotnet/standard/native-interop/comwrappers-source-generation) introduced in .NET 8 to handle everything for me. However, I kept running into a low-level runtime error when it tries to create a wrapper object for the Slang `IGlobalSession` object.
After a little digging, I found the issue. The .NET runtime is checking if the Slang `IGlobalSession` implements `IUnknown` by calling `QueryInterface`. `IGlobalSession` implements `ISlangUnknown`, which shares the same IID as `IUnknown`, …
=> Fixed Session::queryInterface not returning OK when querying for IUnknown/ISlangUnknown

source/core/slang-io.cpp, tools/slang-test/options.cpp, tools/slang-test/options.h, tools/slang-test/slang-test-main.cpp
Intended to address #5979.
From what I can tell, this should be a non-breaking change. The existing tests still run correctly, and I've verified on my computer that I can use an arbitrary test directory with the `-test-dir` option.
While attempting to implement this, I did also notice an off-by-one issue with the binary name on Linux. While `_calcExectuablePath` properly null-terminates the program path, it overwrites the final non-null character of the name. This ends up breaking functions like `Path::getCanonical` later on, because `slang-tes` does not exist. If that change should be in a separate PR, please let me know.
=> Allow explicit test root

source/slang/slang-parser.cpp
The "shared" keyword in GLSL mode should be equivalent to "groupshared" in HLSL & Slang. It got interpreted as a D3D11 effect system thing instead, but that would never appear in GLSL code. Because of this, "shared" was ignored, breaking effectively any GLSL shader using shared memory. This PR fixes that by interpreting "shared" as HLSLGroupSharedModifier when GLSL input is allowed.
Related to #5989 but does not close that issue.
=> Make 'shared' keyword map to 'groupshared' in GLSL mode

source/slang/glsl.meta.slang
`mix(a,b,t)` should be `a` when t=0 and `b` t=1. The cases where `t` is bool have special overloads in `glsl.meta.slang`, which use the OpSelect instruction. The [parameters for OpSelect](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#OpSelect) were flipped, so `mix(a,b,true)` returned `a` instead of `b`. This PR fixes that.
=> Fix GLSL mix(T,T,bool) SPIR-V output

source/slang/glsl.meta.slang
[EXT_texture_shadow_lod](https://github.com/KhronosGroup/OpenGL-Registry/blob/main/extensions/EXT/EXT_texture_shadow_lod.txt) specifies that this function should exist, so it shall.
Not sure why it's missing from the [reference pages](https://registry.khronos.org/OpenGL-Refpages/gl4/html/textureLod.xhtml) though, but it works anyway. I'm using this for cascaded shadow maps, which now work as they should with this patch.
=> Add support for textureLod with sampler2DArrayShadow in GLSL compatibility mode

.github/workflows/ci.yml
The version 3 of actions/upload-artifact will be deprecated soon. https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
This commit upgrades to v4.
There is a document describing how to migrate/upgrade: https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md
The breaking change on v4 is that the uploaded files are immutable and we can no longer append files with the same name. We don't seem to be doing it so it should be fine for us.
Closes https://github.com/shader-slang/slang/issues/6050
=> Upgrade actions/upload-artifact from v3 to v4

source/slang/core.meta.slang, source/slang/hlsl.meta.slang, source/slang/slang-emit-spirv-ops.h, source/slang/slang-emit-spirv.cpp, source/slang/slang-type-system-shared.h, tests/workgraphs/consumer.slang
In order to unblock experiments with SPIRV work-graphs, Slang needs to support a storage class, `NodePayloadAMDX`.
Note that this commit is only to support a storage class, `NodePayloadAMDX`. There are many other parts required for work-graphs to work, which are not implemented yet.
The implementation of `DispatchNodeInputRecord` in this commit is not required, but it is implemented mostly for a testing purpose.
Closes #6049
=> Support a storage class, NodePayloadAMDX, for SPIRV work-graphs

docs/cuda-target.md, source/compiler-core/slang-nvrtc-compiler.cpp
Add basic support for locating OptiX headers:
- detect in downstream compiler arguments
- detect newest version in standard Optix SDK install paths
=> Find OptiX headers

source/slang/slang-ir-autodiff-rev.cpp, tests/autodiff/out-parameters-2.slang
This fixes an issue where 'out' parameters to the primal context function can be accidentally initialized using the wrong input to the backward function.
=> Don't initialize temp var for out parameters when generating the backward diff function

docs/user-guide/03-convenience-features.md
It previously stated that changes would simply not be applied, which is not the case based on the playground:
```slang
struct Foo {
int count;
void setCount(int x) {
count = x;
}
}
void test() {
Foo f;
f.setCount(1);
}
```
Gives this compile error
```
USER error: /user.slang(4): error 30011: left of '=' is not an l-value.
count = x;
^
/user.slang(4): note 30049: a 'this' parameter is an immutable parameter by default in Slang; apply the `[mutating]` attribute to the function declaration to opt in to a mutable `this`
(0): error 39999: import of module 'user' failed because of a compilation error
(0): fatal error 39999: compilation ceased
```
It may also be worth removing the "for gpu performance considerations" since it doesn't impact performance at all.
=> Fix inaccurate documentation in member function mutability.

source/slang/slang-diagnostic-defs.h, tests/diagnostics/missing-return.slang.expected
This PR changes the warning message of 41010
from 
`control flow may reach end of non-'void' function`
to
`non-void function does not return in all cases`
This verbiage is much clearer on what the actual issue is, and addresses issue #5354
=> Fix #5354, change diagnostic definition error message and expect output in test

source/slang/slang-ir-specialize.cpp, source/slang/slang.cpp
This PR runs SCCP in tandem with specialization so that arithmetic expressions are simplified before they can be used to specialize generic objects.
Fixes an issue where the same effective specialization can be replicated several times, causing a type mismatch.
=> Fix issue with specialization using arithmetic expressions

source/slang/slang-ir-legalize-varying-params.cpp, tests/hlsl-intrinsic/system-values-draw-parameters.slang
Closes #6081.
Metal supports multiview rendering through [vertex amplification](https://developer.apple.com/documentation/metal/improving-rendering-performance-with-vertex-amplification) - view index in shader is supported through builtin attribute `[[amplification_id]]`.
=> support SV_ViewIndex for Metal

source/slang/slang-ir-any-value-marshalling.cpp
Fixes the upper 32 bits of 64-bit values in AnyValue packing. The low 32 bits were repeated in the high bits. This caused `reinterpret<T>` to behave incorrectly for basic 64-bit types.
An example of the issue:
```hlsl
export __extern_cpp int main()
{
int64_t ptr = 0x0123456789ABCDEF;
uint64_t ptr2 = reinterpret<uint64_t>(ptr);
printf("%lX\n", ptr);
printf("%lX\n", ptr2);
return 0;
}
```
prints:
```
123456789ABCDEF
89ABCDEF89ABCDEF
```
This also affects pointers, so reinterpreting addresses broke them.
=> Fix reinterpret<T> for 64-bit types

source/compiler-core/slang-gcc-compiler-util.cpp
There is no `-O4` in [gcc docs](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html), and [anything above -O3 is the same as -O3](https://stackoverflow.com/a/30308151) actually.
More importantly, metal compiler will generate a warning `"metal 32023.404: : warning : -O4 is equivalent to -O3 [-Wdeprecated]"` when it is used with `-O4`.
So it‘s better to use `-O3` for `OptimizationLevel::Maximal`.
=> Fix maximal gcc downstream compiler optimization level

source/slang/slang.cpp
=> Catch all exceptions from loadModule* API calls.

source/slang/slang-ir-use-uninitialized-values.cpp, tests/diagnostics/uninitialized-generic.slang, tests/diagnostics/uninitialized-local-variables.slang
While checking the uninitialized variables, we were not resolving the specialized instance correctly. This commit repeats the resolve while the result is a specialization instance. A new test is added for this:
tests/diagnostics/uninitialized-generic.slang
After the problem is fixed, it revealed another problem in existing tests:
tests/compute/nested-generics2.slang
tests/diagnostics/uninitialized-local-variables.slang
When a struct has a member variable whose type is a generic type, we cannot iterate over its member variables yet, because the type is unknown until the generic function/struct is specialized. We will have to give up checking for these cases.
=> Fix incorrect resolve of specialization instance

CMakeLists.txt, cmake/SlangTarget.cmake, docs/building.md, prelude/CMakeLists.txt, source/compiler-core/CMakeLists.txt, source/core/CMakeLists.txt, source/slang-rt/CMakeLists.txt, source/slang/CMakeLists.txt, tools/CMakeLists.txt
Main goal of the PR is to simplify building statically when used as a submodule by a downstream project.
Fixes #5832 by adding missing STATIC arguments in cmake. 
Improves the state on #5821 by fixing build errors, but does not entirely fix the static build install, just disables the failing part. Completely fixing the problem requires being more careful with what dependencies are PRIVATE and PUBLIC or adding additional explicit targets to install.
Also adds an option to disable LTO, this can be useful to limit the size of static libs (`slang.lib` is currently ~2GB when using LTO).
=> Fix static build and install

prelude/slang-cpp-scalar-intrinsics.h, prelude/slang-cuda-prelude.h, source/slang/slang-intrinsic-expand.cpp
This PR allows using abs/min/max with uintptr_t & intptr_t (= size_t as well).
This only covers the CPU and CUDA targets because they use the same code path, where this is easy to implement. For the rest of the targets, there seems to be many more obstacles, so I didn't do those in this PR (`Slang::getIntTypeInfo()` can't handle these types, so there's quite a few contexts where they don't work, it's not just these builtins)
Previously, e.g.
```hlsl
export __extern_cpp int main()
{
size_t a = 1;
size_t b = 2;
printf("%lu\n", max(a, b));
return 0;
}
```
would result in
```
(0): error 99999: Slang compilation aborted due to an exception of N5Slang13InternalErrorE: unexpected: unexpected type in intrinsic definition
```
=> Add intptr_t abs/min/max operations for CPU & CUDA targets

source/slang/hlsl.meta.slang, source/slang/slang-emit-c-like.cpp, source/slang/slang-emit-metal.cpp, source/slang/slang-ir-inst-defs.h, source/slang/slang-ir-metal-legalize.cpp, source/slang/slang-ir.cpp, tests/metal/depth-texture.slang, tests/metal/texture.slang
We translate `Texture2D` to `texture2d` in Metal.
However, when the user calls `Texture2D::SampleCmp()`, we cannot translate it to `texture2d::sample_compare`, because `sample_compare` is only defined on `depth2d` type.
This PR fixes this issue by doing a bitcast to convert `texture2d` to `depth2d` before calling `sample_compare`, which is UB but seems to be compiling just fine by the metal compiler.
Closes #6166.
=> Fix depth texture sampling on Metal.

source/slang/slang-ir-variable-scope-correction.cpp
We cannot modify workList while iterating it, because its type `List` is actually an array container.
=> Fix an incorrect iteration with a workList

source/slang/slang-check-decl.cpp, tests/language-feature/initializer-lists/inheritance-generic.slang
When synthesize the default ctor, if there is a base type we will synthesize an InvokeExpr to call base type's default ctor as well. But we should use the type of the inheritanceDecl instead of base struct decl.
=> Fix the type coerce issue

source/slang/slang-ast-decl.h, source/slang/slang-ast-val.cpp, source/slang/slang-check-decl.cpp, tests/language-server/typename-enum-intval.slang
=> Fix ConstantIntVal::toText when the val is a enum.

source/slang/slang-emit-spirv.cpp, tests/spirv/variable-pointer.slang
=> Declare `VariablePointers` capability when needed.

tools/render-test/render-test-main.cpp, tools/render-test/shader-input-layout.h, tools/render-test/slang-support.h
As [1] shows, creating a D3D12 device and then enabling debug layers causes future device creation to fail.
That means enabling debug layers is a process-wide decision that should be done at startup, and not just before creating an individual device. Previously, Slang-RHI enabled debug layers as part of device creation. The new Slang-RHI revision doesn't do that anymore, but instead allows the user to enable debug layers earlier, with a separate API.
This change calls the mentioned API before creating any device.
This closes #6172.
=> Update Slang-RHI and enable any debug layers up-front

source/slang/slang-ir-glsl-legalize.cpp, source/slang/slang-parser.cpp, tests/spirv/multi-entrypoint-no-rename.slang
=> Auto enable `-fvk-use-entrypoint-name` when there is more than one entrypoint.

source/slang/slang-ir-autodiff-transpose.h, tests/autodiff/matrix-arithmetic-non-sqr.slang
Fix improper calculation of row/col indices.
Fixes: #6280
=> Fix non-square matrix derivative code-gen

source/slang/core.meta.slang
Close #6154
We didn't implement correctly for vector<T, N> regarding the differentiablity. As we check differentiable before specialization, however according to the definition of vector, it has to be specialized to IFloat to know it's conformed to IDifferential type. Therefore for parameter type vector<T, N> will become no_diff.
Therefore, we change the implementation a to make it explicit conform to IDifferential type.
=> Fix autodiff issue for vector<T, N>

source/slang/slang-ir-util.cpp, tests/autodiff/custom-diff-empty-func.slang
DCE will now check for side-effect-ness on other functions that are associated with the callee being checked.
Fixes: #5755
=> Fix DCE for calls to functions that have associations

tests/wgsl/associativity.slang
This case now parses after the following PR was merged. https://github.com/shader-slang/slang/pull/6281
=> Uncomment a previously failing test case

.github/workflows/ci.yml, tools/slangc-test/multiple-source-files/A.slang, tools/slangc-test/multiple-source-files/source1.slang, tools/slangc-test/multiple-source-files/source2.slang, tools/slangc-test/test.sh
I didn't find a way to trigger this via the Slang API, so add a `slangc` test instead.
- Add `slangc` tests to CI
- Add a `slangc` test for issue #6221
This closes #6221.
=> Add test for visibility in translation unit with multiple source files

source/slang/slang-options.cpp, tests/wgsl/multiple-entrypoints.slang
The WGSL code generator already supports this, it just wasn't possible to use it with `slangc`, e.g.:
```sh
cd examples/wgpu-html5
slangc -target wgsl -entry vertexMain -stage vertex -entry fragmentMain -stage fragment -o shader.wgsl shader.slang
```
Fixes #6322
=> Add WGSL to list of formats supporting multiple entry points

source/core/slang-stream.cpp
The musl libc replacement removed fopen64, fgetpos64, and other 64-bit variants because it's 64-bit only. However, it does have the following in its headers:
#define fgetpos64 fgetpos
Just importing `<stdio.h>` is enough to get slang compiling on musl systems like Alpine Linux.
Fixes #6330.
=> Fix compilation on musl libc targets

source/compiler-core/slang-dxc-compiler.cpp, source/slang/hlsl.meta.slang, source/slang/slang-emit-hlsl.cpp, source/slang/slang-ir-hlsl-legalize.cpp, source/slang/slang-ir-inst-defs.h, source/slang/slang-ir-insts.h, tests/expected-failure-github.txt, tests/hlsl/raypayload-attribute-no-struct.slang, tests/hlsl/raypayload-attribute.slang, tests/vkray/raygen-trace-ray-param-non-struct.slang
Closes https://github.com/shader-slang/slang/issues/6104
=> Add raypayload decoration to ray payload structs

source/slang/slang-diagnostic-defs.h, source/slang/slang-ir-legalize-types.cpp, source/slang/slang-legalize-types.cpp, source/slang/slang-legalize-types.h, tests/diagnostics/uninitialized-resource-type.slang, tests/diagnostics/uninitialized-resource-type.slang.1.expected, tests/diagnostics/uninitialized-resource-type.slang.expected
close #6328.
When declare a var with struct type, if the struct has a resource type field and it doesn't provide explicit constructor, because slang won't implicit construct such variable at declare site if user doesn't explicitly call the initializer list, we should report the resource type field uninitialized as an error to prevent future possible crash when legalize any use of such variable.
=> Fix crash when handling uninitialized resource type

tools/slang-test/slang-test-main.cpp, tools/slang-test/test-context.cpp, tools/slang-test/test-context.h
=> Migrate slang-test away from deprecated Slang API

source/slang/slang-diagnostic-defs.h, source/slang/slang-ir-check-shader-parameter-type.cpp, tests/diagnostics/nested-constant-buffer-in-parameter-block.slang, tools/slang-unit-test/unit-test-metal-parameter-block-constant-buffer.cpp
This loosens the check on constant buffers in parameter blocks in metal
Disallow only resources in constant buffers in parameterblocks on metal
closes https://github.com/shader-slang/slang/issues/6200
=> Disallow only resources in constant buffers in parameterblocks on metal

source/slang-core-module/CMakeLists.txt, source/slang/slang-ast-support-types.h, source/slang/slang-lookup.cpp, source/slang/slang-parser.cpp, tests/front-end/in-redeclare.slang
=> Fix modifier parsing.

CMakePresets.json
This commit adds a CMake build target `vs2019-dev`. The suffix `-dev` enables the IR break ability.
=> Add CMake build target vs2019-dev that enables IR break

tests/hlsl/simple-hull-shader-1.slang
One of Hull shader tests was disabled.
Git history doesn't tell much of why it was disabled.
This commit fixes a minor mistake and enables the test for SPIRV.
=> Enable Hull shader test for SPIRV

source/slang/slang-diagnostic-defs.h, source/slang/slang-parameter-binding.cpp, tests/bugs/binding-attribute-ignored.slang
Fix for #4251 
When binding attributes (like [[vk::binding]]) are specified on uniforms that get packed into the default constant buffer, these binding attributes are effectively ignored since the uniform will always be placed at descriptor set 0, binding 0. This can be confusing for users who expect their explicit bindings to take effect.
This change adds a new warning (71) that informs users when their binding attributes on uniforms will be ignored, and suggests declaring the uniform inside a constant buffer to preserve the explicit binding.
The warning helps users understand:
1. Why their binding attribute isn't having the expected effect
2. That the uniform is being packed into the default constant buffer
3. How to fix it by using a constant buffer declaration
Added test case in …
=> Add warning for ignored binding attributes on uniforms

source/slang/hlsl.meta.slang
noise() is currently marked "unsupported" in Slang documentation, and has also been unsupported in HLSL since SM 2.0
Until now, noise() was present only to prevent compilation errors, but not for any actual use since it returns 0.0 always.
Closes #5775
=> Remove noise() from core library

tools/gfx/metal/metal-command-encoder.cpp, tools/gfx/metal/metal-device.cpp
Close #6386.
- Implement uploadTextureData in metal
- Fix a bug in 'copyTextureToBuffer' in metal The last parameter for Metal::copyFromTexture is the 'destinationBytesPerImage', but previous implementation fill in the destination size which is wrong in 3-D texture.
=> Add implementation for 'uploadTextureData' in metal

source/slang/slang-check-overload.cpp, source/slang/slang-compiler.h, source/slang/slang.cpp
If `candidate.candidate.item.declRef.declRefBase` is a genericapp declref created in previous session, it will be an invalid pointer, and `as<DirectDeclRef>(candidate.candidate.item.declRef.declRefBase)` will crash. We should instead use the decl to check if it is a generic decl ref.
=> Fix TypeCheckingCache concurrency and candidate lifetime.

source/slang/slang-diagnostic-defs.h, source/slang/slang-ir-glsl-legalize.cpp, tests/diagnostics/tessellation-legalize-array-size-too-big.slang, tests/spirv/tess-factor-legalize-array-size.slang
When targeting SPIR-V or GLSL, the type for SV_TessFactor must be float[4]; note that it is not a vector but an array. Similarly the type of SV_InsideTessFactor has to be an array of float[2].
When the user shader declare them as arrays smaller than the required size, Slang will legalize them to the required sizes.
Note that it is not the user mistake to declare floar[3] when the hull mode is in "tri", as an example. The unused components are expected to be ignored.
Note also that HLSL allows the type to be float[2|3|4] whereas GLSL and SPIR-V requires it to be always float[4].
Closes https://github.com/shader-slang/slang/issues/6349
=> Legalize array size of SV_TessFactor and SV_InsideTessFactor

source/slang/slang-ir-ssa.cpp, tests/diagnostics/uninitialized-variable-name-in-error-message.slang
When emiting "Undefined", we lost the information of where it was synthasized from. This prevents us from providing more helpful error messages.
The issue was the when we handle "IRLoop", the inputs parameters to the Phi didn't clone the name hint decoration. This commit clones them when emiting "Undefined".
Closes https://github.com/shader-slang/slang/issues/6305
=> Clone name hint decoration when emiting Undefined

source/slang/slang-ir-autodiff-primal-hoist.cpp, source/slang/slang-ir-inst-defs.h, source/slang/slang-ir-insts.h, source/slang/slang-ir-util.cpp, source/slang/slang-ir.cpp, tests/autodiff/reverse-continue-loop.slang, tests/autodiff/reverse-loop-immediate-return.slang
- We introduce a 'OpCheckpointObject' inst and use that to split loop state insts into two pieces (one for within-loop uses and one for outside-loop uses.
- This allows the two kinds of uses to be handled separately by the hoisting mechanism
- `OpCheckpointObject` is then lowered to a no-op after hoisting is complete.
Also added a test to check for this.
Fixes: https://github.com/shader-slang/slang/issues/6394 and https://github.com/shader-slang/slang/issues/5999
=> Fix a bug with hoisting 'IRVar' insts that are used outside the loop

source/slang-glslang/slang-glslang.cpp
This change will allow us to read the SPIRV-asm with more friendly variable names.
Currently it dumps the variables as numbers.
There are variable name decorations defined as a part of the dumped spirv, but we had to manually reference them.
With the friendly-name option enabled, the number style variable names are replaced with the string style names.
It will help us to read the spir-v dump more easily.
=> Enable friendly-name option for SPIRV dump and validation

examples/reflection-api/compute-simple.slang, examples/reflection-api/main.cpp, include/slang-deprecated.h, include/slang.h, source/slang/slang-check-decl.cpp, source/slang/slang-check-impl.h, source/slang/slang-reflection-api.cpp
One of the pain points of working with shaders is needing to keep the definitions of interface types in sync between shader and device code. With the reflection API of slang, it is possible to automate this process by generating a header file for the host language from the reflection data, that contains all interface types used in the shader.
However, one thing missing is the ability to get the value of compile-time constants defined in the shaders. This is useful if you have some constant that an algorithm or a data structure depends on, like a static block or tile size, and you don't want to have to keep them in sync manually between host and shader.
To solve this (at least for integers) this PR adds `VariableReflection::getDefaultValueInt` to get the default value of a variable if it …
=> expose value of constant integers in module reflection

source/slang/slang-emit-spirv.cpp, tests/spirv/atomic-memory-class.slang
=> [SPIRV]: Emit missing storage class in atomic insts.

external/spirv-tools-generated/build-version.inc, external/spirv-tools-generated/generators.inc, external/spirv-tools-generated/operand.kinds-unified1.inc
supersedes https://github.com/shader-slang/slang/pull/6477
This uses the latest public versions, rather than the latest tag
=> Bump glslang and deps

source/slang/slang-check-expr.cpp, source/slang/slang-check-overload.cpp, tests/language-feature/namespaces/namespace-import/overload-resolve.slang
- Fixed comparison returning an inverted value.
- Fixed iteration over lookup result items (should iterate over items even if `declRef` is null)
Fixes: https://github.com/shader-slang/slang/issues/6484
=> Fix overload resolution for `ModuleDeclarationDecl`

CMakePresets.json, tests/bugs/ray-query-in-generic.slang, tests/compute/byte-address-buffer-aligned.slang, tests/compute/byte-address-buffer-array.slang, tools/render-test/options.cpp, tools/render-test/options.h, tools/render-test/render-test-main.cpp, tools/slang-test/slang-test-main.cpp
changes in slang-rhi:
- fix build issue where chrono was not included
- always build cuda driver api
- Viewport::fromSize and ScissorRect::fromSize
- rename structs
- arena allocator cleanup + test
- work on fences
- remove ref counting
- expose dynamically loaded cuda driver api
- add BufferUsage::Shared and TextureUsage::Shared
- Metal improvements
- enable shadowing warnings
- increase warnings on apple clang
- generate label for texture views
- add surface, rasterization and parameter-block device features
- add GPU_TEST_CASE macro
- remove enableBackendValidation from DeviceDesc
- add copy buffer test
- CUDA surface
- update api.md
- Refactor shader object
- cooperative vector support
=> update slang-rhi (shader object refactor)

source/slang/slang.cpp
The default matrix layout mode was applied in addition to any related options, and this caused the wrong matrix layout mode to be used.
For example, tests/compute/column-major was failing when attempting to migrate to the new compilation API.
This helps to address issue #4760
=> Don't add multiple matrix layout options when creating a session

source/slang/slang-check-inheritance.cpp, tests/bugs/gh-6488-where-lookup.slang
Closes #6488.
Given:
```
interface IRealArray<T : __BuiltinFloatingPointType, int D> {}
extension<T : __BuiltinFloatingPointType, int D> vector<T, D> : IRealArray<T, D> where T.Differential : __BuiltinFloatingPointType { }
```
The issue is when we are applying `extension.T` to `IRealArray<T,D>`, we need to check `extension.T` is conforming to `__BuiltinFloatingPointType`. In doing so, we will need to form the inheritance list of `extension.T`. But forming this inheritance list requires us to check all `GenericTypeConstraintDecl`s on the generic decl that `extension.T` belongs to, which means checking the `where` clause. When we check the left hand side of the `where` clause, we need to lookup for `Differential` in `T`, and this gets back to needing the inheritance list of `T`, which is …
=> Fix member lookup in left hand side of `where` clause.

.github/workflows/ci.yml, source/slang/slang-lower-to-ir.cpp, tests/expected-failure-github-runner.txt, tools/slang-unit-test/unit-test-find-check-entrypoint.cpp
- add a repro of the problem
- This is added as a unit test, because the new API is not yet in use for the tests in tests/ 
- This unit test can be removed when the new API is used for tests/
- Simple fix that detects entry points more robustly when applying some "ConstRef hack"
- When using the old API, an explicit EntryPointAttribute was being attached to the entry point, even though none was present in the code
See issue #6507 for debugging notes.
This closes issue #6507.
=> Fix codegen bug when targeting PTX with new API

source/slang/slang.cpp
This helps to address issue #4760.
The particular issue motivating this fix is that
IGlobalSession::parseCommandLineArguments uses a temporary compile request to parse options.
The compile request only adds the OptionKind::ForceDXLayout (-fvk-use-dx-layout) to the "current target" which may be the default target, which IGlobalSession::parseCommandLineArguments didn't look for, meaning that options like ForceDXLayout were just ignored.
This leads to test failures in tests that rely on this option, e.g. tests/spirv/cbuffer-dx-layout-1.slang.
=> Get options also from the default target

source/slang/slang-check-conversion.cpp, source/slang/slang-check-decl.cpp, tests/initializer-list/explicit-ctor-diagnostic.slang, tests/initializer-list/struct-inherit-diagnostics.slang, tests/initializer-list/struct-inherit.slang, tests/language-feature/interfaces/default-construct-conformance.slang
This is fix for the implementation bug, when a struct has explict ctor we should not synthesize the default ctor anymore.
=> Fix a bug in default ctor synthesizing

CMakeLists.txt
Add option to exclude webgpu-dawn and slang-tint from the build, for environments that need to build Slang without internet access.
=> Add option to exclude webgpu-dawn and slang-tint

source/slang/slang-emit-spirv.cpp
The SPIRV Generator ID is actually in the high 16 bits.
=> Fix SPIRV Generator ID.

source/slang/slang-check-shader.cpp
Sharpen condition on warning about used capabilities relative to a requested profile or capability.
If the profile/capability in options set, but set to unknown, then don't count the setting as requesting a particular profile/capability.
This helps in addressing issue #4760 because the new session-based compilation API always adds a profile setting via Linkage::addTarget, even if the profile is unknown.
That caused lots of tests to fail due to unexpected output: "warning 41012: entry point 'computeMain' uses additional capabilities that are not part of the specified profile..."
The old compilation request -based API did not add profile/capabiltiy to the options, and so did not generate this warning.
=> Sharpen condition on warning about used capabilities

source/slang/slang-options.cpp
Previously, the module was just added to the compile request directly. This is a problem because the non-deprecated command line option parsing interface IGlobalSession::parseCommandLineArguments just creates a temporary compile request. Therefore these options are currently not detected by the API.
This helps to address issue #4760 since it will need to access these modules in order to supply all of the required code.
=> Add module reference options to options list when parsing them

source/slang-glslang/slang-glslang.cpp
Precompiled SPIR-V bits can independently resolve to different versions of SPIR-V.
To avoid a linker error about mismatched versions, use a linker feature to automatically use the highest version listed in the modules.
Fixes #6548
=> UseHighestVersion when calling spirv-link

source/slang/slang-compiler-tu.cpp, tools/gfx-unit-test/precompiled-module-2.cpp
Abort precompileForTarget if it's already done.
Fixes #6516
=> Don't crash when precompiling twice

include/slang.h
This allows clients to define `SLANG_USER_CONFIG` to include a config file that sets defines picked up by `slang.h`.
=> add SLANG_USER_CONFIG

tools/gfx-unit-test/link-time-type-layout-nested.cpp
closes https://github.com/shader-slang/slang/issues/6556
=> test that link time extern struct layouts are visible for nested types

source/slang/hlsl.meta.slang, source/slang/slang-emit-wgsl.cpp, source/slang/slang-emit.cpp, tests/cross-compile/get-dimensions.slang
Closes #6582.
Implement `GetDimensions` for `*StructuredBuffer` and `*ByteAddressBuffer` on WGSL.
=> Implement GetDimensions for structured buffers on WGSL

.github/workflows/release-linux-glibc-2-17.yml, .github/workflows/release.yml
Current releases are removing "v" from "vulkan-sdk-1.4.309.0" when they were supposed to remove it from something like "v1.2.4" https://github.com/shader-slang/slang/releases/tag/vulkan-sdk-1.4.309.0
Fixed it so it only removes "v", if next character is a number
=> fix trimming of "v" from version string

source/slang/slang-ir-autodiff-fwd.cpp, tests/autodiff/non-differentiable-swizzle.slang
Fixes: https://github.com/shader-slang/slang/issues/6612
=> Fix crash when swizzling non-differentiable types

source/slang/slang-ir-addr-inst-elimination.cpp, source/slang/slang-ir-autodiff-fwd.cpp, tests/autodiff/get-offset-ptr.slang
Allows non-differentiable ptr types to be used within differentiable function bodies. They will be treated as primal values, but if represented in "pairs", they are a very useful way to perform derivative aggregation.
Fixes: https://github.com/shader-slang/slang/issues/6562
=> Add auto-diff support for `GetOffsetPtr`

external/CMakeLists.txt, tests/bugs/gh-6482-interface-method-existential-specialize.slang
=> Fix MSVC warning D9025 when building external dependencies.

source/slang/glsl.meta.slang, tests/glsl-intrinsic/array-length.slang
Implement array.length() function for GLSL syntax.
Closes #6652
=> Add GLSL array length syntax support

source/slang/glsl.meta.slang, tests/glsl-intrinsic/debug-printf.slang
Related to #6652.
Implements GLSL `debugPrintfEXT` syntax, which just calls the already implemented Slang `printf` function.
=> Add GLSL debugPrintfEXT syntax support

prelude/CMakeLists.txt, tools/slang-embed/slang-embed.cpp
Fixes: #6674 
This change makes it so that we emit the full set of include directories from CMake as a command line argument to slang-embed. 
Hopefully this puts an end to prelude generation issues, and makes it so that we don't have to do elaborate workarounds to our include paths to keep `slang-embed` happy.
=> Improve embed tool to search all include directories as determined by CMake

source/slang/slang-ir-legalize-types.cpp
Close #6541.
Previously in type legalization pass, we skip the `VoidType` field when call `make_struct`, however in some optimization pass we keep counting the `VoidType` field. We have to make this behavior consistently over all our codebase.
So in this change, we spot the `make_struct` call and leave `VoidType` field as it.
=> Make make_struct call consistent

source/slang/slang-parser.cpp, tests/language-feature/namespaces/simple-namespace.slang
This should fix expr like `2.0f * ::a::b::c`
But it will no longer parse something like
```
extension<T> Ptr<T> { static void foo(); }
int*::foo() // won't work, but this is a less common case
```
Fixes #6684
=> Fix mul operator followed by global scope

source/slang/slang-emit-spirv.cpp, tests/hlsl-intrinsic/quad-control/quad-control-frag-many-entry-points.slang
Vulkan validation layers emit warnings on lowercase khr.
=> Fix SPV_KHR_maximal_reconvergence extension name spelling

source/slang/slang-emit.cpp, source/slang/slang-ir-legalize-types.cpp, source/slang/slang-legalize-types.cpp, source/slang/slang-legalize-types.h, tests/metal/empty-struct-remove.slang
Close #6573.
We previously disabled the type legalization for ParameterBlock on Metal, but Metal doesn't allow empty struct in the argument buffer which is mapped from ParameterBlock, so we will need legalizeEmptyTypes on Metal target.
=> Eliminate empty struct on metal target

source/slang/slang-check-shader.cpp
close #6694
We should return nullptr when findAndValidateEntryPoint fails to valid the entrypoint.
=> findAndValidateEntryPoint should return null on failing

tests/hlsl-intrinsic/ray-tracing/rt-pipeline-intrinsics-ahit.slang, tests/hlsl-intrinsic/ray-tracing/rt-pipeline-intrinsics-int.slang, tests/metal/texture.slang
Closes #4919
Related to #6250 
This commit upgrades DXC version from 1.7 to 1.9 that supports CoopVector.
The DXC is compiled from a [public repo](https://github.com/NVIDIA-RTX/DirectXShaderCompiler/tree/CooperativeVector), and it uses `MinSizeRel` build config.
The version information from a command "dxc.exe --help":
Version: dxcompiler.dll: 1.9 - 1.8.0.4817 (CooperativeVector, 018d767f9); dxil.dll: 1.9(1.8.0.4817)
=> Use coopvec supporting dxcompiler.dll and dxil.dll

.github/workflows/ci.yml
MacOS test is accidentally disabled in #6491. Re-enable it.
=> re-enable macos test

source/compiler-core/slang-dxc-compiler.cpp
Closes https://github.com/shader-slang/slang/issues/6442
=> Enable "-HV 2021" option for DXC

source/slang/slang-emit.cpp, source/slang/slang-ir-cleanup-void.cpp, source/slang/slang-ir-legalize-types.cpp, source/slang/slang-legalize-types.cpp, source/slang/slang-legalize-types.h, tests/metal/empty-struct-remove.slang
Remove argument in make_struct call corresponding to void field
- This is a follow-up of #6543, where we leave the VoidType field as it in
make_struct call during legalization pass.
So during cleaning_void IR pass, when we remove "VoidType" from struct,
we will have to also clean up the argument corresponding to the
"VoidType" field.
- Reapply "Eliminate empty struct on metal target (#6603)" which is reverted in (#6711)
Because #6603 is not the root casuse. #6543 is.
=> Metal remove void field

tools/gfx/metal/metal-helper-functions.h, tools/gfx/metal/metal-shader-object-layout.h, tools/gfx/metal/metal-shader-object.cpp, tools/gfx/metal/metal-shader-object.h
Close #4816
Implement the parameter block support for slang-gfx metal backend.
On Metal, we will use argument buffer to bind parameter block, so we have to use argument buffer tier2 rule to calculate the layout for parameter block.
When using argument buffer, everything resources the argument buffer will be bound as bindless resource via device memory pointer or resource IDs, so we will have to notify the encoder to hazard track those resources.
=> Implement parameter block to slang-gfx for Metal backend

source/slang/slang-ir-autodiff.cpp, source/slang/slang-ir-autodiff.h, source/slang/slang-ir-check-differentiability.cpp, tests/bugs/gh-6632.slang
Closes https://github.com/shader-slang/slang/issues/6632
=> Do no fail on missing no_diff annotation on non-differentiable function outputs

source/slang/glsl.meta.slang, source/slang/hlsl.meta.slang, source/slang/slang-ir-legalize-varying-params.cpp, source/slang/slang-ir-legalize-varying-params.h, tests/glsl-intrinsic/shader-subgroup/shader-subgroup-quad.slang, tests/hlsl-intrinsic/subgroup-quad.slang
Closes #6610.
Implements subgroup quad operations for Metal. Metal does not support `QuadReadAcrross*` or `subgroupQuadSwap*` intrinsics directly. They are implemented using `quad_shuffle` and `thread_index_in_quad_group `, as described [here](https://github.com/gpuweb/gpuweb/blob/main/proposals/subgroups.md#appendix-b-wgsl-built-in-function-mappings).
=> Implement subgroup quad operations for Metal

source/slang/slang-emit.cpp, source/slang/slang-ir-cleanup-void.cpp, source/slang/slang-ir-legalize-types.cpp, source/slang/slang-ir-peephole.cpp
This change is a rework on previous PR #6725.
The background of this issue is that we have inconsistent IR instructions cross our code base for make_struct and get_field regarding the `void` field.
Think about the struct:
```
struct
{
void a;
int b;
}
```
this is generated during the resource type legalization pass which will finally be eliminated. However, during IR passes we still need to access such intermediate struct.
So if we call `make_struct(a, b)`, we will have to call `get_field(0)` for a and `get_field(1)` for b, while if we call `make_struct(b)`, we will need to call `get_field(0)` for b.
Both ways are the correct fix, we just need to see which way take us less effort.
Previously in #6725, we choose the 1st way that when constructing construct, we just keep the `void` field in …
=> void field rework

source/slang/slang-check-overload.cpp, source/slang/slang-diagnostic-defs.h, tests/diagnostics/concrete-argument-to-output-interface.slang, tests/diagnostics/concrete-argument-to-output-interface.slang.expected
Fixes #6779 with a more helpful error message.
=> Add a more specific diagnostic message when passing concrete value to interface-typed output parameter

source/slang/slang-emit-glsl.cpp, tests/spirv/pointer-2.slang
Closes #6710.
Fixes field/member acceses for pointer(`*`) syntax when targeting GLSL. The current behavior returns internal error 9999/unexpected IR during code emit.
=> Fix pointer field/member access for GLSL

docs/user-guide/a2-01-spirv-target-specific.md, docs/user-guide/a2-02-metal-target-specific.md, source/slang/glsl.meta.slang, source/slang/slang-emit-spirv.cpp, source/slang/slang-ir-glsl-legalize.cpp, source/slang/slang-ir-legalize-varying-params.cpp, source/slang/slang-ir-legalize-varying-params.h, source/slang/slang-language-server-completion.cpp, tests/glsl-intrinsic/point-coord.slang
Adds support for [`gl_PointCoord`](https://registry.khronos.org/OpenGL-Refpages/gl4/html/gl_PointCoord.xhtml) in the GLSL compatibility mode and a simple test for it.
It'd probably be nice to have this functionality available even without the GLSL compatibility mode, but that requires some kind of API decisions since HLSL doesn't have any equivalent value, and it would only work with the GLSL and SPIRV targets.
=> Add SV_PointCoord to match gl_PointCoord

source/compiler-core/slang-nvrtc-compiler.cpp
On Debian systems, the distro CUDA packages install headers to `/usr/include`.
=> CUDA: try to find cuda headers in /usr/include

.github/workflows/add-issue-labels.yml
The auto labeling CI has been failing as a result of the SLANGBOT_PAT token not having all of the necessary permissions. Change updates the tokens used for requests to use new tokens that were created with the specific permissions needed for the operations in this CI workflow.
=> Update the access tokens used for auto labeling CI

source/slang/slang-parser.cpp
This avoids creating a lot of unnecessary `EmptyDecl`s after parsing a TypeDef decl.
Closes #6760.
=> Consume `;` after parsing typedef decl.

source/slang/slang-ir-specialize.cpp, tests/bugs/gh-6589.slang
Close #6589.
In PR #6487, we support partial specialization. However there is a corner case we didn't handle correctly.
For the IR like this:
```
%val: specialize(...) = some inst;
%arg1: specialize(...) = makeExistential(%val, ...);
%arg2: %SomeConcreteType: load(...);
call func(%arg1, %arg2);
```
when we specialize the `call func` instruct, we will also specialize the function parameters.
On our existing logic, when we find an argument is a `makeExistential`, we will always extract the existential value, and use its type as the new parameter.
But in this case, %arg1 is not fully specialized yet, so it's type will still be a `specialize`. In this case, we will change the function's first parameter from an existential type to a `specialize`. This will result in that we lose the chance to …
=> Fix regression in partial specialization of existential arguments

.github/workflows/vk-gl-cts-nightly.yml
Closes https://github.com/shader-slang/slang/issues/6833
With recent changes in Slang, one more DLL needs to be copied to run vk-gl-cts properly, `slang-glsl-module.dll`.
It is unclear why it had been working on servers other than GCP servers.
=> Copy slang-glsl-module.dll for vk-cts test

source/core/slang-dictionary.h, source/slang/slang-ir-autodiff-loop-analysis.cpp
In slang-ir-autodiff-loop-analysis.cpp (added by 41e7e565eb3dfa13562cbfa3e8641874c2c6d66c), there was a filtering of a dictionary with a range for loop, which is not permitted. I replaced it with proper iterator handling. 
This was crashing when I was running tests (compiled with MSVC). I find it surprising that some of the latest commits passed all the tests and did not have this issue. I may be doing something wrong, but I can't find what?
=> Fixed crash in slang-ir-autodiff-loop-analysis.cpp

include/slang-gfx.h, tools/gfx/debug-layer/debug-device.cpp, tools/gfx/debug-layer/debug-device.h, tools/gfx/renderer-shared.cpp, tools/gfx/renderer-shared.h, tools/gfx/vulkan/vk-api.cpp, tools/gfx/vulkan/vk-device.cpp, tools/gfx/vulkan/vk-device.h, tools/gfx/vulkan/vk-util.cpp, tools/gfx/vulkan/vk-util.h
Closes https://github.com/shader-slang/slang/issues/6791
Basically the PR defers the call to `vkGetPhysicalDeviceCooperativeVectorPropertiesNV` after we get the list of available extensions.
The exact same modification was already implemented on slang-rhi and this PR ports over from slang-rhi to slang-gfx.
In other words, there is no new lines written and all of them are copy-and-pasted from slang-rhi to slang-gfx.
=> Check the available VK extensions before using CoopVec APIs in GFX

cmake/CompilerFlags.cmake
This PR fixes the compiler warning like following, lld-link: warning: ignoring unknown argument '--no-undefined' lld-link: warning: ignoring unknown argument '--build-id', did you mean '-build-id'
chatGPT said that those options are for ELF and not for Windows:
These warnings happen because the Clang toolchain on Windows is invoking lld-link, which is the LLVM linker frontend for link.exe compatibility (i.e., it acts like the MSVC linker). The arguments --no-undefined and --build-id are ELF-specific flags, which are valid when targeting Linux, but not valid in the PE/COFF (Windows) environment.
Here's a breakdown:
⚠️ Warning messages explained:
lld-link: warning: ignoring unknown argument '--no-undefined' → This is a Linux/ELF flag. On Windows, this has no effect and is unknown.
lld-link: …
=> Fix compiler warning on Windows about -build-id

docs/language-reference/04-types.md
This is to address one of cases where a user was confused about why Slang doesn't have operator overloading of multiplication for matrices.
It is little confusing that glsl.meta.slang implemented `operator*()` for matrices but Slang/HLSL doesn't. It turned out that HLSL/Slang performs a component-wise multiplication with `operator*()` whereas GLSL performs a matrix multiplication.
=> Document matrix multiplication operators

docs/64bit-type-support.md, prelude/slang-cpp-scalar-intrinsics.h, prelude/slang-cuda-prelude.h, source/slang/hlsl.meta.slang, tests/hlsl-intrinsic/countbits64.slang
Change modifies the countbits intrinsic to use generics in order to support 64bit countbits on select platforms where this is supported.
This should align with the implementation of other uint64_t intrinsics such as abs, min, max and clamp.
Added new countbits64 test to verify changes.
Updated documentation for 64bit-type-support.html
=> Implement 64bit countbits intrinsic for select targets (#6433)

source/slang/slang-ir-simplify-cfg.cpp, tests/bugs/gh-6860.slang, tests/bugs/gh-6862.slang
Fixes #6862 and #6860, and supersedes #6861 and #6866.
In both cases, unnecessary phis were sticking around, as they had two options: the value before the loop, and themselves. Since in this case the only possible value it could have is the value before the loop, the phi can be removed. This fixes both issues, as both are related to unnecessary self-referential phis messing up optimization or WGSL output.
=> Allow simplifying self-referential Phi parameters

source/slang/hlsl.meta.slang, tests/hlsl-intrinsic/quad-control/quad-control-comp-functionality.slang
Adds SPIRV 1.3 version decoration for quad control intrinsics to fix compilation with downstream glslang compiler.
=> Fix quad control required SPIRV version for emit-spirv-via-glsl path

source/slang/core.meta.slang, source/slang/slang-ast-modifier.h, source/slang/slang-check-modifier.cpp, source/slang/slang-emit-c-like.cpp, source/slang/slang-emit-c-like.h, source/slang/slang-emit-glsl.cpp, source/slang/slang-emit-glsl.h, source/slang/slang-emit-wgsl.cpp, source/slang/slang-emit-wgsl.h, source/slang/slang-ir-inst-defs.h, source/slang/slang-ir-insts.h, source/slang/slang-ir-layout.cpp, source/slang/slang-lower-to-ir.cpp, tests/diagnostics/vk-offset.slang, tests/spirv/vk-offset.slang
Closes #6660.
Adds a `vk::offset` modifier to specify offsets for struct fields. The main use-case for this is for push constants to specify member variables for different shader stages. The `vk::offset` is derived from DXC, this has already been implemented there.
=> Add `vk::offset` to specify member offsets for push constants

include/slang-com-helper.h
This PR adds `SLANG_OVERRIDE` to `SLANG_IUNKNOWN_ADD_REF` and `SLANG_IUNKNOWN_RELEASE`, fixing build for projects that use this macros and use compiler options that forbid not using `override`.
=> Add `SLANG_OVERRIDE` to `SLANG_IUNKNOWN_` macros

tools/gfx/debug-layer/debug-transient-heap.cpp, tools/gfx/renderer-shared.cpp
Hello all,
I am doing something similar as https://github.com/shader-slang/slang/pull/5978 where i am writing COM wrappers for slang. All went good for the core slang lib and reflections APIs thus far, but i hit a few issues with the gfx wrapper.
First one is in the IDevice implementation, in the case another uuid was queried than IDevice it would return null with the OK code. This would crash when the .Net runtime tries to query the interface.
https://github.com/shader-slang/slang/blob/043278a527ab5744674417a08d924c67a60a486b/tools/gfx/renderer-shared.cpp#L398-L410
I hit another snag in the debug transient heap, weirdly the inner object was returned instead of the debug wrapper version. I supposed this was unintended looking at the code. It would cause an access violation when …
=> Fixed various queryInterface implementations

source/slang/slang-check-stmt.cpp, tests/bugs/serialization/gh-6892.slang
Work on #6892
The function `tryInferLoopMaxIterations` in `slang-check-stmt.cpp` was doing:
auto litExpr = m_astBuilder->create<LiteralExpr>();
but the declaration of `LiteralExpr` in `slang-ast-expr.h` had been marked as abstract, during the switch to using the `slang-fiddle` tool to generate code:
FIDDLE(abstract)
class LiteralExpr : public Expr
{ ... }
In this case, the intention of the AST design is that `LiteralExpr` should be kept abstract, and only the concrete subclasses should ever be instantiated.
Because of some historical design choices, the `ASTNodeType` enumeration includes both the concrete and abstract AST classes, so the code ended up constructing a `LiteralExpr` that had the tag `ASTNodeType::LiteralExpr`. Then attempts to use the `ASTNodeDispatcher` code on such a node …
=> Fix attempt to construct an abstract AST node

source/slang/slang-ir-autodiff-loop-analysis.cpp
Addresses the auto-diff crash for #6815
=> Auto-diff loop analysis: Handle case where either side of a conditional branch is empty

source/slang/slang-ir-glsl-legalize.cpp, tests/bugs/gh-9918.slang
Fixes: #6918
Problem: If a mesh shader output attribute (`IRMeshOutputRef`) is the `this` of a struct and a `mutable` method is used, Slang (in IR) will `IRLoad` the `this` pointer of the `IRMeshOutputRef`. This is an issue since `legalizeMeshOutputParam` does not handle `Load` currently and will throw an exception if we `IRLoad` a `IRMeshOutputRef` during our legalization pass.
Solution: Add code to allow `IRLoad` of a `IRMeshOutputRef`.
=> Support use of `this` with Mesh Shader Outputs (`IRMeshOutputRef`)

source/slang/slang-ast-decl.h, source/slang/slang-serialize-ast.cpp, source/slang/slang-serialize.h
There are two fixes included here.
The smaller fix is in `slang-ast-decl.h`, where the `CallableDecl::primaryDecl` and `::nextDecl` fields need to be serialized to make sure that we can properly deserialize a module that contains any function redeclarations.
The larger fix is that the `Encoder` and `Decoder` types used to serialize out the AST nodes in a JSON-like hierarchy were being very strict about matching of integer types, which causes problems in any case where serialization code might use a type that is 32-bit on some targets and 64-bit on others, if serialized modules are ever created on one of those targets and consumed on the other (which happens for the core module for some of our targets).
The fix that this change implements is to make the serialization logic there more …
=> Fixes related to AST serialization change

source/slang-record-replay/replay/decoder-helper.h
`include/slang.h` has `SLANG_NO_THROW` on a few member functions.
The replay implementation didn't use them and compiler was printing warnings which is treated as an error on my machine.
=> Fix compiler warning with clang 18.1.8 on windows

docs/user-guide/03-convenience-features.md, source/slang/hlsl.meta.slang, tests/language-feature/descriptor-handle/desc-handle-4.slang
This is to allow user defined `getDescriptorFromHandle` function to tell more precisely the type of the resource.
Partially addresses #6952.
=> Add `IOpaqueDescriptor::descriptorAccess`.

.github/workflows/falcor-compiler-perf-test.yml
Update the falcor perf test path environment variable so that it checks existing paths only after the build path. This is needed to prevent it from accidentally using a previously installed version of Slang.
=> Update falcor perf test path

docs/user-guide/a1-special-topics.md, docs/user-guide/a2-target-specific-features.md, docs/user-guide/a3-reference.md, docs/user-guide/index.md
For https://github.com/shader-slang/shader-slang.github.io/issues/72
This change adds hidden (commented out) tables of contents to the index of the User Guide, as well as each of the additional chapters, so that readthedocs will render the User Guide structure.
=> Add readthedocs tables of contents to Slang User Guide

tools/slang-fiddle/slang-fiddle-scrape.cpp, tools/slang-unit-test/unit-test-find-check-entrypoint.cpp
`cudaCodeGenBug` is expected to fail on Linux, because the variable `code` is nullptr. When the next test tried to dereference, it causes a seg-fault.
=> Fix seg-fault in cudaCodeGenBug test

source/core/slang-stream.cpp
Closes https://github.com/shader-slang/slang/issues/6974
The use of `_wfopen_s()` was incorrect in a way the the result value had to be checked.
However, even with a proper handling of the failed case, the repro-rate was same.
The issue was reproduced at 5%~20% rate with the following commands,
build/Release/bin/slang-test.exe tests/autodiff/auto-differential-type -api dx11 -use-test-server -server-count 8
_wfsopen appears to be a good alternative.
The intermittency failure is not observed with it; tried 1,000 times and no repro.
=> Fix the intermittent failures of tests/autodiff/auto-differential-type

cmake/CompilerFlags.cmake, source/core/slang-io.cpp, source/slang/slang-ir.h, tools/gfx/metal/metal-device.cpp, tools/slang-test/slang-test-main.cpp, tools/test-server/test-server-main.cpp
Closes https://github.com/shader-slang/slang/issues/6945
Updated https://github.com/shader-slang/slang/issues/5537 to include c++17 header check
=> Update C++ standard to C++20

source/slang/slang-ir-extract-value-from-type.cpp, tests/glsl/interger_pack.slang, tests/language-feature/bit-cast/float-bit-cast.slang
Fix the issue in lowering bitcast that it requires input has the same width with result type.
Close https://github.com/shader-slang/slang/issues/7017.
=> bitcast require the input has same width with result type

source/slang/slang-doc-markdown-writer.cpp
Fixes https://github.com/shader-slang/shader-slang.github.io/issues/98
This change restores the name of the "Properties" section in the Standard Modules Reference after I accidently overwrote it with some code in https://github.com/shader-slang/slang/pull/6904
=> Restore Properties section name in stdlib reference

source/slang/slang-lower-to-ir.cpp, source/slang/slang-mangle.cpp, tests/disabled-tests.txt, tests/language-feature/extensions/generic-extension-3.slang, tests/language-feature/extensions/generic-extension-4.slang
I have had some problems recently with genereics lately, mostly generic extensions. 
I made simple shaders to expose the problem.
example1.slang
```
interface IValuable
{
uint getValue();
};
__generic <Int : __BuiltinIntegerType>
extension Int : IValuable
{
uint getValue()
{
return 0;
}
};
__generic <Float : __BuiltinFloatingPointType>
extension Float : IValuable
{
uint getValue()
{
return 1;
}
};
RWByteAddressBuffer buffer;
[shader("compute")]
[numthreads(1, 1, 1)]
void main(uint3 gl_GlobalInvocationID : SV_DispatchThreadID)
{
uint i = gl_GlobalInvocationID.x;
float f = float(i) / float(10);	
buffer.StoreAligned<uint>(i, i.getValue()); // (a)
buffer.StoreAligned<uint>(i + 1000, f.getValue()); // (b)
}
```
When compiling this shader (I did it in SPIR-V and GLSL), there is no error, but …
=> Fixed name mangling of generic extensions

source/slang/slang-emit-spirv.cpp, source/slang/slang-ir.cpp, source/slang/slang-ir.h, tests/spirv/int-cast-unsigned-to-signed.slang
Closes #7035.
Unsigned to signed casts are currently done using `OpSConvert` which is incorrect as no sign extension should be performed. `OpUConvert` is used instead.
=> Fix SPIRV unsigned to signed widening casts

tools/render-test/options.cpp, tools/render-test/options.h, tools/render-test/slang-support.cpp, tools/slang-test/options.cpp, tools/slang-test/options.h, tools/slang-test/slang-test-main.cpp
This allows us to apply a certain capability while running slang-test.
You can use a command-line argument like,
```
slang-test.exe tests/compute/frem.slang -api vk -capability vk_mem_model
```
And you can also add an option for render-test like,
```
//TEST(compute):COMPARE_COMPUTE:-cpu -shaderobj -output-using-type -capability vk_mem_model
```
=> Add a new option "-capability" to slang-test and render-test

source/slang/slang-lower-to-ir.cpp
A reference-counting pointer type released a heap memory object when it return from the function and we are trying to dereference it later.
We should increment the ref-count by one by assigning it to the context before returning.
=> Fix invalid memory dereference in lower-to-ir

source/slang/slang-diagnostic-defs.h, source/slang/slang-emit.cpp, source/slang/slang-ir-validate.cpp, source/slang/slang-ir-validate.h, tests/diagnostics/invalid-vector-element-count.slang
Closes #6012. Slang currently only supports vector sizes supported by the compilations targets(i.e. no logic exists to lower long vectors), but no checks are done on the element count. Slang may generate invalid code such as `float13`. This PR adds a a check to error out on invalid vector element counts.
=> Error out on invalid vector sizes

docs/user-guide/a2-01-spirv-target-specific.md, docs/user-guide/toc.html
Closes #6805
This change adds a note to the SPIR-V target specific doc that `SV_InstanceID` does not map directly to SPIR-V's `BuiltIn InstanceIndex`, and adds a more detailed explanation of the difference, its motivation, and how to derive the actual value equivalent to `BuiltIn InstanceIndex` with an example.
=> Add explanation for SV_InstanceID usage difference from SPIR-V

docs/command-line-slangc-reference.md, docs/user-guide/a3-02-reference-capability-atoms.md, source/slang/hlsl.meta.slang, source/slang/slang-capabilities.capdef, source/slang/slang-emit-spirv-ops.h, source/slang/slang-emit-spirv.cpp, source/slang/slang-ir-inst-defs.h, source/slang/slang-ir-spirv-legalize.cpp, source/slang/slang-ir.h, tests/cooperative-matrix/load-store-tensorlayout.slang, tests/cooperative-matrix/load-store-tensorview.slang
This commit implements two new types and related Load/Store functions in `CoopMat`.
- tensor_addrressing.TensorLayout
- tensor_addressing.TensorView
- CoopMat.Load(..., TensorLayout)
- CoopMat.Load(..., TensorLayout, TensorView)
- CoopMat.Store(..., TensorLayout)
- CoopMat.Store(..., TensorLayout, TensorView)
- CoopMat.LoadDecode(..., TensorLayout, TensorView)
Currently there are two workarounds to avoid preexisted problems in Slang.
1. When `enum` is used as generic-parameter, Slang accepts overloading that have the same enum at same location. A workaround is to use `uint` instead of `enum`. ([issue 7061](https://github.com/shader-slang/slang/issues/7061))
2. When there are two overloading, `Load<uint>(...)` and `Load<U>(...)`, the first overloading seems to shadow the second one. A …
=> Support tensor addressing

source/slang/slang-check-type.cpp, source/slang/slang-ir-clone.cpp, source/slang/slang-ir-specialize.cpp, source/slang/slang-ir-util.cpp, source/slang/slang-ir-util.h, source/slang/slang-ir.cpp, source/slang/slang-lower-to-ir.cpp, tests/spirv/spec-constant-generic.slang
Close #6840.
This PR add supports to use specialize constant in generic parameter, and that parameter can also be used as array size, e.g. following code should work:
```
struct MyStruct<let N: int> { float buffer[N]; }
MyStruct<SpecConstVar> s;
```
- Loose the restriction from Link-Time to SpecializationConstant when extract generic argument
- Tweak the logic of how we decide whether a inst is hoistable. Besides checking existing hoistable flag of each IRInst, when we detect a IRInst's type is SpecConstRateType, we will treat that inst hoistable. Because IRInst in global scope can be deduplicated, and every SpecConstRateType inst should be in the global scope or IRGeneric scope (which will be at global scope after specialization).
- Remove the SpecConstIntVal to IRInst map in IR lowering …
=> Implement spec const for generic parameter

source/slang/slang-check-decl.cpp, tests/initializer-list/cpp-style-default-member-init.slang
close #7069.
We just insert the assignment expression to the beginning of the user-defined ctor, where the assginee is the member with init expression.
=> Implement C++ style default member initializer

.github/workflows/check-cmdline-ref.yml, .github/workflows/regenerate-cmdline-ref.yml
This change uses a different path for accessing the slangc binary during the command line reference doc regeneration action, as the environment variable referenced for the bin directory may not be accurate.
This change also makes some exclusions from the slang build in the command line reference actions, to speed up those builds for checking/regenerating.
=> Fix slangc path used by cmdline reference doc regeneration action

prelude/slang-cuda-prelude.h
This PR adds missing `tex[2D|2DArray|3D]fetch_int` specializations for signed integer formats to the CUDA prelude.
@mkeshavaNV maybe you could extend existing tests to coverer signed integer formats as well?
=> [CUDA] Add template specializations for signed integer texture fetches

.github/workflows/ci.yml, tools/slang-test/slang-test-main.cpp
- Fix the retry logic. Before it doesn't add to failedUnitTests if the test fails on retry, making the 2nd retry attempt impossible. Remove the bool check.
- Add print to show when a test is about to run; making it easy to identify which test fails next.
-  Update the CI yml file to allow manual dispatch, so that we can test in its own branch before creating PR.
-  Mark `slang-unit-test-tool/RecordReplay.internal` expected failure until we get 90% passing for it in CI.
#7148
=> Fix retry logic and skip high intermittent test failure

source/slang/slang-ast-val.cpp, source/slang/slang-ast-val.h, source/slang/slang-check-expr.cpp, source/slang/slang-lower-to-ir.cpp, source/slang/slang-mangle.cpp, tests/hlsl-intrinsic/size-of/size-of-compile-time.slang
=> Make sizeof(T) & alignof(T) of generic types work as compile-time constants

source/slang/core.meta.slang, source/slang/slang-check-conversion.cpp, tests/spirv/pointer-default-constructor.slang
Make `Ptr` type a c-tyle type to be able to initialize pointer variables with the `{}` syntax.
=> Add default constructor for Ptr type

source/core/slang-riff.h
Fixes when building with Clang 14.0 with a series of non-conventional cmake options
```
/usr/bin/ccache /usr/bin/clang++ -DMINIZ_STATIC_DEFINE -DNOMINMAX -DSLANG_ENABLE_DXIL_SUPPORT=0 -DSLANG_STATIC -DSTB_IMAGE_STATIC -DUNICODE -DVC_EXTRALEAN -DWIN32_LEAN_AND_MEAN -D_UNICODE -I/slang/source -I/slang/include -I/slang/external/miniz -I/slang/build/external/miniz -I/slang/external/lz4/build/cmake/../../lib -I/slang/external/unordered_dense/include -O3 -DNDEBUG -flto=thin -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wno-switch -Wno-parentheses -Wno-unused-local-typedefs -Wno-assume -Wno-reorder -Wno-invalid-offsetof -Wno-newline-eof -Wno-return-std-move -Wnarrowing -Wextra -std=gnu++20 -MD -MT source/core/CMakeFiles/core.dir/slang-archive-file-system.cpp.o -MF …
```
=> Fix nullptr_t compiling failure

docs/user-guide/03-convenience-features.md
1. github pages requires new-line before table to render table correctly as per [spec](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-tables). This is required to unbreak tables on the slang-website
2. Grammer problem.
=> fix doc's website table & grammer

source/slang/hlsl.meta.slang, source/slang/slang-ast-type.cpp, source/slang/slang-check-constraint.cpp, source/slang/slang-emit-spirv-ops.h, source/slang/slang-emit-spirv.cpp, source/slang/slang-ir-inst-defs.h, source/slang/slang-ir-insts.h, source/slang/slang-ir-legalize-types.cpp, source/slang/slang-ir-spirv-legalize.cpp, source/slang/slang-ir.cpp, source/slang/slang-lower-to-ir.cpp, tests/cooperative-matrix/map-element-single.slang, tests/cooperative-matrix/map-element-tuple.slang, tests/language-feature/tuple/tuple-expand-multiple.slang, tests/language-feature/tuple/tuple-expand.slang
With this PR, MapElement works for the following signatures:
- CoopMat<...>::MapElement(functype(...));
- CoopMat<...>::MapElement(capturing-lambda);
- CoopMat<...>::MapElement(not-capturing-lambda);
- Tuple<CoopMat<...>,...>::MapElement(functype(...));
- Tuple<CoopMat<...>,...>::MapElement(capturing-lambda);
- Tuple<CoopMat<...>,...>::MapElement(not-capturing-lambda);
Note: New tests are effectively disabled because currently the CI runners don't have a graphics driver that supports CoopMat2 features.
=> Implement MapElement for CoopMat

tools/slang-test/slang-test-main.cpp, tools/test-server/test-server-main.cpp
Previously when running slang-test with "-use-test-server" to run slang-unit-test-tool and gfx-unit-test-tool tests, these would fail with a message like, "error: Unable to launch tool". These issues appear to have been resolved, however debug runs of gfx-unit-test-tool using "-use-test-server" were still showing errors of the following nature:
````
error: rpc failed
error: result code = -858993460
standard error = {
}
standard output = {
}
ignored test: 'gfx-unit-test-tool/uint16BufferTestVulkan.internal'
````
These errors all appeared to be the result of Vulkan VUID print outs and were occuring for nearly every Vulkan test.
Existing comments in slang-test-main.cpp indicated that VUID print outs get misinterpreted as the result from a test due to limitations in the Slang RPC …
=> Fix test-server debug issues with gfx-unit-test-tool (#7119)

.github/workflows/ci.yml, source/compiler-core/slang-test-server-protocol.h, tools/render-test/render-test-main.cpp, tools/slang-test/options.cpp, tools/slang-test/options.h, tools/slang-test/slang-test-main.cpp, tools/slang-test/test-context.h, tools/test-server/test-server-main.cpp
A variable `disableDebugLayer` is renamed to `enableDebugLayers`, and a corresponding command-line argument is added, `-enable-debug-layers`.
The previous option `-disable-debug-layer` is still available, but it prints a deprecation warning message.
The reason why it is added is to make the option available to both Debug and Release. On Debug build, it will be enabled by default, and it will be disabled on Release build. We should be able to not only disable it, but also enable it on Release build.
Ideally this option should be enabled all the time, but currently there are too many VUID error messages printed and we are enabling only for Debug build for now.
Note that the CI/CD will run with the option disabled until we resolve all of VUID errors.
=> Add a new slang-test option `-enable-debug-layers`

source/compiler-core/slang-test-server-protocol.cpp
Fix a mistake caused by a recent PR
- https://github.com/shader-slang/slang/pull/7300
The new argument added was not properly sent to the client process, because it was not reflected on its RTTI data.
This caused all of gfx-unit-test to fail when ran with debug build.
=> Fix rpc errors on slang-unit-tests

source/slang/hlsl.meta.slang, source/slang/slang-check-decl.cpp, source/slang/slang-check-inheritance.cpp, source/slang/slang-check-overload.cpp, tests/language-feature/extensions/extension-override-2.slang
Closes #7364.
Given:
```slang
interface IBar
{}
interface IFoo : IBar
{
void execute();
}
extension<T:IBar> T : IFoo
{
void execute()
{
printf("Extension::execute();\n");
}
}
void test<T:IFoo>(T t)
{
t.execute();
}
```
There is an issue in `CompareLookupResultItems` during checking `t.execute` in `test`, which would prefer `extension::execute` over a lookup of `IFoo.execute` using the witness parameter. This is because `CompareLookupResultItems` always prefers a concrete definition over an interface definition. This shouldn't be the case when the concrete definition is in a free-form generic extension.
=> Fix an issue in extension override.

source/slang/slang-check-expr.cpp, tests/bugs/gh-6756.slang
Close #6756.
When we synthesize the struct decl for Differential type, we should add the ownedScope for this decl, because the scope is used in lots of locations in the following synthesized processes, e.g. constructor synthesize. And that could cause surprising behavior, e.g. the 'this' expression could access the members of parent struct decl.
Fix the issue by adding the scope. The containerDecl will be the Differential struct decl itself, parent scope will be the parent struct.
=> Fix issue of missing scope for 'Differential' type

source/slang/slang-check-expr.cpp, tests/autodiff/differential-type-syntheize-diagnostics.slang
Close #6176.
If the struct has a `no_diff` member, it should not be its Differential type. We miss this check.
=> Fix issue that struct with  member is not its Differential type

source/compiler-core/slang-nvrtc-compiler.cpp
CUDAU 12.8+ prints a warning that shader model before 7.5 is deprecated.
This PR bumps the minimum shader model version from 5.0 to 7.5 when nvrtc version is 12.8 or above.
Closes https://github.com/shader-slang/slang/issues/7026
- https://github.com/shader-slang/slang/issues/7026
=> Bump the min shader model version for CUDA 12.8+

include/slang.h
The current declaration of `kDefaultTargetFlags` causes problems when used with C++ modules:
```
usr/local/include/slang.h:3824:8: error: ‘struct slang::TargetDesc’ exposes TU-local entity ‘kDefaultTargetFlags’
3824 | struct TargetDesc
|        ^~~~~~~~~~
/usr/local/include/slang.h:725:39: note: ‘kDefaultTargetFlags’ declared with internal linkage
725 |     constexpr static SlangTargetFlags kDefaultTargetFlags =
|                                       ^~~~~~~~~~~~~~~~~~~
```
I propose this fix.
=> "kDefaultTargetFlags" exposing TU-local entity with modules 

source/slang/slang-language-server.cpp, source/slang/slang-language-server.h, tools/slang-test/test-context.cpp
The "textDocument/publishDiagnostics" Notification in the official Language Server Protocol, or LSP for short, is a notification that the server sends to the client such as VSCode or Visual Studio without the client having to ask for it. Its purpose is to provide a list of errors, warnings, or other informational "squiggles" for a specific file.
Because the notification is an asynchronous push notification, it is receieved as an unexpected RPC message during the slang-test CI tests. When a notificatoin is unexpectedly sent to slang-test, the communication goes out-of-sync and the rest of language-server based tests intermittently fails.
In order to address the problem, this PR adds a new command-line argument to change the behavior of the notification and it will be sent in a more …
=> Disable periadic diagnostic update on language-server on CI

docs/user-guide/06-interfaces-generics.md, source/slang/slang-ast-modifier.h, source/slang/slang-check-decl.cpp, source/slang/slang-check-impl.h, source/slang/slang-check-modifier.cpp, source/slang/slang-diagnostic-defs.h, source/slang/slang-parser.cpp, tests/diagnostics/missing-override.slang, tests/language-feature/interfaces/default-method-generic-interface.slang, tests/language-feature/interfaces/override-default-method.slang
This change requires explicit `override` modifier for functions that overrides a default interface implementation.
Part of the default interface method proposal.
=> Require `override` keyword for overriding default interface methods.

.github/workflows/ci.yml, CMakeLists.txt
https://github.com/shader-slang/slang/commit/0cb89b3062f89ec5f5c5812f0164f8c90f3f9aba uses `BUILD_LOCAL_INTERFACE`, which reques cmake 3.26+
Fixes: #7453
=> Update CMake version to 3.26

source/slang/hlsl.meta.slang
Fixes #7504. The equations were found using a small program that computes the Laplace expansions and prints out which entries were accessed. I simplified the N==4 case by hand a bit.
=> Add default implementation for determinant so that it works with `-target cpu`

.github/workflows/ci.yml, docs/building.md, extras/verify-documented-compiler-version.sh
Closes https://github.com/shader-slang/slang/issues/7376
=> Document supported compiler versions in building.md

source/slang/slang-check-overload.cpp, tests/library/ambiguous-extern-export-entry.slang, tests/library/ambiguous-extern-export-lib1.slang, tests/library/ambiguous-extern-export-lib2.slang
Close #7509.
When there are both `export` and `extern` decls in lookup result, we should remove all `extern` decls.
=> Fix ambiguous reference for 'extern' and 'export'

source/slang/slang-emit-spirv.cpp, tests/spirv/array-stride-decoration-1.slang, tests/spirv/array-stride-decoration-2.slang, tests/spirv/array-stride-decoration-3.slang, tests/spirv/array-stride-decoration-4.slang
Close #7508.
SPIRV doesn't allow decoration on type with Private or Function storage class.
In our lowering logic, since if the array type is used by buffer type it will always have stride operand after lowering. So if the array is not used by buffer type, it must be used only by thread_local or group_shared variable, and it will not have stride operand. For this case, we don't need to emit stride decoration for SPIRV.
=> Fix the invalid SPIRV decoration issue

source/slang/slang-ir.cpp
Fixes #7542 and potentially many more issues, at least with release builds on GCC 15. The issue description has the analysis of what I think is going on. In any case, many passes read insts after `removeAndDeallocate()` has been called on them; while this in itself is a bit questionable, it turns into UB due to the manual destructor call done in `removeAndDeallocate()`.
Since the destructor marks the end of the object's lifetime, you're not supposed to read from it afterwards anyway, so I guess GCC 15 just optimizes all prior assignments away.
=> Fix undefined behaviour after IRInst::removeAndDeallocate

source/slang/core.meta.slang, tests/bugs/gh-7156-ifloat-scale.slang
Generic implementation of IFloat.scale for float vectors and matrices. Prevents an internal compiler error when writing generic functions for use with both scalar and vector/matrix types. Includes a test.
Fixes #7156
=> Implement IFloat.scale for vectors, matrices

source/slang/core.meta.slang, source/slang/slang-ast-modifier.h, source/slang/slang-emit-hlsl.cpp, source/slang/slang-ir-inst-defs.h, source/slang/slang-ir-insts.h, source/slang/slang-lower-to-ir.cpp
Removes the PayloadAttribute class and related infrastructure that was made redundant by PR #6595, which added ray payload access qualifiers (PAQs) per the DXR spec. The new [raypayload] attribute with access qualifiers provides the same functionality.
Changes:
- Remove PayloadAttribute class from slang-ast-modifier.h
- Remove [payload] attribute syntax from core.meta.slang
- Remove PayloadDecoration IR instruction and related processing
- Remove HLSL emission of [payload] attribute
- Remove IR lowering support for old PayloadAttribute
The new [raypayload] attribute with PAQ support remains unchanged.
=> Remove redundant [payload] attribute (Fix #7528)

cmake/CompilerFlags.cmake
This PR is to allow a compiler warning even when all warnings are requested to be treated as errors.
The following pattern is very common in Slang code base:
```
if (auto var = as<...>(...))
```
And when `var` is not used, the compiler prints a warning.
Alternatively we can remove `auto var =` part but there are too many.
=> Allow a compiler warning on MacOS

.gitmodules
Close #7491.
As the PR KhronosGroup/SPIRV-Tools#6198 is already merged, we can switch spirv-tools repo to upstream repo now.
=> fix spirv-opt bug

source/compiler-core/slang-json-value.cpp, source/slang/slang-ast-decl-ref.cpp, source/slang/slang-ast-print.cpp, source/slang/slang-check-decl.cpp, source/slang/slang-check-expr.cpp, source/slang/slang-content-assist-info.h, source/slang/slang-language-server-auto-format.h, source/slang/slang-language-server-completion.cpp, source/slang/slang-language-server.cpp, source/slang/slang-language-server.h, tests/language-server/existential-decl-path.slang, tests/language-server/override-completion-2.slang, tests/language-server/smoke.slang.expected.txt
1. Add a configuration to turn on/off format-on-type.
2. Fix `LookupDeclRef::toText` to correctly print associated type lookups.
3. Fix override completion to include `static` modifier when necessary.
4. Fix highlighting/hover for associated type declref exprs.
=> Misc language server improvements.

source/compiler-core/slang-json-native.cpp, source/slang/slang-language-server.cpp, source/slang/slang.cpp
Previously, the language server only triggered module loading and compilation through semantic token requests. When semantic tokens were disabled, didOpenTextDocument and didChangeTextDocument would only update the workspace without compiling modules, meaning no diagnostics were generated.
This change:
- Adds module loading to didOpenTextDocument for .slang/.hlsl files
- Adds module loading to didChangeTextDocument for .slang/.hlsl files
- Triggers diagnostic updates via resetDiagnosticUpdateTime for Slang files
- Ensures diagnostics appear immediately when opening/editing files
- Maintains backward compatibility with existing LSP features
Additionally fixes JSON serialization to properly handle NullResponse types by serializing them as JSON null instead of empty objects, improving LSP …
=> Fix diagnostics not appearing when semantic tokens are disabled (#7477)

.github/workflows/ci.yml
Our merge queue takes a long time to drain. This PR disables full GPU and SlangPy/SlangRHI tests on merge queues.
This is fine because full tests are still run on PRs and each master branch commits, so we are still capturing all regressions.
We run a smaller set of checks in the merge queue just to make sure there aren't merge errors.
=> Don't run full gpu tests on merge queue.

docs/command-line-slangc-reference.md, docs/user-guide/a3-02-reference-capability-atoms.md, source/slang/slang-capabilities.capdef, source/slang/slang-options.cpp, source/slang/slang-profile-defs.h
in vulkan terminology, an amplification shader is referred to as task shader. so, same as with tessellation control and evaluation shaders, adding this one as an alias.
also on the way of adding task shader fixed some inconsistencies like not having a profile for glsl mesh shader.
=> add task shader alias

.github/copilot-instructions.md, .github/workflows/ci.yml
It is better to keep full tests on merge_queue and disable rerunning the tests on `push` to master.
Closes #7595.
=> Run full check on merge_queue, but not on push.

.github/actions/common-setup/action.yml
Fixes https://github.com/shader-slang/slang/issues/7480
=> Remove swiftshader from github action

source/slang/slang-ir-spirv-legalize.cpp, tests/bugs/gh-7431.slang
Per Vulkan VUID-VkShaderModuleCreateInfo-pCode-08737, if a SPIRV struct is marked as a block, it cannot also be a field in another structure. This change iterates over a program and identifies structs with this condition, and moves the block usage into a wrapper struct.
Fixes #7431
=> Fix for mixed block/embedded usage of structs in SPIRV

source/slang/slang-language-server-ast-lookup.cpp, source/slang/slang-language-server-ast-lookup.h, source/slang/slang-language-server-completion.cpp, source/slang/slang-language-server-completion.h, tests/language-server/completion-sorting-1.slang, tests/language-server/completion-sorting-2.slang, tests/language-server/completion-sorting-3.slang, tests/language-server/completion-sorting-4.slang, tests/language-server/completion-sorting-5.slang, tools/slang-test/slang-test-main.cpp
This change improves the language server auto completion experience by sorting the candidates based on their relevance to the context.
Specifically, if the language server can determine the expected type at the location of the completion request, it will sort the candidates such that those that has the matching type will be listed first.
For example,
```
enum Color { Red, Green, Blue }
void myFunc(Color c);
void test()
{
myFunc( /*request here*/
}
```
should list `Color` first.
=> Language server: sort completion candidate by relevance.

examples/reflection-api/main.cpp
The bug here is subtle enough that it was missed during development of the example, and it it unlikely to be hit by typical applications. All that said, it is good to ensure that this example does things correctly, since we are pointing developers to it as an example of how to correctly extract information using the reflection API.
In order to get the bug to surface, one can target Vulkan/SPIR-V using input code like:
```
struct Small
{
float4 v;
Texture2D t;
}
struct Big
{
float4 u;
ConstantBuffer<Small> smallCB;
ParameterBlock<Small> smallPB;
}
ConstantBuffer<Big> bigCB;
```
Without this change, the example would display an incorrect cumulative offset for `bigCB.smallPB.t`. The incorrectly-computed offset showed that the `binding`s consumed by `bigCB.smallCB` (for both its constant …
=> Fix a bug in examples/reflection-api

docs/command-line-slangc-reference.md, source/core/slang-command-options-writer.cpp, source/slang/slang-options.cpp
For #7088 
The output of `slangc --help` is very long, and although it is split into subsections based on categories, it is not immediately obvious from the wall of text that the `-h` option can take a category as a value to only display that category. You have to look in the "General" category near the top of the help output to find that `-h` can take an optional value `<help-category>`. Furthermore, these categories are not listed in the output.
This change adds a new value category for `<help-category>` values as the last help category, listing all of the preceding categories (and itself), with this message at the end of the text output advising users that they can narrow down the output of `slangc -h`.
```
Getting Help for Specific Categories
=====================================
To …
```
=> Add <help-category> list and hint on usage in slangc -h

source/slang/hlsl.meta.slang
Fixes #7141 (although a new build of Slang will be needed for this fix to propagate to the docs)
Corrects listed meaning of `rgb10_a2` from `4 channel 10/10/10/2-bit signed integer texture` to `4 channel 10/10/10/2-bit normalized unsigned integer texture`
=> Fix typo for rgb10_a2 in image format table

source/slang/slang-syntax.cpp, tests/bindings/vk-image-format.slang
Fixes #7556 
VK image formats that end with `_snorm` are not properly recognized by Slang because `findVkImageFormatByName` adds an underscore if it detects that the format name ends with `snorm`. This allows developers to use the format without underscores, e.g. `rgba16snorm` is recognized as `rgba16_snorm`, but adds an extra underscore if there is one already, e.g.  `rgba16_snorm` is rejected as `rgba16__snorm`.
This change adds a check for the underscore in the name, only adding one if `snorm` is not preceded by `_`, so both `rgba16snorm` and `rgba16_snorm` are mapped to `rgba16_snorm`, etc.
=> Avoid inserting underscore to _snorm format name if it has one already

source/slang/diff.meta.slang, source/slang/slang-check-expr.cpp, source/slang/slang-check-impl.h, source/slang/slang-diagnostic-defs.h, source/slang/slang-ir-check-differentiability.cpp, tests/autodiff/dynamic-dispatch-bwd-diff.slang, tests/autodiff/dynamic-dispatch-generic-2.slang, tests/autodiff/dynamic-object-bwd-diff.slang, tests/autodiff/material2/DiffuseMaterial.slang, tests/autodiff/material2/GlossyMaterial.slang, tests/autodiff/material2/MxLayeredMaterial.slang, tests/autodiff/member-func-extension-custom-derivative.slang, tests/autodiff/nondiff-call.slang, tests/diagnostics/const-to-nodiff-function-diagnostic-improvement.slang, tests/diagnostics/const-to-nodiff-function-diagnostic-improvement1.slang, tests/diagnostics/force-no-diff-this.slang
close #6286.
This PR is to improve the diagnostics for no_diff usage.
1. In a differentiable function, any calls to a non-diff function with constant arguments should not require `no_diff` attribute.
This PR adds this extra check at `checkAutoDiffUsages` where it checks the differentiability on IR.
2. In a differentiable method, we will force to use `[NoDiffThis]` attribute if there is access to non-differentiable `This` type. Once this access is detected we will report a warning to bring users attention that this access won't generate any derivative, they have to use `[NoDiffThis]` to suppress that warning.
This PR adds this check at type checking stage, because it's the easiest way to find out all the `This` accesses.
=> no_diff diagnostics improvement

source/slang/hlsl.meta.slang
This appears to just have been a simple copy/paste error in somewhat rare functionality.
=> Fix CommittedRayInstanceCustomIndex generating wrong SPIR-V opcode

source/core/slang-command-options-writer.cpp
Fixes #7088
`slangc --help` prints long lists of possible values for each of the value categories like `<capability>`. This information takes up more than half of the text output, and is largely redundant as we already list the values where they are mentioned, e.g.
```
Target
======
Target code generation options
-capability <capability>[+<capability>...]: Add optional capabilities to a code generation target. See Capabilities 
below.
<capability> can be: spirv_1_{ 0, 1, 2, 3, 4, 5 }, Invalid, textualTarget, hlsl, glsl, c, cpp, cuda, metal, spirv,
...
```
This change omits the separate value categories from the full `slangc  --help` output, e.g.
```
<capability>
============
A capability describes an optional feature that a target may or may not support. When a -capability is specified, …
```
=> Only append slangc --help value categories if explicitly specified

source/slang/slang-emit-spirv.cpp, source/slang/slang-ir-inline.cpp, source/slang/slang-ir-specialize-address-space.cpp, source/slang/slang-ir-specialize-address-space.h, tests/spirv/pointer-access.slang
Fixes #7654.
The problem is that when we inline a function called with a pointer-typed argument, we did not immediately propagate the address spaces from the argument into the cloned function body. So the `FieldAddress` instructions in the cloned callee still have address space `General` even when the argument is in address space `UserPointer`. When this IR reaches spirv-emit, we will be emitting invalid spirv.
This PR adds a fixup pass to propagate the address space after inlining, which fixes the addr space mismatch problem.
=> Fixup address spaces after inlining.

source/slang/glsl.meta.slang, source/slang/hlsl.meta.slang, tests/pipeline/rasterization/mesh/task-simple.slang
Fixes #7733
Copy gl_NumWorkGroups into hlsl.meta.slang as WorkgroupCount function so that it can be used for GLSL and SPIR-V targets without GLSL syntax.
Also change WorkgroupSize function to allow use with mesh shading capability. Update pipeline/rasterization/mesh/task-simple.slang to test it in task and mesh stages.
=> Add WorkgroupCount function

source/slang/core.meta.slang, source/slang/slang-ast-support-types.cpp, source/slang/slang-ast-support-types.h, source/slang/slang-check-expr.cpp, source/slang/slang-check-impl.h, source/slang/slang-check-overload.cpp, source/slang/slang-diagnostic-defs.h, source/slang/slang-ir-fuse-satcoop.cpp, tests/diagnostics/implicit-cast-lvalue.slang.expected, tests/diagnostics/invalid-constant-pointer-taking.slang, tests/diagnostics/methods/mutating-method-on-rvalue.slang.expected, tests/diagnostics/setter-method.slang.expected
The original diagnostics for the pointer taking operation just shows "expecting l-value".
This PR adds additional message to better convey the error message.
Fixes: https://github.com/shader-slang/slang/issues/6743
=> Emit additional diagnostic for invalid pointer taking operations

docs/command-line-slangc-reference.md, source/slang/slang-options.cpp
Not sure when the behavior got changed since this flag was introduced in #2856, but currently the default is no prefix.
=> Correct help text for `-dump-intermediate-prefix`

source/slang/slang-emit.cpp
The original implementation strip away all the spirv inst with `SpvOpExtInst` whose 3rd operand is in the set of `debugExtInstNumbers`.
However, `SpvOpExtInst` can refer to other type of inst, not just `DebugInfo` so the 3rd operand does not necessarily make sense to the `debugExtInstNumbers`.
For example
```
%2 = OpExtInstImport "NonSemantic.Shader.DebugInfo.100"
%141 = OpExtInstImport "GLSL.std.450"
...
%181 = OpExtInst %float %141 Pow %180 %float_8
```
The inst. above would be stripped away because the third operand `Pow` happens to be in the range of ``debugExtInstNumbers`.`, but that inst. actually belongs to "GLSL.std.450".
This PR checks the 2nd operand and only strip it away if it's SemanticDebugInfoExtId
=> Strip debug info only for the SpvOpExtInst of debug import type

source/slang/slang-ir-extract-value-from-type.cpp
Closes #7790. Not including a test, since reproducing this concisely seems spectacularly difficult; removing superficially unrelated code seems to cause the compiler to take a different, non-broken path.
#7717 introduced this problem, but only indirectly by starting to use `emitBitCast` with different types than before. At least with the C++ emitter, this caused the generated code to look like this:
```cpp
#line 56
static int32_t * unpackAnyValue8_0(AnyValue8 _S7)
{
#line 56
return (slang_bit_cast<int32_t *>(uint64_t((_S7.field0_0) | ((_S7.field1_0) << 32U))));
}
```
where GCC aptly notes the following:
```
slang-cpu-utils/tests/sort_test.slang: In function 'int32_t* unpackAnyValue8_0(AnyValue8)':
slang-cpu-utils/tests/sort_test.slang:56:81: warning: left shift count >= width of type …
```
=> Fix BitCast emitting bit shifts with too small integer types

source/slang/slang-ast-decl.h, source/slang/slang-ir-link.cpp, source/slang/slang-ir-link.h, source/slang/slang-lower-to-ir.cpp
This changes how force inlined functions are handled during IR lowering by using a prelinking step to copy the IR from the defining module to the user module, instead of re-run the lowering logic on the AST of the original function.
This allowed us to skip serializing function bodies unconditionally.
This brings our serialized core module from 5.9MB to 3.9MB.
=> Prelink ForceInlined functions during lowering.

source/slang/slang-check-impl.h, source/slang/slang-check-overload.cpp, source/slang/slang-check-type.cpp, source/slang/slang-parameter-binding.cpp, tests/language-feature/types/conditional-varying.slang, tests/spirv/spec-constant-generic.slang, tools/slang-unit-test/unit-test-conditional-vertex-input.cpp
Fixes https://github.com/shader-slang/slang/issues/7834.
Declaring a field of `Conditional<T, false>` type, and with a semantic such as `COLOR0` should not crash the compiler.
Add a unit test to exercise using Conditional<T> to declare vertex inputs, and specialize it with link time constants.
Make sure that `GenericDecl<SpecConstant>` is an error.
=> Fix Conditioanl<T, false> fields with a semantic.

source/slang/slang-check-shader.cpp, tests/language-feature/capability/capability-as-string.slang
Fixes: #7869 
Changes:
* Instead of assuming capabilities are an `int` option, handle the string case
* if a string-capability is passed in, we have a very intentionally added a capability, consider this as a sign that "a specific capability was requested"
Why is this a breaking change?
* We currently do not warn/error always with capabilities (in user-code using the slang-api) due to this bug. Now we will warn, this "breaks" code
=> Fix passing a capability as a string into Slang crashes/is-invalid

source/slang/slang-ir-clone.cpp, source/slang/slang-ir-util.cpp, tests/language-feature/generics/generic-interface-linkage-2.slang
After PR #6688 was merged, users encountered redefinition errors when specializing generic functions with let parameters that have different constant values. For example:
```
float4 getColor<let doStuff : bool>() { ... }
// Both calls generated the same mangled name, causing redefinition error
getColor<true>();
getColor<false>();
```
```
Error: redefinition of '_ShB23F6712314C5976G00'
```
The issue was in the getTypeNameHint() function in source/slang/slang-ir-util.cpp. This function is used by PR #6688's specialized linkage decoration logic to generate mangled names for generic specializations. However, it only handled kIROp_IntLit literals but not other types like kIROp_BoolLit, causing both true and false to be omitted from the mangled name.
This PR added support for all major literal …
=> Fix for Generic Function Redefinition Error

source/slang/slang-emit-spirv.cpp
Fixes #7903
SPV_NV_viewport_array2 says ViewportMaskNV corresponds to gl_ViewportMask
=> Fix nv_viewport_mask semantic to emit SpvBuiltInViewportMaskNV

source/slang/slang-ir-eliminate-multilevel-break.cpp, tests/bugs/gh-7748-switch-continue-bug.slang
The multi-level break elimination pass failed with dictionary key collisions when encountering continue statements inside nested control structures (issue #7748). The pass only tracked break blocks as region exits, missing continue blocks as potential multi-level branch targets.
Improved multi-level branch tracking to include all potential exits out of regions, including continue blocks, and used continue elimination to remove such exits before proceeding with the usual multi-level break elimination.
- Extended BreakableRegionInfo to track both break and continue blocks as exit points
- Added detection logic for when continue elimination is needed (multiple exit blocks with multi-level branches, or unique exit block is not the break block)
- Automatically invoke …
=> Improve multi-level branch elimination to handle continue blocks

.github/workflows/benchmark.yml, .github/workflows/check-cmdline-ref.yml, .github/workflows/check-formatting.yml, .github/workflows/check-toc.yml, .github/workflows/falcor-compiler-perf-test.yml, .github/workflows/falcor-test.yml
These workflows are already run on each PR, so disable them on main branch commits to reduce CI workload.
=> Disable more CI workflows on master push.

source/slang/slang-language-server.cpp
Fixes high latency when opening a big folder.
For some reason, vscode is sending openDoc to langauge server on many files that are not opened by the user. The language server should defer checking these files upon opening them.
=> [Language Server]: Don't eagerly check file upon open doc.

source/slang/slang-check-decl.cpp, source/slang/slang-diagnostic-defs.h, tests/bugs/static-const-without-default-value.slang
Fixes #7989
Changes:
* Add validation in SemanticsDeclHeaderVisitor::checkVarDeclCommon to detect static const variables without initializers and emit proper error diagnostics instead of allowing an uninitialized `static const`
* Do not error if `extern static const` or if `interface` member
=> disallow `static const` variables without default-value

.github/workflows/ci.yml
Don't run the following tests on Debug config for commits in the merge_group:
- Slang-RHI tests on Debug Config.
- SlangPy tests on Debug config.
Don't run the following tests on merge_group:
- Examples
- GLSL backend
=> Reduce merge_group CI workload.

source/core/slang-io.cpp, tools/slang-unit-test/unit-test-lock-file.cpp
This commit fixes two problems.
1. uninitialized file handle for lock-file test
2. uninitialized static variable for lock-file test
The first bug is more of speculartive rather than actual bug.
The second bug was causing heap corruption when it was retried, because the counter was not reset to zero on "retry" and it wrote data to an invalida range in an array.
=> Fix bug in lock-file slang-unit-test

tools/slang-unit-test/unit-test-record-replay.cpp
Disabling ray-tracing-pipeline test as a part of slang-test.
Because it appears to cause a crash on Windows Graphics driver.
We should re-enable once the issue is resolved.
Related to
- https://github.com/shader-slang/slang/issues/8022
- https://github.com/shader-slang/slang/issues/7965
=> disable ray-tracing-pipeline test

examples/example-base/example-base.cpp
This commit enables the debug-layers on examples; but only when it is not in "test mode".
When slang-test runs the replay tests, the examples run with "-test-mode" option.
Slang-test expects certain text message output from the example.
If the debug-layers is enabled during the slang-test replay test, the output messages from the debug layers could mix up with the expected output. If it happens, the test will intermittently fail.
For that reason, the debug-layers is not enabled in test mode.
The debug layers can still print messages when the examples run individually; not through slang-test.
Currently there is no way to disable the debug-layers for the examples.
If needed later, we can add a new command-line argument to disable it.
Related to
- …
=> Enable debug-layers for examples when not using test-mode

.github/workflows/release-linux-glibc-2-27.yml, .github/workflows/release.yml
Previously there were tag name `vulkan` and it was causing build errors. The cmake build script currently expect the name to be in a pattern of `v2025.1` which starts with `v` and followed by numbers.
=> Restrict the release tag name to a pattern the build script expects

include/slang-deprecated.h, include/slang.h, source/slang/slang-ast-expr.h, source/slang/slang-ast-iterator.h, source/slang/slang-check-expr.cpp, source/slang/slang-check-overload.cpp, source/slang/slang-language-server-ast-lookup.cpp, source/slang/slang-language-server.cpp, source/slang/slang-linkable.cpp, source/slang/slang-linkable.h, source/slang/slang-reflection-api.cpp, tools/CMakeLists.txt, tools/slang-unit-test/unit-test-function-lookup-resolution.cpp
This change adds a new deprecated API to unblock SlangPy. This API allows the slang compiler to filter overload candidates using its builtin rules.
=> Add reflection api for overload candidate filtering.

source/slang-core-module/slang-embedded-core-module-source.cpp, source/slang/slang-ast-base.h, source/slang/slang-ast-builder.cpp, source/slang/slang-ast-builder.h, source/slang/slang-ast-decl.h, source/slang/slang-check-decl.cpp, source/slang/slang-end-to-end-request.cpp, source/slang/slang-global-session.cpp, source/slang/slang-global-session.h, source/slang/slang-options.cpp
Background
----------
The Slang compiler currently relies on the idea that AST nodes derived from `Val` are always deduplicated based on their opcode and operands. Deduplication requires caching, and we thus have to determine the right scope at which to allocate and cache different `Val`s.
We need to ensure that `Val`s that refer to declarations/nodes in a specific compilation session/linkage are not cached in a scope that will outlive that session/linkage (or else the cache will contain garbage pointers). Conversely, we also need to ensure that any `Val`s that are referred to by something like a builtin module's AST will remain alive at least as long as that module/AST, and that every compilation session/linkage that refers to that module will find that `Val` cached if they try to create …
=> A new approach to AST node deduplication

tools/slang-test/README.md
This PR adds a bit of explanation in `tools/slang-test/README.md` about how to ignore different kinds of tests.
=> Document how to ignore tests

tests/cpu-program/gfx-smoke.slang, tools/gfx/gfx.slang
The test was deleted in #7577, but we actually still need slang-gfx, so this PR undeletes it. Also, this PR fixes `tools/gfx/gfx.slang` which was broken by #7711.
=> Add back GFX smoke test

.gitignore
This file keeps getting created and deleted: it was originally created in #6310, then I deleted it in #6620, then it was accidentally added in #7579, then deleted again in #7577. We should just have it in `.gitignore`.
=> Add `lock` file to `.gitignore`

source/slang/slang-serialize-ast.cpp
Overview
--------
This change basically just flips a `#define` switch to enable the changes that were already checked in with PR #7482. That earlier change added the infrastructure required to do on-demand deserialization, but it couldn't be enabled at the time due to problematic interactions with the approach to AST node deduplication that was in place. PR #8072 introduced a new approach to AST node deduplication that eliminates the problematic interaction, and thus unblocks this feature.
Impact
------
Let's look at some anecdotal performance numbers, collected on my dev box using a `hello-world.exe` from a Release x64 Windows build. The key performance stats from a build before this change are:
```
[*]              loadBuiltinModule      1         254.29ms
[*] …
```
=> Enable on-demand deserialization of AST decls

source/slang/slang-emit-spirv.cpp, tests/spirv/atomic-float16-vector.slang
Update the SPIRV emit of atomic fp16 vector extension from its previous incorrect name to SPV_NV_shader_atomic_fp16_vector.
=> Fix atomic fp16 vector SPIRV emit

docs/scripts/release-note.sh
This commit adds a new command-line argument for `docs/script/release-note.sh`, which is `--previous-release-hash`.
It will allow us to generate the release note at more finer granularity.
The current help message is following,
```
Usage: ./docs/scripts/release-note.sh [--since DATE | --previous-release-hash HASH]
--since DATE                    Generate notes since the given date (e.g., 2025-08-06)
--previous-release-hash HASH    Generate notes since the given commit hash
Legacy usage (deprecated): ./docs/scripts/release-note.sh DATE
```
Fixes
- https://github.com/shader-slang/slang/issues/5188
- https://github.com/shader-slang/slang/issues/6887
=> Add a new option to use hash for release-note script

cmake/LLVM.cmake, docs/building.md, external/build-llvm.ps1, external/build-llvm.sh, source/slang-llvm/slang-llvm.cpp
Full set of mutually exclusive choices for upgrading LLVM:
- #8031 (you are here)
- #8035
- #8036
- #8034
- #8038
- #8039
- #8033
Alternative to #8028. Required some minor changes due to these upstream commits:
- llvm/llvm-project@e463b69736da8b0a950ecd937cf990401bdfcdeb
- llvm/llvm-project@89b57061f7b769e9ea9bf6ed686e284f3e55affe
=> Update LLVM from 13.0.1 to 14.0.6

prelude/slang-cuda-prelude.h, source/core/slang-platform.cpp, source/slang/hlsl.meta.slang, tests/cuda/optix-cluster.slang, tests/cuda/optix-coopvec.slang, tests/cuda/optix-hit-attributes.slang, tests/cuda/optix-ignore-hit.slang, tests/cuda/optix-ser.slang
Due to an older version of spec referred there was an inconsitency v1.29 2/20/2025 - [HitObject LoadLocalRootArgumentsConstant]
Latest spec
https://microsoft.github.io/DirectX-Specs/d3d/Raytracing.html#hitobject-loadlocalroottableconstant
Refer:
OptiX backend support for Shader Execution Reordering (SER) features as outlined in issue #6647. -
=> Fix intrinsic LoadLocalRootTableConstant for optix

tests/bugs/op-select-return-composite.slang
What is fixed:
Since we make `vk` tests compile as GLSL, we must use a capability that specifies a GLSL equivalent.
If we do not do this, we will get an error since we are not specifying GLSL capabilities (but are specifying a profile).
Since a profile is specified, we emit capability errors.
=> Fix `tests\bugs\op-select-return-composite.slang` Test Failing

flake.nix
This PR puts the [Khronos official Vulkan Loader](https://github.com/NixOS/nixpkgs/blob/6027c30c8e9810896b92429f0092f624f7b1aace/pkgs/by-name/vu/vulkan-loader/package.nix#L22-L27) in `LD_LIBRARY_PATH` for the `flake.nix` dev shell, allowing Vulkan tests to run.
For example, before this PR:
```
$ build/Debug/bin/slang-test tests/compute/array-param.slang
Supported backends: glslang spirv-dis clang gcc genericcpp llvm spirv-opt
found test: 'tests/compute/array-param.slang'
Check vk,vulkan: Not Supported
Check cuda: Not Supported
ignored test: 'tests/compute/array-param.slang (cuda)' 
passed test: 'tests/compute/array-param.slang.1 (cpu)' 
ignored test: 'tests/compute/array-param.slang.2 (dx11)' 
ignored test: 'tests/compute/array-param.slang.3 (dx12)' 
ignored test: …
```
=> Allow `flake.nix` users to run Vulkan tests

source/slang/slang-ast-val.cpp
#1729 renamed `Val::_toStringOverride` to `Val::_toTextOverride` but did not update the error message for when it is not overridden. This PR fixes that.
=> Fix error for not defining `Val::_toTextOverride`

source/slang/slang-emit-cuda.cpp, source/slang/slang-intrinsic-expand.cpp, tests/cuda/raygeneration.slang
Fixes: #8167
Current emitting logic does not work, this has been corrected.
The provided test ensures our CUDA code is valid by compiling PTX from it.
`m_writer->emit("OptixTraversableHandle");` should be `out <<` since `out` adds to type-name-cache; otherwise using a type twice will produce bad type-names (since we filled type-name cache with "" instead of "typeName")
=> [CUDA] Fix incorrect `kIROp_RaytracingAccelerationStructureType` emitting logic

docs/user-guide/a3-02-reference-capability-atoms.md
This file is automatically overwritten by the build:
https://github.com/shader-slang/slang/blob/b7df3c7aa27301f88e31ed0a7bbf230688adab6a/source/slang/CMakeLists.txt#L68-L78
It is currently out of date (running the build gives rise to unstaged changes), so this PR updates it.
=> Update capability atoms reference page

docs/user-guide/01-get-started.md
Added a note section under the Installation section that warns users about potential conflicts when multiple Slang installations are present on the system. The note specifically addresses:
* The scenario where Slang from Vulkan SDK might conflict with a standalone installation
* How LD_LIBRARY_PATH on Linux overrides the RUNPATH in the slangc executable
Closes https://github.com/shader-slang/slang/issues/7405
=> Add multiple slang installations note to doc

source/core/CMakeLists.txt, source/slang-rt/CMakeLists.txt, source/slangc/CMakeLists.txt
Slang compiler doesn't use thread and we should declare the dependency to the thread library when we don't need it.
The use of Thread is limited to the tools such as slang-test.
=> Reduce the dependency to thread library

.github/workflows/ci.yml
There was a case where a PR passed CI test a long time ago, and when it is merged, it caused a regression. We like to run via-glsl test when it gets merged to prevent it.
=> Enabling via-glsl test for "merge" event

source/slang/hlsl.meta.slang, tests/bugs/gh-8185.slang
Fixes #8185. The previous implementation is incorrect and basically only works in the `x = 0` case. `delta` was the smallest possible positive value representable as a float, but that's below the rounding error of addition with almost all reasonably sized floats.
This fixed implementation is based on bit twiddling instead. I've checked the float case against the C++ `nextafterf` with both a -inf -> inf and inf -> -inf sweep, in addition to the test included in this PR.
=> Fix nextafter()

source/slang/slang-reflection-json.cpp, tests/reflection/attribute.slang.expected
`emitReflectionVarLayoutJSON` will output the `userAttribs` section twice as it gets output by `emitReflectionModifierInfoJSON` first before being output again by a direct call to `emitUserAttributes`.
It seems the answer here is to just remove the extra explicit call to `emitUserAttributes` and rely on the call in `emitReflectionModifierInfoJSON`?
=> Fix reflection JSON writing userAttribs section twice for some cases.

source/slang-record-replay/record/parameter-recorder.h, source/slang-record-replay/record/slang-component-type.cpp, source/slang-record-replay/record/slang-component-type.h, source/slang-record-replay/record/slang-component-type2.cpp, source/slang-record-replay/record/slang-component-type2.h, source/slang-record-replay/record/slang-composite-component-type.cpp, source/slang-record-replay/replay/decoder-consumer.h, source/slang-record-replay/replay/json-consumer.cpp, source/slang-record-replay/replay/json-consumer.h, source/slang-record-replay/replay/replay-consumer.cpp, source/slang-record-replay/replay/replay-consumer.h, source/slang-record-replay/replay/slang-decoder.cpp, source/slang-record-replay/replay/slang-decoder.h, source/slang-record-replay/util/record-format.h
Add record and replay support for the IComponentType2 struct and its functions getTargetCompileResult and getEntryPointCompileResult.
=> Add record and replay support for IComponentType2

source/core/slang-platform.cpp
On Linux, `slang-platform.cpp` compiles with libstdc++ only because `unistd.h` is being transitively included. It fails to compile with standard libraries that don't include `unistd.h` like libc++.
This is the how it's being transitively included with libstdc++:
```
/home/mcvm/dev/slang/source/core/slang-platform.h
/home/mcvm/dev/slang/source/core/../core/slang-string.h
/home/mcvm/dev/slang/source/core/../core/slang-hash.h
/home/mcvm/dev/slang/external/unordered_dense/include/ankerl/unordered_dense.h
/usr/lib64/gcc/x86_64-unknown-linux-gnu/15.1.0/../../../../include/c++/15.1.0/memory
/usr/lib64/gcc/x86_64-unknown-linux-gnu/15.1.0/../../../../include/c++/15.1.0/bits/shared_ptr_atomic.h
/usr/lib64/gcc/x86_64-unknown-linux-gnu/15.1.0/../../../../include/c++/15.1.0/bits/atomic_base.h …
```
=> Fix readlink missing include

.github/workflows/release.yml
This is a first pass at adding WASM builds to releases. ~~I haven't tested the outputs yet but it appears to build successfully in my fork at least.~~
Edit: Made a fake release in my fork for testing, seems to be working well for my use case at least: https://github.com/davidar/slang/releases/tag/v2025.999
Fixes #8207
=> Add WASM platform support to release workflow

CMakeLists.txt, CMakePresets.json, examples/CMakeLists.txt, tools/CMakeLists.txt
This PR marks the `slang-rhi` a required dependecy for `platform` and `gfx-unit-test`, and only build them when `SLANG_ENABLE_SLANG_RHI=ON`.
This should allow the slang still to be built without those tests components when `SLANG_ENABLE_SLANG_RHI=OFF`.
=> Update slang-rhi deps for gfx-unit-test

.github/workflows/ci.yml
This PR enables slang-rhi and slangpy tests in the slang CI for MacOS.
* exclude the slang-rhi `sampler-array` test for mac; issue tracked in  https://github.com/shader-slang/slang/issues/8246
* update slang-rhi for fix of `nested-parameter-block-2`
* for slangpy test, install the required python package in the github mac runner only each CI run.
Closes: https://github.com/shader-slang/slang/issues/7330
=> Enable slangpy and slang-rhi tests for Mac

include/slang.h, source/core/slang-platform.cpp
The header execinfo.h and the related backtrace functionality is not available on all linux platforms. In particular it's missing on musl linux and on Android before API version 33. This causes compilation errors on those platforms.
With this change, we first check if backtrace functionality is available by checking if we are using glibc or a compatible Android version.
Tested on manylinux_2_28 with glibc 2.28 and musllinux_1_2 with musl 1.2, has not been tested on Android.
=> Add check for backtrace availability

tests/compute/texture-subscript.slang
=> Fix #8314 - Enable tests/compute/texture-subscript.slang for CUDA

source/slang/slang-check-expr.cpp, tests/language-server/completion-in-initexpr.slang
Fixes this regression:
```slang
struct MyType
{
// Regression Condition 1: there must be more than one member in the lookup scope.
float v;
int getSum() { return 0; }
}
void m(MyType t)
{
// Regression condition 2: the completion must be in an init expression.
// Regression condition 3: none of the candidate members can coerce to the expected type.
// Regression behavior: no completion candidates are shown, because
// SemanticsVisitor::resolveOverloadedLookup throws an error when there are 0 applicable candidates
// after type coercion filtering.
Texture2D x = t.;  // completion request after . here
}
```
The root cause is that we shouldn't be applying candidate filtering on the candidate list when in completion checking mode.
Closes #8417.
=> Fix language server auto-complete regression in debug build.

source/slang/slang-emit-spirv.cpp, source/slang/slang-parameter-binding.cpp, source/slang/slang-type-layout.cpp, tests/spirv/c-layout-buffer-3.slang
Closes #8409, but ended up being more about fixing another bug. While the issue itself seems to only be a simple typo fix (see second commit in this PR), I found out during writing a test that pointers never got correct locations regardless of layout. Their locations were always assigned to zero due to lacking a resource usage entry in `TypeLayout`. They were also missing the `Flat` decoration, so I went ahead and added that too.
I can split this up into two separate PRs if that's preferred; both aspects just share a test right now and fix a similar-looking issue in the resulting SPIR-V.
=> Fix pointers and C-like layout in varying parameters

source/slang/slang-emit.cpp
The `SpirvInstructionHelper::loadBlob()` method could segfault when calling `m_headerWords.addRange()` if the SPIR-V blob contained insufficient data for the required 5-word header.
To reproduce, run 
```
./build/Debug/bin/slangc.exe tests/modules/environment.slang -o tests/modules/environment.slang-module -target spirv -separate-debug-info
(0): error 57004: output SPIR-V contains no exported symbols. Please make sure to specify at least one entrypoint.
Segmentation fault
```
The error is expected, but the `Segmentation fault` is not.
This PR adds the check to ensure the SPIR-V blob has at least `SPV_INDEX_INSTRUCTION_START * sizeof(SpvWord)` bytes (20 bytes minimum) before attempting to process the header words.
Related to: https://github.com/shader-slang/slang/issues/7547
=> Fix segfault in SPIR-V header processing in SpirvInstructionHelper

.github/actions/common-setup/action.yml, .github/workflows/release.yml
- Remove hard-coded Win SDK version.
- Using self-hosted machine for building release package in Windows.
- Remove the steps from release.yml that have been done in common steup.
=> Use self-hosted runner for Windows release build

source/core/slang-platform.cpp
fixes https://github.com/shader-slang/slang/issues/8472
Fixes an issue with GCC 9.4.0 on Ubuntu 20.04, it will throw an error about PATH_MAX not being declared.
=> include limits.h in slang-platform.cpp

.github/workflows/ci.yml
This allows doc only changes to PASS the CI by skipping jobs.
=> Check if any required jobs failed (allow success or skipped)

source/slang/slang-check-conversion.cpp
I think the commit diff speaks for itself.
=> Fixed typo in `SemanticsVisitor::_readAggregateValueFromInitializerList`

tools/render-test/options.cpp, tools/render-test/options.h, tools/render-test/render-test-main.cpp, tools/render-test/slang-test-device-cache.cpp, tools/render-test/slang-test-device-cache.h, tools/slang-test/options.cpp, tools/slang-test/options.h, tools/slang-test/slang-test-main.cpp, tools/slang-test/test-context.cpp, tools/slang-test/test-context.h
This PR introduces two key improvements to the Slang test infrastructure:
1. **RHI Device Caching**: Implements device caching to significantly speed up test execution by reusing graphics devices across tests, **RHI Device Caching reduces slang-test execution time from ~15 minutes to ~5 minutes in Windows release builds**
2. **Test Prefix Exclusion**: Adds `-exclude-prefix` option to skip tests matching specified path prefixes
- **New `DeviceCache` class** (`slang-test-device-cache.h/cpp`): Thread-safe device cache with LRU eviction (max 10 devices)
- **Cache control option**: `-cache-rhi-device` flag in both `slang-test` and `render-test`
- Default: **enabled** in slang-test, **disabled** in render-test when run standalone
- Automatically skips caching for CUDA devices (due to driver …
=> Add RHI Device Caching and Test Prefix Exclusion

.github/workflows/ci-slang-test.yml, tools/render-test/options.cpp, tools/slang-test/options.cpp, tools/slang-test/options.h, tools/slang-test/slang-test-main.cpp, tools/slang-test/test-context.cpp, tools/test-server/test-server-main.cpp
With the recent Windows runtime libraries, a new popup window started appearing when `abort()` is called. This was observed when VVL prints a message as a part of WGPU test.
Although it can be helpful when we want to debug it, it breaks the behavior of CI scripts when the tests are expected to continue even when they fail. When the test fail, CI script stops in the middle and wait for a user to click on a button on the dialog window, which cannot happen. As a result, when there is a VVL error message, CI run stops in the middle and the testing stops prematurely.
This commit adds a new command-line argument, `-ignore-abort-msg`, that ignores the abort message and it wouldn't show the dialog popup window.
From the implementation perspective, there are three places that are related.
- …
=> Adding slang-test option to ignore abort popup message

docs/command-line-slangc-reference.md, source/slang/hlsl.meta.slang, source/slang/slang-capabilities.capdef, source/slang/slang-emit-c-like.cpp, source/slang/slang-emit-metal.cpp, source/slang/slang-emit-metal.h, source/slang/slang-emit-spirv.cpp, source/slang/slang-ir-insts-stable-names.lua, source/slang/slang-ir-insts.lua, source/slang/slang-ir.cpp, tests/language-feature/descriptor-handle/desc-handle-nv-bindless-texture.slang, tests/metal/atomic-texture-buffer.slang
Treat DescriptorHandle as uint64_t instead of uint2. Implement target-specific SPIR-V emission with the bindless texture support.
For OpImageTexelPointer, Image must have a type of OpTypePointer with Type OpTypeImage. Fix the issue by using [constref] in __subscript.
Add a test coverage for various texture/sampler handle types.
=> Add SPV_NV_bindless_texture support

source/slang/slang-ir-byte-address-legalize.cpp, tests/language-feature/descriptor-handle/byte-address-buffer-handle.slang
This is crash that be triggered by providing custom `getDescriptorFromHandle` and use it to return access a ByteAddressBuffer from a bindless handle.
Closes #8355.
=> Handle getEquivalentStructuredBuffer(castDynamicResource) in byte address legalization pass.

docs/user-guide/a3-02-reference-capability-atoms.md, source/slang/slang-parser.cpp, tests/front-end/link-time-struct-same-line.slang, tests/front-end/modern-syntax-semantic.slang, tests/front-end/struct-result-type.slang
- Fix bug parsing multiple link-time structs on the same line. Closes #8553.
- Fix bug parsing anonymous struct type as function return type in modern syntax. Closes #8558
- Support semantics on modern style param/var declarations.
=> Misc parser improvements.

.github/workflows/release.yml
For #8564
Similar to #8580, this re-adds the cross-compile target setup step for macOS releases that was erroneously removed in https://github.com/shader-slang/slang/pull/8470, which made x86_64 releases build aarch64 binaries.
It also simplifies the workflow logic a bit by adding a separate `arch` variable to the release matrix, which refers to the target architecture in the manner that the setup requires, so that we do not have to replace the string `"aarch64"` with `"arm64"` in setting `CMAKE_OSX_ARCHITECTURES` for native aarch64 macOS builds and do not have to conditionally set the MSVC `arch` to `amd64_arm64` for Windows cross-compilation.
=> Re-add macOS cross-compile setup to release workflow

source/slang/slang-ast-modifier.h, source/slang/slang-check-decl.cpp, source/slang/slang-check-impl.h, tests/autodiff/custom-differential-type-error.slang, tests/autodiff/custom-differential-type.slang
Close #8568.
The root cause of this issue is that when the struct is indirectly inherited from IDifferentiable type, we will not check the reference of the DerivativeMember attribute. This PR fixes this issue by checking the DerivativeMember attribute right before synthesize the requirement methods of IDifferentiable interface.
=> Fix the missing derivative member check

source/slang/slang-ir-legalize-matrix-types.cpp
Fixes these issues:
* During matrix legalization, `MakeMatrix` crashed if it was given a list of vectors instead of individual elements.
* Matrix casts, IRem, and Frem would be emitted using arrays, e.g. `IntToFloatCast` with `float2[2]` parameters.
I found these bugs while enabling various `hlsl-intrinsic` tests for the LLVM target. For now, I've chose to get rid of all matrix types with the matrix legalization pass so that the LLVM emitter doesn't need to be aware. These bugs were preventing `tests/hlsl-intrinsic/matrix-double-reduced-intrinsic.slang` and `tests/hlsl-intrinsic/matrix-double.slang` from passing there.
=> Matrix legalization for missing instructions & MakeMatrix of vectors

source/slang/hlsl.meta.slang, tests/hlsl-intrinsic/matrix-int-mul.slang
Integer mul(matrix, matrix) and mul(vector, matrix) are not disambiguated between __BuiltinIntegerType and __BuiltinLogicalType, emitting an ambiguous call compilation error.
Use the OverloadRank attribute to prefer the IntegerType overload over the LogicalType overload.
Fixes #8424
=> Prefer IntegerType over LogicalType integer matrix mul() overloads

tools/slang-unit-test/unit-test-find-check-entrypoint.cpp
Test `slang-unit-test-tool/cudaCodeGenBug.internal` requires that the CUDA toolkit is available. Add a check for the NVRTC backend to avoid a failure when this is not the case.
Fixes #6636
=> Add check for NVRTC backend in unit test cudaCodeGenBug

docs/user-guide/10-link-time-specialization.md, docs/user-guide/toc.html, source/slang/slang-ast-decl.h, source/slang/slang-ast-iterator.h, source/slang/slang-ast-support-types.h, source/slang/slang-check-decl.cpp, source/slang/slang-check-expr.cpp, source/slang/slang-check-impl.h, source/slang/slang-ir-insts-stable-names.lua, source/slang/slang-ir-insts.h, source/slang/slang-ir-insts.lua, source/slang/slang-ir-link.cpp, source/slang/slang-ir.cpp, source/slang/slang-language-server-ast-lookup.cpp, source/slang/slang-lower-to-ir.cpp, source/slang/slang-parameter-binding.cpp, source/slang/slang-parser.cpp, source/slang/slang-syntax.h, source/slang/slang-type-layout.cpp, source/slang/slang-type-layout.h, tests/language-feature/modules/wrapper-inout.slang, tools/gfx-unit-test/link-time-type-generic.cpp, tools/gfx-unit-test/link-time-type-multi-use-generic.cpp, tools/gfx-unit-test/link-time-type-multi-use.cpp, tools/slang-unit-test/unit-test-link-time-type-reflection.cpp
This change achieves link-time type resolution with a different mechanism.
For `extern struct Foo : IFoo = FooImpl;`,
instead of synthesizing a wrapper type `Foo` that has a `FooImpl inner` field and dispatches all interface method calls to `inner.method()`, this PR completely removes this synthesis step, and instead just lower such `extern`/`export` types as `IRSymbolAlias` instructions that is just a reference to the type being wrapped.
Then we extend the linker logic to clone the referenced symbol instead of the SymbolAlias insts itself during linking.
By doing so, we greatly simply the logic need to support link-time types, and achieves higher robustness by not having to deal with many AST synthesis scenarios.
Closes #8554.
=> Use symbol alias instead of wrapper synthesis to implement link-time types.

docs/user-guide/a2-03-wgsl-target-specific.md, docs/user-guide/toc.html
As mentioned in #8316 , there is a small duplicated and outdated section in WGSL-Specific Functionalities documentation about specialization constants support,
remove the outdated duplicated one
as there is a new section in the page
=> Minor Documentation Update to Remove Outdated Section
