shader-slang/slang

slang.sln
source/slang/lexer.cpp
source/slang/preprocessor.cpp
tests/preprocessor/escaped-newlines.slang

The changes here are primarily to allow for backslash-escaped newlines. There is a functional change to the lexer, and then a test case.
Adding that test case also exposed a bug in the preprocessor, and so I've included a fix for the issue. The test case thus also serves as a regression test for that bug.

Escaped newlines

---

source/slang/check.cpp
source/slang/diagnostic-defs.h
source/slang/parser.cpp
source/slang/slang-stdlib.cpp
source/slang/syntax.cpp
source/slang/syntax.h
tests/front-end/interface.slang

- Add a test case for `interface` declarations and the exected implicit type conversion rules around them
- Rename exising "trait" declaration kind to "interface"
- There was already basic syntax for `__trait` declarations, and a bunch of related machinery.
- Not all of it worked as needed, but it was clearly a start at solving the problem
- Change `InterfaceConformanceDecl` to a more general `InheritanceDecl` that covers inheritance from any type expression (leave it to other code to validate the cases that should be allowed)
- Instead of keeping a raw `bases` array on interface/trait declarations, turn all inheritance clauses into `IheritanceDecl` members
- Add support for inheritance clause on `struct` types
- Remove the `__conforms` syntax only used in the stdlib, in favor of …

Add basic support for `interface` declarations

---

source/slang/check.cpp
source/slang/emit.cpp
source/slang/lookup.cpp
source/slang/lookup.h
source/slang/parameter-binding.cpp
source/slang/parser.cpp
source/slang/reflection.cpp
source/slang/syntax.cpp
source/slang/syntax.h
source/slang/type-layout.cpp
source/slang/type-layout.h

For context: a `DeclRef` is supposed to capture both a pointer to a particualr declaration, and also any information needed to specialize that declaration for a context (e.g., generic parameter substitutions).
The existing approach had a hiearchy of specialized decl-ref types that mirrored the AST hierarchy, but that led to a lot of boilerplate where you had to recapitulate the exact same hierarchy.
The new appraoch basically treats `DeclRef<T>` as a sort of "smart pointer" in that it wraps a pointer to a `T` (the declaration), plus a side field for the specialization info, and then allows it to be cast as needed to other types (where the pointer cast would be allowed), while carrying along the side info.
To enable this, all the things that used to be member functions of …

Replace `DeclRef` approach

---

source/slang/check.cpp
source/slang/emit.cpp
source/slang/parser.cpp
source/slang/syntax.h

When in rewriter mode, the emit logic will never see function applications inside function bodies, but it *will* see function application expressions at global scope, and some of these expressions might be unchecked.
The challenge here is that even simple math operations now show up as function calls, so we need a bit of special-case logic to detect unchecked calls and then emit them using the syntax they were written with (e.g., use infix syntax if they were written as an infix expression).

Bug fix: handle unchecked operator application in emit logic

---

slang.h
source/core/slang-io.h
source/core/slang-string.h
source/slang/compiler.h
source/slang/options.cpp
source/slang/parser.cpp
source/slang/preprocessor.cpp
source/slang/preprocessor.h
source/slang/slang.cpp
source/slang/slang.vcxproj
source/slang/slang.vcxproj.filters
source/slang/token-defs.h
source/slangc/main.cpp
tests/render/auto-import.hlsl
tests/render/auto-import.slang.h
tools/render-test/options.cpp
tools/render-test/options.h
tools/render-test/slang-support.cpp

The basic idea of this change is that user code can just write:
#include "foo.h"
and then if `foo.h` gets found in a list of registered directories for "auto-import," then it actually gets interpreted as if the user had writte, more or less:
__import foo;
That is, the code in `foo.h` will be treated as Slang, and will be fully parsed and checked (no matter what the source language had been), and the scoping rules will be those of `__import` instead of `#include`.
This is a really big hammer, and I could imagine it smashing fingers if used poorly.
I'm not sure this feature will pan out, but we need to try things to know.
One big piece of that that I'll likely keep in either case is an overhaul of command-line options parsing for `slangc`. In particular, this logic has been moved into the …

Allow for automatic importing of Slang code

---

source/slang/check.cpp
source/slang/compiler.h
source/slang/parser.cpp
source/slang/parser.h
source/slang/profile.h
source/slang/slang.cpp
source/slang/slang.vcxproj
source/slang/slang.vcxproj.filters
source/slang/syntax-visitors.h

That is, even if the user specified the `-no-checking` option (or the equivalent via API), we still want/need to apply full semantic checks to Slang code, so that cross-compilation will be possible.

Make sure that semantic checks always apply to Slang files

---

source/slang/lexer.cpp

The previous changes had left out logic for "scrubbing" a token value that includes an escaped newline, because I expected it would only occur within whitespace. Unfortunately, some user code looked like this:
```
a + b
```
That is, there was a token at the very start of the line, after the escaped newline.
As a result, after consuming the leading whitespace (which didn't end up consuming the escaped newline - but we could consider making it do so in future), the lexer started to lex a token that *starts* with an escaped newline, but turns out to be an identifer (which gets an invalid name).
This change adds some ad-hoc code to "scrub" the value of *every* token, which wasteful but at least solves the problem.

Bug fix for newline escaping.

---

source/slang/slang-stdlib.cpp
source/slang/syntax.cpp
source/slang/syntax.h
tests/bugs/gh-34.hlsl

Fixes #34.
I'd declared these as if they were `InputPatch<T>`, but they are really `InputPatch<T,N>`.
This change fixes the declarations, and makes these types no longer inherit from the contrived `BuiltinGenericType`.
Instead they are more-or-less ordinary `DeclRefType`s using the same approach that `MatrixExpressionType` uses.

Fix types for `InputPatch` and `OutputPatch`

---

examples/hello/hello.cpp
slang.h
source/slang/check.cpp
source/slang/compiled-program.h
source/slang/compiler.cpp
source/slang/compiler.h
source/slang/options.cpp
source/slang/parameter-binding.cpp
source/slang/parameter-binding.h
source/slang/parser.cpp
source/slang/parser.h
source/slang/preprocessor.h
source/slang/slang.cpp
source/slang/syntax-visitors.h
source/slangc/main.cpp
tools/render-test/render-d3d11.cpp
tools/render-test/slang-support.cpp

The main user-visible change here is that instead of `spAddTranslationUnitEntryPoint` we have `spAddEntryPoint`, to reflect that the list of entry points is "global" to a compile request.
As a result, `spGetEntryPointSource` now only needs the entry point index, and not the translation unit index.
There are a bunch more behind-the-scenes changes, though, reflecting a streamlining of the concepts related to compilation into a smaller number of classes.
Now there is:
- `Session` (unchanged) to manage the lifetimes of shared stuff like the stdlib
- `CompileRequest` (merges in `CompileOptions`) to handle all the lifetime related to a single invocation of the compiler
- `TranslationUnitRequest` (merges `TranslationUnitOptions`, `CompileUnit`) to represent a single translation unit ("module") …

Overhaul handling of entry points and translation units.

---

source/slang/emit.cpp
source/slang/parser.cpp
source/slang/syntax.h
tests/hlsl/dxsdk/SimpleBezier11/SimpleBezier11.hlsl

String literals can be used as part of attributes, but we lacked an actual AST representation for them.
This change adds basic parsing for string literals, as well as emit logic for them.
I also included a fix for parsing of chained right-associative operators.
To test these fixes, I've re-enabled one of the HLSL tests I disabled a while back. It would be good to go through and see how many of those we can re-enable now.

Fix parsing of string literals.

---

source/slang/emit.cpp
tests/render/imported-parameters.hlsl
tests/render/imported-parameters.slang

This fixes up a bug in the earlier change that provided reflection for imported parameters; I'd failed to confirm that the code generation logic can handle imported parameters correctly.
The main fix was to have an `import` declaration automatically use the global-scope layout already determined, sine imported parameters will in general appear there.

Emit global-scope parameters from imported files.

---

source/slang/check.cpp
source/slang/parser.cpp
source/slang/syntax.h
tests/front-end/import-exported-a.slang
tests/front-end/import-exported-b.slang
tests/front-end/import-exported.slang

If module `A.slang` contains `__exported __import B;` then any declarations from `B.slang` will be visible to any client code that does `__import A;`.
This allows a user to make a single "umbrella" file that encompases a bunch of code files.
Note that this really only affects scoping during Slang compilation/checking; at code generation time everything always gets emitted as raw HLSL/GLSL so that names will be visible whether we want them to be or not.

Allow for re-export of an `import` declaration

---

source/slang/parser.cpp
tests/front-end/import-subdir.slang
tests/front-end/subdir/import-subdir-a.slang

The code:
__import foo.bar;
will try to import from a file matching "foo/bar.slang".
I also went ahead and allowed a raw string literal in and import:
__import "foo/bar";
(In the latter case, an explicit `/` must be used instead of `.`)

Allow "dotted" import paths

---

source/slang/check.cpp
source/slang/emit.cpp
source/slang/lexer.h
source/slang/parameter-binding.cpp
source/slang/parser.cpp
source/slang/reflection.cpp
source/slang/syntax.cpp
source/slang/syntax.h
source/slang/type-layout.cpp

The lexer was creating an `unsigned long long` value, and then the AST was storing it in an `int`.
This change makes both use a `long long`.
This is obviously still a stopgap until I can get arbitrary precisions in here.

Store integer literals at high precision in AST

---

source/core/core.natvis
source/core/slang-io.cpp
source/core/slang-string.cpp
source/core/slang-string.h
source/core/smart-pointer.h
source/core/stream.h
source/core/text-io.cpp
source/core/text-io.h
source/slang/check.cpp
source/slang/lexer.cpp
source/slang/options.cpp
source/slang/parameter-binding.cpp
source/slang/parser.cpp
source/slang/slang-stdlib.cpp
source/slang/syntax.h
source/slangc/main.cpp
tools/slang-test/main.cpp
tools/slang-test/os.cpp

- `RefPtr` no longer tries to have distinct cases for interal-vs-external reference counts. Instead we always require an internal reference count.
- Types the used `RefPtr` but weren't `RefObject` were made to inherit `RefObject`
- The `ReferenceCounted` base class was removed, so that only `RefObject` remains
- Implicit conversion from `RefPtr<T>` to `T*` added
- This created some complicates for other types that relied on implicit conversions, so this isn't a net cleanup right now
- The main type that got messed up by the above was `String`, which previously held a `RefPtr<char, ...>`. This change thus *also* includes a major overhaul of `String`:
- `String` now holds all its data via indirection, using a `StringRepresentation` that is a `RefObject`. This object holds a length, …

Overhaul `RefPtr` and `String`

---

source/slang/check.cpp
source/slang/compiler.h
source/slang/decl-defs.h
source/slang/expr-defs.h
source/slang/lookup.h
source/slang/modifier-defs.h
source/slang/object-meta-begin.h
source/slang/object-meta-end.h
source/slang/slang-stdlib.cpp
source/slang/slang.cpp
source/slang/slang.vcxproj
source/slang/slang.vcxproj.filters
source/slang/stmt-defs.h
source/slang/syntax-base-defs.h
source/slang/syntax-defs.h
source/slang/syntax-visitors.h
source/slang/syntax.cpp
source/slang/syntax.h
source/slang/type-defs.h
source/slang/val-defs.h
source/slang/visitor.h
tests/diagnostics/while-predicate-type.slang.expected

- The big change here is that all the definitions for syntax-node classes have been macro-ized, to that we can do light metaprogramming over them
- The use of macros for this has big down-sides, but I'm not quite ready to do anything more heavy-weight right now
- The macro-ized definitions can be included multiple times, to generate different declarations/code as needed
- The first example of using this meta-programming facility is a new visitor system
- The actual visitor base classes and the dispatch logic are all generated from the meta-files
- There was only one visitor left in the code: the semantics checker, so that was ported to the new system.
- All current test cases pass, so *of course* that means all is well.

Add meta-definitions for AST types

---

slang.h
source/slang/check.cpp
source/slang/compiler.cpp
source/slang/emit.cpp
source/slang/emit.h
source/slang/expr-defs.h
source/slang/lower.cpp
source/slang/lower.h
source/slang/modifier-defs.h
source/slang/parameter-binding.cpp
source/slang/parser.cpp
source/slang/slang.vcxproj
source/slang/slang.vcxproj.filters
source/slang/stmt-defs.h
source/slang/syntax.cpp
source/slang/syntax.h
source/slang/type-layout.h
source/slang/val-defs.h
tests/render/cross-compile-entry-point.slang
tools/render-test/render-d3d11.cpp

This is largely just infrastructure work. I've added an initial AST->AST lowering pass that is meant to desugar language constructs that can't be handled trivially during emit logic.
Right now the main desugaring that is going on is to generate a GLSL-style `void main()` for an entry point when cross-compiling.
The other big difference is that when cross-compiling (native Slang -> *), we only output symbols that were actually referenced (transitively) by the entry point.

Initial work on cross-compilation

---

source/core/exception.h
source/core/int-set.h
source/core/list.h
source/core/slang-io.cpp
source/core/slang-string.cpp
source/core/slang-string.h
source/core/smart-pointer.h
source/core/text-io.cpp
source/core/text-io.h
source/slang/check.cpp
source/slang/diagnostics.cpp
source/slang/diagnostics.h
source/slang/emit.cpp
source/slang/lower.cpp
source/slang/options.cpp
source/slang/parameter-binding.cpp
source/slang/preprocessor.cpp
source/slang/reflection.cpp
source/slang/slang-stdlib.cpp
source/slang/slang.cpp
source/slang/syntax.cpp
source/slang/syntax.h
source/slang/type-layout.cpp
tools/render-test/main.cpp
tools/render-test/render-d3d11.cpp
tools/render-test/render-gl.cpp

The code should now compile cleanly with warnings as errors for VS2015 with `W3`.
Most of the changes had to do with propagating a real pointer-sized integer type through code that had been using `int`.

Fix issues found during testing of v0.4.0 with Falcor

---

source/slang/check.cpp
source/slang/emit.cpp
source/slang/lower.cpp
source/slang/slang-stdlib.cpp
source/slang/syntax.h
source/slang/visitor.h

This PR includes a pretty major overhaul of how `emit.cpp` is structured (it now uses the visitor infrastructure) and then implements a bunch of fixups toward getting Slang->GLSL cross-compilation working.

More work on cross compilation

---

source/slang/emit.cpp
source/slang/lower.cpp
source/slang/reflection.cpp
source/slang/slang-stdlib.cpp
source/slang/type-defs.h
source/slang/type-layout.cpp
source/slang/type-layout.h

This is mostly work to fix up the lack of `imageBuffer` as a type on the GLSL side.
The work to add the type was easy (3 lines), but I tried to make the new rewriter a bit more robust to the case where it doesn't understand a type in user code.
(I'm thinking, though, that maybe this class of error should not be suppressed, even in "rewriter" mode)

Falcor work

---

source/slang/emit.cpp

I forgot to include a trailing space.

Fix emission of `static` for HLSL

---

source/slang/emit.cpp

The emit logic was checking for a missing decl, and then asking that same (missing) declaration for its name.

Handle function name properly for unchecked call

---

slang.h
source/slang/compiler.cpp
source/slang/compiler.h
source/slang/slang.cpp
tools/glslang/glslang.cpp
tools/glslang/glslang.h

- Refactored to allow Slang compiler to work with raw data instead of Strings.
- Added interface to get code as raw data.
- Added support for regular SPIR-V output in glslang wrapper.

SPIR-V Support

---

source/slang/slang-stdlib.cpp
tests/reflection/image-types.glsl
tests/reflection/image-types.glsl.expected

- Update stdlib so taht `image*` types have read-write access encoded in their type
- TODO:  this isn't 100% right, since there are GLSL qualifiers that might override this
- Add a test case to verify  that the reflection API reports `image*` parameters

Improve reporting of GLSL `image*` types

---

source/slang/emit.cpp
source/slang/lower.cpp
source/slang/slang-stdlib.cpp

This is more work on scalarizing types that mix resource and uniform types. Mostly it addresses bugs in the earlier PR.
Also I added lowerings to GLSL for the HLSL `ddx*` and `ddy*` functions, since those were needed by the code I was using.

Resources in structs

---

source/slang/parser.cpp
tests/bugs/gh-75.hlsl
tests/bugs/gh-75.hlsl.expected

Fixes #75
In order to avoid cascaded errors, I went ahead and made the parser refuse to skip past a `}` in recovery mode. The problem with this is that we fail to make forward progress if we are stuck on a `}` (this happens if you have an extra `}` at the global scope.

Make parser recovering more robust to avoid infinite loops

---

slang.h
source/slang/compiler.cpp
source/slang/emit.cpp
source/slang/lower.cpp
source/slang/reflection.cpp
source/slang/type-layout.h
tests/reflection/arrays.hlsl.expected
tests/reflection/gh-55.glsl.expected
tests/reflection/global-uniforms.hlsl.expected
tests/reflection/image-types.glsl
tests/reflection/image-types.glsl.expected
tests/reflection/multi-file-extra.hlsl
tests/reflection/multi-file.hlsl
tests/reflection/multi-file.hlsl.expected
tests/reflection/reflect-imported-code.hlsl.expected
tests/reflection/reflection0.hlsl.expected
tests/reflection/resource-in-cbuffer.hlsl.expected
tests/reflection/sample-rate-input.glsl
tests/reflection/sample-rate-input.glsl.expected
tests/reflection/std430-layout.glsl
tests/reflection/std430-layout.glsl.expected

This adds an initial API query to check if an entry point needs to be evaluated at "sample rate." In the context of Vulkan/D3D12, this basically means "did the entry point reference any input with the `sample` qualifier, or the built-in variable that exposes sample index?"

Sample rate reflection

---

source/slang/check.cpp
source/slang/compiler.cpp
source/slang/diagnostics.cpp
source/slang/diagnostics.h
source/slang/emit.cpp
source/slang/lower.cpp
source/slang/modifier-defs.h
source/slang/parser.cpp
source/slang/slang-stdlib.cpp

- When assigning tuples `(a0, ...) = (b0, ...)` generate a tuple of assignments `(a0 = b0, ...)`
- Given an expression statement on a tuple `(a0, ...);` generate a sequence of statements `a0; ...`

Fixes for shader cross-compilation

---

source/slang/reflection.cpp
source/slang/type-layout.cpp
tests/bindings/gh-84.frag

Fixes #84
- When computing resource usage for an array type, don't multiply the resource usage of the element type by the element count foor descriptor-table-slot resources.
- When reporting the "stride" of an array type through reflection, report the stride for descriptor table slots as zero, always.

An array of resources in Vulkan only consumes one binding

---

slang.h
source/slang/compiler.cpp
source/slang/compiler.h
source/slang/slang.cpp
tools/glslang/glslang.cpp
tools/glslang/glslang.h

Calling:
spSetDumpIntermedites(compileRequest, true);
will set up a mode where Slang tries to dump every intermediate HLSL, GLSL, DXBC, SPIR-V, etc. file it generates. If SPIR-V or DXBC is requested then we also dump assembly of those.
Right now the files are all named as `slang-<counter>.<ext>`, and get dropped in whatever the working directory is, but I'm open to ideas on how to improve that.
Note: this change introduces a new binary interface to `glslang`, so pulling it requires an updated `glslang.dll`.

Add support for dumping intermediates for debugging.

---

source/slang/modifier-defs.h
source/slang/parser.cpp
source/slang/reflection.cpp
tests/reflection/thread-group-size.comp
tests/reflection/thread-group-size.comp.expected
tests/reflection/thread-group-size.hlsl
tests/reflection/thread-group-size.hlsl.expected

Fixes #15
These are the modifiers like:
layout(local_size_x = 16) in;
Unlike the HLSL case, these don't get attache to the entry point function itself, so there is a bit more work involed in looking them up.
Just to make sure I didn't mess up the HLSL case, I went ahead and added two tests for this capability: one for GLSL and one for HLSL.

Add reflection support for GLSL thread-group-size modifier

---

source/slang/emit.cpp
source/slang/parameter-binding.cpp
source/slang/slang-stdlib.cpp

Fixes #105.
The root cause was an error in the shader code itself (it wasn't importing something it used), but the Slang compiler behavior around that error wasn't good (we crashed instead of letting the HLSL compiler report the issue). This change fixes up some of our behavior around bad input.

Don't crash-fail on errors in entry point parameters

---

source/slang/emit.cpp
source/slang/lower.cpp
source/slang/profile.h
tests/cross-compile/gl-layer-pick-version.slang
tests/cross-compile/gl-layer-pick-version.slang.glsl

`gl_Layer` as a fragment input requires at least version 4.30 of GLSL, so we try to track that information when we see the name used.
Note that this does *not* override a user-specified `#version` line.
This required re-ordering when lowering happens relative to emitting the `#version` directive, since this code works by actually modifying the chosen profile for the entry point.
Yes, that is kind of gross and we should do something cleaner in the long term.

Pick correct GLSL version when `gl_Layer` used

---

source/slang/emit.cpp
source/slang/reflection.cpp
source/slang/slang-stdlib.cpp
source/slang/syntax.cpp
source/slang/type-defs.h
source/slang/type-layout.cpp
source/slang/type-layout.h

Fixes #94
We'd been handling HLSL `Buffer` and `RWBuffer` in a one-off fashion, and that led to a lot of code duplication, and also to the issue that we weren't handling `RasterizerOrderedBuffer` at all.
This change basically folds `Buffer` in so that it is conceptually a texture type (just with a unique shape). Hopefully all the other logic still works.

Handle `Buffer` types more like textures

---

source/slang/parameter-binding.cpp

- When generating parameter binding/reflection info, treated imported modules as Slang code, instead of the source language of the outer translation unit
- This fixes an issue where global-scope shader parameters in a `.slang` file were getting ignored for binding-generation purposes when imported by a GLSL file

Make sure to treat imported modules as Slang

---

source/slang/check.cpp
source/slang/diagnostic-defs.h
source/slang/emit.cpp
source/slang/expr-defs.h
source/slang/lower.cpp
source/slang/parameter-binding.cpp
source/slang/slang-stdlib.cpp
tests/reflection/thread-group-size.hlsl.expected
tests/rewriter/varying-struct.slang
tests/rewriter/varying-struct.vert

This is a bunch of fixes for issues I encountered while trying to run the Falcor VK "Shadows" sample.
The main interesting fix here is support for global-scope varying input/output with `struct` types that include system-value semantics on fields.

Falcor shadow fixes

---

source/slang/parameter-binding.cpp
source/slang/parser.cpp

We generate implicit names for global-scope parameter blocks (including HLSL `cbuffer`s, since the "name" the user sees is really just for reflection purposes), but this had a few problems:
- We used the generated names for parameter-binding purposes
- Except for a GLSL block with an explicit name, in which case we'd use the internal name and not the reflection name for matching
- The generated named didn't match between GLSL and HLSL/Slang declarations
This change tries to fix both of these issues. I changed the name generation to try to make it identical between HLSL and GLSL (to the extent we can control it), just in case. But then I also went and changed the parameter-binding-generation logic to use the *reflection* name instead of the internal name when deciding if things are the …

Fixes for how parameter block names are set up.

---

slang.h
slang.sln
source/slang-glslang/slang-glslang.cpp
source/slang-glslang/slang-glslang.h
source/slang-glslang/slang-glslang.vcxproj
source/slang-glslang/slang-glslang.vcxproj.filters
source/slang/compiler.cpp
source/slang/slang.vcxproj
source/slangc/main.cpp

- Change the `slang` project from a static library to a dynamic one
- Add some details around `slang.h` to make sure DLL export stuff is working
- Make the `slangc` executable use the dynamic library
- Rename the `glslang` sub-project to `slang-glslang` and move it into the main source hierarchy
- This reflects the fact that it isn't a stand-alone tool, and isn't in any way a standard binary of glslang, but rather just an artifact of how Slang uses glslang

Build a dynamic library for Slang

---

appveyor.yml
build/slang-build.props
test.bat

- Change naming convention for output directory
- `windows-x86` and `windows-x64`
- Lower-case for `debug`, `release`
- Test script needed to be patched up for this
- Add packaging and deployment logic to AppVeyor CI script
- Trigger deployment on new tag
- Compute a release version based on Git tag name (`vX.Y.Z` becomes `X.Y.Z`)
- Fallback to hash in case tag isn't available (it should always be)
- Bundle files into a few artifacts (binary package + source package)
- Set up to push those files into existing GitHub tag/release

Use AppVeyor to deploy to GitHub Releases

---

source/core/common.h
source/core/exception.h
source/core/slang-string.cpp
source/core/slang-string.h
source/core/smart-pointer.h
source/slang/check.cpp
source/slang/compiler.cpp
source/slang/diagnostic-defs.h
source/slang/diagnostics.cpp
source/slang/diagnostics.h
source/slang/emit.cpp
source/slang/lexer.cpp
source/slang/lower.cpp
source/slang/options.cpp
source/slang/parameter-binding.cpp
source/slang/parser.cpp
source/slang/preprocessor.cpp
source/slang/reflection.cpp
source/slang/slang-stdlib.cpp
source/slang/slang.cpp
source/slang/syntax-base-defs.h
source/slang/syntax.cpp
source/slang/token.cpp
source/slang/type-layout.cpp

The change is mostly about trying to make sure the compiler "fails safe" when it encounters an internal assumption that isn't met.
Most internal errors will now throw exceptions (yes, exceptions are evil, but this will work for now), and these get caught in `spCompile` so that they don't propagate to the user (they just see a message that compilation aborted due to an internal error).
Subsequent changes are going to need to work on diagnosing as many of these situations as possible, so that users can at least know what construct in their code was unexpected or unhandled by the compiler.

Try to improve handling of failures during compilation

---

source/slang-glslang/slang-glslang.vcxproj
source/slang/emit.cpp
source/slang/emit.h
source/slang/lower.cpp
source/slang/lower.h
source/slang/parameter-binding.cpp
tests/nv-extensions/multi-view-per-view-attributes.slang
tests/nv-extensions/multi-view-per-view-attributes.slang.glsl

- The easy part here is treating `NV_` prefixed semantics as another case of "system-value" semantics
- Mapping the new semantics (`NV_X_RIGHT` and `NV_VIEWPORT_MASK`) to their GLSL equivalents is harder
- Instead of a single "right-eye vertex" output, GLSL defines an array of per-view positions
- Instead of a vector of masks, GLSL defines an array of per-view masks
- Another point here is that a lot of semantics that appear as `uint` in HLSL are `int` in GLSL, which can lead to conversion issues.
- The approach here is to have the lowering pass introduce a notion of assignment with "fixups," which will try to cast things as needed
- When assigning to a simple value with the "wrong" type, introduce a cast
- When assigning to an array from a vector, break out multiple assignments of …

Translate NV single-pass stereo extension from Slang to GLSL

---

source/slang/lower.cpp

The requirements for using `gl_Layer` differ by stage, and so we need to pick an appropriate GL version based on the target stage, and then also require a specific extension for anything other than geometry or fragment.

Require extension when using `gl_Layer` in VS

---

slang.h
source/slang/compiler.cpp
source/slang/compiler.h
source/slang/emit.cpp
source/slang/slang.cpp

- API users can use this to get "clean" output to aid with debugging Slang issues
- Also changes the prefix on intermediate files that Slang dumps, to make them easier to ignore with a regexp

Add an API option to control emission of `#line` directives

---

source/slang/lower.cpp
tests/bugs/gh-133.slang
tests/bugs/gh-133.slang.glsl

Fixes #133
We already had logic to skip adding `flat` to a vertex input, and this just extends it to not adding `flat` to a fragment output.
Note that explicit qualifiers in the input HLSL/Slang will still be carried through to the output, so it is still possible for a Slang user to shoot themself in the foot with interpolation qualifiers.

Don't add `flat` qualifier to integer fragment output

---

source/slang/emit.cpp
source/slang/parameter-binding.cpp
source/slang/type-layout.h
tests/reflection/cross-compile.slang.expected

- We use this to work around the fact that, e.g., `Texture2D.Load` doesn't take a sampler, but the equivalent GLSL operation `texelFetch` requires one
- Previously we tried to hide the sampler from the user, hoping that glslang would drop it and we could just ignore it, but that doesn't work
- For now we'll go ahead and explicitly show the sampler in the reflection info so that an app can react appropriately
- We also generate a unique binding for the sampler, instead of the old behavior that fixed it with `binding = 0`
- We still fix it with `set = 0`, so it might still surprise users

Make the "hack" sampler explicit for now

---

source/slang/lower.cpp
tests/rewriter/glslang-bug-988-workaround.frag
tests/rewriter/glslang-bug-988-workaround.slang
tests/rewriter/resources-in-structs.glsl

The basic bug there is that if you have a member of `struct` type in a `uniform` block and then pass a reference to that member directly to a call:
```
struct Foo { vec4 bar; };
uniform U { Foo foo; };
void main() { doSomething(foo); }
```
then glslang generates invalid SPIR-V which seems to cause an issue for some drivers.
This change works around the problem by detecting cases where an argument to a function call is a reference to `uniform` block member (of `struct` type) and then rewrites the code to move that value to a temporary before the call.

Work around glslang issue 988

---

source/slang/lower.cpp
tests/rewriter/glslang-bug-988-workaround.frag

There was a bug where the intialization expression for a variable was being lowered after the declaration was added to the output code, so that any sub-expressions that get hoisted out actually get computed *after* the original variable. This obviously led to downstream compilation failure.
I've updated the test case to stress this scenario.

Fixup for the glslang bug workaround

---

source/slang/compiler.cpp
source/slang/compiler.h
source/slang/diagnostic-defs.h
source/slang/options.cpp
source/slang/slang.cpp
source/slangc/main.cpp

Fixes #11
- This adds a `-o` command-line option for specifying an output file.
- The code tries to be a bit smart, to glean an output format from a file extension, and also to associate multiple `-o` options with multiple `-entry` options if needed.
- There is a restriction that all the output files need to agree on the code generation target. This is reasonable for now, but might be something to lift eventualy
- There is a restriction that only one output file is allowed per entry point
- Together with the previous item this means you can't output both a `.spv` and a `.spv.asm` in one pass, even though both should be possible
- There is currently a restriction that output paths only apply to entry points
- This means there is no way to output reflection JSON to a file with `-o` (but …

Add a `-o` option to command-line `slangc`

---

slang.h
source/core/slang-string.cpp
source/core/slang-string.h
source/slang/compiler.cpp
source/slang/compiler.h
source/slang/diagnostics.cpp
source/slang/diagnostics.h
source/slang/emit.cpp
source/slang/lexer.cpp
source/slang/lexer.h
source/slang/lower.cpp
source/slang/options.cpp
source/slang/parser.cpp
source/slang/parser.h
source/slang/preprocessor.cpp
source/slang/preprocessor.h
source/slang/slang.cpp
source/slang/slang.vcxproj
source/slang/slang.vcxproj.filters
source/slang/source-loc.cpp
source/slang/source-loc.h
source/slang/syntax-base-defs.h
source/slang/syntax-visitors.h
source/slang/token.h
tests/preprocessor/line.slang
tests/preprocessor/line.slang.expected

Fixes #24
So far the code has used a representation for source locations that is heavy-weight, but typical of research or hobby compilers: a `struct` type containing a line number and a (heap-allocated) string.
This is actually very convenient for debugging, but it means that any data structure that might contain a source location needs careful memory management (because of those strings) and has a tendency to bloat.
The new represnetation is that a source location is just a pointer-sized integer.
In the simplest mental model, you can think of this as just counting every byte of source text that is passed in, and using those to name locations.
Finding the path and line number that corresponds to a location involves a lookup step, but we can arrange to store all the files in an array …

Make source location lightweight

---

source/slang/check.cpp
source/slang/compiler.h
source/slang/decl-defs.h
source/slang/emit.cpp
source/slang/lexer.cpp
source/slang/lower.cpp
source/slang/parser.cpp
source/slang/parser.h
source/slang/slang.cpp
source/slang/syntax.cpp
source/slang/syntax.h

The existing parser code was doing string-based matching on the lookahead token to figure out how to parse a declaration, e.g.:
```
if(lookAhead == "struct") { /* do struct thing */ }
else if(lookAhead == "interface") { /* do interface thing * }
...
```
That approach has some annoying down-sides:
- It is slower than it needs to be
- It is annoying to deal with cases where the available declaration keywords might differ by language
- Most importantly, it is not possible for us to introduce "extended" keywords that the user can make use of, but which can be ignored by the user and treated as an ordinary identifier.
That last part is important. Suppose the user wanted to have a local variable named `import`, but we also had a Slang extension that added an `import` keyword. Then a line of …

Look up declaration keywords using ordinary scoping.

---

source/slang/check.cpp
source/slang/compiler.h
source/slang/decl-defs.h
source/slang/emit.cpp
source/slang/lower.cpp
source/slang/modifier-defs.h
source/slang/parser.cpp
source/slang/slang-stdlib.cpp
source/slang/slang.cpp
source/slang/syntax.cpp
source/slang/syntax.h

Just like the previous change did for declaration keywords, this change uses the lexical environment to drive the lookup and dispatch of modifier parsing.
This allows us to easily add modifiers to Slang, even when they might conflict with identifiers used in user code (because the modifier names are no longer special keywords, but ordinary identifiers).
There was already some support for ideas like this with `__modifier` declarations (`ModifierDecl`) used to introduce some GLSL-specific keywords (so that they wouldn't pollute the namespace of HLSL files).
The new approach changes these to be actual `syntax` declarations (`SyntaxDecl`) with the same representation as those used to introduce declaration keywords.
Because many modifiers just introduce a single keyword that maps to a simple …

Data-driven parsing of modifiers

---

source/slang/parameter-binding.cpp
tests/rewriter/gh-160.hlsl
tests/rewriter/gh-160.slang

Fixes #160
If the front-end runs into a type it doesn't understand in the parameter list of an entry point, it will create an `ErrorType` for that parameter, but then the parameter binding/layout rules will fail to create a `TypeLayout` for the prameter (and return `NULL`).
There were some places where the code was expecting that operation to succeed unconditionally, and so would crash when there was a bad type.
The specific case in the bug report was when the return type of a shader entry point was bad:
// `vec4` is not an HLSL type
vec4 main(...) { ... }
Note that the specific case in the buf report only manifests in "rewriter" mode (when the Slang compiler isn't allowed to issue error messages from the front-end), but the same basic thing would happen if the varying parameter/output …

Handle possibility of bad types in varying input/output signature.

---

source/slang/diagnostic-defs.h
source/slang/diagnostics.cpp
source/slang/parameter-binding.cpp
source/slangc/main.cpp
tests/diagnostics/gh-38-fs.hlsl
tests/diagnostics/gh-38-vs.hlsl
tests/diagnostics/gh-38-vs.hlsl.expected

Closes #38
- Change overlapping bindings case from error to warning (it is *technically* allowed in HLSL/GLSL)
- Make diagnostic messages for these cases include a note to point at the "other" declaration in each case, so that user can more easily isolate the problem
- Unrelated fix: make sure `slangc` sets up its diagnostic callback *before* parsing command-line options so that error messages output during options parsing will be visible
- Unrelated fix: make sure that formatting for diagnostic messages doesn't print diagnostic ID for notes (all have IDs < 0).
- Note: eventually I'd like to not print diagnostic IDs at all (I think they are cluttering up our output), but doing that requires touching all the test cases...

Improve diagnostics for overlapping/conflicting bindings

---

source/slang/ir.cpp
source/slang/ir.h
source/slang/lower-to-ir.cpp
source/slang/lower-to-ir.h
source/slang/slang.vcxproj
source/slang/slang.vcxproj.filters
source/slang/visitor.h

Right now none of this is hooked up, but I want to get things checked in incrementally rather than have along long-lived branches.
- Added placeholder declarations for IR representation of instructions, basic blocks, etc.
- Start adding a `lower-to-ir` pass to translate from AST representation to IR
Again: none of this is functional, so it shouldn't mess with existing users of the compiler.

Starting to add intermediate representation (IR)

---

source/slang/slang.cpp

The Slang API allows an expert user to feed in source code that the compiler then treats as if it came from the Slang "standard library."
They can use this to introduce new builtin types, functions, etc. - so long as they are careful, and are willing to deal with the lack of any compatibility guarantees across versions.
At some point I split the Slang standard library into distinct modules, so that GLSL and HLSL builtins wouldn't pollute each other's namespace.
In that change, I had to decide what module any new user-defined builtins should get added to, and I apparently decided they should go into the module for the Slang language, which would only affect `.slang` files.
This doesn't work at all if the user wants to declare new HLSL builtins.
I've gone ahead and made user extensions add …

Add user-defined builtins to the "core" module

---

slang.h
source/slang/lower.cpp
source/slang/options.cpp
tests/rewriter/type-splitting.hlsl
tests/rewriter/type-splitting.slang

The `-split-mixed-types` flag can be provided to command-line `slangc`, and the `SLANG_COMPILE_FLAG_SPLIT_MIXED_TYPE` flag can be passed to `spSetCompileFlags`.
Either of these turns on a mode where Slang will split types that included both resource and non-resource fields.
The declaration of such a type will just drop the resource fields, while a variable declare using such a type turns into multiple declararations: one for the non-resource fields, and then one for each resource field (recursively).
This behavior was already implemented for GLSL support, and this change just adds a flag so that the user can turn it on unconditionally.
Caveats:
- This does not apply in "full rewriter" mode, which is what happens if the user doesn't use any `import`s. I could try to fix that, but it seems …

Add a flag to control type splitting

---

source/core/hash.h
source/slang/emit.cpp
source/slang/ir.cpp
source/slang/ir.h
source/slang/lower-to-ir.cpp

- Make all instructions store their argument count for now, so we can iterate over them easily.
- Longer term we might try to optimize for space because the common case is that the operand count is known, but keeping it simpler seems better for now
- Split apart the creation of an instruction from adding it to a parent
- Use the above capability to make sure that we add a function to its parent *after* all the parameter/result type emission has occured.
- Perform simple value numbering for types during IR creation
- This logic also tries to pick a good parent for any type instructions, so that types don't get created local to a function unless they really need to
- Create all constants at global scope, and re-use when values are identical

IR generation cleanup work

---

source/slang/emit.cpp
source/slang/ir-inst-defs.h
source/slang/ir.cpp
source/slang/ir.h
source/slang/lower-to-ir.cpp
source/slang/slang.vcxproj
source/slang/slang.vcxproj.filters

- Change IR instructions to just hold an integer opcode instead of a pointer to the "info" structure
- Externalize definition of IR instructions to a header file, and use the "X macro" approach to allow generating different definitions
- Add notion of function types to the IR, so that we can easily query the result type of a function
- Add some convenience accesors to allow walking the IR in a strongly-typed manner (e.g., iterate over the parameters of a function)
- TODO: these should really be changed to assert the type of things, as least in debug builds
- Add very basic logic to `emit.cpp` so  that it can walk the generated IR and start printing it back as HLSL
- This isn't meant to be usable as-is, but it is a step toward where we need to go

Add some dummy logic to print IR to HLSL

---

source/slang/lower.cpp
source/slang/parser.cpp
tests/bugs/gh-171.slang
tests/bugs/gh-172.slang
tools/slang-test/main.cpp

Fixes #171
Fixes #172
These two bugs related to bad logic in handling of splitting resource-containing `cbuffer` declarations.
- Issue #171 was the case where a `cbuffer` *only* had resource fields, in which case we crashed whenever referencing any field (some code was assuming there had to be non-resource fields)
- Issue #172 was a case where two fields were declared with a single declaration (`Texture2D a, b;`), and the logic we had for tracking resource-type fields was accidentally tagging *both* fields with a single modifier so that field `b` would get confused for `a` in some contexts, and attempts to access `b` would crash.
Both issues are now fixed, and regression tests have been added.

Fix some resources-in-structs bugs

---

source/core/smart-pointer.h
source/slang/lower.cpp
source/slang/slang.cpp

The root of the problem here is that:
- We do a shallow copy of modifiers when "lowering" declarations/statements, by just copying over the head pointer of the linked list of modifiers
- During lowering we sometimes add additional modifiers (only used during lowering), and these can thus accidentally get added to the end of the list of modifiers for the original declaration (rather than just the lowered decl)
- If the same declaration is used by multiple entry points to be output, then a modifier added by the first entry point (which could reference entry-point-specific storage) will be earlier in the modifier list and might be picked up by a later entry point, so that we dereference already released memory
The simple fix for right now is the use the support for a "shared" modifier node …

Fix some issues around cloned modifiers.

---

source/slang/check.cpp
source/slang/emit.cpp
source/slang/expr-defs.h
source/slang/lower.cpp
source/slang/modifier-defs.h
source/slang/parser.cpp
source/slang/slang-stdlib.cpp
source/slang/syntax-base-defs.h
source/slang/syntax.cpp
source/slang/syntax.h
tests/hlsl/simple/implicit_conversion.hlsl

- Previously, there were a variety of rules in `check.cpp` to pick the conversion cost for various cases involving scalar, vector, and matrix types.
- The main problem of the previous approach is that any lowering pass would need to convert an arbitrary "type cast" node into the right low-level operation(s).
- The new approach is that a type conversion (implicit or explicit) always resolves as a call to a constructor/initializer for the destination type. This means that the existing rules around marking operations as builtins should work for lowering.
- The support this, the checking logic needs to perform lookup of intializers/constructors when asked to perform conversion between types. It does this by re-using the existing logic for lookup and overload resolution if/when a type was …

Move implicit conversion operations to stdlib

---

slang.h
source/slang/emit.cpp
source/slang/intrinsic-defs.h
source/slang/ir-inst-defs.h
source/slang/ir.cpp
source/slang/ir.h
source/slang/lower-to-ir.cpp
source/slang/modifier-defs.h
source/slang/options.cpp
source/slang/parser.cpp
source/slang/slang-stdlib.cpp
tests/bindings/binding0.hlsl

This gets us far enough that we can convert a single test case to use the IR, under the new `-use-ir` flag.
Getting this merged into mainline will at least ensure that we keep the IR path working in a minimal fashion, even when we have to add functionality the existing AST-based path
There is definitely some clutter here from keeping both IR-based and AST-based translation around, but I don't want to have a long-lived branch for the IR that gets further and further away from the `master` branch that is actually getting used and tested.
Summary of changes:
- Add pointer types and basic `load` operation to be able to handle variable declarations
- Add basic `call` instruction type
- Add simple address math for field reference in l-value
- Always add IR for referenced decls to global scope
- …

Continue work on IR-based codegen

---

source/slang/emit.cpp
source/slang/type-layout.cpp
source/slang/type-layout.h
tests/hlsl/dxsdk/AdaptiveTessellationCS40/Render.hlsl

I had expected this to be the first case where control-flow instructions were needed, but it turns out that we aren't testing that entry point right now.
The real work/fix here ended up being handling of the `row_major` layout qualifier on a matrix inside a `cbuffer`. The existing AST-based code was passing it through easily (although I don't believe it was handling the layout rules right).
Getting it working in the IR involved beefing up the type-layout behavior so that it can handle explicit layout qualifiers (at least for matrix layout) which should also improve the layout computation for non-square matrices with nonstandard layout in the AST-based path.
There are still some annoying things left to do:
- The `row_major` and `column_major` layout qualifiers in HLSL/GLSL mean different …

Get IR working for `AdaptiveTessellationCS40/Render` test

---

slang.h
source/core/slang-string.cpp
source/core/slang-string.h
source/slang/compiler.cpp
source/slang/compiler.h
source/slang/emit.cpp
source/slang/hlsl.meta.slang
source/slang/hlsl.meta.slang.cpp
source/slang/ir-inst-defs.h
source/slang/ir-insts.h
source/slang/ir.cpp
source/slang/ir.h
source/slang/lower-to-ir.cpp
source/slang/options.cpp
source/slang/profile-defs.h
source/slang/slang.vcxproj
source/slang/slang.vcxproj.filters
source/slang/type-layout.cpp
tests/ir/loop.slang
tests/ir/loop.slang.expected

This change includes a bunch of fixes and additions to the IR path:
- `slang-ir-assembly` is now a valid output target (so we can use it for testing)
- This uses what used to be the IR "dumping" logic, revamped to support much prettier output.
- A future change will need to add back support for less prettified output to use when actually debugging
- IR generation for `for` loops and `if` statements is supported
- HLSL output from the above control flow constructs is implemented
- Revamped the handling of l-values, and in particular work on compound ops like `+=`
- Add basic IR support for `groupshared` variables
- Add basic IR support for storing compute thread-group size
- Output semantics on entry point parameters
- This uses the AST structures to find semantics, so its still needs work …

IR: handle control flow constructs

---

tests/render/render0.hlsl
tools/render-test/render-d3d11.cpp

This should in principle allow for the D3D-only tests to run on AppVeyor so that we can validate running things for CI purposes (and is probably a whole lot easier than trying to plug the VM up to the rendering tests).
I've switched up one of the tests so that it should run even on AppVeyor, so fingers crossed that it will actually run.

Use WARP for D3D rendering tests.

---

examples/hello/hello.vcxproj
slang.h
source/slang/core.meta.slang
source/slang/core.meta.slang.cpp
source/slang/emit.cpp
source/slang/ir-inst-defs.h
source/slang/ir-insts.h
source/slang/ir.cpp
source/slang/ir.h
source/slang/lower-to-ir.cpp
source/slang/mangle.cpp
source/slang/mangle.h
source/slang/slang.vcxproj
source/slang/slang.vcxproj.filters
tests/ir/loop.slang.expected
tools/render-test/render-test.vcxproj
tools/render-test/slang-support.cpp

None of these changes are made "live" at the moment. I'm just trying to get them checked in to avoid divering too far from `master` at any point during development.
- Add basic emit logic to produce GLSL from the IR in a few cases (the existing IR emit logic was ad hoc and HLSL-specific)
- When lowering a function declaration, walk up its chain of parent declarations to collect additional parameters as needed
- When lowering a call, make sure to add generic arguments that come from the declaration reference being called
- Attach a "mangled name" to symbols when lowering, so that we can eventually use that name to resolve things for linkage.
- After the above work, I had to apply some fixups to make sure that generic arguments *don't* get added when the user is calling an `__intrinsic_op` …

More work on IR-based lowering and cross-compilation

---

.travis.yml
Makefile
README.md
source/core/platform.cpp
source/core/slang-string.cpp
source/slang-glslang/slang-glslang.cpp
source/slang-glslang/slang-glslang.h
source/slang/slang.cpp
tests/reflection/arrays.hlsl
tests/reflection/gh-55.glsl
tests/reflection/global-uniforms.hlsl
tests/reflection/image-types.glsl
tests/reflection/multi-file.hlsl
tests/reflection/reflect-imported-code.hlsl
tests/reflection/reflection0.hlsl
tests/reflection/resource-in-cbuffer.hlsl
tests/reflection/std430-layout.glsl
tests/reflection/thread-group-size.comp
tests/reflection/thread-group-size.hlsl
tools/slang-test/main.cpp
tools/slang-test/os.cpp
tools/slang-test/os.h

- Fix up `dlopen` abstraction
- Fix up some test cases to request hlsl (rather than default to dxbc) so they can run on non-Windows targets
- Fix up test runner ignore tests that can't run on current platform (and not count those as failure)
- Fix file handle leeak in process spawner absttraction
- Get additional test-related applications building
- More tweaks to Travis script; in theory deployment is set up now (yeah, right)

Get tests running/passing under Linux

---

source/core/slang-string.h
source/slang/bytecode.cpp
source/slang/emit.cpp
source/slang/ir-insts.h
source/slang/ir.cpp
source/slang/ir.h
source/slang/lower-to-ir.cpp
tests/render/render0.hlsl
tools/slang-test/main.cpp

When outputting GLSL from a Slang or HLSL entry point, we need to translate any parameters or results of an entry-point function into global declarations of `in` or `out` parameters, as needed by GLSL.
This change adds these transformations at the IR level, so that they don't need to complicate the emit logic.
More detailed changes:
- Make `render0` test use IR. It passes out of the box.
- Fix test runner to not always dump diffs on failures
I accidentally initialized an option to `true` instead of `false` when working on debugging the Travis CI failures.
- Special-case output for component-wise multiplication to handle GLSL `matrixCompMul()`
- Handle GLSL vs. HLSL output for calls to `mul()`
- Output proper `layout(std140)` on GLSL constant buffer declarations
- Require appropriate GLSL …

Perform some transformations on IR to legalize for GLSL

---

source/slang/parser.cpp
tests/parser/cast-precedence.hlsl

We were accidentally parsing this:
(uint) a / b
as this:
(uint) ( a / b )
when it should be:
((uint) a) / b
This is a bug that seems to have been inherited from a long time ago. It has taken a while to bite anybody because the only class of expressions it would hit are multiplicative ones, and in many cases the difference in the cast order won't be noticed for values in a limited range.

Parser: fix precedence of cast expressions

---

source/slang/preprocessor.cpp
tests/preprocessor/define-redefine.slang
tests/preprocessor/define-redefine.slang.expected
tests/preprocessor/undef.slang
tests/preprocessor/undef.slang.expected

The logic for `undef` directives was failing to suppress macro expansion when reading the name to un-define, and so it wasn't actually working at all. We didn't notice this because we didn't have a test case, and users hadn't tried it.
The logic for `define` had a similar bug, which meant that any attempt to define an already-defined macro would fail with a cryptic error, rather than raising the intended warning.
Test cases have been added for both issues, along with the fixes.

Preprocessor: fix `undef` and redefinition

---

source/slang/emit.cpp
tests/bugs/cbuffer-member-init.hlsl

Given an input declaration like:
cbuffer C
{
int a = -1;
}
Slang was automatically generating a `packoffset` semantic to place the member manually, but was emitting it *after* the initializer of the original declaration:
cbuffer C : register(b)
{
int a = -1 : packoffset(c0);
}
That syntax is invalid, of course, and we actually want:
cbuffer C : register(b)
{
int a : packoffset(c0) = -1;
}
This wasn't spotted earlier because putting initializers on a `cbuffer` member is not commonly done, since it requires reading those values via the reflection API. Slang's reflection API currently provides no way to access default values like this, so they aren't of much use yet. Still, it is better to emit correct syntax even in cases like this one.

Fix emit logic for `cbuffer` member with initializer

---

source/slang/slang.cpp

This is intended to produce a better experience for end users when they encounter internal compiler errors.

Fixup: re-enable exception guard

---

slang.h
source/slang/compiler.cpp
source/slang/compiler.h
source/slang/emit.cpp
source/slang/ir-insts.h
source/slang/ir.cpp
source/slang/lower-to-ir.cpp
source/slang/lower.cpp
source/slang/options.cpp
source/slang/slang.cpp
source/slang/syntax.cpp
source/slang/type-defs.h
source/slang/type-layout.cpp
tests/ir/loop.slang
tests/ir/loop.slang.expected

This is really only useful for debugging, so I've replaced the functionality with a `-dump-ir` command line option (which dump's the IR for an entry point before doing codegen).

Get rid of the `-slang-ir-asm` target

---

slang.h
source/slang/lower.cpp
source/slang/parameter-binding.cpp
source/slang/reflection.cpp
source/slang/type-layout.h
tests/reflection/thread-group-size.hlsl.expected
tests/reflection/vertex-input-semantics.hlsl
tests/reflection/vertex-input-semantics.hlsl.expected
tools/slang-reflection-test/main.cpp

This is functionality required to support a Falcor bug fix.
Most of the code to compute the right semantic name/index for a parameter was already present.
This change adds:
- Storage for semantic name/index on every `VarLayout`
- Note: this is wasteful and should be optimized later
- A public API to query the semantic name/index
- The contract is that this API returns `NULL` if the parameter had no semantic
- A bit of work in `parameter-binding.cpp` to attach semantics to varying input/output when traversing varying parameters.
- Note: this is intentionally set up so that it associates semantics even with non-leaf parameters, so that an API user can query the semantic of a `struct` parameter and know that its members will be assigned sequential semantic indices from its starting value.
- …

Reflection: allow querying of semantics on varying input/output

---

source/slang/glsl.meta.slang
source/slang/glsl.meta.slang.h
tests/bugs/matrix-mult.glsl
tests/cross-compile/matrix-mult.slang
tests/cross-compile/matrix-mult.slang.glsl

When Slang sees a matrix multiplication `M * v` in GLSL code it should (obviously) output GLSL code that also does `M * v`, but there was a bug introduced where the type-checker manages to resolve the operation and recognize it as a matrix-vector multiply, and then the code-generation logic says "oh, I'm generating output for GLSL, and that is reversed from HLSL/Slang, so I'd better reverse these operands!" and outputs `v * M`... which isn't what we want.
I've fixed the problem in an expedient way, by having the front-end resolve the operation to what it believes is an intrinsic multiply operation, rather than a matrix-vector operation. If we ever support cross compilation *from* GLSL (unlikely), we've need to fix this up so that we have both real matrix-vector multiplies and "reversed" …

Fix output for matrix multiple in GLSL code

---

source/slang/emit.cpp

Fixes #237
There were some cases where we would try to emit an `ErrorType` to the output HLSL, which obviously isn't allowed. This change tries to avoid emitting error types, and instead use the original expression when it is available.
I tried adding a test case for the change, but I can't convince Slang to output matching line numbers for the error message; it seems like more work is needed on that front.

Fix output for type cast when checking fails

---

external/dxc/dxcapi.h
slang.h
source/slang/compiler.cpp
source/slang/compiler.h
source/slang/dxc-support.cpp
source/slang/options.cpp
source/slang/profile-defs.h
source/slang/slang.vcxproj
source/slang/slang.vcxproj.filters
source/slang/type-layout.cpp

- Add shader model 6.0, 6.1, and 6.2 targets
- Add DXIL and DXIL assembly as output formats
- Add header for DXC API to `external/`
- Add `dxc-support.cpp` that wraps usage of the API
- Add `-pass-through dxc` option, equivalent to what we have for `fxc`
Notes:
* This does *not* include any logic to add `dxcompiler.dll` to our build process; that is way out of scope for the build complexity I'm ready to deal with
* For right now, the use of `dxcompiler.dll` is hard-coded, and it must be discoverable in the current executable's search path; options to customize can come later
* The `-pass-through` option is kind of silly because the code doesn't actually pay attention to the value (just whether it is set). If you set it to `fxc` but ask for DXIL, we pass through `dxc` anyway.

Allow use of dxc compiler for DXIL generation

---

source/slang/check.cpp
source/slang/syntax.cpp

Add a `GenericValueParamDecl` case in `doesGenericSignatureMatchRequirement()`
Return a substituted `DeclaredSubtypeWitness` in `DeclaredSubtypeWitness::SubstituteImpl()` instead of return this.
Need more work in `DeclaredSubtypeWitness::SubstituteImpl` to properly implement substitution of the `DeclaredSubTypeWitness` val into an actual` IRWitnessTable` argument value that comes from a GenericSubstitution.

Cleanup of "support generic interface method".

---

source/slang/emit.cpp
source/slang/ir-inst-defs.h
source/slang/ir-insts.h
source/slang/ir.cpp
source/slang/lower-to-ir.cpp
source/slang/mangle.cpp
tests/ir/loop.slang.expected

- Change function mangling so we use `p<parameterCount>p` instead of just `p<parameterCount>` to avoid the parameter count running into digits at the start of a mangled type name and tripping up the un-mangling logic.
- We really need to step back at some point and define our mangling scheme a bit more carefully, especially if we are going to keep going down this road where un-mangling things is important for generating HLSL output.
- Also allow the unmangling logic to unmangle a few more cases of generic parameters, so that it can skip over them to get to the parameter count of the underlying function.
- Add a notion of an `unreachable` instruction to the IR, and emit it as the terminator (if needed) at the end of the last block for a function with a non-void return type.
- This does …

Various IR fixes for Falcor

---

source/slang/emit.cpp
tests/bugs/gh-295.hlsl

Fixes #295.
The code previously had a white list of attributes that it passed through, implemented in `emit.cpp` in an ad hoc fashion. The fix here is to just pass through whatever attributes the user wrote, and then let the downstream compiler diagnose if any of them are errorneous.

Fix emitting of loop attributes for HLSL pass-through

---

source/slang/ir.cpp
source/slang/syntax.cpp
source/slang/syntax.h

This PR fixes the ad-hoc handling of global-generic-type substitutions introduced in #293.
1. Add a new function:
`substituteSubstitutions(Substitutions * substHead, Substitutions subst, int * ioDiff)`
This function substitutes the type arguments referenced in a linked list of substitutions headed at `substHead` using the substitutions specified by `subst`. If the linked list `substHead` does not contain `GlobalGenericParamSubstitution` entries, they will be added to the bottom (outter most) of the linked list.
Note that this function should be called when `substHead` is known to be the head of substitution linked list because the existance of `GlobalGenericPaaramSubstitution` is detected assuming the linked lists starts at `substHead`. If a substitution that is not the head of a …

Fix substitution mechanism to remove special cases for global params

---

source/slang/ast-legalize.cpp
source/slang/check.cpp
source/slang/compiler.h
source/slang/ir.cpp
source/slang/lower-to-ir.cpp
source/slang/parameter-binding.cpp
source/slang/slang.cpp

The basic idea here is that for each module that gets loaded via `import`, we should also generate the initial IR for the declarations in that module at the time it gets loaded.
Furthermore, when we generate initial IR for a module, we will only generate IR *declarations* (not *definitions*) for any functions/variables in modules it imports.
Later, when cloning IR to begin code generation for an entry point, we will effectively "link" all of the loadedm modules together, so that a given global value can get its definition from any of the IR modules present.
- Change the `loadedModulesList` and related data structures to hold a new `LoadedModule` type, instead of just the AST (and then have a `LoadedModule` own both the AST and the IR module)
- Share some logic between the `import` and …

Generate IR per-module for loaded modules

---

slang.h
source/slang/ast-legalize.cpp
source/slang/ir-legalize-types.cpp
source/slang/parameter-binding.cpp
source/slang/reflection.cpp
source/slang/type-layout.h
tests/reflection/sample-rate-input.glsl.expected
tests/reflection/vertex-input-semantics.hlsl.expected
tools/slang-reflection-test/main.cpp

Fixes #301
The problem here is that if you have input GLSL code like:
```glsl
// example.vs
in vec3 pos;
```
and:
```glsl
// example.fs
in vec3 worldPos;
```
Then both `pos` and `worldPos` are reflected as global variables (parameters of the *program*), which both get bound to "varying input" resources, but there is no way to tell through the API that `pos` is a vertex parameter while `worldPos` is a fragment one.
The original request in issue #301 was to expose parameters like this not as a global variables, but rather as parameters of the entry point in their specific file. That is, treat it as if the user had written, e.g.:
```glsl
// example.vs
void vsMain(in vec3 pos) { ... }
```
Doing that would unify the GLSL and HLSL/Slang cases a bit, but would require the Slang reflection API to …

Add API to query stage of varying parameter

---

slang.h
source/slang/ast-legalize.cpp
source/slang/emit.cpp
source/slang/legalize-types.cpp
source/slang/reflection.cpp
source/slang/type-layout.cpp
source/slang/type-layout.h
tests/reflection/resource-in-cbuffer.hlsl.expected

Fixes #307
This ends up being a major overhaul over how type layout computation is structured and exposed.
The big problems all arise around cases where both the "container" for a parameter block or CB, and the "element" type both use the same kind of resource.
E.g., if you define a CB with a texture in it, then in Vulkan both the CB and the texture use the same kind of resource, and so if you query the CB's resource usage it will just tell you it uses two descriptor-table slots, but nothing more than that.
Similar confusion still arises in the HLSL case, when a CB with a texture in it reports its parameter category as "mixed" so that a user might query for a category they didn't mean to. There were also cases in the existing code where a parameter block might expose *both* a …

Fix parameter block binding for Vulkan

---

source/slang/emit.cpp
source/slang/reflection.cpp
source/slang/type-layout.cpp
source/slang/type-layout.h
tests/bindings/glsl-parameter-blocks.slang
tests/bindings/glsl-parameter-blocks.slang.glsl

I'm adding a small cross-compilation test to try to make sure that we are testing the binding generation for GLSL output. We probably still need a more complex test that uses multiple blocks, plus variables not in a block.
The big changes here are:
- Change the `containerTypeLayout` field to a `containerVarLayout` in the `ParameterGroupTypeLayout`, so that we can store the base offsets for the fields in a uniform fashion (even though these will all be zero).
- Switch the emit logic to carefully use either the container or element var layout depending on what they are emitting bindings for. This involved adding something akin to the "reflection path" notion that Falcor has to use, but only for the emit step.

More fixups for Vulkan parameter block bindings

---

source/slang/parameter-binding.cpp
source/slang/reflection.cpp
tests/bindings/glsl-parameter-blocks.slang.glsl
tests/reflection/parameter-block.slang
tests/reflection/parameter-block.slang.expected
tests/reflection/thread-group-size.comp.expected
tests/reflection/thread-group-size.hlsl.expected
tools/slang-reflection-test/main.cpp

The bug in this case arises when there is both a parameter block and global-scope resources, all of which are relying on automatic binding assignment. If the parameter block is the first global-scope parameter that gets encountered, then it is possible for it to allocate regsiter space/set zero for itself, which confuses the logic for handling other global-scope parameters (which assumes that *they* get space/set zero).
I've also made some fixup to the reflection test harness and reflection API code:
- Have the hardness handle register-space allocations when printing, and be sure to only show their `index` and not their `space` (since that would be redundant)
- Have the reflection API only auto-redirect queries on a parameter group type layout to its container type layout *if* the …

More fixups for parameter block binding generation

---

source/slang/parameter-binding.cpp
tests/reflection/sample-index-input.hlsl
tests/reflection/sample-index-input.hlsl.expected
tests/reflection/sample-rate-input.hlsl
tests/reflection/sample-rate-input.hlsl.expected

In the HLSL case, it is possible to do this detection entirely based on declared signatures (it doesn't have a dependency on code generation like the GLSL case does). I've added test cases for the two main ways that a shader can become sample rate:
1. Qualify a fragment input with `sample`
2. Accept an input with the `SV_SampleIndex` semantic
In each case I nested the input inside a `struct` to try to match common HLSL idiom, and to make sure that we handle the nested case.
This code is *not* robust against shaders that declare such an input and then never use it, but that is to be expected given the goals for Slang.

Add sample-rate-input detection for HLSL.

---

source/slang/ast-legalize.cpp
tests/bugs/gh-333.slang

Fixes #333
The code in `ast-legalize` is passed an array of declarations that have been ordered by dependencies using a topological sort. Unfortunately, it was only using that list in the case where the request was considered to be a "rewrite" request, and would otherwise rely on the order in which things get forced during the recursive walk (which doesn't really work for our needs).

Always respect dependency order when lowering decls via AST

---

source/slang/diagnostics.cpp
source/slang/source-loc.cpp
source/slang/source-loc.h

Fixes #345
A brief refresher: a `SourceLoc` in the Slang implementation is just an integer (more or less an absolute byte index into all of the source compiled so far). We convert that integer to a "humane" source location (a file name and line/column numbers) by finding the file and line that match the integer via binary search. The data structures used for that search are owned by a `SourceManager`.
In order to avoid running out of source locations when used in a long-running application (that might reload shaders many times), the implementation creates one `SourceManager` per `CompileRequest`, along with a single shared `SourceManager` that is used for locations in the builtin libraries.
The root of the bug here was that some code was using the `SourceManager` for a compile request …

Bug fix for humane source location computation.

---

source/slang/emit.cpp
source/slang/slang.vcxproj
source/slang/slang.vcxproj.filters

This PR includes yet another fix to the output `struct` declaration order (this time in the IR + rewriter case, rather than the ordinary rewriter-only case), and then a small debugging fix to help make our lives easier.

Fix struct decl order again

---

source/slang/type-layout.cpp
source/slang/type-layout.h
tests/bindings/array-of-struct-of-resource.hlsl

Should fix #351
The basic problem is that the type layout logic in Slang isn't taking into account the way that resource-type fields in aggregate types get split. When you just have a bare aggregate, this oversight doesn't cause a problem, but once you put those aggregates into an array, the problems become clear.
Given:
```hlsl
struct Test
{
Texture2D a;
Texture2D b;
};
Test test[8];
```
The default type-layout algorithm gives `Test::a` an offset of zero, and `Test::b` an offset of one.
However, after splitting, we have something like:
```hlsl
Texture2D test_a[8];
Texture2D test_b[8];
```
It is clear in this case that `test_b` can't start at an offset of one relative to `test_a` - it needs to start at `register(t8)`.
This change handles things by adjusting the layout of an array type to …

Fix bug around arrays of structs of resources

---

slang.h
source/slang/check.cpp
source/slang/compiler.h
source/slang/parameter-binding.cpp
source/slang/reflection.cpp
source/slang/slang.cpp
source/slang/type-layout.h

Added two API functions:
1. `spReflection_FindTypeByName`, which returns a DeclRefType to the struct type with the given name. The function finds from all loaded modules in a `CompileRequest` for a decl with the given name, construct a `Type` object and cache it in `CompileRequest::types` dictionary. The subsequent calls to `spReflection_FindTypeByName` with the same name will simply returned the cached Type objects.
2. `spReflection_GetTypeLayout`, which returns a `TypeLayout` for a given `Type`. This function creates and caches the `TypeLayout` in the `TargetRequest` object that is used to create the `ProgramLayout`.

Add API for querying TypeLayout from a Type

---

source/slang/ast-legalize.cpp
source/slang/check.cpp
source/slang/emit.cpp
source/slang/ir.cpp
source/slang/legalize-types.cpp
source/slang/lower-to-ir.cpp
source/slang/mangle.cpp
source/slang/mangle.h
source/slang/parameter-binding.cpp
source/slang/syntax-base-defs.h
source/slang/syntax.cpp
source/slang/syntax.h
source/slang/type-defs.h
source/slang/val-defs.h

This commit changes the type of `DeclRefBase::substitutions` from `RefPtr<Substitutions>` to `SubstitutionSet`, which is a new type defined as following:
```
struct SubstitutionSet
{
RefPtr<GenericSubstitution> genericSubstitutions;
RefPtr<ThisTypeSubstitution> thisTypeSubstitution;
RefPtr<GlobalGenericParamSubstitution> globalGenParamSubstitutions;
}
```
This change get rid of most helper functions to retreive the substitution of a certain type, as well as surgery operations to insert a `ThisTypeSubstitution` or `GlobalGenericTypeSubstittuion` at top or bottom of the substitution chain. It also simplies type comparison when certain type of substitution should not be considered as part of type definition.

Refactor substitution representation in DeclRefBase

---

source/slang/check.cpp
source/slang/ir.cpp
source/slang/lookup.cpp
source/slang/syntax.cpp
source/slang/syntax.h
source/slang/val-defs.h

1. prevent cyclic lookups when an interface inherits transitively from itself.
2. in `createGlobalGenericParamSubstitution`, create a default substitution for the base type declref before using it to lookup the witness table.

bug fixes to get falcor example shader code to compile.

---

source/slang/check.cpp
source/slang/diagnostic-defs.h
source/slang/slang.cpp
tests/diagnostics/local-used-before-declared.slang
tests/diagnostics/local-used-before-declared.slang.expected
tests/diagnostics/local-used-in-own-declaration.slang
tests/diagnostics/local-used-in-own-declaration.slang.expected

The basic problem here arises when a local variable is used either before its own declaration:
```hlsl
int a = b;
...
int b = 0;
```
or when a local variable is used *in* its own decalration:
```hlsl
int b = b;
```
In each case, Slang considers the scope of the `{}`-enclosed function body (or nested statement) as a whole, and so the lookup can "see" the declaration even if it is later in the same function.
This behavior isn't really correct for HLSL semantics, so the right long-term fix is to change our scoping rules, but for now users really just want the compiler to not crash on code like this, and give an error message that points at the issue.
This change makes both of the above examples print an error message saying that variable `b` was used before its declaration, which is accurate …

Fix some crashing bugs around local variable declarations.

---

source/slang/slang.cpp

The recent change that removed `#import` accidentally introduced a regression that made *any* code that imports the same module in more than one place fail.
I'm just fixing the bug for now to unblock users, but this should really get a regression test.

Fix a bug in import handling

---

README.md
docs/api-users-guide.md
docs/building.md
docs/command-line-slangc.md
docs/language-guide.md
docs/layout.md

- Remove references to building by embedding source (not recommended at this point)
- Push users more toward binary builds rather than building from source (but include a document that talks about how to build)
- Remove most (all?) references to supporting GLSL input
- Expand the language guide to talk about the new features
- Add a document that talks about the parameter layout algorithm

Revamp documentation

---

source/slang/ast-legalize.cpp

The logic was creating a `PairPseudoExpr` as part of a subscript (`operator[]`) operation, but neglecting to fill in its `pairInfo` field, which led to a null-pointer crash further along.

Fix bug when subscripting a type that must be split

---

source/slang/core.meta.slang
source/slang/core.meta.slang.h
source/slang/emit.cpp
source/slang/hlsl.meta.slang
source/slang/hlsl.meta.slang.h
source/slang/ir-insts.h
source/slang/ir.cpp
source/slang/ir.h
source/slang/lower-to-ir.cpp
tests/bindings/glsl-parameter-blocks.slang
tests/bindings/glsl-parameter-blocks.slang.glsl

The standard library already has a bunch of these decorations, since they were added to support Slang->Vulkan codegen on the AST-to-AST path. This change makes the IR code generator able to exploit the modifiers so that we pick up a bunch of Vulkan support "for free" in the short term.
The basic change is in `lower-to-ir.cpp` where we copy over any `TargetIntrinsicModifier`s to become `IRTargetIntrinsicDecoration`s with the same information. We then need a bit of logic in `ir.cpp` to make sure we clone them as needed.
The core work of using the modifiers is in `emit.cpp`, where I basically just copy-pasted the existing logic that applied in the AST path (all the AST-related code there is dead, and we should clean it up soon).
The big change that comes with this logic is that when dealing …

Support __target_intrinsic modifiers in IR codegen

---

slang.h
source/slang/emit.cpp
source/slang/ir-inst-defs.h
source/slang/ir-insts.h
source/slang/ir-ssa.cpp
source/slang/ir-ssa.h
source/slang/ir.cpp
source/slang/ir.h
source/slang/lower-to-ir.cpp
source/slang/slang.vcxproj
source/slang/slang.vcxproj.filters
source/slang/vm.cpp
tests/bindings/glsl-parameter-blocks.slang.glsl
tests/ir/loop.slang.expected

The basic idea here is simple: in the front-end after we have lowered the AST to initial IR we will apply a set of "mandatory" optimization passes. The first of these is to attempt to translate the all functions into SSA form so that they are amenable to subsequent dataflow optimizations. Eventually, the mandatory optimization passes would include diagnostic passes that make sure variables aren't used when undefined, etc.
Just doing basic SSA generation already cleans up a lot of the messiness in our IR today, because constructs that used to involve many local variables can now be handled via SSA temporaries.
The implementation of SSA generation is in `ir-ssa.cpp`, and it follows the approach of Braun et al.'s "Simple and Efficient Construction of Static Single Assignment Form." I used …

Generate SSA form for IR functions

---

source/slang/diagnostic-defs.h
source/slang/ir-legalize-types.cpp
source/slang/legalize-types.cpp
source/slang/legalize-types.h
source/slang/parameter-binding.cpp

The changes in this PR both relate to cases where the user feeds the Slang compiler two distinct translation units (e.g., distinct files for their vertex and fragment shader), which share declarations of some global shader parameters (either by duplicating declarations, or by `#include`ing a common file).
The first change deals with the case where such parameters have the same name, but their types are somehow inconsistent between the declarations. The place where this check should be made was already present in the parameter binding logic, and just wasn't implemented.
The second change tries to make the IR code generator (type legalization in particular) robust in these cases. Previously we would end up dropping type layout information in cases where a shader parameter's layout was based …

Handling of duplicate global shader parameter declarations

---

source/slang/emit.cpp
source/slang/ir-insts.h
source/slang/ir.cpp

The approach here isn't ideal. We already have a pass that transforms HLSL varying input/output types into GLSL global variables. This change makes it so that when those inputs/outputs have system-value semantics, we generate a global variable declaration with the appropriate `gl_*` name (leaving the type the same for now). Later, when emitting code, we just skip emitting declarations for declarations with mangled names that start with `gl_*`.
A more complete implementation will be needed later on, which handles cases where the translation requires types to be changed (so that conversion code needs to be inserted).

Implement IR-level translation of system values for GLSL

---

source/slang/core.meta.slang
source/slang/core.meta.slang.h
source/slang/emit.cpp
source/slang/hlsl.meta.slang
source/slang/hlsl.meta.slang.h

- Make sure to emit `image*` instead of `texture*` for `RWTexture*` types
- Change `GetDimensions` to call `imageSize` instead of `textureSize` when we use images
- Always output a `layout(rgba32f)` for variables that translate to `image` types
- TODO: we should emit an appropriate format based on the type, or let the user specify one
- Fix GLSL translation for `any()` function (required boolean inputs)
- Add GLSL translation for `GroupMemoryBarrierWithGroupSync()`
- Map HLSL `groupshared` to GLSL `shared`
These together are enough to get the Falor `ComputeShader` example to work.

stdlib fixes for Vulkan

---

source/slang/core.meta.slang
source/slang/core.meta.slang.h
source/slang/hlsl.meta.slang
source/slang/hlsl.meta.slang.h
tests/front-end/uav-write.slang

Work on #415
This issue is already fixed in the `v0.10.*` line, but I'm back-porting the fix to `v0.9.*`.
The issue here was that the stdlib declarations for texture types were only including the `get` accessor for subscript operations, even if the texture was write-able.
I've also included the fixes for other subscript accessors in the stdlib (notably that `OutputPatch<T>` is readable, but not writable, despite what the name seems to imply).

Allow writes to UAV textures

---

slang.h
source/core/smart-pointer.h
source/slang/compiler.h
source/slang/emit.cpp
source/slang/ir-insts.h
source/slang/ir.cpp
source/slang/ir.h
source/slang/lower-to-ir.cpp
source/slang/memory_pool.cpp
source/slang/memory_pool.h
source/slang/slang.cpp
source/slang/slang.vcxproj
source/slang/slang.vcxproj.filters
source/slang/syntax-base-defs.h
source/slang/syntax.cpp
source/slang/type-defs.h
tools/render-test/slang-support.cpp

1. make IRModule class own a memory pool for all IR object allocations
2. For now, we allow IR objects to own other (externally) heap allocated objects, such as String, List and RefPtrs by tracking all IR objects that  has been allocated for the IRModule in a list named `IRModule::irObjectsToFree`. and call destructor for all these objects upon the destruction of the IRModule. In the long term, we should eliminate the use of all these externally allocated types in IR system and get rid of this tracking and explicit destructor calls.
3. remove non-generic `createValueImpl` functions and retain only generic versions in IRBulider so we can properly call the constructor of the IR types to set up virtual tables correctly for destructor dispatching.
4. add `MemoryPool` class for allocation of …

Fix IR memory leaks.

---

source/slang/compiler.h
source/slang/emit.cpp
source/slang/ir-insts.h
source/slang/ir-legalize-types.cpp
source/slang/ir.cpp
source/slang/ir.h
source/slang/legalize-types.h
source/slang/lower-to-ir.cpp

This allows us to get rid of `IRGlobalValue::dispose()`.

Make `IRGlobalValue::mangledName` a `Name*`

---

source/slang/parser.cpp
tests/diagnostics/missing-semicolon-after-semantic.slang
tests/diagnostics/missing-semicolon-after-semantic.slang.expected

The code for parsing semantics was looking for a fixed set of tokens to terminate a semantic list, rather than assuming that whenever you don't see a `:` ahead, you probably are done with semantics. This meant that you could get into an infinite loop just with simple mistakes like leaving out a `;`.
This change fixes the parser to note infinite loop in this case, and adds a test case to verify the fix.

Fix infinite loop in semantic parsing

---

slang.h
source/slang/core.meta.slang
source/slang/core.meta.slang.h
source/slang/emit.cpp
source/slang/glsl.meta.slang
source/slang/glsl.meta.slang.h
source/slang/hlsl.meta.slang
source/slang/hlsl.meta.slang.h
source/slang/slang.vcxproj
source/slang/slang.vcxproj.filters
source/slang/syntax.cpp
source/slang/syntax.h
source/slang/type-defs.h
source/slang/type-system-shared.cpp
source/slang/type-system-shared.h

Pull BaseType, TextureFlavor and SamplerStateFlavor enums and helper functions into a shared file "type-system-shared.h", so that they can be used by both the front-end and IR type systems.

Refactor IR type system, step 0

---

source/slang/syntax.cpp

The code in `DeclRefType::Create` was treating all of the point/line/triangle output stream types as `HLSLPointStreamType`, which meant we always output GLSL geometry shaders with `layout(points) out;`.

Fix GS stream types

---

source/slang/bytecode.cpp
source/slang/emit.cpp
source/slang/ir-constexpr.cpp
source/slang/ir-inst-defs.h
source/slang/ir-insts.h
source/slang/ir-legalize-types.cpp
source/slang/ir-ssa.cpp
source/slang/ir.cpp
source/slang/ir.h
source/slang/legalize-types.h
source/slang/lower-to-ir.cpp
source/slang/slang.natvis
source/slang/syntax.h

This change tries to streamline the representation of the IR in the following ways:
* Every IR value is an instruction (there is no `IRValue` type any more)
* All IR values that can contain other values share a single base (`IRParentInstruction`)
* Dynamic casts to specific IR instruction types can be accomplished with a new `as<Type>(inst)` operation, that uses the IR opcode to implement casts.
The biggest change in terms of number of lines is getting rid of `IRValue`. The diff here could probably be smaller if I'd just done `typedef IRInst IRValue;`.
Along the way I also renamed the `getArg`/`getArgs`/`getArgCount` combination over to `getOperand`/`getOperands`/`getOperandCount` to avoid being confusing when we have something like a `call` instruction where the "arguments" of the call …

IR: "everything is an instruction"

---

slang.h
source/slang/compiler.h
source/slang/diagnostic-defs.h
source/slang/diagnostics.cpp
source/slang/diagnostics.h
source/slang/emit.cpp
source/slang/ir-constexpr.cpp
source/slang/ir-inst-defs.h
source/slang/ir-insts.h
source/slang/ir-legalize-types.cpp
source/slang/ir-ssa.cpp
source/slang/ir-validate.cpp
source/slang/ir-validate.h
source/slang/ir.cpp
source/slang/ir.h
source/slang/lower-to-ir.cpp
source/slang/options.cpp
source/slang/slang.natvis
source/slang/slang.vcxproj
source/slang/slang.vcxproj.filters
tests/ir/loop.slang.expected

The main practical change here is that things that used to be `IRValue`s, like literals, are now being expressed as instructions in the global scope.
In order to validate that things are actually being handled correctly, this change introduces an explicit "validation" pass that can be run on the IR to check for different invariants (although it doesn't check many of the important ones right now). I've left the validation pass turned off by default, but with a command-line flag to enable it. We may want to make it be on by default in debug builds, just to keep us honest. The main invariant for the moment is that when on IR instruction is used as an operand to another, it had better come from the same IR module.
Some of the existing passes were violating this rule, in particular when it …

IR: next phase of "everything is an instruction"

---

source/slang/check.cpp

This is trigered when compiling the following code
```
interface ILight
{
ShadingResult evalLighting<TBxDF:IBxDF>(ShadingPoint<TBxDF> p, float shadowFactor);
}
ShadingResult evalMaterial<TBxDF : IBxDF, TLight : ILight>(ShadingPoint<TBxDF> p, TLight light, float shadowFactor)
{
return light.evalLighting(p, shadowFactor); // trigered when trying to resolve overload here.
}
```

Add a case to `TryUnifyVals` to cover `SubtypeWitness` vals

---

slang.h
source/slang/reflection.cpp
tests/reflection/shared-modifier.hlsl
tests/reflection/shared-modifier.hlsl.expected
tools/slang-reflection-test/main.cpp

This is a request from Falcor, because the `shared` modifier can be used as a hint to optimize the grouping of parameters for binding. The intention is that `shared` marks shader parameters (including parameter blocks) that will us the same values across many draw calls (e.g., per-frame data, as opposed to per-model or per-instance).
The mechanism I'm using here is to provide a general reflection API for exposing the `Modifier`s already attached to declarations. While the only modifier exposed is `shared`, and the only modifier information being exposed is presence/absence, this interface could be extended down the line.

Expose HLSL `shared` modifier through reflection.

---

source/core/slang-string.cpp
source/core/slang-string.h
source/slang/core.meta.slang
source/slang/core.meta.slang.h
source/slang/glsl.meta.slang
source/slang/glsl.meta.slang.h
source/slang/hlsl.meta.slang
source/slang/hlsl.meta.slang.h
source/slang/slang-stdlib.cpp
tools/slang-generate/main.cpp
tools/slang-generate/slang-generate.vcxproj

There is nothing too significant in these changes, but I'm trying to get
things in place so that we can:
- Clean up the stdlib code to do less explicit `StringBuilder`
operations and instead to use more of the "template engine" approach
- Start using slang-generate for code other than the slang stdlib, so
that we can generate more of our boilerplate.
The main new functionality here is that in a template/meta file, you can
now enclose an expression in `$(...)` to indicate that is should be
spliced into the result. E.g. instead of:
class ${{ sb << someClassName; }}
{
...
}
We can now write:
class $(someClassName)
{
...
}
The other bit of new functionality is support for a whole-line statement
escape, so that instead of:
${{ for( auto a : someCollection ) { }}
void $(a)() { ... }
${{ } }}
We …

Cleanups on slang-generate

---

source/slang/ir.cpp

This change add a checking in `cloneGlobalValueWithMangledName` to ensure the `originalVal` being cloned is not already part of current `IRModule` before actually making a copy of the global value. This prevents duplicates of functions due to specialization.
When specializing a generic function G (which is already in target module), where G calls a normal function F (which is already in target module), then when we are making a copy of G via cloneFuncCommom(), it will recursively clone F, however we don't want to make a duplicate of F in the target module.

Prevent duplicating global values during specialization

---

source/slang/diagnostic-defs.h
source/slang/slang.cpp
tests/bugs/import-with-error.slang.expected
tests/diagnostics/recursive-import.slang.expected

This PR makes Slang generate a `Fatal` diagnostic when a imported module failed to parse or code gen. Currently we are still hitting compiler crashes when trying to access nullptr values from broken imported modules, this change should further prevent that from happening.

Stop compilation when a imported module contains errors.

---

source/slang/legalize-types.cpp

The type legalization logic currently looks up layout information for the fields of an aggregate type using the mangled name of the field (since this should be consistent even when legalization changes the number of  fields). The problem at present is that type layouts for specialized generic types were storing the mangled names of *specialized* field decl-refs, while the lookup was using the mangled names of the unspecialized declarations. The latter (unspecialized names) is what we want for simplicity, so this change fixes the comparison.

Don't use specialized field names when legalizing types

---

source/slang/emit.cpp

This allows users who call `spAddBuiltins` to specify `struct` types that are provided for a target, and that should not be part of the generated HLSL/GLSL from Slang.
The existing emit logic already skips emitting any basic, vector, matrix, or resource types, so this case really only triggers when the standard library needs to declare a completely ordinary `struct`.
No provision is made right now for a `struct` type that might be builtin on one target, but need to be declared on another. That is a clear next step for this feature.

When emitting from IR, skip structured types with `__builtin` modifier

---

source/slang/lower-to-ir.cpp
source/slang/parameter-binding.cpp

This commit contains two small bug fixes:
1. In `specializeProgramLayout`, we cannot assume the resourceInfo entries in a varLayout and its corresponding type layout has the same order. Should use `FindResourceLayout`.
2. When generating ir for a switch statement, make sure to remove the breakLabel from the shared context when done. For some reason if a switch statement is being lowered twice, the Dictionary::Add method will complain the statement key already exists.

Small bug fixes to get latest refactored Falcor shader library to work

---

source/slang/check.cpp
source/slang/compiler.cpp
source/slang/compiler.h
source/slang/core.meta.slang
source/slang/core.meta.slang.h
source/slang/diagnostic-defs.h
source/slang/dxc-support.cpp
source/slang/emit.cpp
source/slang/expr-defs.h
source/slang/lower-to-ir.cpp
source/slang/parameter-binding.cpp
source/slang/parser.cpp
source/slang/profile.h
source/slang/slang.cpp
source/slang/syntax.cpp
source/slang/type-defs.h

These are changes working toward supporting the `[shader("...")]` attribute on input as an alternative to `-entry ...` options on the command line, and then also outputting the attribute so that it can be recognized by dxc when generating DXIL libraries.
The support here isn't really finished, but it should be at a good state to check in. The next step would be to fundamentally break up the "profile" concept in the compiler implementation so that we more completely decouple stages and "profile versions."

Entry point attribute

---

docs/api-users-guide.md
source/core/core.vcxproj
source/core/slang-result.h
tools/render-test/main.cpp
tools/render-test/options.cpp
tools/render-test/options.h
tools/render-test/render-d3d11.cpp
tools/render-test/render-d3d12.cpp
tools/render-test/render-gl.cpp
tools/render-test/render-vk.cpp
tools/render-test/render.h
tools/render-test/slang-support.cpp
tools/slang-test/README.md
tools/slang-test/main.cpp

The testing code, when an error occurred would often just call exit(1). Whilst this worked it made debugging more difficult - as program flow was terminated.
To work around the problem added the SlangResult (or Slang::Result) type, which is compatible with HRESULT. This is an integral type that can return success or failure - as well as identifying what specifically caused a failure. It is then used to propagate errors just as a return code. The Renderer interface is changed slightly such that it returns SlangResult on methods that can fail.  
Added a first pass README.md file for slang-test.

SlangResult and small bug/typos fixes

---

source/core/slang-com-ptr.h
source/core/slang-result.h
tools/render-test/main.cpp
tools/render-test/render-d3d11.cpp
tools/render-test/render-gl.cpp
tools/render-test/render-vk.cpp
tools/render-test/render.h

Achieved by making the Renderer and it's opaque types derive from Slang::RefObject. The render-test code was changed to hold the previously global pointers, to members of 'RenderTestApp' class - which makes it much easier to control life times of resources.
* Renderer and resource types derive from Slang::RefObject - can use RefPtr to handle scoping
* Fixed a bug in D3D11Renderer::createInputBuffer where creating the shader resource view would fail.
* render-test uses RenderTestApp to manage lifetimes of resources

Renderer resource mangement for render-test

---

source/slang/check.cpp
source/slang/syntax.cpp
tests/bugs/gh-449.slang
tests/bugs/gh-449.slang.expected

Most of the description is in the second commit message below. This is a fix for bug #449.

Unify all generic parameters, even if some mismatch

---

source/slang-glslang/slang-glslang.vcxproj
source/slang-glslang/slang-glslang.vcxproj.filters

This is an attempt to alleviate some driver crashes caused by invalid SPIR-V. Because Slang drives `glslang` with GLSL source code, any invalid output is likely due to `glslang` bugs.
I chose top-of-tree for `glslang` because it wasn't clear what their release process is. Hopefully we can go another year without having to update this dependency.
The build setup we use for `glslang` had to change to account for one more `#define` that the code expects to have passed in externally.

Update to top-of-tree glslang (2018-04-02).

---

source/slang/emit.cpp
source/slang/modifier-defs.h
source/slang/parser.cpp
tests/render/nointerpolation.hlsl

This is a short-term fix, because we (1) don't have an IR-level representation of interpolation qualifiers, and (2) can't introduce one until *after* the IR-level type system is introduced (to be able to handle `struct` fields).
The approach here is to find the AST-level declaration, either from layout information (in the case of an ordinary variable or function parameter), or from struct field information (because structs are being output from the AST form anyway).
I've included a single end-to-end rendering test to confirm that we handle the `nointerpolation` modifier the same as HLSL.
I also added the `noperspective` modifier, which seemed to be missing from our implementation.

Pass AST interpolation modifiers through to codegen.

---

source/slang/lexer.cpp
source/slang/lexer.h
source/slang/preprocessor.cpp
source/slang/token-defs.h

* For a `#error` or `#warning`, read the rest of the line as raw text to include in the error message
* When skipping tokens (e.g., in an `#ifdef`d out block), don't emit errors on invalid characters
* TODO: we could clearly get more efficient and skip whole raw lines in the future
* Fix an issue when a macro invocation that expands to nothing (zero tokens) is the last thing before a directive. The preprocessor was returning the `#` as an ordinary token, because it has already gone past its test for directives.

Preprocessor cleanups

---

source/slang/slang.cpp

A previous fix avoided crashes when an `import`ed module has errors by making the "failed to import" error a fatal one.
Unfortunately, the code path that handles fatal errors was failing to copy diagnostic output from the sink over to the member variable on the `CompileRequest` that exposes the output through the API.
This meant that API users lost all context on error messages in `import`ed code.
This change fixes the immediate issue by plumbing through the error output, but doesn't fix the more fundamental issue: the front-end should not crash when an `import` fails, by any means.

Propagate diagnostics when imported module has errors

---

source/slang/emit.cpp
source/slang/legalize-types.cpp

The main error here was checking for `IRSamplerType` instead of `IRSamplerTypeBase`, which means the relevant logic only triggered for the `SamplerState` type and not the `SamplerComparisonState` type.
The two affected places were type legalization (so that comparison samplers in `struct` types weren't being hoisted out) and the emit logic when deciding whether to introduce local temporaries (so we were emitting temporaries for comparison samplers, leading to GLSL errors).

Fix some logic around legalization of sampler types

---

source/slang/emit.cpp
source/slang/mangle.cpp

This is required for the unmangling we do on some builtin function names.
The work here is mostly just a band-aid, and a more comprehensive pass over the name mangling/unmangling code is required to make any of this robust.

Fix up name mangling/unmangling for extensions

---

source/slang/check.cpp
source/slang/compiler.h
source/slang/diagnostic-defs.h
source/slang/lower-to-ir.cpp
source/slang/slang.cpp

These are two changes that try to improve the user experience when Slang hits an internal error. Yes, it is important to fix those errors, but for now it is important to give users as much context as possible into why a failure occurred, in case that helps them find a workaround.

Better diagnostics when compilation is aborted

---

source/slang/check.cpp
source/slang/diagnostic-defs.h
tests/diagnostics/setter-method.slang
tests/diagnostics/setter-method.slang.expected

Work on #529
This helps to avoid the case where a Slang user writes a struct with helpful `setter` methods, and finds that it doesn't work as expected because the `this` parameter is currently handled like an `in` parameter (passed by value, but mutable in the callee).
Fixing this issue actually involved making a more broad fix to how l-value-ness is propagated. The existing checking logic was assuming that l-value-ness is just a property of a particular member declaration (e.g., a field is either mutable or not), and didn't take into account whether the "base expression" was mutable. This change fixes that oversight, which might lead to additional errors being issued if we aren't correctly making things mutable when we should.
A `ThisExpr` was already immutable by default, so that part …

Diagnose attempts to write to fields in methods

---

source/slang/diagnostic-defs.h
source/slang/ir-validate.cpp
source/slang/lower-to-ir.cpp
tests/diagnostics/unreachable-code.slang
tests/diagnostics/unreachable-code.slang.expected

Fixes #527
There were a few problem cases for the IR emit logic. The most obvious, which came up in #527 is that a function body with multiple `return` statements would generate invalid code:
```hlsl
int foo()
{
return 1;
int x = 2;
return x;
}
```
In that case the IR for `foo` would have a single block that has two `return` instructions, which is invalid.
Another case that seems to be arising more often, but that had less obvious consequences was when one arm of an `if` statement ends in a `return`:
```hlsl
if(a)
{
return b;
}
else
{
int c = 0;
}
int d = 0;
```
In that case, the `return` instruction for `return b` would be followed by a branch to the end of the `if` (the `int d = 0;` line), because that would be the normal control flow without the early `return`.
The fix implemented here …

Fix emit logic when "terminators" occur in the middle of a block

---

source/core/slang-string.cpp
source/core/slang-string.h
source/slang/diagnostic-defs.h
source/slang/diagnostics.cpp
source/slang/diagnostics.h
source/slang/modifier-defs.h
source/slang/parameter-binding.cpp
source/slang/parser.cpp
tests/diagnostics/gh-38-vs.hlsl.expected
tests/diagnostics/packoffset.slang
tests/diagnostics/packoffset.slang.expected
tests/diagnostics/register-bindings.slang
tests/diagnostics/register-bindings.slang.expected
tests/hlsl/dxsdk/AdaptiveTessellationCS40/Render.hlsl
tests/hlsl/dxsdk/BasicHLSL11/BasicHLSL11_PS.hlsl
tests/hlsl/dxsdk/BasicHLSL11/BasicHLSL11_VS.hlsl
tests/hlsl/dxsdk/CascadedShadowMaps11/RenderCascadeShadow.hlsl
tests/hlsl/dxsdk/DynamicShaderLinkage11/DynamicShaderLinkage11_VS.hlsl
tests/hlsl/dxsdk/MultithreadedRendering11/MultithreadedRendering11_VS.hlsl
tests/hlsl/dxsdk/OIT11/SceneVS.hlsl
tests/hlsl/dxsdk/VarianceShadows11/RenderVarianceShadow.hlsl
tests/reflection/explicit-register-space.slang
tests/reflection/explicit-register-space.slang.expected

This change adds support for specifying explicit register spaces, like:
```hlsl
// Bind to texture register #2 in space #1
Texture2D t : register(t2, space1);
```
I added a test case to confirm that the register space is properly propagated through the Slang reflection API.
This change also adds proper error messages for some error/unsupported cases that weren't being diagnosed:
* Specifying a completely bogus register "class" (e.g., `register(bad99)`)
* Failing to specify a register index (`register(u)`)
* Specifying a component mask (`register(t0.x)`)
* Using `packoffset` bindings
I added test cases to cover all of these, as well as the new errors around support for register `space` bindings.
In order to get the existing tests to pass, I had to remove explicit `packoffset` bindings from …

Add support for explicit register space bindings

---

source/slang/emit.cpp
source/slang/ir-inst-defs.h
source/slang/ir-insts.h
source/slang/ir.cpp
source/slang/lower-to-ir.cpp

This was a known issue in our IR representation, which was now biting a user. The basic problem is that in code like the following:
```hlsl
RWStructureBuffer<float4> buffer;
...
buffer[index].xz = value;
```
we ideally want to be able to reproduce the original HLSL code exactly, but that requires directly encoding the way that this code writes to two elements of a vector, but not the others.
The currently lowering strategy we had produced IR something like:
```hlsl
float4 tmp = buffer[index];
tmp.xz = value;
buffer[index] = tmp;
```
That transformation might seem valid, but it has some big problems:
* It generates UAV reads that are not needed, which could impact performance
* It performs read-modify-write operations on memory that the programmer didn't explicitly write, which could …

Add support for "swizzled stores"

---

source/slang/check.cpp
source/slang/compiler.h
source/slang/slang.cpp
source/slang/syntax.h

This change adds caches to built-in operator overload resolution and type coersion to avoid running these time-consuming operations every time.
- Adds `TypeCheckingCache` type, which is defined in check.cpp, that contains two dictionaries for the cached results of `ResolveInvoke` and `CanCoerce` calls.
- Add `destroyTypeCheckingCache` and `getTypeCheckingCache` methods to `Session` class to reuse these cached results over the entire session.
Addressing #538.

Speedup type checking using cached overload resolution results.

---

tools/render-test/main.cpp
tools/render-test/options.h
tools/render-test/png-serialize-util.cpp
tools/render-test/png-serialize-util.h
tools/render-test/render-d3d11.cpp
tools/render-test/render-d3d12.cpp
tools/render-test/render-gl.cpp
tools/render-test/render-test.vcxproj
tools/render-test/render-test.vcxproj.filters
tools/render-test/render-vk.cpp
tools/render-test/render.h
tools/render-test/surface.cpp
tools/render-test/surface.h

* Added Surface type - as a simple value type to hold a 2d collection of pixels.
* Added PngSerializeUtil allows currently for just writing Surface of RGBA format 
* Removes dependency on stbi_image except for in PngSerializeUtil.
* Removed use of gWindowWidth/Height globals - instead pass the size in Desc to initialize on Renderer.

Improvements around Surface type

---

slang.h
source/slang/ir-dominators.cpp
source/slang/ir-dominators.h
source/slang/ir-ssa.cpp
source/slang/slang.vcxproj
source/slang/slang.vcxproj.filters

This code is currently not used by anything, but I wanted to check in a first pass at an implementation of dominator tree construction so that we don't have to keep avoiding implementing algorithms that rely on having dominator information available.
The algorithm used to construct the dominator tree is taken from "A Simple, Fast Dominance Algorithm" by Keith D. Cooper, Timothy J. Harvey, and Ken Kennedy.
This is not the "best" algorithm in terms of asymptotic performance, but it is among the simplest algorithms for computing a dominator tree that still outperforms naive iterative set-based methods.
The actual data structure and API for the dominator tree has a bit of "cleverness" in it to try to make the common queries reasonably fast (e.g., you can check whether A dominates B in …

Add a pass for computing dominator trees

---

tools/render-test/main.cpp
tools/render-test/render-d3d11.cpp
tools/render-test/render-d3d12.cpp
tools/render-test/render-gl.cpp
tools/render-test/render-vk.cpp
tools/render-test/render.h
tools/render-test/surface.cpp
tools/render-test/surface.h

Screen capture now writes result into a Surface. This allows client code to decide what to do with the pixels.
It can still serialize the Surface out using PngSerializeUtil. In the future could also just directly compare captures between different renders without having to write to a file/png.

Use Surface for screen capture in Renderer interface

---

source/slang/emit.cpp
source/slang/ir.cpp
source/slang/ir.h
tests/bindings/glsl-parameter-blocks.slang.glsl

The emit logic already had an idea of when an instruction should be "folded" it its use site(s), and this change just expands on that logic to try to be more aggressive. The basic idea is that instead of outputting this:
```hlsl
float4 _S3 = a_0 + b_0;
float4 _S4 = c_0 * _S3;
d_0 = _S4;
```
we can hopefully output something like this:
```hlsl
d_0 = c_0 * (a_0 + b_0);
```
The way this works is that after dealing with the various special cases that decide an instruction `I` must/cannot be folded in, we look and see if it has the following properites:
* `I` has no side effects
* `I` has a single user, `U`
* `I` and `U` are in the same block (and `I` comes before `U` in that block)
* for every instruction `X` between `I` and `U` (exclusive), `X` has no side effects
If all of these conditions …

Allow more complex compound expressions when emitting from IR

---

source/slang/emit.cpp

This was based on feedback from Falcor users, who felt like changing the default to have no line directives didn't work out well. Since I'd only made them disabled by default based on what I perceived to be Falcor's needs, I'm happy to turn this back on by default.
I also added a few changes to clean up the output:
* Don't emit a directive for a sub-expression, since that breaks up the code too much. The only directives inside a function body will be on top-level instructions that didn't get folded into a use site.
* Add logic to emit a directive for top-level declarations (globals, functions, structs), and clean up their printing so that they put any extra space *after* the declaration rather than before (so the line numbers can be accurate)
* Don't emit the file path part of a directive …

Re-enable emission of #line directives and clean up output

---

source/slang/emit.cpp

This is a quick workaround to deal with cases where we try to emit an unreferenced IR type that contains references to pre-legalization types (which might have been removed from the IR even thought they are still referenced). The basic fix is to *not* add types to our global order of instructions to emit by default, and only add them on demand as they are referenced by other instructions.
This is not a real fix for the underlying issue, which is that type legalization is only being applied to a subset of global instructions instead of all of them. A more detailed fix for that problem will need to be devised next.
This fix also doesn't address the question of why an unreferenced `struct` type came to be present in the IR code passed to the back-end in the first place. It would be good to …

Workaround for cases where we emit illegal-but-unused types

---

slang.h
source/slang/compiler.h
source/slang/options.cpp
source/slang/reflection.cpp
source/slang/slang.cpp
source/slang/type-layout.cpp
source/slang/type-layout.h
tests/reflection/matrix-layout.slang
tests/reflection/matrix-layout.slang.1.expected
tests/reflection/matrix-layout.slang.expected

Up to this point, the Slang compiler has assumed that the default matrix layout conventions for the target API will be used.
This means column-major layout for D3D, and *row major* layout for GL/Vulkan (note that while GL/Vulkan describe the default as "column major" there is an implicit swap of "row" and "column" when mapping HLSL conventions to GLSL).
This commit introduces two main changes:
1. The default layout convention is switched to column-major on all targets, to ensure that D3D and GL/Vulkan can easily be driven by the same application logic. I would prefer to make the default be row-major (because this is the "obvious" convention for matrices), but I don't want to deviate from the defaults in existing HLSL compilers.
2. Command-line and API options are introduced for setting …

Add options to control matrix layout rules

---

source/slang/dxc-support.cpp
source/slang/emit.cpp
source/slang/profile-defs.h
source/slang/slang.cpp

This adds `vs_6_3` and friends as available profiles, but doesn't add any new builtins specific to Shader Model 6.3.
In order to better support the ray tracing shader stages, Slang will now automatically map any attempt to compile a DXR shader up to SM 6.3 (the shader model officially required for these stages) and to the `lib_*` profiles (because there are no stage-specific profiles for these cases).
As an added detail, when invoking `dxcompiler.dll` to generate DXIL for DXR shaders, specify an empty entry-point name, since that is expected for `lib_*` profiles.

Add basic support for Shader Model 6.3 profiles

---

source/slang/ir-legalize-types.cpp
source/slang/legalize-types.cpp

PR #577 tries to eliminate empty `struct` types by replacing them with a `LegalType::tuple` with zero elements, but this seems to run into problems in some cases, where we end up trying to match up `::none` values with empty `::tuple`s.
An alternative way to handle this is to never create empty `LegalType::tuple`s (and the same for `LegalVal::tuple`), and instead create `LegalType::none` and `LegalVal::none`. PR #577 avoided this because there were various cases in the legalization logic that didn't robustly handle `LegalType::Flavor::none`.
This PR thus includes two main changes:
1. Construct a `::none` type when we have an empty `struct` type.
2. Survery all places that handle the `::tuple` case and extend them to handle the `::none` case if it was missing.
This fixes an issue filed in …

Fixes related to handling of empty types

---

source/slang/options.cpp

Fix problem when doing options parse, that failure doesn't leave appropriate message in diagnostic string.

Fix spProcessCommandLineArguments not setting diagnostic string on failure.

---

tools/slang-test/README.md
tools/slang-test/main.cpp
tools/slang-test/render-api-util.cpp
tools/slang-test/render-api-util.h

* Parsing of control of api parameters no longer needs comma separator.
* Parsing of API list now can take an initial state.
* Document the command line option (in README.md)

Improved command line control for apis and synthesized tests

---

source/slang/core.meta.slang
source/slang/core.meta.slang.h
source/slang/lower-to-ir.cpp
source/slang/mangle.cpp

Partially fixes #615
There's kind of a mess going on here, and it is difficult to be sure which of the changes here are strictly necessary.
Also, our testing isn't setup to run tests that use `RWTexture2D`, so the only testing I can really run is manual tests using Falcor.
The most basic issue here is that in an earlier change I added `ref` accessors for the subscript operation on various `RW*` types in the standard library, and that included `RWTexture2D` (and the other `RWTexture*` types). The compiler ended up favoring a `ref` accessor over a `set` accessor even when the `set` would suffice, but only the `set` accessor could be lowerd to GLSL/SPIR-V.
This change ends up implementing two different fixes for the same problem:
* Logic has been added to try and favor a `set` accessor over …

Fix translation of RWTexture subscript operations for Vulkan

---

.gitmodules
examples/model-viewer/main.cpp
premake5.lua
source/core/smart-pointer.h
tools/gfx/d3d-util.cpp
tools/gfx/gfx.vcxproj
tools/gfx/gfx.vcxproj.filters
tools/gfx/gui.cpp
tools/gfx/gui.h
tools/gfx/render-d3d11.cpp
tools/gfx/render-d3d12.cpp
tools/gfx/render-gl.cpp
tools/gfx/render-vk.cpp
tools/gfx/render.cpp
tools/gfx/render.h
tools/gfx/window.cpp

This isn't being made visible just yet, but it will allow us to have a simple UI for loading models into the model-viewer example.
In order to support rendering with IMGUI I had to add the following to the `Renderer` layer:
* viewports
* scissor rects
* blend support
These are really only fully implemented for D3D11, but adding them to the other back-ends should be a reasonably small task.

Add basic support for "Dear IMGUI"

---

source/slang/emit.cpp
source/slang/hlsl.meta.slang
source/slang/hlsl.meta.slang.h
source/slang/ir-inst-defs.h
source/slang/ir.h
source/slang/reflection.cpp
source/slang/syntax.cpp
source/slang/type-defs.h
source/slang/type-layout.cpp
tests/front-end/rasterizer-ordered-uav.slang

Fixes #627
The front-end has support for `RasterizerOrderedBuffer` and `RasterizerOrderedTexture*`, but left out support for:
* `RasterizerOrderedByteAddressBuffer`
* `RasterizerOrderedStructuredBuffer`
[Nitpick: these tyeps are all amazingly annoying to type. It is easy to want to write `RasterOrdered` instead of the bulkier `RasterizerOrdered`, and almost everybody does in casual speech. There's already the issue of wanting to type `StructureBuffer` (a buffer of structures) instead of `StructuredBuffer` (a buffer that is... structured?). Then you have `ByteAddressBuffer` which is just adding to the confusion because it is nominally a "byte addressable" buffer (so that `ByteAddressedBuffer` would actually make sense), but then actually *isn't* byte addressable in practice.]
There were a …

Add support for more RasterizerOrdered types

---

source/slang/check.cpp
source/slang/diagnostic-defs.h
source/slang/preprocessor.cpp
tests/preprocessor/pragma-once-a.h
tests/preprocessor/pragma-once-b.h
tests/preprocessor/pragma-once.slang

This work is broken into three changes just to keep it clean:
1. Add a better error message for function redefinition. My test case for `#pragma once` started out giving an internal compiler error for a simple issue, so I cleaned up the code.
2. Add basic support for recognizing `#pragma` directives. The existing code was just blindly ignoring all of them, so I added support for dispatching on the "sub-directive" token. This also added a warning for unknown `#pragma` sub-directives.
3. Actually add `#pragma once` in the simplest way possible.
There's plenty of work that could still be done on this, as discussed in the commit message for the third change. Still, this is hopefully enough that many users can muddle through.

Add basic support for #pragma once

---

source/slang/check.cpp
source/slang/diagnostic-defs.h

A common mistake that seems to come up when using global generic type parameters:
```hlsl
interface IHero { ... }
type_param H : IHero;
ParameterBlock<H> gHero;
```
is to accidentally try to specialize the type parameter `H` using `H` itself as the argument (instead of some concrete type like `Batman`). The current front-end checks naively let this pass, because `H` satisfies all the requirements (it sure does declare that it implements `IHero`, which is the only requirement we have). This currently leads to downstream failure when we generate code with generic type parameters still left in the IR.
This change implements a simple fix which is to:
- Check when we are trying to specialize a global generic parameter using another global generic parameter, since this is currently always a …

Add a better error message for common global generic failure

---

test.bat
tools/slang-test/main.cpp

* Unit tests appear in unit-test category
* Unit tests 'appear' (as there is no actual directory) in a directory unit-tests. 
* Removed the -unitTests command line option
Thus can run a specific unit test with 
`unit-tests/Free` will run any unit tests starting with Free (such as FreeList)
Or just for unit tests you can also use
`-category unit-test`

Control unit tests being run with -category -exclude and using prefix.

---

source/slang/diagnostic-defs.h
source/slang/preprocessor.cpp
tests/diagnostics/undefined-in-preprocessor-conditional.slang
tests/diagnostics/undefined-in-preprocessor-conditional.slang.expected

This can mask an error when the user either typos a macro name when writing a conditional, or (as was the case for the user who pointed out this issue) they mistakenly assume that a `#define` in an `import`ed file has been made visible to them.
This change just adds the warning in the obvious place, with a test code to ensure it triggers.

Warn when undefined identifier used in preprocessor conditional

---

slang.h
source/slang/check.cpp
source/slang/compiler.h
source/slang/core.meta.slang
source/slang/core.meta.slang.h
source/slang/dxc-support.cpp
source/slang/emit.cpp
source/slang/lexer.cpp
source/slang/mangle.cpp
source/slang/parser.cpp
source/slang/reflection.cpp
source/slang/slang-stdlib.cpp
source/slang/syntax.cpp
source/slang/syntax.h
source/slang/type-defs.h
source/slang/type-layout.cpp
source/slang/type-layout.h
source/slang/type-system-shared.h

The main change here is to fill out the `BaseType` enumeration so that it covers the full range of 8/16/32/64-bit signed and unsigned integers, as well as 16/32/64-bit floating-point numbers, and then propagate that completion through various places in the code.
More details:
* The current `half`, `float`, `double`, `int`, and `uint` types are still the default names for their types, so things like `float16_t` and `int32_t` were added as `typedef`s.
* We still need to generate the full gamut of vector/matrix `typedef`s for the new types, so that things like `float16_t4x3` will work (yes, I know that is ugly as sin, but that's the HLSL syntax...).
* A few pieces of dead code from earlier in the compiler's life got removed, since I did a find-in-files for `BaseType::` and tried to either …

Improve support for non-32-bit types.

---

source/slang/compiler.h
source/slang/options.cpp
source/slang/slang.cpp

Added -serial-ir option, to make generateIR always serialize out and in before further processing. This tests the serialization path, and adding a kind of 'firewall' between compiler front end and backend.

Added -serial-ir command line option

---

source/slang/emit.cpp

When emitting high-level expressions we obviously need to avoid emitting expressions that mean something different than the original code. So if we had IR like:
```
%t0 = add %a %b
%t1 = mul %t0 c
```
and `t0` isn't used anywhere else in the code, we can emit HLSL like:
```hlsl
float t1 = (a + b) * c;
```
but not:
```hlsl
float t1 = a + b *c; // oops! precedence changed the meaning!
```
The existing strategy in Slang has been to be overly conservative about when it emits parentheses to guarantee precedence is respected, so you might get something like:
```hlsl
float t1 = ((a) + (b)) * (c);
```
which not only looks silly, but also leads to unhelpful diagnostics from the clang-based dxc, about all those extra parentheses being redundant.
This change follows the pattern of (and actually …

Don't emit extra parentheses when outputting HLSL/GLSL

---

slang-com-helper.h
source/slang/default-file-system.cpp
source/slang/default-file-system.h
source/slang/slang.cpp
source/slang/slang.vcxproj
source/slang/slang.vcxproj.filters

* IncludeFileSystem -> DefaultFileSystem
* Improvements in 'singleton'ness of DefaultFileSystem
* Made WrapFileSystem a stand alone type - to remove 'odd' aspects of deriving from DefaultFileSystem  (such as inheriting getSingleton method/fixing ref counting)
* Simplified CompileRequest::loadFile - becauce fileSystemExt is always available.

Small improvements on include refactor

---

source/slang/emit.cpp
source/slang/ir-insts.h
source/slang/ir.cpp
source/slang/ir.h
source/slang/lower-to-ir.cpp

I'm honestly not sure how the original work on this feature in #648 worked at all (probably insufficient testing).
We have these front-end modifiers to indicate that a particular function definition requires a certain GLSL version, or a GLSL extension in order to be used, and they are supposed to be automatically employed by the logic in `emit.cpp` to output `#extension` lines in the output GLSL. However, it turns out that nothing is actually wired up right now, so that adding the modifiers to a declaration is a placebo.
This change propagates the modifiers through as decorations, and then uses them during GLSL code emit, which allows the functions that require `EXT_samplerless_texture_functions` to work.

Fix sampler-less texture functions

---

slang.h
source/core/slang-io.cpp
source/core/slang-io.h
source/slang/default-file-system.cpp
source/slang/default-file-system.h
source/slang/slang.cpp
tests/front-end/import-subdir-search-path.slang

* Added getPathType to ISlangFileSystemExt.
There are couple of reasons for the change. On some platforms 'getCanonicalPath' only succeeds if the path exists - but this isn't so for all platforms. Also the thoughts on how getCanonicalPath 'really' was changed. To in the limit just returning the path passed in (and therefore no test). 
So the fix here was to add an explicit method to test for a paths existence (and type). Thus when doing a search it means the file doesn't have to be read. Doing this means that if an implementer implements just the ISlangFileSystem interface - we still use the Path::getFileType - that checks for existence via the file system.
This might not be what you want. So something closer to the original intent might try to read the file from the underlying file …

Fix problem with __import not working 

---

source/slang/emit.cpp
tests/bugs/vk-image-atomics.slang
tests/bugs/vk-image-atomics.slang.glsl

The basic problem was that the front-end was generating code that used a `uint` vector for the coordinates, while GLSL requires an `int` vector.
Without support for implicit type conversions, this leads to GLSL compilation failure.
The fix here is to insert the type conversion as late as possible (during GLSL emit). This isn't a pretty solution, but it is the easiest one to implement in the current compiler.
A more forward-looking approach would be to support "force inline" functions in the stdlib, so that we can implement the conversion logic in a stdlib implementation specialized for the Vulkan/GLSL target.
At the moment, everything to do with image atomics is all sleight of hand anyway, so making it incrementally messier isn't a bit hit.

Fix Vulkan codegen for image atomics

---

source/slang/preprocessor.cpp

By a copy-paste error, `>=` in a preprocessor condition was behaving as `<=`.

Fix implementation of >= in preprocessor conditionals

---

source/slang/compiler.cpp
source/slang/slang.cpp

The logic in `getEffectiveProfile()` function was mapping these to use `Stage::Unknown` in an early attempt to handle the way that dxc requires the `lib_*` profile for DXR shaders, instead of anything that mentions the stage name (in constrast to, e.g., `vs_5_1`). At the same time, the `GetHLSLProfileName()` function was updated to explicitly handle the DXR shaders and map anything it doesn't expect (including `Stage::Unknown`) to a profile named `unknown`, which dxc obviously doesn't like.
This change tries to fix both issues by:
* Having `getEffectiveProfile()` no longer clobber the stage part of a profile for DXR shaders.
* Having `GetHLSLProfileName()` map all unhandled cases to the `lib_*` profiles, since that seems likely to be how any future stages will need to be handled as well …

Fix handling of DXR profiles

---

Makefile
premake5.lua

Newer versions of gcc, optimize away tests for this being null, because this being null is defined as undefined behavior in the standard. This is a workaround that disables that optimization for now.

Disable compilers optimizing away tests for this against null

---

slang.h
source/slang/compiler.cpp
source/slang/compiler.h
source/slang/diagnostic-defs.h
source/slang/dxc-support.cpp
source/slang/options.cpp
source/slang/slang.cpp

This change adds an API function and command line options for controlling the default floating-point behavior for a target, with options for "fast" and "precise" computation.
The "precise" option gets mapped to the "IEEE strictness" mode in `fxc` and `dxc` (there is currently no equivalent option for glslang that I could find).

Add support for a "strict" floating-point mode

---

source/slang/compiler.cpp
source/slang/dxc-support.cpp

* Fix bug outputting dxbc assembly
* Make the disassembly methods returns SlangResult and String as last output param so as to make error case clear.

Fix output of dxbc assembly.

---

slang.h
source/slang/compiler.cpp
source/slang/parameter-binding.cpp
source/slang/reflection.cpp
source/slang/type-layout.cpp
source/slang/type-layout.h
tests/reflection/unbounded-arrays.hlsl
tests/reflection/unbounded-arrays.hlsl.1.expected
tools/slang-reflection-test/main.cpp

With this change, Slang shaders can use unbounded-size arrays as parameters, e.g.:
```hlsl
Texture2D t[] : register(t3, space2);
SamplerState s[];
```
As shown in the above example, Slang supports both explicit `register` declarations on unbounded-size arrays and also implicit binding.
When doing automatic parmaeter binding, Slang will allocate a full register space to an unbounded-size array of textures/smaplers, starting at register zero.
Note that for the Vulkan target, an array of descriptors of any size (including unbounded size) consumes only a single `bindign`, so much of this logic is specific to D3D targets.
Details on the changes made:
* The single biggest change is a new `LayoutSize` type that is used to store a value that can either be a finite unsigned integer or a dedicated …

Add support for unbounded arrays as shader parameters

---

tools/gfx/render-d3d11.cpp
tools/render-test/main.cpp

* Try using hardware device before reference on dx11
* Output error string on renderer construction failure

Use hardware if available for Dx11 testing

---

slang.h
source/slang/type-layout.cpp
tests/reflection/parameter-block.slang
tests/reflection/parameter-block.slang.1.expected
tests/reflection/parameter-block.slang.2.expected

The change here is that the logic that used to be controlled by `-parameter-blocks-use-register-spaces` is now turned on unconditionally, meaning that a `ParameterBlock<X>` will get its own register `space` by default when targetting D3D Shader Model 5.1 and later.
I had originally made this feature optional because I wasn't sure whether Shader Model 5.1 should default to using register spaces or not, because D3D 11 doesn't support spaces at the API level and MSDN documetnation made it sound like SM5.1 was available for D3D11 as well. Subsequent reading has led me to understand that MSDN is wrong on this front, and SM5.1 and later are D3D12-only, so it is always safe to use spaces.
The new logic is now that we automatically use spaces for parameter blocks any time it is possible (SM5.1+ …

Use register spaces by default for D3D12 targets

---

source/slang/compiler.h
source/slang/diagnostic-defs.h
source/slang/parameter-binding.cpp
source/slang/type-layout.cpp
tests/diagnostics/vk-bindings.slang
tests/diagnostics/vk-bindings.slang.expected
tests/reflection/parameter-block-explicit-space.slang
tests/reflection/parameter-block-explicit-space.slang.expected

This PR pulls together two changes.
The first one is a bit of infrastructure work to make sure that we ignore Vulkan-directed binding syntax (e.g., `[[vk::binding(...)]]`) when targeting D3D and vice versa for D3D `register` bindings on Vulkan. That change also adds a warning message if you are compiling a shader with explicit `register` bindings for Vulkan, if you forgot to also include `[[vk::binding(...)]]`. That whole change is really just here to avoid some subtle bugs it could create for the next bit.
The second change allows the user to specify something like `register(space1234)` on a `ParameterBlock` declaration to indicate that it should use space `1234`, and similarly to use `[[vk::binding(0,1234)]]` (where the `0` binding is required) for Vulkan.
As with all explicit binding …

Allow parameter blocks to be explicitly bound to spaces

---

docs/design/README.md
docs/design/capabilities.md
docs/design/coding-conventions.md
docs/design/decl-refs.md
docs/design/existential-types.md
docs/design/ir.md
docs/design/overview.md

This change adds a set of documents about the design/implementation of the Slang compiler intended for helping to onboard new contributors, explain some of the choices that go into the current implementation, and outline the broad strokes of some of our future feature goals.
As explained in the `README` for these docs, I don't expect them to be kept in sync with the code in the long run; there is no expectation that people making a PR for code changes also go and fix up these documents.
The purpose of these is to add a bit of a "historical record" of design choices and project goals to the project itself, so they can be browsed in a way that is more convenient than the issue tracker or source control history.
The "Coding Conventions" document is very much a first attempt, and I'm not 100% …

Add more design documents

---

docs/design/coding-conventions.md

After a lot of discussion, I'm backpedaling and making this document what the (main) conventions of the codebase *are* rather than trying to prescribe what I think they should be. In particular:
* Go back to `m_` for implementation-details member variable names, since that is the main convention in place for them
* Put the `k` prefix back on C-style `enum` types since that is how they are currently being defined.
My inclination is to just stick with what we have for now to avoid extended debates. Its a bit of an inconsistent mess, but its enough for getting work done.

Tweak coding conventions

---

source/slang/emit.cpp
source/slang/ir-inst-defs.h
source/slang/ir-insts.h
source/slang/ir-legalize-types.cpp
source/slang/ir-missing-return.cpp
source/slang/ir-restructure-scoping.cpp
source/slang/ir-sccp.cpp
source/slang/ir-serialize.cpp
source/slang/ir-serialize.h
source/slang/ir-ssa.cpp
source/slang/ir-validate.cpp
source/slang/ir.cpp
source/slang/ir.h
source/slang/legalize-types.cpp
source/slang/lower-to-ir.cpp
source/slang/slang.natvis
tests/compute/mutating-methods.slang
tests/ir/string-literal.slang.expected

I tried to keep this as distinct commits to make the diffs easier, but the third one ended up being pretty big anyway. The commit message there explains most of what is going on, but the high order bit is that `IRDecoration` now inherits from `IRInst`, and an `IRInst` holds a single list of both decorations and children.

Decorations are instructions

---

slang.h
source/core/slang-writer.cpp
source/core/slang-writer.h

Replace with begin/endAppendBuffer. 
Means that valist is no longer part of the public interface. That in effect each ISlangWriter has some limited memory workspace. This could have been avoided - but in doing so it would mean there would be allocations/deallocations for each valist/format, this way that is minimized.

Remove the valist from the ISlangWriter interface. 

---

source/slang/check.h
source/slang/emit.cpp
source/slang/ir-inst-defs.h
source/slang/ir-insts.h
source/slang/ir-legalize-types.cpp
source/slang/ir.cpp
source/slang/lower-to-ir.cpp
source/slang/slang.vcxproj
source/slang/slang.vcxproj.filters
tests/bindings/array-of-struct-of-resource.hlsl
tests/bindings/binding0.hlsl
tests/cross-compile/non-uniform-indexing.slang.glsl
tests/vkray/anyhit.slang.glsl
tests/vkray/closesthit.slang.glsl

Before this change, global shader parameters were represented in the IR as just being ordinary global variables.
The only indication that a particular global represented a parameter was when it got a layotu attached to it (as part of back-end processing), and we've had a number of bugs related to layouts being dropped so that what should have been a shader parameter turned into an ordinary global variable in the output.
This change is more strongly motivated by the fact that making shader parameters look like globals means that we cannot easily reason about their value when doing IR transformations.
If we see two `load`s from the same global variable can we assume they yield the same value?
In the general case we cannot, and this means that any transformation that wants to rely on the …

Represent global shader parameters explicitly in the IR

---

source/slang/compiler.h
source/slang/ir-serialize.cpp
source/slang/ir-serialize.h
source/slang/preprocessor.cpp
source/slang/slang.cpp
source/slang/source-loc.cpp
source/slang/source-loc.h

* Make SourceView and SourceFile no longer derive from RefObject
* Both have life time of SourceFile and SourceView managed by SourceManager
* Tidied up a little around the serialization test code

Improvements around review of debug serialization info

---

source/slang/slang.cpp

Fixes problem when passing in nullptr for the channel - we need the DiagnosticSink.writer to be nullptr so that we get the buffered result. Unfortunately here, it was set to the default for the channel, which in diagnostics case meant throwing away the diagnostic.

Fix for buffering diagnostic when writer is nullptr

---

source/slang/check.cpp
tests/bugs/enum-init-cast.slang

The logic in `check.cpp` for declaration checking is very messy and needs to be re-written, but in the interim we need to be careful to avoid any cases where a declaration, or some piece of it, gets redundantly checked multiple times.
The way the logic had been working, the different "cases" in an `enum` type were being checked twice, and that meant that any initialization expression for a case would be type-checked the first time (potentially leading to a new AST) and then the checked AST would be checked again. This created a problem if the first round of checking introduced any AST nodes that the checking logic would not expect to see (because the parser cannot possibly produce them).
The fix here is to follow the style of the other declaration checking cases, where checking is …

Fix up declaration checking order for enums

---

source/slang/lower-to-ir.cpp
tests/cross-compile/function-static-const.slang
tests/cross-compile/function-static-const.slang.hlsl
tools/slang-test/slang-test-main.cpp

Previously the IR codegen logic was treating function-scope `static const` variables just like `static` variables, which results in them generating less efficient output HLSL/GLSL.
This change special-cases function-local `static const` variables with logic that mirrors how we handle global-scope `static const` variables.
The approach in this change attempts to find a simpler solution to deal with `static const` variables inside of generic functions than what is currently done for `static` variables in generic functions, but I haven't tested whether that works in practice, so I didn't apply the same approach to the plain `static` case. That would make a good follow-on change.
I've included a single test case to demonstrate that with this fix the Slang compiler generates output DXBC that …

Add proper IR codegen support for local static const variables

---

source/slangc/main.cpp

Somehow the work to support output redirection when running things in `slang-test` ended up interfering with the API-specified diagnostic callback in the `slangc` code.
This change doesn't include fixes to the testing infrastructure to prevent a regression like this happening again.

Fix diagnostic output for command-line slangc

---

source/slang/options.cpp

The code for options validation had something like:
```c++
{
if(rawTarget.redundantProfileSet)
if(rawTarget.conflictingProfileSet)
{ ... }
else if(rawTarget.redundantProfileSet)
{ ... }
}
```
The first `if` there seems to be stray code left over from some edit to this logic, since its case is handled later on.

Delete what appears to be stray code in options validation

---

source/core/slang-io.cpp
source/core/slang-io.h
source/core/slang-std-writers.cpp
source/core/slang-std-writers.h
source/core/slang-string-util.cpp
source/core/slang-string-util.h
source/core/slang-writer.cpp
source/slang/slang-file-system.cpp
source/slang/slang-file-system.h
source/slang/slang.cpp
source/slangc/main.cpp
tests/preprocessor/include/pragma-once-c.h
tests/preprocessor/pragma-once.slang
tools/render-test/render-test-main.cpp
tools/slang-reflection-test/slang-reflection-test-main.cpp
tools/slang-test/slang-test-main.cpp
tools/slang-test/unit-test-path.cpp

* Fix memory bug around expanding va_args - needed buffer to have space for terminating 0
* Fix problem with FileWriter defaults being globals, as memory they allocate, will only be freed after return from main - work around by making StdWriters RefObject derived, and kept in scope such the writers are destroyed before checks for leaks is found
* Added SimplifyPathAndHash mode for CacheFileSystem - will simplify the path and see if simplified path is in cache before reading file (limiting amout of underlying file requests)
To explain a little more - there are actual 3 'modes' with the file system depending on what you set as your file system.
OSFileSystem is literally a wrapper on underlying file system. Calling loadFile will hit the file system. Calling getCanonicalPath will return a …

Path simplification/hash mode, plus bug fixes

---

source/slang/diagnostics.cpp
source/slang/diagnostics.h

* Only output a 'verbose path' if it's different from the already output nominal path
* Fix comment on VerbosePath flag

Unique file identity review

---

source/slang/check.cpp
source/slang/decl-defs.h
source/slang/expr-defs.h
source/slang/lower-to-ir.cpp
source/slang/parameter-binding.cpp
source/slang/parser.cpp
source/slang/stmt-defs.h
source/slang/syntax.h

The AST class hierarchy for variable declarations had a few messy bits.
First, there are more subclasses of `VarDeclBase` than seem strictly necessary; especially for stuff like `struct` member variable which use `StructField` even for `static` fields (which are effectively globals).
Second, the AST node type for the "cases" within an `enum` was made a subclass of `VarDeclBase` for expediency, but this isn't really semantically accurate (and doesn't seem to be paying off much in deduplication of code).
This change tries to address both of those problems.
First, we replace the existing `Variable` and `StructField` cases with a single `VarDecl` case that covers globals, locals, and member variables.
I haven't gone so far as to replace function parameters or generic value parameters, but …

Clean up variable declaration class hierarchy

---

source/slang/ir-glsl-legalize.cpp
tests/cross-compile/geometry-shader.slang
tests/cross-compile/geometry-shader.slang.glsl

The underlying problem here was that legalization of entry point parameters for GLSL eliminates all the parameters to `main()`, but we still left a dangling reference to one of those parameters if it was a geometry shader output stream. The un-parented parameter would lead to an infinite loop in a later IR step, because it would never be reached by the transformation, and thus could never change its status to the one for "visited" instructions.
The fix here is to simply replace any refernces to the GS input stream parameter with an `undefined` instruction in the IR, and then rely on the fact that the downstream GLSL emit logic wouldn't actually reference that value anyway (hence why the danlging reference wasn't originally an issue).
I included a basic cross-compilation test case for …

Fix a regression in geometry shader cross-compilation

---

source/slang/core.meta.slang
source/slang/core.meta.slang.h
tests/cross-compile/texture-load.slang
tests/cross-compile/texture-load.slang.glsl

A user found that the `Texture2D<float2>.Load(...)` operation was not being compiled to GLSL properly, such that it returned a `vec4` instead of the expected `vec2`.
The GLSL texture-related functions always return (and take) 4-component vectors, and we already have infrastructure in `emit.cpp` for recognizing a `$z` operator in the GLSL intrinsic definition to stand in for an appropriate swizzle based on teh number of components in the texture result type.
This change just adds that `$z` operator to the GLSL code for several more texture operations (including `Load()`) that are defined on a `Texture*<T>` and that return `T`.
This change doesn't try to add additional GLSL translations for texture-related operations (e.g., additional variations like `SampleCmp` that we have defined in the …

Fix GLSL translation of several Texture* operations

---

source/slang/parser.cpp

The way we handle generics in the AST is to have a `GenericDecl` AST node that can wrap an arbitrary "inner" `Decl`.
This representation has proved valuable, but it also creates some gotchas because a `GenericDecl` is also a `Decl`.
One example of where this can be tricky is for attributes and other modifiers attached to something generic:
```hlsl
[special]
void foo<T>(...) { ... }
```
In this case, the current parser logic was gobbling up a list of `Modifier`s (including the `[special]` attribute here), then parsing the declaration that follows, and then attaching those modifiers to the resulting declaration.
In this case, however, the "resulting declaration" is not a `FuncDecl` as one might expect, but the `GenericDecl` that wraps it.
The solution is pretty simple: when we are done …

Fix parsing of modifiers on generic declarations

---

source/slang/check.cpp

If I write:
```
struct Foo : IDoesntExist
{}
```
Then currently Slang complains first that `IDoesntExist` is an undefined identifier, then it complains that it expected an interface type in the inheritance clause. The second ("cascading") error isn't really helpful, because of *course* if something isn't defined it isn't an interface.
This change detects the case where the type expression is erroneous so that we avoid the cascading error.

Produce a better error message on errors in inheritance clauses

---

source/slang/lower-to-ir.cpp

We somehow have been compiling `++i` as `i++` (and vice versa) for a long time without noticing.
This change fixes the implementation of these pseudo-ops in IR codegen, and adds a comment to explain the rationale for why their definitions should be what they are.

Fix confused definitions of pre/post increment/decrement

---

source/slang/check.cpp
source/slang/compiler.cpp
source/slang/compiler.h
source/slang/decl-defs.h
source/slang/diagnostic-defs.h
source/slang/emit.cpp
source/slang/ir-link.cpp
source/slang/ir-link.h
source/slang/ir-specialize.cpp
source/slang/lower-to-ir.cpp
source/slang/parameter-binding.cpp
source/slang/parser.cpp
source/slang/syntax-base-defs.h
source/slang/syntax.cpp
source/slang/syntax.h
tests/bugs/gh-357.slang
tests/compute/assoctype-generic-arg.slang
tests/compute/global-type-param-array.slang
tests/compute/global-type-param-in-entrypoint.slang
tests/compute/global-type-param.slang
tests/compute/global-type-param1.slang
tests/compute/global-type-param2.slang
tests/compute/int-generic.slang
tests/compute/tagged-union.slang
tests/reflection/global-type-params.slang

Prior to this change, the Slang implementation required users to use global `type_param` declarations in order to specialize a full shader. For example:
```hlsl
type_param L : ILight;
ParameterBlock<L> gLight;
[shader("fragment")]
float4 fs(...)
{ ... gLight.doSomething() ... }
```
With this change we can rewrite code like the above using explicit generics, plus the ability to have `uniform` entry-point parameters:
```hlsl
[shader("fragment")]
float4 fs<L : ILight>(
uniform ParameterBlock<L> light,
...)
{ ... light.doSomething() ... }
```
Having this support in place should make it possible for us to eliminate global generic type parameters and the complications they cause (both at a conceptual and implementation level).
The most central and visible piece of the change is that …

Allow entry points to have explicit generic parameters

---

source/slang/compiler.cpp
tests/compute/bit-cast.slang

* Fix problems and improve test coverage of bit cast, particularly for asfloat. 
* Make the values being cast between valid 'typical' floats.
* Typo fix

Improve coverage around asfloat bitcasts

---

source/slang/parameter-binding.cpp
tests/bugs/gh-841.slang
tests/bugs/gh-841.slang.glsl
tests/reflection/sample-index-input.hlsl.expected
tests/reflection/sample-rate-input.hlsl.expected
tests/reflection/vertex-input-semantics.hlsl.expected

Fixes #841
This reverts a small change made in #815 that seemed innocent at the time: we stopped tracking an explicit `Stage` to go with every `VarLayout` that is part of an entry-point varying parameter, and instead only associated the stage with the top-level parameter. That change ended up breaking the logic to emit the `flat` modifier automatically for integer type fragment-shader inputs for GLSL, but we didn't have a regression test to catch that case.
This change adds a regression test to cover this case, and adds the small number of lines that were removed from `parameter-binding.cpp`.
A few other test outputs had to be updated for the change (these are outputs that were changed in #815 for the same reason).

Track stage for varying sub-fields

---

source/slang/preprocessor.cpp
tests/preprocessor/if-ignore.slang

* Fix condition expression being evaluated in #if when skipping (just ignore and default to true)
* Fix some typos

Ignore expression if hit #if when skipping.

---

source/slang/emit.cpp
tests/cross-compile/array-of-buffers.slang.glsl
tests/vkray/closesthit.slang.glsl

* Output readonly on buffers for glsl if resource is readonly.
* Fix some typos 
Didn't add to emitGLSLParameterGroup because the cases there seem to to either be implicitly read only, or allow write.

Output readonly for suitable glsl buffers

---

tools/render-test/render-test-main.cpp

* Added test such that if m_pipelineState is not constructed an error is returned

Fix for Dx12 to stop crash when dxil cannot be handled by driver

---

source/slang/parser.cpp

* Remove typo in TryRecover
* Remove GLSL specific check - as no longer support GLSL
* Remove erroneous check for { on parseClass

Small parser fixes

---

docs/layout.md
source/slang/ir-link.cpp
source/slang/parameter-binding.cpp

The `specializeProgramLayout()` primarily existed to support global generic parameters.
The guiding idea of the design had been that plugging in concrete types for global generic parameters should only affect the layout/binding of shader parameters that depend on the global generic type parameters.
All other shader parameters should keep the same layout/location across all specializations.
This idea was implemented by conceptually having two phases of layout:
* A generic-argument-independent phase would do layout on all the shader parameters that *don't* depend on global generic type parameters.
* A second phase would then pick up where the other one left off (re-using existing parameter layouts to guarantee a match), and just layout out the shader parameters that *do* depend on global …

Eliminate the specializeProgramLayout() function

---

source/slang/parameter-binding.cpp
source/slang/type-layout.cpp
source/slang/type-layout.h

This affects layout computation for both the global and entry-point scopes, where multiple discrete shader parameters can be declared, but for layout purposes they must be treated as if they lived in the same `struct` type. If that `struct` type ends up consuming any "ordinary" data (`LayoutResourceKind::Uniform`) then an implicit constant buffer will be needed for that scope (e.g., the way fxc produces a `$Globals` constant buffer for the global scope).
The logic for computing those scope layouts had a bug in it, in that the struct type was not being updated to have the right size for uniform data at the scope. That bug hasn't bitten anybody yet because no Slang users are relying on entry-point uniforms, and global-scope uniforms aren't fully implemented (and get diagnosed as an error …

A small refactor to how implicit constant buffers are getting created.

---

source/slang/check.cpp
source/slang/compiler.cpp
source/slang/compiler.h
source/slang/parameter-binding.cpp
source/slang/syntax.h
source/slang/type-layout.h

There's a certain amount of logic in `parameter-binding.cpp` that just has to do with the basic problem of enumerating the shader parameters of a `Program`. The main source of complexity is that for legacy/compatibility reasons we need to consider two shader parameters with the same name as being the "same" parameter for layout purposes, and then we need to do a bunch of validation to ensure that these parameters have compatible types.
The biggest part of this change is moving that logic to `Program`, so that it builds up a list of its shader parameters during the front-end work, so that any errors related to bad redeclarations will now come up even if we aren't generated target-specific layouts/code.
All of the code for `getReflectionName`, `StructuralTypeMatchStack`, etc. is pretty much …

Move enumeration of shader parameters to Program/EntryPoint

---

source/slang/compiler.h
source/slang/slang.cpp
tests/preprocessor/include-search-path.slang
tools/render-test/slang-support.cpp

Search paths set using spSearchPath were not being used for #include. This is because there are now two sets of search paths one on the FrontEndCompileRequest and one on linkage. That the slang API only set the paths on Linkage. 
This meant that import (and the test for that) worked- because it used these search paths set on the linkage, but #include did not because it was empty. 
The fix for now was to make the #include use searchPaths on the Linkage. That a full fix probably needs to add/alter method to the slang API to set paths for the separate purposes.

#include not using search paths

---

source/slang/slang.cpp
source/slang/source-loc.cpp
source/slang/source-loc.h

* Fix issue with dependency including source path - even if source was compiled from a string
* Added FromString Type to PathInfo to identify paths that are not from 'files'

Don't add string source paths to dependency list

---

source/slang/hlsl.meta.slang.h

On doing complete rebuild hlsl.meta.slang.h appears to be slightly out of step. 
This just uses what appears correct generated hlsl.meta.slang.h .

Fix small issue on generated hlsl.meta.slang.h

---

source/slang/compiler.h

If this pointer is non-zero, Linkage::isBeingImported triggers a crash when the function accesses this pointer.

Properly initialize m_modulesBeingImported otherwize it will segfault

---

tools/gfx/window.cpp

Fixes issue #874
The problem here was that a pointer was being cast to `LONG` so that it could be used with the `SetWindowLongPtr` API, but that API actually expects a `LONG_PTR`. Since `LONG` is a 32-bit type on 64-bit Windows, the pointer we stored was getting truncated, leading to crashes.
I'm kind of surprised this wasn't biting more of our applications (e.g., the render tests).

Fix a 64-bit issue in our Windows UI code

---

source/slang/reflection.cpp
source/slang/slang.cpp

`FindTypeByName` is broken by some recent changes. This PR fixes the issue.
The existing implementation works by trying to type check user's string by placing the newly constructed `Expr` under the scope of each loaded `Module`. If the `Expr` failed to type check, the diagnostic message will be written to a temp `DiagnosticSink`. This `DiagnosticSink` must be initialized with `sourceManager`, or the compiler will crash.
The new `checkProperType` function will no longer return `nullptr` when it fails, instead it will now return `ErrorType`, so `Program::getTypeFromString` must change accordingly.

Fix `spReflection_FindTypeByName`

---

source/slang/emit.cpp
tests/cross-compile/vector-comparison.slang
tests/cross-compile/vector-comparison.slang.glsl

Add special case emit logic for select expression (`x?y:z`) for GLSL when `x` is a `bool` vector. In this case, we should generate a call to `mix` instead of a select expression since GLSL does not support a vector-typed condition expression.
Fixes #892

Fix GLSL emit logic for select expr

---

source/slang/hlsl.meta.slang
source/slang/hlsl.meta.slang.h
source/slang/ir-legalize-types.cpp
source/slang/ir-specialize.cpp
source/slang/ir.cpp
source/slang/ir.h
tests/cross-compile/non-uniform-indexing.slang.glsl
tests/cross-compile/vk-texture-indexing.slang
tests/cross-compile/vk-texture-indexing.slang.glsl

Before type legalization we might have code like: (using pseudo-Slang-IR):
struct P { ... Texture2D<float>[] t; }
global_param p : ParameterBlock<P>;
...
// p.t[someIndex].Load(...);
//
let ptrToArrayOfTextures = getFieldPtr(p, "t")                            : Ptr<Texture2D<float>[]>;
let ptrToTexture         = getElementPtr(ptrToArrayOfTextures, someIndex) : Ptr<Texture2D<float>>;
let texture              = load(ptrToTexture)                             : Texture2D<float>;
let result               = call(loadFunc, texture, ...)                   : float;
Legalization needs to move the `t` array there out of the `p` parameter block, so the global declarations become something like:
struct P_Ordinary { ... }; // no more "t" field
global_param p_ordinary : ParameterBlock<p_ordinary); …

Fix handling of arrays of resources in type legalization

---

docs/command-line-slangc.md
slang.h
source/slang/compiler.cpp
source/slang/compiler.h
source/slang/diagnostic-defs.h
source/slang/dxc-support.cpp
source/slang/options.cpp
source/slang/slang.cpp

The short version for command-line users is:
* Use `-g` to get debug info in the output, where supported
* Use `-O0` to disable optimizations, in case that improves debugability
* Use `-O2` for optimized/release builds where you can spend the extra compile time
The command-line options are matched with new API functions `spSetDebugInfoLevel()` and `spSetOptimizationLevel()` that set the equivalent information.
Right now these settings only affect how we invoke fxc and dxc. In the longer run I expect we will want to use them to control other things:
* Once we are emitting our own SPIR-V, the `-g` option should control what source-level name information we include in it.
* Whether or not `-g` is used could be used to decide whether we preserve the "name hints" in the IR, which in  turn …

Add options to control optimization and debug information

---

tools/render-test/options.cpp
tools/render-test/options.h
tools/render-test/render-test-main.cpp

* Optionally use -profile to set profile on render-test
* If not set will use the same mechanism as before that implies the profile

Command line option to set profile on render-test

---

source/slang/ir-legalize-types.cpp

The `tuple` case in `getPointedToType` was failing to add the elements it computed to the output tuple type.
This isn't triggered in any of our test cases, but was caught by some work I was doing in another branch.

Fixup for missing code in #896

---

slang.h
source/slang/reflection.cpp

Added a new `SLANG_ACCELERATION_STRUCTURE` enum in `SlangResourceShape`. Added handling for `RaytracingAccelerationStructureType ` to return this new value in `spReflectionType_GetResourceShape()`.
In `VK_NV_raytracing` extension, they introduced a new opaque type `accelerationStructureNV ` in GLSL for ray tracing acceleration structure, as well as a new descriptor type `VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_NV`. Slang needs to return a dedicated resource shape for this resource type in order for users to properly create descriptor set layout for the acceleration structure.
Original issue: https://github.com/shader-slang/slang/issues/894

Add SLANG_ACCELERATION_STRUCTURE resource shape for RaytracingAccelerationStructureType

---

source/slang/emit.cpp

* On GLSL targets, output texture layouts that are 3 component as 4 component, because 4 component style is not supported by glslang currently

On GLSL targets emit 3 component texture layouts as 4 component

---

source/slang/ir-glsl-legalize.cpp

* Set the underlying type for sv_groupthread_id and sv_groupid for glsl, so if smaller type is used conversion is performed

Handle sv_groupthread_id & sv_groupid with different vec size on glsl

---

tests/compute/half-calc.slang

The half-calc test runs, but is not actually doing any half maths. If the code is changed such that it is, the device fails when the shader is used. This can be seen by looking at dxil-asm - the test as currently constructed does not use half, but if vector half2 ops are used, it does and then the test fails.

Disable Dx12 half tests. 

---

tools/gfx/render-d3d12.cpp

Due to if a resource was initialized with data, the actual resource constructed might be larger, for alignment issues. This led to a memcpy potentially copying from after the allocated source data and therefore a crash. Now only copies the non aligned amount of data.

Fix intemittent crash on dx12.

---

tools/gfx/d3d-util.cpp
tools/gfx/d3d-util.h
tools/gfx/render-d3d11.cpp
tools/gfx/render-d3d12.cpp
tools/gfx/render-gl.cpp
tools/gfx/render-vk.cpp
tools/gfx/render.cpp
tools/gfx/render.h
tools/render-test/options.cpp
tools/render-test/options.h
tools/render-test/render-test-main.cpp
tools/slang-test/options.cpp
tools/slang-test/options.h
tools/slang-test/slang-test-main.cpp

* Make adapter used selectable on the command line (-adapter)
+ If set the device string must contain the specified substring
* Added 'adapter' to Renderer::Desc with dx11, dx12, vk honoring it
* GL will check that the renderer matches, but cannot select a specific adapter
* Share functionality on dx adapter selection in D3DUtil
Note - that on tests that use OpenGL and the adapter doesn't match it will ignore the test (and display a message that the appropriate device couldn't be started)

Adapter selection for Renderer

---

source/slang/parameter-binding.cpp
tests/reflection/default-space.slang
tests/reflection/default-space.slang.expected

If the user declares global shader parameters for D3D SM5.1+ or Vulkan, then they need to go into an appropriate `space` or `set`:
```hlsl
Texture2D    t; // should go in space/set 0
SamplerState s; // same here...
```
This also applies to allocation of spaces/sets to parameter blocks:
```hlsl
ParameterBlock<X> x; // should get space/set 0
ParameterBlock<Y> y; // should get space/set 1
```
In cases where there are a combination of explicitly and implicitly bound parameters, anything left implicitly bound goes into a "default" space/set:
```
ParameterBlock<X> x : register(space0); // this has claimed space/set 0
Texture2D    t; // this needs a space, so a "default" space/set of 1 will be claimed
SamplerState s; // this also needs a space/set, and will use the default
```
The logic for …

Improve logic for when a "default space" is needed

---

source/slang/emit.cpp
tests/vkray/closesthit.slang.glsl

Having `readonly buffer` on a shaderRecordNV storage buffer produces the following validation error in Vulkan. Removing it resolved the error.
```
[ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object: VK_NULL_HANDLE (Type = 0) | 
SPIR-V module not valid: Target of NonWritable member decoration is invalid:
must be the struct type of a uniform block or storage buffer
%_S1 = OpTypeStruct %MyConstants_0_0
```

Avoid SPIR-V validation error by removing readonly flag from shaderRecordNV buffer

---

.gitmodules
source/slang/emit.cpp
tests/compute/half-texture.slang.expected

This PR updates the version of glslang we depend on.
* This should pull in the fix for #937 that was made upstream.
* It also folds in our in-progress fix for KhronosGroup/glslang#1748, with the expectation that we will switch to a vanilla version of upstream glslang once a completed version of that PR is accepted.
* There was one extension that got renamed inside of the glslang compiler that required changes to how we emit GLSL code. It seems like the old name was effectively a bug (and our code has a comment about how it seemed weird), so this seems like a reasonable fix.

Update glslang version

---

source/slang/object-meta-begin.h
source/slang/object-meta-end.h

When building with VS2017, compilation failed for slang because of an 'unreachable code' warning is produced for code generated using macros - such as with expr-defs.h. The reason for warning couldn't be determined by visual inspection. To fix the warning is disabled when the macros are used via the 'object-meta-begin.h' and 'object-meta-end.h' include. 
It may worth looking into more in the future why VS2017 thinks there is a problem, and perhaps doing so will allow for a less heavy handed solution.

Fix 'unreachable code' stopping compilation on VS2017.

---

source/core/slang-io.cpp
source/core/slang-io.h
source/core/slang-shared-library.cpp
source/core/stream.cpp
source/slang/slang-file-system.cpp
tools/slang-test/options.cpp
tools/slang-test/slang-test-main.cpp
tools/slang-test/test-context.cpp
tools/slang-test/unit-test-path.cpp

* Make Path:: use lowerCamel method names as per coding standard
* Small improvements to make closer to standard
* GetDirectoryName -> getParentDirectory - previous method name's action was somewhat unclear, hopefully this is better

Bring Path class more inline with stated codebase conventions

---

source/slang/emit.cpp
tests/bugs/gh-941.slang
tests/bugs/gh-941.slang.glsl

Fixes #941
The GLSL we were emitting for unbounded-size arrays was the obvious:
```hlsl
// This HLSL:
Texture2D t[];
```
```glsl
// ... becomes this GLSL:
texture2D t[];
```
Unfortunately, the legacy GLSL behavior for an array without a declared size is what is called an "implicitly-sized" array, which means that it is assumed to actually have a fixed size, which is determined by the maximum integer constant value used to index into it (and only integer constants are allowed to be used when indexing into it).
Users hadn't noticed the issue for a while, because most of our users who rely on unbounded-size arrays were also using the HLSL `NonUniformResourceIndex` function:
```hlsl
float4 v = t[NonUniformResourceIndex(idx)].Sample(...);
```
When mapping such code to GLSL we use the …

Enable appropriate GLSL extension for unbounded-size resource arrays

---

source/slang/emit.cpp
source/slang/ir-clone.cpp
source/slang/ir-clone.h
source/slang/ir-inst-defs.h
source/slang/ir-insts.h
source/slang/ir-ssa.cpp
source/slang/lower-to-ir.cpp
source/slang/modifier-defs.h
source/slang/parser.cpp
tests/cross-compile/precise-keyword.slang
tests/cross-compile/precise-keyword.slang.glsl
tests/cross-compile/precise-keyword.slang.hlsl

Fixes #858
The `precise` keyword exists in both HLSL and GLSL and when applied to a variable declaration is supposed to indicate that all computations that contribute to the value of that variable should not be altered based on "fast-math" optimizations. The main examples are that separate multiply and add operations should not be turned into fused multiply-add (fma) operations, and that operations cannot ignore the possibility of infinity or not-a-number values (e.g., by assuming that `x * 0.0f` is always `0.0f`).
(Aside: it is possible that my understanding of what the semantics of `precise` are in HLSL and GLSL is imperfect so that either the GLSL variant isn't sufficient to provide the semantics of the HLSL keyword, or that the definition of "all computations that contribute" to a …

Initial support for the `precise` keyword

---

source/slang/ir-glsl-legalize.cpp

The gl_primitiveID built in type is int, but can be uint on HLSL. The change trys to cast for glsl targets to avoid glslang producing a type error.

Fix glsl geometry shader problem setting gl_primitiveID

---

source/slang/source-loc.cpp

Fix a buffer overrun that can occur when the last byte of the file is '\r' or '\n' and the byte adjacent to the last character in the file in memory is '\r' or '\n'.

HotFix: Fix a random crash that can occur due to a buffer overun.

---

slang.h
source/slang/reflection.cpp
source/slang/type-layout.cpp
source/slang/type-layout.h

Suppose I have an interface, and a simple implementation of it:
```hlsl
interface IModifier
{
float modify(float value);
}
struct Doubler : IModifier
{
float modify(float value) { return 2 * value; }
}
```
And now suppose I want to define an implementation that recursively uses the same interface:
```hlsl
struct MultiModifier : IModifier
{
IModifier first;
IModifier second;
float modify(float value)
{
value = first.modify(value);
value = second.modify(value);
return value;
}
}
```
And now consider that I might have a generic entry point that uses the interface:
```hlsl
void myShader<M : IModifier>( uniform M modifier, ... )
{ ... }
```
I can easily specialize `myShader` for `M = Doubler`, but in order to specialze it for `M = MultiModifier` I need a way to specify what the types of …

Basic layout and reflection for specialized types

---

docs/language-guide.md

I found this while I was reading the guide, I think this is what was intended to be there from the start.

[Update language-guide.md] Error on the associated types example

---

slang.h
source/core/slang-platform.h
source/core/slang-render-api-util.cpp

A previous PR changed the behavior of calculating shared library filenames. The change meant that on windows shared libraries when their name was calculated the '.dll' was added. This was necessary because other code now wanted to delete the dlls before creating them. Before it was not a problem because in windows if the .dll extension is left off the file is still correctly found and loaded.
Unfortunately in code that used the SharedLibrary slang module, when it new it was only used on windows, the file shared library was loaded with the .dll extension as part of the filename. That the SharedLibrary because it works across platforms, should not include the extension when loading (unless being loaded with the 'Platform' API methods). 
The fix just removes the .dll extension which was …

Fix shared library loading for testing.

---

source/slang/slang-parser.cpp

A literal like:
2.0h
is supposed to default to `half` precision, but there was a typo in our logic that meant that the `half` case was mistakenly checking for `l` and not `h` and so it would never trigger (because the `double` case right before it was checking for `l` first), and certainly wouldn't trigger on an `h`.
There was also a bug that a literal with `hf`:
2.0hf
would go into the path for the `f` suffix without considering the `h`.
These changes really ought to have some tests for them, but this was also just a quick issue I noticed while working on something else.

Fix bug in handling of `h` literal suffix.

---

.gitignore
slang-com-helper.h
slang.h
source/core/core.vcxproj
source/core/slang-writer.h
source/slang/slang-check.cpp
source/slang/slang-compiler.cpp
source/slang/slang-compiler.h
source/slang/slang-diagnostic-defs.h
source/slang/slang-diagnostics.h
source/slang/slang-emit.cpp
source/slang/slang-file-system.h
source/slang/slang-ir-link.cpp
source/slang/slang-parameter-binding.cpp
source/slang/slang-parser.cpp
source/slang/slang-reflection.cpp
source/slang/slang-type-layout.cpp
source/slang/slang-type-layout.h
source/slang/slang.cpp
source/slang/slang.natvis
source/slang/slang.vcxproj
source/slang/slang.vcxproj.filters
tests/compute/interface-shader-param-in-struct.slang
tests/compute/interface-shader-param3.slang
tests/compute/interface-shader-param4.slang
tests/reflection/parameter-block-explicit-space.slang.expected

This change is mostly about exposing a new API to the Slang compiler that allows more fine-grained control over the compilation flow. The basic concepts in the new API are:
* An `IGlobalSession` is the granularity at which we load/parse the Slang stdlib, and therefore gives applications a way to amortize startup cost for the library across multiple compiles. This is a concept that might be able to go away in a future version of Slang.
* An `ISession` owns all the code that gets loaded/compiled/generated. Any `import`ed modules are shared across everything in a session (we don't re-parse/-check the code when we see another `import` for the same module). Any generic- or interface-based code in the session can be specialized using types from the same session (but not necessarily across …

Start exposing a new COM-lite API

---

source/core/slang-string-util.cpp
source/core/slang-string-util.h
source/slang/slang-source-loc.cpp
tools/slang-generate/main.cpp
tools/slang-test/unit-test-string.cpp

* Make extractLine return a bool.
* Kept the special UnownedStringSlice for the end of text string (and for the ioText) - as works well with LineParser.

Change extractLine signature based on review of LineParser

---

source/core/slang-io.cpp

Remove the memory leak that is being reported on Visual Studio, due to getExecutablePath having a static local variable that is not freed before leaks are dumped. The solution is sort of clumsy, in so far as it just removes the cache. Would be nice to have a better way to handle such situations.

Hot fix: Remove getExecutablePath reported memory leak

---

source/slang/hlsl.meta.slang
source/slang/hlsl.meta.slang.h
tests/front-end/sincos.slang

The function was accidentally defined with a generic `int` parameter copy-pasted  from the vector definition, but that made the scalar version impossible to call with inferred generic arguments, because there wasn't a way to infer `N` when it isn't used in the parameter list.
Includes a simple test case to confirm that the front-end no longer chokes on calls to scalar `sincos()`.

Fix declaration of scalar sincos() function.

---

source/core/slang-gcc-compiler-util.cpp
source/slang/slang-emit-c-like.cpp
source/slang/slang-emit-c-like.h
source/slang/slang-emit-cpp.cpp
source/slang/slang-emit-cpp.h
source/slang/slang-emit-source-writer.cpp
source/slang/slang-emit-source-writer.h
source/slang/slang-emit.cpp
source/slang/slang-ir-insts.h
source/slang/slang-ir.cpp
source/slang/slang-ir.h
source/slang/slang-mangled-lexer.h
source/slang/slang-syntax.h
tests/cross-compile/c-cross-compile.slang
tests/cross-compile/slang-cpp-prelude.h
tools/slang-test/slang-test-main.cpp

* Preliminary support for outputting slang code as C++
* Handles most HLSL intrinsics
* Generates HLSL intrinsic functions on demand as needed
* Uses a 'c like' way to define vector and matrix types
* Uses a prelude file that defines scalar intrinsics 
One of the main things missing here is a ABI for communicating between the C++ code produced and client code. The code does test compiling slang code and C++, and that compilation doesn't produce any errors but does not execute that code. 
The generating of many of the intrinsics is fairly simple - but there are a few edge cases which are verbose and clumsy - such as with normalize, length, cross etc. That ideally we would define an implementation for these in the stdlib, and depending on the target it would choose a 'built in intrinsic' or …

WIP: slang to C++ code generation

---

source/slang/slang-emit-c-like.cpp
source/slang/slang-emit.cpp
source/slang/slang-ir-inst-defs.h
source/slang/slang-ir-insts.h
source/slang/slang-ir-link.cpp
source/slang/slang-ir-link.h
source/slang/slang-ir.cpp
source/slang/slang-lower-to-ir.cpp

This change adds back a little bit of explicit support for global constants in the IR, after a previous change completely removed the existing `IRGlobalConstant` node type.
The new `IRGlobalConstant` is *not* a parent instruction, and doesn't function at all like the old one.
Instead it is effectively a simple instruction that takes zero or one operands:
* The zero-operand case represents a constant with unknown value. This would usually come from another module, and thus would have an `[import(...)]` linkage decoration, so that after linking it resolves to a constant with a known value.
* In the one-operand case, the single operand represents the value of the constant, so that the operation semantically behaves like an identity function. It exists just to give decorations something to …

Add back a notion of IR global constants

---

source/slang/core.meta.slang
source/slang/core.meta.slang.h
source/slang/slang-check.cpp
source/slang/slang-diagnostic-defs.h
source/slang/slang-diagnostics.cpp
source/slang/slang-diagnostics.h
source/slang/slang-modifier-defs.h
source/slang/slang-parameter-binding.cpp
tests/diagnostics/overlapping-bindings.slang
tests/diagnostics/overlapping-bindings.slang.expected

Currently if the user gives two global shader parameters conflicting bindings, they get a warning diagnostic:
```hlsl
Texture2D a : register(t0);
Texture2D b : register(t0); // WARNING: overlapping bindings
```
This change adds a way to locally disable that warning using an attribute:
```hlsl
[allow("overlapping-bindings")] Texture2D a : register(t0);
[allow("overlapping-bindings")] Texture2D b : register(t0); // OK
```
Note that as a policy decision, the implementation requires `[allow("overlapping-bindings")]` on both declarations in order to disable the warning, under the assumption that the behavior should be strictly opt-in, and not silently affect a programmer who adds a new shader parameter with no knowledge or expectation of possible overlap.
The `[allow(...)]` attribute is …

Add an attribute to disable the overlapping-bindings warning

---

docs/cpu-target.md
source/core/slang-gcc-compiler-util.cpp
source/slang/slang-compiler.cpp
tests/cpp-compiler/c-compile-pass-through-shared-library.c
tools/slang-test/slang-test-main.cpp
tools/slang-test/test-context.cpp
tools/slang-test/test-context.h

* Simplify some of test code around CPPCompiler
* Test using 'callable' with pass-through
* Small cpu doc improvements
* Correctly set source code type for pass-thru
* Fix issue passing Clang output
* Handling 'severity for diagnostics for external tools

Small improvements around C/C++ testing

---

source/slang/slang-compiler.cpp

Fix bug where in emitCPUBinaryForEntryPoint for HostCallable doesn't correctly return the created SharedLibrary.

Fix bug with HostCallable not returning SharedLibrary correctly

---

source/slang/slang-diagnostic-defs.h
source/slang/slang-file-system.cpp
source/slang/slang-file-system.h
source/slang/slang-options.cpp
source/slang/slang.cpp
tests/preprocessor/file-identity/b.h
tests/preprocessor/file-identity/c.h
tests/preprocessor/file-identity/sub-folder/file-identity.slang
tests/preprocessor/pragma-once.slang

This adds a new test file-identity-test.slang that aims to explore #pragma once file identity. In part it is different in that files are relative by being in parent directories. 
There is another issue that the changed tests address. That by default slang handles includes (unless the include handler is replaced) with the OSFileSystem (now OSFileSystemExt). That this implements the ISlangFileSystemExt interface - so it owns the responsibility for uniquely identifying files, and that implementation uses canonical paths.
Clients may not want to implement the ISlangFileSystemExt interface - and that's fine and they can just implement ISlangFileSystem. If they do this, internally slang will wrap CachedFileSystem around it which *does* implement the ISlangFileSystemExt interface. 
The emulation …

A more convoluted #pragma once file identity test, using relative paths.

---

source/slang/slang-options.cpp
tests/preprocessor/file-identity/sub-folder/file-identity.slang
tests/preprocessor/pragma-once.slang

Internally slang uses the ISlangFileSystemExt interface. In typical usage this either uses the default configuration or a user supplied ISlangFileSystem. 
In default configuration ISlangFileSystemExt is *actually* CachedFileSystem, wrapping a OsFileSystemExt. When a user supplied ISlangFileSystem is used it is again wrapped in CachedFileSystem (say with using the `-file-system read-file`. 
So to test the interface and use another implementation other than CachedFileSystem the option `-file-system os` is added and tested on some #pragma include tests.

Added 'os' file-system testing

---

source/slang/slang-check.cpp
tests/compute/enum.slang

The set of supported operations in front-end constant folding was very limited: `+`, `-`, `*`, `/`, and `%`.
This meant that enum declarations like:
```
enum MyBits
{
A = 1 << 0,
B = 1 << 1,
C = A | C,
}
```
would fail to compile, with a claim that the expressions like `1 << 0` aren't compile-time constants.
This change adds `<<`, `>>`, `&`, `|`, and `^` to the list of integer operations we will cosntant-fold in the front-end. It also changes one of the declarations in the existing test case for `enum`s to use the added functionality.
Note that this change does *not* address the more deep-seated problems with our approach to constant-folding in the front-end. It does not change the constant folding to rely on IR machinery, or to allow for more general `constexpr` functions, and it does …

Support shifts and a few other ops in front-end constant folding

---

docs/cpu-target.md
prelude/slang-cpp-types.h
source/slang/slang-emit-cpp.cpp
source/slang/slang-ir-entry-point-uniforms.cpp
source/slang/slang-ir-inst-defs.h
tests/compute/entry-point-uniform-params.slang
tools/render-test/cpu-memory-binding.cpp
tools/render-test/cpu-memory-binding.h
tools/render-test/render-test-main.cpp
tools/render-test/shader-input-layout.cpp
tools/render-test/shader-input-layout.h
tools/render-test/shader-renderer-util.cpp
tools/slang-test/slang-test-main.cpp

* Uniform entry point params become separate parameter on CPU ABI
* Added isCPUOnly to binding information - explained below
* Update documentation to reflect ABI change
* entry-point-uniform-params.slang works
The main effort here was to make the CPU work more simply for uniform entry point params. This was achieved in part by making the uniform entry point params a separate parameter to the ABI function. This is also means that the reflection is more directly relevant, and there is no hidden knowledge that those parameters are just pointed to by a pointer at the end of the UnformState structure.
The change was achieved by marking global parameters that are created/moved from the entry point with the 'EntryPointDecoration'. Then in the c++ emit this information can be used to determine …

CPU uniform entry point params

---

source/slang-glslang/slang-glslang.cpp

In our 'multi-thread' story if client code wants to execute multiple parallel compilations via slang, the advice is to make multiple SlangSessions one per thread. It probably also makes sense to have a pool of such sessions and have worker threads, reuse them. The reason for this is that there is a significant cost associated with creating a session as doing so compiles the slang stdlib. 
As it turns out though, if the target was spir-v slang would use glslang in order to compile the output glsl. Unfortunately it appears that doing so was not thread safe and would cause a crash. To fix this...
* Have a single call to glslang::InitializeProcess() 
* Explicitly call glslang::InitThread
In the glslang api it says that glslang::InitializeProcess()  should be called once per *process*. We were …

Allow multiple threads to call glslang

---

slang.h
source/slang/slang-check.cpp
source/slang/slang-compiler.h
source/slang/slang-reflection.cpp
source/slang/slang.cpp

As I've been integrating the new/revised Slang API (using the "COM-lite" interfaces) I've run into some cases where the API was either missing features or didn't really work as originally implemented. This change fixes the gaps/problems that came up.
There are two main things here:
1. Some of the routines that returned an `IComponentType*` as a function result weren't actually doing anythign to retain the object they returned (e.g., putting it into a cache). Leaving aside the question of whether we need to add that caching layer, it made sense to instead have the return be through an output argument. Discussion after the initial iteration of the COM-lite API came around to the point that properly reference-counting objects that get returned would be useful if we ever decide we don't like …

Revisions to "new" Slang API based on use in Falcor

---

tests/compute/half-structured-buffer.slang

Disable D3D12 half-structured-buffer.slang test, as produces inconsistent results, confusing CI.

Disable half-structured-buffer.slang for D3D12

---

source/slang/slang-check.cpp
source/slang/slang-diagnostic-defs.h
source/slang/slang-emit-c-like.cpp
source/slang/slang-emit-c-like.h
source/slang/slang-emit-cpp.cpp
source/slang/slang-emit-cpp.h
source/slang/slang-emit-glsl.cpp
source/slang/slang-emit-hlsl.cpp
source/slang/slang-emit-hlsl.h
source/slang/slang-ir-inst-defs.h
source/slang/slang-ir-insts.h
source/slang/slang-lower-to-ir.cpp
source/slang/slang-modifier-defs.h
source/slang/slang-parser.cpp
source/slang/slang-reflection.cpp
tests/ir/string-literal.slang.expected

Added decorations for
IROutputControlPointsDecoration
IROutputTopologyDecoration
IRPartitioningDecoration
IRDomainDecoration
IRMaxVertexCountDecoration
IRInstanceDecoration 
IRNumThreadsDecoration
These are then used where appropriate in emitting instead of Attribute types which cannot be serialized.

IR types for subset of Attributes

---

source/slang/slang-compiler.cpp

Make CPU/C++ generate a single temporary file name basis that is used for both source (if source isn't available as a file) and binaries.

Use single filename basis for CPU generated source/binary

---

slang.h
source/slang/slang-compiler.h
source/slang/slang-emit-c-like.cpp
source/slang/slang-options.cpp

This change adds a `-obfuscate` command-line option (and corresponding API flag) that can be used to turn off the use of original source name information in generated HLSL/GLSL. This option can be used when clients of the Slang compiler would like to produce DXIL or SPIR-V that doesn't include information about the original names in their source program, but don't want to deal with IR-specific tools for stripping such information.
Note that this change does not address things like `#line` directives, which can technically be controlled by other flags, but might want to also be covered by `-obfuscate`.

Add ability to obfuscate name when generating GLSL/HLSL source

---

source/slang/slang-emit-c-like.cpp
source/slang/slang-emit-c-like.h
source/slang/slang-emit-cpp.cpp
source/slang/slang-emit-glsl.cpp
source/slang/slang-emit-glsl.h
source/slang/slang-emit-hlsl.cpp
source/slang/slang-emit-hlsl.h
source/slang/slang-ir-bind-existentials.cpp
source/slang/slang-ir-entry-point-uniforms.cpp
source/slang/slang-ir-glsl-legalize.cpp
source/slang/slang-ir-inst-defs.h
source/slang/slang-ir-insts.h
source/slang/slang-ir-legalize-types.cpp
source/slang/slang-ir-link.cpp
source/slang/slang-ir-union.cpp
source/slang/slang-ir.cpp
source/slang/slang-ir.h
source/slang/slang-legalize-types.cpp
source/slang/slang-legalize-types.h
source/slang/slang-lower-to-ir.cpp
source/slang/slang-type-layout.cpp
source/slang/slang-type-layout.h

This change builds on previous work that moves toward a more IR-based representation of layout.
Those steps added some instructions for representing layout in the IR (initially just proxies for the AST layout objects), and an explicit lowering pass that could build a target-specific IR module that binds parameters and entry points to layout information.
This change aims to complete that work, in the sense that the IR representation of layout is now self-contained and does not rely on having pointers back into the AST-level representation.
Achieving this requires two main kinds of work:
1. Update any code that used layout information derived from the IR (most notably all the `slang-emit-*` code) to use the new IR representation and its accessors.
2. Update any code that *constructs* …

User IR-based layout for all IR steps

---

docs/repro.md
slang.h
source/core/slang-io.cpp
source/core/slang-riff.cpp
source/core/slang-stream.cpp
source/core/slang-stream.h
source/core/slang-text-io.cpp
source/core/slang-text-io.h
source/slang/slang-compiler.h
source/slang/slang-file-system.cpp
source/slang/slang-ir-serialize.cpp
source/slang/slang-options.cpp
source/slang/slang-state-serialize.cpp
source/slang/slang-state-serialize.h
source/slang/slang.cpp

* Added support for serializing output filenames - such that now should be able to replicate most command line invocations exactly. 
* Added API functions spEnableReproCapture and spExtractRepro.
* Added MemoryStreamBase - which can be used to read from without copying the data.
* Small improvements to documentation. 
* Renamed Stream related method/variables to be closer to conventions

Expose more repro in API, support output params.

---

source/core/slang-relative-container.h
source/slang/slang-state-serialize.cpp
tools/slang-test/unit-relative-container.cpp

* Added comments/documentation to better describe Relative/Safe types and usage
* Renamed allocate methods to newObject/newArray on RelativeContainer.

Documentation around Relative types 

---

source/core/slang-riff.cpp
source/core/slang-riff.h
source/slang/slang-check-shader.cpp
source/slang/slang-compiler.cpp
source/slang/slang-compiler.h
source/slang/slang-ir-serialize.cpp
source/slang/slang-ir-serialize.h
source/slang/slang-lower-to-ir.cpp
source/slang/slang-options.cpp
source/slang/slang-parameter-binding.cpp
source/slang/slang.cpp
tests/serialization/serialized-module-entry-point-test.slang
tools/render-test/options.cpp
tools/render-test/options.h
tools/render-test/slang-support.cpp

The basic idea here is that when writing out a `.slang-lib` file based on a compile request, we include new sections in the generated RIFF that represent the entry points that were requested. The entry-point information is serialized in an entirely ad hoc fashion (a future change might clean it up to use the `OffsetContainer` machinery), and contains the name, profile, and mangled symbol name of an entry point.
When deserializing this information, we create a list of "extra" entry points that gets attached to the front-end compile requests. These "extra" entry points get turned into `EntryPoint` objects at the same place in the code that entry points specified on the command line or via API would be checked, but the extra entry points bypass the semantic checking and just create "dummy" …

Add basic support for entry points in `.slang-lib` files.

---

source/slang/slang-emit.cpp
source/slang/slang-ir-dce.cpp
source/slang/slang-ir-dce.h
source/slang/slang-lower-to-ir.cpp

* Removed strip pass from emit as no longer needed
* If obfuscate is enabled do strip on Layout
* Add option to keep insts that have layout decoration (else DCE strips layout)
* Add NameHint back in lowering - as strip now correctly removes. 
On last point we may want NameHintDecoration in some stages even with obfuscation, as long as they are removed appropriately at the end. One reason is such that earlier IR stages can give more meaningful error messages because NameHintDecorations are available to them.  
These fixes came out of trying to resolve how some symbols were leaking into slanglib and our emit code without a strip in emit.

Improvements around stripping and Obfuscation

---

source/core/slang-memory-arena.h
source/core/slang-random-generator.cpp
source/core/slang-random-generator.h
source/core/slang-riff.cpp
source/core/slang-riff.h
tools/slang-test/unit-test-riff.cpp

* Added option to get random bytes from RandomGenerator
* Added ability to allocate only in current block on MemoryArena
* Allowed RiffContainer to not allocate new Data blocks, if can just extend the Data it has (because it's at the end of current block and there is space for the new data).
* Added coverage for change on Riff unit test - for single block and multiblock

Riff Container Stream Writing

---

examples/cpu-hello-world/main.cpp

Fix ref counting bug in cpu-hello-world that meant session was not released correctly.
Care is needed with using ComPtr and spCreateSession. Create session returns a session with a ref count of 1. ComPtr on ctor/assigning adds a ref count. Neither is especially 'wrong'. With interfaces as out parameters, which is more common, this is less of an issue as using ComPtr, the method writeRef is used/needed.
There may be an argument for adding a method that that returns a SlangResult and outputs the session as an out parameter. 
```
{
/// Wrong - session will never be released. But is the most natural way to write the code.
ComPtr<ISlangSession> session(spCreateSession(nullptr));
}
{
/// Correct (albeit clunky)
ComPtr<ISlangSession> session;
session.attach(spCreateSession(nullptr));
}
```

Fix ref counting bug in cpu-hello-world

---

source/slang/slang-name.cpp
source/slang/slang-name.h
source/slang/slang-parameter-binding.cpp
source/slang/slang-reflection.cpp
source/slang/slang-type-layout.h
tools/render-test/slang-support.cpp
tools/slang-test/slang-test-main.cpp

* Added the name to the EntryPointLayout so is always available
* Made spReflectionEntryPoint_getName use name
* Improved checking for entry point name in render-test
* Improved COMPILE test type to allow failure and output of failure.
* Added getCStr(Name*)

Make spReflectionEntryPoint_getName work with entry point in a library

---

premake5.lua

This change adds the flag, but doesn't wire it up to anything.
The idea is to allow us to modify CI build scripts to use the flag in cases where it will be needed, so that we can later on disable building glslang from source by default, without an intermediate step where CI is broken.

Add a premake flag to control whether glslang is built from source

---

source/slang/slang-compiler.cpp
source/slang/slang-diagnostic-defs.h
source/slang/slang-options.cpp
source/slang/slang-profile.h

* Adds a new `-lang` slangc command line option that can precede an input file
* `-lang` valid options are `slang,hlsl,glsl,c,cxx`
* Can be used to override the file extension when using the slangc command line tool
* Any filenames that follow the option will be built using the translation unit specified

Add command line option to override language file extension

---

source/slang/core.meta.slang
source/slang/core.meta.slang.h
source/slang/hlsl.meta.slang
source/slang/hlsl.meta.slang.h
source/slang/slang-check-impl.h
source/slang/slang-compound-intrinsics.h
source/slang/slang-ir-inst-defs.h
source/slang/slang-ir-serialize.cpp
source/slang/slang-ir.cpp
source/slang/slang-ir.h
source/slang/slang-lower-to-ir.cpp
source/slang/slang-modifier-defs.h
source/slang/slang-stdlib.cpp
source/slang/slang-syntax.h
source/slang/slang.vcxproj
source/slang/slang.vcxproj.filters

Built-in functions in the Slang standard library can be marked with `__intrinsic_op(...)` to indicate that they should not lower to functions in the IR, and that instead call sites to those functions should be translated directly to the IR.
There are two cases where `__intrinsic_op(...)` gets used:
1. In the case where the argument to `__intrinsic_op(...)` is an actual IR instruction opcode, the IR lowering logic directly translates a call into an instruction with the given opcode. The arguments to the call become the operands of the instruction.
2. In the case where the argument to `__intrinsic_op(...)` is one of a set of "pseudo" instruction opcodes, the IR lowering logic directly handles the lowering to IR with dedicated code. The operands to the call might be handled differently …

Clean up the concept of "pseudo ops"

---

slang.h
source/slang/slang-compiler.cpp
source/slang/slang-compiler.h
source/slang/slang-diagnostic-defs.h
source/slang/slang-options.cpp
source/slang/slang.cpp

* Added ability to name the prefix for intermediates
* Allowed parameters after -load-repro - as pretty useful if somewhat risky thing to do (depending on parameters)

Added -dump-intermediate-prefix option

---

source/slang/slang-syntax.cpp
source/slang/slang-syntax.h

Profiling was showing that the internal routines behind `dynamic_cast` were the worst offenders in the whole codebase, and a lot of this was being driven by casting inside the semantic checking logic.
This change takes advantage of the fact that we *already* had a custom RTTI structure built up for the classes of syntax nodes that was previously being used to implement string->class lookup and factory services to support "magic" types and modifier in the stdlib (e.g., the way that a modifier declaration in the stdlib just lists the *name* of a C++ class that should be instantiated for it).
That RTTI information already included a pointer from each syntax class to its base class (if any), based on the restriction that the AST node types form a single-inheritance hierarchy.
The existing …

Add a custom RTTI implementation for the AST

---

source/slang/slang-check.cpp

If a locator is not set for a SlangPassThrough type, that doesn't *necessarily* mean that there isn't a suitable DownstreamCompiler. 
For example with the GENERIC_C_CPP option - it relies on *other* DownstreamCompilers to be present. This could also be fixed by say giving this type an empty locator, or special casing. The option chosen here, is to allow lookup even if there isn't a locator. Note that there is some special case handling, where a generic lookup, will prime all of the specific types.

Fix GenericCCPP compiler not being found

---

source/slang/slang-emit-cpp.cpp
source/slang/slang-emit-cpp.h
source/slang/slang-emit-cuda.cpp
source/slang/slang-emit-cuda.h
source/slang/slang-emit.cpp
source/slang/slang-ir-type-set.cpp
source/slang/slang-ir-type-set.h
tests/cuda/compile-to-cuda.slang

* Added 'clear' to IRTypeSet
* Fix scoping issue around the module used in CPPSourceEmitter and IRTypeSet - the IRTypeSet was being dtored after a module it referenced. 
* Removed need to add vector types for matrices on the fly
* Added addAllBuiltinTypes to find all built in types used from a module

Fix scoping issue around use of IRTypeSet

---

slang.h
source/slang/slang-reflection.cpp
tests/cross-compile/cpp-resource-reflection.slang.32.expected
tests/cross-compile/cpp-resource-reflection.slang.64.expected
tests/reflection/arrays.hlsl.expected
tests/reflection/attribute.slang.expected
tests/reflection/binding-gl.hlsl.expected
tests/reflection/binding-push-constant-gl.hlsl.expected
tests/reflection/buffer-layout.slang.1.expected
tests/reflection/buffer-layout.slang.expected
tests/reflection/cross-compile.slang.expected
tests/reflection/default-space.slang.expected
tests/reflection/explicit-register-space.slang.expected
tests/reflection/global-type-params.slang.expected
tests/reflection/matrix-layout.slang.1.expected
tests/reflection/matrix-layout.slang.expected
tests/reflection/multi-file.hlsl.expected
tests/reflection/parameter-block-explicit-space.slang.expected
tests/reflection/parameter-block.slang.1.expected
tests/reflection/parameter-block.slang.2.expected
tests/reflection/parameter-block.slang.expected
tests/reflection/reflect-imported-code.hlsl.expected
tests/reflection/reflection0.hlsl.expected
tests/reflection/resource-in-cbuffer.hlsl.expected
tests/reflection/sample-index-input.hlsl.expected
tests/reflection/sample-rate-input.hlsl.expected
tests/reflection/shared-modifier.hlsl.expected
tests/reflection/structured-buffer.slang.expected
tests/reflection/vertex-input-semantics.hlsl.expected
tools/slang-reflection-test/slang-reflection-test-main.cpp

This change adds some new entry points to the reflection API to cover corner cases that a majority of applications won't care about.
These are most likely to come up for users who want to make a complete copy of the Slang reflection information into a data format of their own design.
All of the information is stuff that we already computed as part of layout, and just hadn't exposed:
* Alignment information for type layouts. This is only useful for ordinary/uniform data; in all other cases alignment is always one. Even for uniform/ordinary data, it is unlikely that any application would actually make use of it.
* Layout information for the result of an entry point function. This would be useful for applications that need to enumerate the varying outputs (user- or system-defined) of a …

Cover a few corner cases in reflection API

---

source/slang/slang-reflection.cpp

If `spReflection_FindTypeByName` is called with a string that refers to the name of a variable instead of a type, then it ends up causing a fatal error to be diagnosed, leading to an `AbortCompilationException` being thrown. This exception then propagates up to the application that called `spReflection_FindTypeByName()`, which actually violates the contract for our `extern "C"` API.
This change adds a wrapper `try`/`catch` around the meat of the operation and turns any exception into a null result (this function has no other way to report errors to the caller).
It would be nice for a separate change to make the error message that caused the problem non-fatal, but that is orthogonal to this fix.

Catch exceptions inside FindTypeByName()

---

source/slang/slang-parameter-binding.cpp
tests/reflection/mix-explicit-and-implicit-spaces.slang
tests/reflection/mix-explicit-and-implicit-spaces.slang.expected

The logic for handling explicit `space`/`set` bindings on shader parameters for parameter blocks was not correctly marking the `space`/`set` that gets grabbed as used, and as a result it was possible for another parameter block that relies on implicit assignment to end up with a conflicting space.
This change fixes the original oversight, and adds a test case to prevent against regression.

Fix a bug in handling explicit register space bindings

---

docs/cuda-target.md
prelude/slang-cuda-prelude.h
source/core/slang-nvrtc-compiler.cpp
source/slang/slang-emit-cuda.cpp
source/slang/slang-type-layout.cpp
tools/render-test/cuda/cuda-compute-util.cpp
tools/render-test/cuda/cuda-compute-util.h

* CUDA implement StructuredBuffer/ByteAddressBuffer as pointer/count as is on CPU.
* Allow bounds check to zero index.
* Update docs
* Fix bug reporting from nvrtc when filename contained a drive letter 
* Update render-test to support StructuredBuffer/ByteAddressBuffer layout change

CUDA Structured Buffer/ByteAddressBuffer

---

source/slang/hlsl.meta.slang
source/slang/hlsl.meta.slang.h
tests/cross-compile/rw-buffer.slang
tests/cross-compile/rw-buffer.slang.glsl

This appears to have been an oversight in the work that added support for `imageStore` as well as atomics when writing to `RWTexture*` and friends. The HLSL/Slang `RWBuffer` type maps to GLSL as an `imageBuffer`, which is effectively just another case of writable texture image (bonus points to anybody who can explain to me the meaningful distinction between an `imageBuffer` and an `image1D`).
This change copies the handling of subscript access (`operator[]`) from textures over to buffers, and adds a test case to confirm that the new handling works for the simple case of setting a buffer element.

Add support for RWBuffer writes on GLSL/SPIR-V target

---

source/slang/slang-check-decl.cpp
source/slang/slang-check-expr.cpp
source/slang/slang-check-impl.h
source/slang/slang-diagnostic-defs.h
source/slang/slang-lookup.cpp
source/slang/slang-lookup.h
tests/bugs/keyword-undefined-identifier.slang
tests/bugs/keyword-undefined-identifier.slang.expected

The HLSL language has keywords with very common names like `triangle`, and Slang doesn't want to preclude users from using such names for their variables/functions/etc.
In addition, Slang adds new keywords on top of HLSL (like `extension`) and we don't want those to prevent us from compiling existing code.
As a result, almost all keywords in Slang are contextual keywords, and they can be shadowed by user varaibles.
The down-side to making all keywords contextual is that in a case like this:
```
int test() { return triangle; }
```
The identifier `triangle` is *not* undefined as far as lookup (it is defined as a modifier keyword), so the existing "undefined identifier" logic gets bypassed, and instead we ran into an internal compiler error trying to construct an expression that refers to a …

Improve behavior when undefined identifier is a contextual keyword

---

source/slang/core.meta.slang
source/slang/core.meta.slang.h
source/slang/slang-check-conversion.cpp
source/slang/slang-check-decl.cpp
source/slang/slang-check-expr.cpp
source/slang/slang-check-impl.h
source/slang/slang-diagnostic-defs.h
source/slang/slang-syntax.h
tests/diagnostics/parameter-already-defined.slang.expected
tests/diagnostics/variable-redeclaration.slang
tests/diagnostics/variable-redeclaration.slang.expected

This change turns checking for redeclarations into a dedicated phase of semantic checking, and ensures that it applies to the main categories of declarations: functions, types, and variables.
Note that "variables" here includes function parameters and `struct` fields in addition to the more obvious global and local variables.
Some of the logic for checking redeclarations already existed for functions, and was refactored to deal with other cases of declarations. The checking for functions still needs to be special-cased because functions are much more flexible about the kinds of redeclarations that are allowed.
In addition to improving the diagnosis of redeclaration itself, this change also changes the error message that is produced when referencing a symbol that is ambiguous due to begin …

Improve checks and diagnostics around redeclarations

---

source/slang/slang-lexer.cpp
source/slang/slang-lexer.h
source/slang/slang-parser.cpp
source/slang/slang-preprocessor.cpp

* Module local functions/static functions _ prefix
* m_ prefix member variables for classes with ctor/ (significant) methods
* Method names upper camel -> lower camel

Code standard changes for Lexer

---

source/slang/core.meta.slang
source/slang/core.meta.slang.h
source/slang/slang-emit-c-like.cpp
tests/compute/entry-point-uniform-params.slang
tools/render-test/cuda/cuda-compute-util.cpp
tools/render-test/cuda/cuda-compute-util.h
tools/render-test/render-test-main.cpp
tools/render-test/shader-input-layout.cpp
tools/render-test/shader-input-layout.h
tools/render-test/shader-renderer-util.cpp

* Add support for SampleLevel
* Fixed problem with Sample - used the wrong type
* Added $T 'special macro magic' option. 
* Fixed kernel launch for CUDA to take into account blocks
* Turned isCPUOnly hack into 'onlyCPULikeBinding'. Still horrible - but hey it now works on CUDA!

Fixes to make all CPU compute shaders work on CUDA

---

source/slang/slang-ir-glsl-legalize.cpp
tests/cross-compile/geometry-shader.slang
tests/cross-compile/geometry-shader.slang.glsl

We had been translating an `SV_PrimitiveID` input in a shader over to `gl_PrimitiveID` in GLSL.
That translation seemed to work just fine for users, so we thought it was correct.
It turns out that `gl_PrimitiveID` is the correct GLSL for a primitive ID input in every stage *except* a geometry shader.
In a geometry shader, `gl_PrimitiveID` is a primitive ID *output*, and if you want the input case you have to write `gl_PrimitiveIDIn` (note the `In` suffix).
This change sets aside my bewilderment at the above long enough to implement a workaround in the GLSL legalization step.
I also modified our current geometry shader cross compilation test to make use of an input primitive ID.

Fix output GLSL for primitive ID in a geometry shader

---

source/slang/slang-check-modifier.cpp
tools/slang-reflection-test/slang-reflection-test-main.cpp

There are two main fixes here:
The first is to remove a memory leak in the reflection test tool, in the case where Slang compilation fails. There is no real reason to be using the reflection test tool for tests that produce diagnostics (we have the slangc tool for that), but it makes sense to go ahead and fix the leak rather than work around it. This was one of those leaks that could have been avoided with smart pointers and a COM-lite API.
The second issue was that the logic for constructing an `AttributeDecl` based on a user-defined `struct` was not correctly setting the parent of the attribute decl. The code in question was a little hard to follow and had a few steps that didn't seem strictly necessary given its goals, so I went ahead and scrubbed+commented it to just do what made …

Make fixes for the attribute-error test case.

---

tools/slang-test/slangc-tool.cpp

Fix ref counting for session - simple test had a path to not releasing compile request.

Session ref count fix for test harness

---

source/slang/slang-ir-glsl-legalize.cpp
tests/cross-compile/sv-coverage.slang
tests/cross-compile/sv-coverage.slang.glsl

There were two overlapping issues here:
1. We always mapped `SV_Coverage` to `gl_SampleMask`, even though `gl_SampleMaskIn` is the correct built-in variable to use for an input varying.
2. We treated `gl_SampleMask` like it was a scalar shader input, when it and `gl_SampleMaskIn` are actually arrays of indeterminate size (as a byproduct of trying to future-proof for implementations that might support hundreds or thousands of samples per pixel...)
The fix here is simple: map to either `gl_SampleMask[0]` or `gl_SampleMaskIn[0]` as appropriate. I suppose that this approach doesn't handle the possibility of eventually supporting >32 samples per pixel by having something like `uint2 coverage : SV_Coverage`, but I think we can cross that bridge when we come to it.

Fix support for SV_Coverage on GLSL path

---

source/slang/hlsl.meta.slang

These new cases were added in DXR 1.1 (Shader Model 6.5), while the `enum` type came from DXR 1.0, so that I failed to revisit it when adding the new features.

Add two missing RAY_FLAG cases

---

source/slang/slang-check-expr.cpp
source/slang/slang-check-impl.h
source/slang/slang-check-overload.cpp
source/slang/slang-check-type.cpp
source/slang/slang-syntax.cpp
source/slang/slang-val-defs.h
tests/bugs/ray-flags-non-constant.slang
tests/bugs/ray-flags-non-constant.slang.expected

This arose when a user tried to specialize the DXR 1.1 `RayQuery` type to a local variable:
```hlsl
RAY_FLAG rayFlags = RAY_FLAG_CULL_FRONT_FACING_TRIANGLES | RAY_FLAG_CULL_NON_OPAQUE;
RayQuery<rayFlags> query;
```
In this case, we issued an error around `rayFlags` not being a constant as expected, but then we also crashes later on in checking because the `DeclRef` that was being used for the type had a null pointer for the generic argument corresponding to `rayFlags`.
The main fix here was thus to add an `ErrorIntVal` case that can be used to represent something that should be an `IntVal` but where there was some kind of error in the input code so that the actual value isn't known to the compiler.
A secondary fix here is that we were issuing error messages about expecting a constant for …

Fix a crash when a generic value argument isn't constant

---

source/slang/slang-ir.cpp

We currently represent the `groupshared` qualifier as a kind of "rate" at the IR level (where a rate can qualify a type to indicate the frequency/rate at which a value is stored and/or computed). This means that when computing the type that a pointer points to, we need to handle both, e.g., `Ptr<Int>` and `@GroupShared Ptr<Int>`.
The logic that was trying to handle the rate-qualified case when deducing the "pointee" type of a pointer was somehow written incorrectly, and was querying `getDataType()` on an `IRRateQualifiedType` which is asking for the type of the type itself (null in this case), rather than `getValueType()` which gets the `T` part from a rate-qualified type `@R T`.
Somehow none of our tests were hitting this case, and I'm not immediately clear on how to write a targeted …

Fix some IR logic around load from a rate-qualified pointer

---

source/slang/slang-syntax-base-defs.h
source/slang/slang-syntax.cpp
source/slang/slang-syntax.h
source/slang/slang.cpp

* Replaced getClass with getClassInfo on NodeBase
* Calculate a range for each ClassInfo that all sub classes must be in
* Implement dynamic cast/as inline
* Use range for dynamic casting
On Visual Studio nearly halves stdlib compile time on release.

Constant time dynamic cast

---

source/slang-glslang/slang-glslang.cpp
source/slang-glslang/slang-glslang.h
source/slang/slang-compiler.cpp

Safer binary compatibility between 1.0 and 1.1 versions, without using struct embedding, which can produce different results because of structs aligment requirements.

Improve glslang binary compatibility

---

prelude/slang-cuda-prelude.h
source/core/slang-nvrtc-compiler.cpp
source/slang/hlsl.meta.slang
tests/hlsl-intrinsic/wave-matrix.slang
tests/hlsl-intrinsic/wave-vector.slang

* Support vector and matrix types for Wave intrinsics
* Fix parsing issue for CUDA compiler output
* Better documentation of convergence issues
* Removed mask parameter from _wave functions in CUDA prelude

CUDA support for vector/matrix Wave intrinsics

---

docs/language-reference/02-lexcial-structure.md
docs/language-reference/03-preprocessor.md
docs/language-reference/04-types.md
docs/language-reference/05-expressions.md
docs/language-reference/06-statements.md
docs/language-reference/07-declarations.md
docs/language-reference/08-attributes.md
docs/language-reference/README.md

We already had the `language-guide.md` document under `docs/`, but this is an attempt to introduce a more full-featured reference to the Slang language and its features.
Right now it is mostly focused on the syntax and what the language allows to be declared, and it is a little light on semantic details throughout (mostly relying on familiarity with C to explain the things that are left unsaid). Even so, this hopefully provides a starting point to continue adding more detail.

First pass at a language reference

---

source/slang/core.meta.slang
tools/slang-test/slang-test-main.cpp

* Added diagnostic compare which ignores line number changes in std libs.
This is a rather brute force fix. That one of the tests bad-operator.slang was breaking every small change was made to stdlib. The reason for the fail was that line numbers are included in the output, and they would change, even though the actual diagnostic would not.
This fix looks for lines that aren't the same. If they are from the standard libraries, and the the actual diagnostic is the same the line is allowed to be equal. This only happens on tests marked as DIAGNOSTIC_TEST, and currently only if it's a 'simple test'.

Diagnostic compare special case for stdlib line number changes

---

source/slang/core.meta.slang
tests/diagnostics/bad-operator-call.slang.expected

* Remove RWTextureCube and RWTextureCubeArray - as not supported type.
* Put multisample code in a block to make nesting more readable.

Remove RWTextureCube/Array from stdlib

---

docs/target-compatibility.md
prelude/slang-cpp-prelude.h
source/slang/slang-emit-c-like.cpp
source/slang/slang-emit-c-like.h
source/slang/slang-emit-cpp.cpp
source/slang/slang-emit-cpp.h
source/slang/slang-emit-cuda.cpp
source/slang/slang-emit-cuda.h
source/slang/slang-emit-glsl.cpp
source/slang/slang-emit-glsl.h
source/slang/slang-emit-hlsl.cpp
source/slang/slang-emit-hlsl.h
tests/compute/loop-unroll.slang

* Add [unroll] support for CUDA
* Add a sort of placeholder support for [unroll] in C++
* Write up about unroll in target-compatibility.md
* Updated loop-unroll.slang so 
* Doesn't assume all threads happen simultaneously (they don't currently on CPU)
* Enable for other targets where it should work
That currently the DX12 DXC test is disabled, because it causes a crash. Not clear why yet (after all it works with DXBC).

Unroll target improvements

---

source/slang/slang-ir-specialize.cpp

The DXR `RayQuery` type is our first generic type defined in the stdlib that is marked as a target intrinsic but does *not* map to a custom `IRType` case. Instead, a reference to `RayQuery<T>` is encoded in the IR as an ordinary `specialize` instruction.
Unfortunately, this doesn't play nice with the current specialization logic, which considered a `specialize` instruction to not represent a "fully specialized" instruction, which then inhibits specialization of generics/functions that use such an instruction.
The fix here was to add more nuanced logic to the check for "fully specialized"-ness, so that it considers a `specialize` to already be fully specialized when the generic it applies to represents a target intrinsic.
I also added a note that the whole notion of "fully …

Fix a bug around generic functions using DXR RayQuery

---

tests/cross-compile/dxc-error.hlsl.expected

I'm not sure how this slipped in, but I know that I missed this when testing all my recent PRs because I end up havign a bunch of random not-ready-to-commit repro tests in my source tree which means I always get at least *some* test failures and have to scan them for the ones that are real. Somehow I have had a blind spot for this one.

Fix expected output for dxc-error test.

---

source/slang/slang-emit-c-like.cpp
source/slang/slang-emit-c-like.h
source/slang/slang-emit-glsl.cpp
source/slang/slang-emit-hlsl.cpp

For a long time the various source-to-source back-ends have been emitted the text `/* unhandled */` when they encounter an IR instruction opcode that didn't have any emit logic implemented. This choice had two apparent benefits:
* In most common cases, emitting `/* unhandled */` in place of an expression would lead to downstream compilation failure, so most catastrophic cases seemed to work as desired (e.g., if we emit `int i = /* unhandled */;` we get a downstream parse error and we know something is wrong.
* In a few cases, if a dead-but-harmless instruction slips through (e.g., a type formed in the body of a specialized generic function), we would emit `/* unhandled */;`, which is a valid empty statement.
It is already clear from the above write-up that the benefits of the policy …

Replace /* unhandled */ in source emit with a real error

---

source/slang/slang-parser.cpp

A previous changed attempted to perform more constant folding - in particular around prefix ops. One of the ops that was supported is !, but the simple logic used there assumed the type returned from the folding is the same as the originating type. That's not right for ! - as it will turn a float or int into a bool.
One fix would be to do the folding and emit true or false based on the literal. That's not the choice taken here though, that here the folding is just removed. 
That discussed elsewhere a more complete constant folding pass is probably wanted, and ideally it will only be implemented for one representation - probably the IR.

Fix for literal constant folding for not.

---

source/slang/slang-check-decl.cpp
tests/language-feature/static-members/generic-static-method.slang

The front-end logic that was testing if a member was usable as a static member neglected to unwrap any generic-ness and look at the declaration inside (the parser currently puts all modifiers on the inner declaration instead of the outer generic).
The test case included here is not a full compute test so that it only runs the front-end checking logic (where we had the bug).

Fix front-end handling of generic static methods

---

source/core/slang-string-util.cpp
source/core/slang-string-util.h
tests/cross-compile/dxc-error.hlsl
tools/slang-test/slang-test-main.cpp

There seem to be at least two official DXC versions that are reporting the same errors with different line numbers.
This was causing failures on some machines and not others. Some CI tests failed on some machines and others didn't. In particular this was a problem for dxc-error.hlsl.
The 'fix' here was to make the dxc-error.hlsl a diagnostic test, which is presumably should have been. Then there is a more difficult problem - that DXC diagnostic output does not match say standardized Slang diagnostic output. 
For now the 'fix' used here is to have special case handling for lines that start with 'dxc:', such that line/column numbers are ignored.
In the future we may want to remove this loosening of the test - because ideally the diagnostic *would* match. 
It could be argued adding the …

Workaround for matching of dxc diagnostics

---

source/slang/hlsl.meta.slang
tests/cross-compile/half-conversion.slang
tests/cross-compile/half-conversion.slang.glsl

These ended up being additional cases where we needed to use an explicit loop over components in the stdlib in order to produce valid GLSL output, but the existing declarations weren't doing it.
I added a very minimal cross-compilation test just to confirm that we generate valid SPIR-V for code using `f16tof32()`.

Fix stdlib definitions of half<->float conversion

---

source/slang/slang-check-decl.cpp
source/slang/slang-check-expr.cpp
source/slang/slang-check-impl.h
source/slang/slang-check-overload.cpp
source/slang/slang-lookup.cpp
source/slang/slang-syntax.h
tests/diagnostics/call-instance-from-static.slang
tests/diagnostics/call-instance-from-static.slang.expected

Currently we fail to diagnose code that calls an instance method from a static method using implicit `this`, and instead crash during lowering of the AST to the IR.
This change introduces a bit more detail to the "this parameter mode" that is computed during lookup, so that it differentiates three cases. The existing two cases of a mutable `this` and immutable `this` remain, but we add a third case where the "this parameter mode" only allows for a reference to the `This` type.
When turning lookup "breadcrumb" information into actual expressions, we respect this setting to construct either a `This` or `this` expression.
In order to actually diagnose the incorrect reference, I had to add code around an existing `TODO` comment that noted how we should diagnose attempts to refer to instance …

Diagnose attempts to call instance methods from static methods

---

tests/pipeline/ray-tracing/raygen.slang
tools/slang-test/slang-test-main.cpp

When running `slang-test`, the OptiX tests will be skipped by default for now, and must be explicitly enabled by adding `-category optix` on the command line.
I will need to add a better discovery mechanism down the line, closer to how support for different graphics APIs is being tested, but for now this should be enough to unblock our CI builds.

Disable OptiX tests by default.

---

source/slang/hlsl.meta.slang

This change makes the various `WaveActive*()` functions have default implementations that call `WaveMask*()` passing `WaveActiveMask()`. The new definitions will be used during CUDA code generation, which simplifies some of the duplication that was occuring in the `__target_intrinsic` modifiers.
This change does *not* add logic to make computation of `WaveGetActiveMask()` corect on CUDA, so these functions will still fail to provide the behavior that users need/expect. A future change will need to add logic to synthesize the value of `WaveGetActiveMask()` automatically.

Make stdlib WaveActive* call WaveMask*

---

tests/hlsl-intrinsic/byte-address-buffer/byte-address-16bit.slang

The CI system doesn't have a new enough dxc to support 16-bit load/store from byte-addressed buffers, so I am disabling the test for now.
A better long-term fix is to put an appropriate version of dxc into `slang-binaries` and use that for our CI tests.

Disable a test that was breaking on CI

---

appveyor.yml

We trigger releases by creating tags on GitHub, and ideally we try to include a commit log of stuff that changed since the previous release. Unfortunately, the way that AppVeyor CI is currently set up, it clobbers the information for a release (including its description) as part of the deployment step, so all releases just list `Slang <verison>` as the description even if the programmer manually created a suitable release log message.
This change tweaks a setting in `appveyor.yml` that seems (AFAICT from the documentation and various issues I've been reading) to make it so that AppVeyor will simply push the binary artifacts to the release if it already exists, rather than set all of the release information from scratch.
We will have to wait until we next do a release to see how this …

Try to stop AppVeyor from clobbering release logs

---

source/slang/slang-ast-base.h
source/slang/slang-ast-decl.h
source/slang/slang-ast-expr.h
source/slang/slang-ast-modifier.h
source/slang/slang-ast-reflect.h
source/slang/slang-ast-stmt.h
source/slang/slang-ast-type.h
source/slang/slang-ast-val.h

AST nodes now use the C++ extractor in order to generate the reflection material to make runtime casting work. 
That the definitions of AST nodes is somewhat complicated because we also want to declare a method on SLANG_CLASS tagged classes - the 'accept' method, but we don't want to do this for all classes. 
Prior to the C++ extractor this was achieved, by varying the macros when the 'base' types were included from the other types. With the extractor e have to inject the correct definition the first time the class is seen, as it's a regular C++ class.
In the prior C++ extractor version this was achieved by defining the specific implementation needed for each of the files in the file. This worked - but had a kind of code smell about it.
The challenge here is to at the point of injection …

Simplify AST reflection macros

---

slang.h

These are cases where the C-style API had the appropriate `SLANG_*` case defined, but the wrapper C++ `enum class` declaration didn't have a matching case.

Add a few missing enum cases to slang.h

---

source/slang/slang-check-shader.cpp
source/slang/slang-diagnostics.cpp
source/slang/slang-lexer.cpp
source/slang/slang-lower-to-ir.cpp
source/slang/slang-parameter-binding.cpp
source/slang/slang-parser.cpp
source/slang/slang-preprocessor.cpp
source/slang/slang-reflection.cpp
source/slang/slang-token.cpp
source/slang/slang-token.h
tools/slang-cpp-extractor/slang-cpp-extractor-main.cpp
tools/slang-profile/slang-profile-main.cpp

The 64 bits Token type was taking up 40 bytes per token, the changes here bring this down to 24. This was due to 3 reasons
* The token type/flags were each 32 bits by default
* Identifers can hold a pointer to a Name
* The lexeme is held as a UnownedStringSlice
To save space therefore we
* Use 8 bits for type/flags
* Have a union that either holds a Name* or chars* which is identified by a flag (rather than TokenType)
* We don't need to use a pointer sized value for the length of the lexeme, 32 bit is enough
The  current layout is still somewhat wasteful, with 6 bytes not being used on 64 bits.
```
struct Token
{
TokenType   type = TokenType::Unknown;
TokenFlags  flags = 0;
SourceLoc   loc;
uint32_t charsCount = 0;              ///< Amount of characters. Is set if name or not.
void* …
```

Reduce the size of Token

---

source/slang/slang-ast-base.h
source/slang/slang-ast-reflect.cpp
source/slang/slang-ast-reflect.h
source/slang/slang-ast-support-types.h
source/slang/slang-syntax.cpp

AST types had virtual accept methods, that would in turn call dispatch_X on the appropriate visitor. 
This code was generated via the output of the C++ extractor. One complication was that it required 'ABSTRACT' and 'NONE' (non ABSTRACT here) classes to inject different code in the SLANG_CLASS and SLANG_ABSTRACT_CLASS macros.
The change here uses the ASTNodeType and code generation to make the accept function not need to be virtual, and is replaced by a switch over appropriate types.
Note previously there was some special handling around IValVisitor. 
```
void Type::accept(IValVisitor* visitor, void* extra)
{
accept((ITypeVisitor*)visitor, extra);
}
```
I did produce something that emulated this behavior. But on looking into it some more it's kind of fragile - it assumes that IValVisitor …

Non virtual accept implementation on AST types

---

source/core/slang-gcc-compiler-util.cpp

Visual Studio issues a warning about this on systems using a code page that does not contain the character, causing build to fail due to the treat-all-warnings-as-errors setting.
Removing these offending characters fixes this issue.

Remove non-ascii characters from source file.

---

source/slang/slang-check-shader.cpp
source/slang/slang-compiler.cpp
source/slang/slang-diagnostics.cpp
source/slang/slang-diagnostics.h
source/slang/slang-options.cpp
source/slang/slang-parser.cpp
source/slang/slang.cpp
tools/slang-cpp-extractor/slang-cpp-extractor-main.cpp

* GetErrorCount -> getErrorCount
* Documented some of the more of how some of the more esoteric aspects of the sink works (like writer/outputBuffer)
* There is an argument to change this behavior - to say always output to a writer, and have an implementation that is String backed
* Made some members non public

Small improvements around DiagnosticSink

---

source/slang/slang-ast-base.h
source/slang/slang-ast-builder.cpp
source/slang/slang-ast-builder.h
source/slang/slang-ast-dump.cpp
source/slang/slang-ast-dump.h
source/slang/slang-ast-reflect.cpp
source/slang/slang-ast-reflect.h
source/slang/slang-ast-support-types.h
source/slang/slang-check-modifier.cpp
source/slang/slang-parser.cpp
source/slang/slang-syntax.cpp

* Made Substitutions derive from NodeBase
* Added astNodeType member to NodeBase
* Made getClassInfo non virtual (can do so because of astNodeType member)
* Set the astNodeType on creation via ASTBuilder - via init function (that can also set ASTBuilder - replacing setASTBuilder)
* Make all NodeBase construction through ASTBuilder create functions
* Made the ReflectClassInfo create function type take an ASTBuilder parameter, such that it is constructed through the ASTBuilder

NodeBase types constructed with astNodeType member set

---

source/slang/slang-emit-c-like.cpp
source/slang/slang-emit-c-like.h
source/slang/slang-emit-glsl.cpp
source/slang/slang-emit-glsl.h
source/slang/slang-emit.cpp

A fragment shader that uses ray casting features did not add the #version 460 requirement. This was correctly handled for ray tracing specific stages. 
* Added the 460 requirement when not in a 'ray tracing' stage
* Moved part of CLikeSourceEmitter setup into init, so that some GLSL setup could be moved into the GLSLSourceEmitter.

Bug fix problem with ray tracing from fragment shader

---

source/slang/slang-emit-cuda.cpp
source/slang/slang-emit-cuda.h
tests/hlsl-intrinsic/active-mask/for-break.slang
tests/hlsl-intrinsic/active-mask/for-continue-ext.slang
tests/hlsl-intrinsic/active-mask/for-continue.slang
tests/hlsl-intrinsic/active-mask/for.slang
tests/hlsl-intrinsic/active-mask/if-conditional-exit.slang
tests/hlsl-intrinsic/active-mask/if-early-exit.slang
tests/hlsl-intrinsic/active-mask/if-one-sided.slang
tests/hlsl-intrinsic/active-mask/if.slang
tests/hlsl-intrinsic/active-mask/switch-no-default.slang
tests/hlsl-intrinsic/active-mask/switch-trivial-fallthrough.slang
tests/hlsl-intrinsic/active-mask/switch.slang
tests/hlsl-intrinsic/wave-active-product.slang
tests/hlsl-intrinsic/wave-broadcast-lane-at.slang
tests/hlsl-intrinsic/wave-diverge.slang
tests/hlsl-intrinsic/wave-is-first-lane.slang
tests/hlsl-intrinsic/wave-matrix.slang
tests/hlsl-intrinsic/wave-prefix-product.slang
tests/hlsl-intrinsic/wave-prefix-sum.slang
tests/hlsl-intrinsic/wave-read-lane-at.slang
tests/hlsl-intrinsic/wave-shuffle-vk.slang
tests/hlsl-intrinsic/wave-shuffle.slang
tests/hlsl-intrinsic/wave-vector.slang
tests/hlsl-intrinsic/wave.slang

There are two fixes here:
* The code generation that follows active mask synthesis was requiring CUDA SM architecture version 7.0 for one of the introduced instructions, but not all of them. This change centralizes the handling of upgrading the required CUDA SM architecture version, and makes sure that the instructions introduced by active mask synthesis request version 7.0.
* The tests for active mask synthesis were not flagged as requiring the `cuda_sm_7_0` feature when invoking `render-test-tool`, which meant they run but produce unexpected results when invoked on a GPU without the required semantics for functions like `__ballot_sync()`. This change adds the missing `-render-feature cuda_sm_7_0` to those tests.

Fixes for active mask synthesis + tests

---

tools/slang-cpp-extractor/slang-cpp-extractor-main.cpp

When producing text from a stream of token care must be taken, as some concats can change meaning.
For example previously
```
'Thing' 'const' '*' -> Thingconst*
```
The change checks consecutive token types and adds a space if needed.

Fix problem with C++ extractor ernoneous concating of type tokens 

---

premake.bat

This change adds `./premake.bat` to the repository, which users in Windows (64-bit) can use to conveniently invoke the copy of premake that is pulled via the `slang-binaries` submodule. It should be possible to pass whatever options you passed to `premake5.exe` through to `premake.bat`. E.g., if you invoke:
```
.\premake.bat vs2015
```
then you should get the desired results for the project/solution files we want to check in.

Add a batch file for invoke premake

---

source/slang/slang-emit-cuda.cpp

CUDA output was broken from changes in #1396 
* Cast to UniformState
* Use KernelContext to name context.

Fix handling of UniformState from #1396

---

tools/slang-test/slang-test-main.cpp

The -api option (which is perhaps badly named), does have some effect in so far as it limits what tests can be synthesized. But that can already be explicitly controlled via synthesizedTestApis. 
The original intention I believe was to be able to limit tests, and it currently doesn't have that behavior. The fix, makes -api control which tests are run, by ignoring tests which require APIs that aren't specified in the -api line.  Note this only effects the execution of render-test tests. 
The -api line allows simple expressions to specify the apis to use
all-dx11    (all render APIs except dx11)
cpu+cuda (cpu and cuda)
etc
```
none - no render api 
all - all 'render apis'
gl,ogl,opengl
vk,vulkan
dx12,d3d12
dx11,d3d11
cpu
cuda
```

Fix -api to ignore tests if 'API' not specified

---

tests/compute/dynamic-dispatch-1.slang
tests/compute/dynamic-dispatch-2.slang
tests/compute/dynamic-dispatch-3.slang
tests/compute/dynamic-generics-simple.slang

When CUDA support is available, tests can be synthesized, and since it is derived from cpu path, the synthesizing code assumes a CPU compute test will work on CUDA. 
To disable it requires an explicit DISABLE_TEST(...) that specifies -cuda. This could be better.
I'm not clear in this if the CUDA tests were expected to work - but I'm assuming for now disabling is ok.

Disable dynamic dispatch tests on CUDA 

---

tools/gfx/vulkan/vk-device-queue.cpp

Only call m_api functions if m_api has been validly set on dtor of VulkanDeviceQueue.

Bug fix: Crash in dtor of VulkanDevice queue if init fails without setting m_api.

---

source/slang/slang-ast-serialize.cpp

This is an attempt to change code in `slang-ast-serialize.cpp` so that it doesn't trigger a warning(-as-error) in one of our build configurations.
The original code is fine in terms of expressing its intent, so the right answer might actually be to silence the warning.

Attempt to silence some warnings

---

tools/slang-cpp-extractor/slang-cpp-extractor-diagnostics.cpp
tools/slang-cpp-extractor/slang-cpp-extractor-main.cpp

* The diagnostic structure in Slang changed, but the macro wasn't altered in C++ extractor making diagnostics broken 
* Add a clause to catch uncaught exceptions and display an error in C++ extractor

Bug fix in C++ extractor

---

tests/hlsl-intrinsic/active-mask/for-break.slang
tests/hlsl-intrinsic/active-mask/for-continue-ext.slang
tests/hlsl-intrinsic/active-mask/for-continue.slang
tests/hlsl-intrinsic/active-mask/for.slang
tests/hlsl-intrinsic/active-mask/if-conditional-exit.slang
tests/hlsl-intrinsic/active-mask/if-early-exit.slang
tests/hlsl-intrinsic/active-mask/if-one-sided.slang
tests/hlsl-intrinsic/active-mask/if.slang
tests/hlsl-intrinsic/active-mask/switch-no-default.slang
tests/hlsl-intrinsic/active-mask/switch-trivial-fallthrough.slang
tests/hlsl-intrinsic/active-mask/switch.slang
tools/gfx/vulkan/render-vk.cpp
tools/gfx/vulkan/vk-api.h
tools/gfx/vulkan/vk-device-queue.cpp
tools/gfx/vulkan/vk-device-queue.h
tools/gfx/vulkan/vk-swap-chain.cpp
tools/gfx/vulkan/vk-swap-chain.h

The Slang test suite would fail Vulkan tests after around 50 tests have been executed. Subsequent tests would fail because the device creation would fail. 
On looking more carefully into the VKRenderer it appears that it doesn't destroy the vkDevice when the VKRenderer is destroyed. That adding the call caused other crashes. This was fixed by carefully destroying other resources before the vkDevice. 
Disabled all of the tests in active-mask directory as the results may change depending on driver version, and so lead to CI fails.

Fix for vulkan tests failing

---

source/slang/slang-ast-decl.h
source/slang/slang-ast-support-types.h
source/slang/slang-check-conformance.cpp
source/slang/slang-check-decl.cpp
source/slang/slang-check-impl.h
source/slang/slang-check-shader.cpp
source/slang/slang-check-type.cpp
source/slang/slang-check.cpp
source/slang/slang-compiler.h
source/slang/slang-lookup.cpp
source/slang/slang-syntax.cpp
source/slang/slang-syntax.h
source/slang/slang.cpp
tests/bugs/extension-lifetime.slang
tests/diagnostics/extension-visibility-a.slang
tests/diagnostics/extension-visibility-b.slang
tests/diagnostics/extension-visibility-c.slang
tests/diagnostics/extension-visibility.slang
tests/diagnostics/extension-visibility.slang.expected
tests/language-feature/extensions/extension-import-helper.slang
tests/language-feature/extensions/extension-import.slang

During semantic checking, the compiler used to link together `ExtensionDecl`s into a singly-linked list dangling off of the `AggTypeDecl` that they applied to. This approach made lookup relatively easy, because given a `DeclRef` to an `AggTypeDecl` one could easily find and walk the list of candidate extensions.
Unfortunately, the simple approach has two major strikes against it:
* First, as we recently ran into, it creates a lifetime/ownership problem, in cases where the `ExtensionDecl` is outlived by the `AggTypeDecl` it applies to. This creates the one and only place in the compiler today where an "old" AST node might point to a "new" AST node, and it resulted in use-after-free problems in client code.
* Second, the scoping of `extension`s ends up being completely wrong. All of the …

Fix the way extension declarations are cached for lookup

---

source/slang/slang-check-decl.cpp
source/slang/slang-check-overload.cpp
source/slang/slang-diagnostic-defs.h
tests/diagnostics/interfaces/mutating-impl-of-non-mutating-req.slang
tests/diagnostics/interfaces/mutating-impl-of-non-mutating-req.slang.expected
tests/diagnostics/methods/mutating-method-on-rvalue.slang
tests/diagnostics/methods/mutating-method-on-rvalue.slang.expected

There are two main bug fixes here:
* We were failing to diagnose when code calls a `[mutating]` method on a value that doesn't support mutation (that is an r-value instead of an l-value).
* We had a bug in the synthesis logic for interface requirements where we used the *result* type of the requirement in place of each of the *parameter* types.
The second bug made synthesis often produce incorrect signatures with `void` parameters.
The first bug meant that even though a `[mutating]` method should not be able to satisfy a non-`[mutating]` method (and we had code to enforce this for the "exact match" case), when we go on to try and synthesize a non-`[mutating]` method that satisfies the requirement by delegating to the user-written one, it would end up succeeding, because nothing was …

Fix bugs related to mutating implementations of interface methods

---

source/slang/slang-emit-c-like.cpp

The logic that detects intrinsic functions during emit was not able to properly detect an intrinsic generic method nested in a generic type. The basic problem was that this led to a `specialize(specialize(...), ...)` in the IR, which wasn't being handled (only one level of `specialize` was handled). The fix is local and simple.
The larger issue was that the author of this commit had thought our IR ruled out nested generics like this, when in fact that is precisely how we handle nested generics throughout the IR. This oversight/misunderstanding means that we might have broken passes in other places that assume nested generics cannot happen. This change doesn't pretend to fix that other issue, but we should pay attention to it.

Fix support for nested generic intrinsics

---

source/slang/slang-emit-c-like.cpp
source/slang/slang-emit-c-like.h
source/slang/slang-emit-cuda.cpp
source/slang/slang-emit-cuda.h
source/slang/slang-emit.cpp
source/slang/slang-ir-explicit-global-context.cpp
source/slang/slang.vcxproj
tools/render-test/cuda/cuda-compute-util.cpp

The Big Picture
===============
Given input Slang code like:
```hlsl
Texture2D gA;
[shader("compute")]
void kernelFunc(uniform Texture2D b, uint3 tid : SV_DispatchThreadID)
{ ... }
```
the existing CUDA code generation strategy would always generate a kernel with a signature like:
```c++
struct GlobalParams { Texture2D gA; }
struct EntryPointParams { Texture2D b; }
extern "C" __global__
void kernelFunc(EntryPointParams* entryPointParams, GlobalParams* globalParams)
{ ... }
```
This choice was consistent with the conventions of the CPU kernel target, and shares the advantage that it is easy for the user to data-drive the logic for filling in parameters and then invoking a kernel.
However, the approach outlined above has two serious problems when used for CUDA kernels:
* First, it defies …

Change parameter passing convention for CUDA

---

source/core/slang-riff.h
source/slang/slang-ir-serialize.cpp

As an optimization inside of the IR serialization, when it compresses lists of uint32_t (instructions or whatever). The result of the compression is to store the result in a List<uint8_t>. As an optimization the implementation attempted not to copy and reallocate memory, by just taking the allocation of the contents of the list, and giving ownership to the RiffContainer (which then gave it to the MemoryArena). 
Unfortunately this is a serious bug - because memory in the list is allocated via new T[N], and so it can only be freed with delete []. MemoryArena only deals with chunks of memory through malloc and free. Using free on something allocated with new T[N] is as serious error that will typically lead to the memory not being freed and/or crash, but worse leaving the memory system in a …

Bug fix for incorrect freeing of memory allocated in List in IR serialization

---

prelude/slang-cpp-types.h
source/slang/slang-diagnostic-defs.h
source/slang/slang-ir-any-value-marshalling.cpp
source/slang/slang-ir-any-value-marshalling.h
source/slang/slang-ir-insts.h
source/slang/slang-ir-lower-generics.cpp
source/slang/slang-ir.cpp
source/slang/slang.vcxproj
source/slang/slang.vcxproj.filters
tests/diagnostics/interfaces/anyvalue-size-validation.slang
tests/diagnostics/interfaces/anyvalue-size-validation.slang.expected

This change adds a new subpass to `lower-generics` that generates implementations for the `packAnyValue` and `unpackAnyValue` pseudo instructions.
Specifically, the pass:
- Generates a `struct` type for each `IRAnyValueType` defined in the IR module. For example, `IRAnyValueType(size:8)` would lower into: 
```
struct AnyValue8
{
uint field0;
uint field1;
};
```
- For each concrete type involved in a `packAnyValue` or `unpackAnyValue` instruction, generate packing and unpacking functions between the type and the generated `AnyValueN` type. The packing functions recursivesly reads/writes every element of the concrete type, following a special layout rule detailed below. For example, 
```
struct A {int a; float b;}
struct B : ISizeIs16 {float c[2]; A t; }
```
The `packAnyValue` function for …

AnyValue packing/unpacking pass.

---

source/slang-glslang/slang-glslang.cpp

In glslang upgrade a change was made to automatically set the majority of TBuiltInResource in glslang. Unfortunately this missed the member `minProgramTexelOffset` which should be -UNLIMITED.

Glslang texel offset bug fix

---

slang.h
source/slang/slang-ast-support-types.h
source/slang/slang-check-decl.cpp
source/slang/slang-compiler.h
source/slang/slang-emit-cpp.cpp
source/slang/slang-ir-generics-lowering-context.cpp
source/slang/slang-lower-to-ir.cpp
source/slang/slang.cpp

This PR includes a series of changes to expose witness tables and RTTI objects in the compiled DLL, and provide a reflection function to get the mangled name of a type witness. These changes allows the host to fill in an existential value.
Detailed changes:
- Ensure that witness tables and RTTI objects are defined with the `extern "C"` modifier in the generated C++ code.
- RTTI objects use the mangled name of the type directly, so that can be queried using the type's mangled name directly from the resulting DLL.
- Expose `Linkage::getTypeConformanceWitnessMangledName` to return the mangled name of witness tables to the host.
- Ensure that all witness tables (including those for associated types) have proper mangled name.

Export witness table and RTTI objects in compiled libraries.

---

source/slang/slang-ast-serialize.cpp
source/slang/slang-ast-support-types.h
source/slang/slang-ast-val.cpp
source/slang/slang-ast-val.h
source/slang/slang-check-conformance.cpp
source/slang/slang-check-expr.cpp
source/slang/slang-check-overload.cpp
source/slang/slang-lookup.cpp
source/slang/slang-lower-to-ir.cpp
tests/compute/extension-on-interface.slang

In order to undestand this change, it is important to undestand how lookup through base interfaces works prior to this change. In order to understand *that* it helps to be reminded of how inheritance relationships get encoded in the AST.
Suppose the user writes:
struct Base { int val; }
struct Derived : Base { ... }
...
Derived d = ...;
int v = d.val;
The question is how an expression like `d.val` gets semantically checked, and how it is encoded into the IR after semantic checking. You might assume it gets checked and encoded so that we end up with:
int v = ((Base) d).val;
and that seems like it should Just Work... so of course that isn't what Slang has been doing. Instead, we relied on the fact that the inheritance relationship `Derived : Base` is represented as an `InheritanceDecl` …

Clean up the way that lookup "through" a base type is encoded

---

source/slang/slang-ast-support-types.h
source/slang/slang-check-decl.cpp
source/slang/slang-check-impl.h
source/slang/slang-hlsl-intrinsic-set.cpp
source/slang/slang-hlsl-intrinsic-set.h
source/slang/slang-ir-link.cpp
source/slang/slang-lower-to-ir.cpp
source/slang/slang-syntax.cpp

Most people agree that it is a Good Thing when compilers are deterministic: the exact same input bits produce the exact same output bits every time the compiler is run. Bonus points are awarded if the results are independent of the platform the compiler was compiled for and run on.
One of the easiest kinds of nondeterminism to have sneak into a compiler is for it to produce the "same" code inside functions, but sometimes emits functions or other global symbols in a different order from run to run. Right now, the Slang compiler has some of this kind of nondeterminism.
The main way (but not necessarily the only way) that a compiler ends up producing output with a different ordering across runs is by iterating over the contents of a hash-based container (in our codebase, a `Dictionary` or …

Avoid nondeterministic ordering of output

---

source/core/core.vcxproj
source/core/core.vcxproj.filters
source/core/slang-dictionary.h
source/core/slang-linked-list.h
source/slang/slang.vcxproj

This PR adds back `EnumerableDictionary` that was previously removed and named it `OrderedDictionary` and `OrderedHashSet`.
`OrderedDictionary`s stores key value pairs in a separate linked list to support deterministic iterating order and still allows fast removal.

Add OrderedDictionary to core.

---

slang.h
source/core/slang-platform.cpp
source/core/slang-platform.h
source/core/slang-shared-library.cpp
source/core/slang-shared-library.h
source/slang/slang.cpp
tools/render-test/cpu-compute-util.cpp
tools/render-test/cpu-compute-util.h
tools/render-test/render-test-main.cpp
tools/render-test/shader-input-layout.cpp
tools/render-test/shader-input-layout.h
tools/slang-test/slang-test-main.cpp

This change adds support for specifying dynamic existential shader parameter values in render-test.
Specifically:
1. allow two new types of element in a `data=[]` block: `rtti(typename`) and `witness(c, I)`, so this is now valid:
```
//TEST_INPUT:cbuffer(data=[rtti(MyImpl) witness(MyImpl, IInterface) 1 0], stride=4):
ConstantBuffer<IInterface> gCb;
```
2. Add a new `spCompileRequest_getSession` to get a `ISession` handle from the legacy end-to-end compile request object. This allows the test infra to call `Linkage::getTypeConformanceMangledName`.
3. Add `CPUComputeUtil::populateRTTIEntries` that is run as a setup step, which fills in actual rtti pointer values in the data buffer of the provided `shaderInputLayout`.

Support dynamic existential shader parameters in render-test

---

source/slang/hlsl.meta.slang

Fixes GitLab issue 85
These functions are intrinsic for HLSL, but were not marked as such, leading to emitting code that manually loops for the vector case. The looping code resulted in lower performance for some users, because apparently dxc was unable (or unwilling?) to unroll the loop, and ended up generating temporary ("stack-allocated") arrays for the vectors produced.
As a longer-term solution, we may need to consider how the `VECTOR_MAP...` and `MATRIX_MAP...` idioms used in the stdlib get lowered, so that we can emit fully-unrolled versions in cases where the vector/matrix shape is known at the time we generate code. This PR does not attempt to address that larger issue.

Mark f32tof16 and f16tof32 as HLSL intrinsics

---

source/slang/slang-type-layout.cpp
source/slang/slang-type-layout.h

As a part of dynamic dispatch support, this change reworks the type layout rules for existential typed shader parameters.
Currently, a type layout contains a `base` part and a `pending` part. An incomplete type (that contains existential fields) will have all the ordinary parts laid out first in the `base` part, and all existential fields placed in the `pending` part. When the type is specialized (and becomes a `ExistentialSpecailizedType`, the concrete type used to specialize the existential gets filled in in the `pending` part of the layout and comes after all the ordinary fields.
The original `base` and `pending` layout mechanism is designed to allow variable sized fields on targets that does not support pointers, since if we had pointers, any values that has unknown size at layout …

Rework type layout for ExistentialSpecializedType

---

source/slang/slang-compiler.cpp

The refactorings that added support for multiple entry points in an output file seemingly introduced a regression such that we crash on compilation that is not "end-to-end." Unfortunately, all of our testing only covers end-to-end compilation, and many users only use that mode.
I've added a fix for the issue I ran into, but I haven't addressed the testing gap in this change. Without adding testing for non-end-to-end compilation, I expect further regressions to slip in over time.

Fix a crashing issue for non-end-to-end compilation

---

source/slang/slang-compiler.cpp
source/slang/slang-emit-cpp.cpp
source/slang/slang.cpp

* If a blob is not returned from CompileResult return a failure
* Test for failures when getBlob is used
* Make spGetEntryPointCode handle lack of blob gracefully

Improvements around CompileResult::getBlob 

---

source/slang/slang-emit-cpp.cpp
source/slang/slang-emit-cpp.h
source/slang/slang-ir-any-value-marshalling.cpp
source/slang/slang-ir-deduplicate.cpp

Bug fixes for dynamic dispatch compiler passes.
- Prevent redundant witness table types being emitted.
- Prevent lower-generic passes that does in-place instruction modification from corrupting `IRSharedBuilder::globalValueNumberingMap` and `IRSharedBuilder::constantMap`s.

Dynamic dispatch bug fixes.

---

source/core/slang-nvrtc-compiler.cpp
source/slang/slang-check.cpp
source/slang/slang-compiler.cpp
source/slang/slang-compiler.h
source/slang/slang-diagnostic-defs.h
tools/slang-test/options.h

The main change here is that when locating the NVRTC compiler we try multiple library names and take the first one that loads successfully (with an ordering that means we try newer versions before older ones).
In order to support this change, I needed to fix the wrapping logic that invokes the downstream compiler "locator" function, so that it does not report every failed dynamic library load as an error diagnostic (leading to compilation failure), but instead only reports such failures once the locator has reported failure.
The form of the diagnostic output for failures is also changed, in that we now report a single umbrella error about failing to load a downstream compiler, and then report the actuall dynamic library load failures as notes on that diagnostic instead of errors of their …

Search for multiple NVRTC versions

---

prelude/slang-cuda-prelude.h

The logic we use to compute `SV_DispatchThreadID` and friends for CUDA makes use of the `gridDim` and `blockDim` built-in variables in CUDA. These variables have type `dim3` which is similar to `uint3` but is considered a distinct type for some reason.
The logic for computing the `SV`s currently pretends that `gridDim` and `blockDim` are `uint3`s, and this means that the code they emit doesn't always compile cleanly (although it does in our existing test cases...).
This change adds a few overloads that work on `dim3` to the CUDA prelude and that seem to make the code we emit work again.
Note: This change should be seen as a somewhat hacky quick fix rather than a real resolution to the underlying issue. It is probably better if we emit code that replaces uses of `gridDim` with …

Fix some issues around dim3 for CUDA

---

source/slang/slang-parameter-binding.cpp

The `SimpleScopeLayoutBuilder` helper that is used to build up binding information for entry-point parameter lists has logic to try to support both explicit and implicit binding of parameters. This logic was added as part of supporting dual-source color blending on Vulkan. The basic approach is similar to that used for the global scope, where parameters with explicit binding first "carve out" the ranges they claim via a `UsedRangeSet`, and then parameters without explicit binding allocate space from what is left.
The logic is (seemingly by accident) also applied to uniform/ordinary data, which creates a problem because the `ScopeLayoutBuilder` base type is also responsible for computing a layout for uniform/ordinary data that is 100% implicit (while dealing with all the relevant alignment …

Fix an issue with double-counting uniform data for CUDA/CPU

---

source/slang/slang-emit-c-like.cpp
source/slang/slang-emit-c-like.h
source/slang/slang-emit-cuda.cpp
source/slang/slang-emit-cuda.h
source/slang/slang-ir-link.cpp
source/slang/slang-ir.cpp
tests/bugs/vk-image-atomics.slang.glsl
tests/compute/dynamic-dispatch-10.slang
tests/compute/dynamic-dispatch-11.slang
tests/compute/dynamic-dispatch-12.slang
tests/compute/dynamic-dispatch-13.slang
tests/compute/dynamic-dispatch-2.slang
tests/compute/dynamic-dispatch-3.slang
tests/compute/dynamic-dispatch-4.slang
tests/compute/dynamic-dispatch-5.slang
tests/compute/dynamic-dispatch-6.slang
tests/compute/dynamic-dispatch-7.slang
tests/compute/dynamic-dispatch-8.slang
tests/compute/dynamic-dispatch-9.slang
tests/cross-compile/sv-coverage.slang.glsl
tests/slang-extension/atomic-float-byte-address-buffer-cross.slang.glsl
tests/vkray/intersection.slang.glsl

This change enables all the remaining dynamic dispatch tests on CUDA.
The main issue being addressed is that some global temporaries are not being emitted to CUDA code correctly (missing the `__device__`) specifier, and caused CUDA compiler to fail. The fix is to overload `emitTempModifiers` for CUDA and emit an `__device__` specifier there.
The second issue is that none of these temporaries are necessary (e.g. `getAddress(witnessTable)`) as they should be folded as an expression. They are somehow being emitted because the logic around pointer type is over conservative.
The last issue is that the handling of `public` modifiers in linking step should be turned on for CUDA in addition to C++ target.

Enable all dynamic dispatch tests on CUDA.

---

source/slang/slang-emit-c-like.cpp

This problem is only visible when
* using `RWByteAddressBuffer.Load<V>`,
* when `V` is `vector<T,N>`,
* and `V` is a non-32-bit type
In such a case, the Slang compiler generates output HLSL like:
someBuffer.Load<vector<T,N>>(someOffset);
and dxc balks because it fails to parse the `>>` as closing the generics, and instead parses it as a shift operator.
The solution here is simple: add a space before the closing `>` when emitting a `.Load<T>` operation.
Note that this change does not come with a test fix *yet* because writing the test case exposed a more complicated issue with GLSL codegen for this same scenario. This change includes the simple single-byte fix, to unblock users while we work on a fix for the GLSL case (and that fix will include the test coverage).

Fix a bug around byte-address buffer loads of vectors

---

examples/cpu-hello-world/main.cpp
examples/cpu-hello-world/shader.slang
slang.h
source/slang/slang-compiler.cpp
source/slang/slang-compiler.h
source/slang/slang-options.cpp
source/slang/slang.cpp

This change exposes a new target flag: `SLANG_TARGET_FLAG_GENERATE_WHOLE_PROGRAM` that can be set on a target with `spSetTargetFlags`. When this flag is set, `spCompile` function generates target code for the entire input module instead of just the specified entrypoints. The resulting code will include all the entrypoints defined in the input source.
The resulting whole program code can be retrieved with two new functions: `spGetTargetCodeBlob` and `spGetTargetHostCallable`.
This change also cleans up the unnecessary `entryPointIndices` parameter of `TargetProgram::getOrCreateWholeProgramResult`, and modifies the `cpu-hello-world` example to make use of the new whole-program compilation API to simplify its logic.

Add API for whole program compilation.

---

source/slang/slang-emit-cuda.cpp

This change defines witness tables and RTTI objects as `__constant__` global values in CUDA instead of `__device__` to make sure they are placed in constant memory.

Make RTTI objects `__constant__` in CUDA

---

source/slang/slang-lower-to-ir.cpp
tests/bugs/multiple-definitions.slang

The basic problem here is that when a function has multiple declarations with matching signatures (e.g., a forward declaration and then a later definition with a body), the IR lowering logic would lower all declarations whenever the first one was encountered, but then would only register an IR value as the lowered version of the first declaration. Other matching declarations would then run the risk of being lowered again, and in the case where they included features like loops with break/continue labels, that would create the risk of keys getting inserted into certain dictionaries more than one, leading to exceptions.
This change ensures that when lowering a function that has multiple matching declarations to IR, we register an IR value for all of those declarations and not just the …

Fix a bug in IR lowering

---

source/slang/slang-ir-lower-generic-call.cpp
source/slang/slang-ir.cpp
source/slang/slang-ir.h

This change makes dynamic dispatch pass to bottleneck all interface method calls through dedicated dispatch functions.
For example, when we see `call(lookup_interface_method(witnessTable, reqKey), args)`, we will create a dispatch function `IInterface_MethodName`, and change the call to `call(IInterface_MethodName, witnessTable, args)`.
This allows us to implement the dispatch logic differently based on the target we emit code for.
Currently the `IInterface_MethodName` function is still implemented as `call(lookup_interface_method(witnessTable, reqKey), args)`. This change sets up the stage for a `switch` statement based dispatching logic implementation for GPU targets.

Bottleneck interface dispatch calls through a single function.

---

source/slang/slang-ir-generics-lowering-context.h
source/slang/slang-ir-lower-generic-call.cpp
source/slang/slang-ir-lower-generics.cpp
source/slang/slang-ir-specialize-dispatch.cpp
source/slang/slang-ir-specialize-dispatch.h
source/slang/slang.vcxproj
source/slang/slang.vcxproj.filters
tests/compute/dynamic-dispatch-13.slang

Our previous implementation of dynamic dispatch makes use of function pointers on both CPU and GPU. Upon initial performance benchmarks, we observed very slow performance of function-pointer calls on CUDA. Combined with CUDA's restriction that all functions callable from a function pointer must be defined in the same CUDA module, the function-pointer based implementation is not beneficial in anyways in practice.
This change adds a new subpass `specializeDispatchFunctions` to the `lower-generics` pass that modifies the dispatch functions introduced in #1584 with `if` statement based dispatch logic. This subpass is enabled on GPU targets only.
Currently the dispatch function produced by this pass will perform cascaded `if` comparisons on the witness table argument to all witness tables of …

Generate `if` based dispatch logic on GPU targets.

---

.gitignore
slang.h
source/slang/slang-compiler.h
source/slang/slang-ir-inst-defs.h
source/slang/slang-ir-insts.h
source/slang/slang-ir-specialize-dispatch.cpp
source/slang/slang.cpp

This change is the first step towards identifying witness tables and RTTI objects with integer IDs and generating dynamic dispatch logic consisting of a `switch` statement on the integer ID instead of using cascading `if`s to do pointer comparisons.
This change adds a mapping from a witness table's mangled name (a.k.a the mangled name of a TypeConformance) to an integer value in `Linkage`, along with a user facing API that queries the dictionary for (or assigns) a witness table's sequential ID. This mapping is used by the generics lowering pass to identify witness table objects with sequential IDs. The lowering generics pass also writes to the mapping for all witness tables that the user did not assign sequential IDs for, so that if the user decides to query the ID after code gen they …

Add sequential ID cache in Linkage for witness tables and RTTI objects.

---

source/slang/slang-emit-cpp.cpp
source/slang/slang-ir-inst-defs.h
source/slang/slang-ir-insts.h
source/slang/slang-ir-lower-generics.cpp
source/slang/slang-ir-specialize-dispatch.cpp
source/slang/slang-ir.cpp
source/slang/slang-ir.h

This PR changes the dynamic dispatch function from using cascading `if` statements to a `switch` statement.
The key to enable `switch` statement is to turn witness table pointer comparisons into a sequential ID based dispatch.
All witness tables are assigned a sequential ID generated in the natural order regarding to the interface it is implementing. The user-facing API for querying/specifying the sequential IDs has been added in PR #1590. The existing `specializeDispatchFunction` pass is changed to:
1. Generate a new version of the dispatch functions, with the first argument changed from an `IRWitnessTable` to `UInt`.
2. Add a new inst, `GetSequentialID` that returns the sequential ID of a witness table.
3. All call sites to the dispatch function are modified to `call(dispatchFunc, …

Generate `switch` based dynamic dispatch logic.

---

source/slang/slang-ir-validate.cpp
source/slang/slang-ir.cpp

The Slang IR builder has a notion of "hoistable" instructions, which are basically those instructions that represent a pure side-effect-free operation on their operands, and which can and should be deduplicated. Most types are "hoistable" instructions.
In order to make deduplication of hoistable instructions work, we need to emit them at the right location. Consider if we had:
```hlsl
void myFunc<T>(...)
{
if(someCondition) {
vector<T, 4> a = ...;
...
} else {
vector<T, 4> b = ...;
}
}
```
The IR instruction that represents `vector<T,4>` can't be inserted at the global scope, because then the parameter `T` would not be visible to it. That instruction also shouldn't be inserted into the same block that declares `a`, because then the instruction itself wouldn't be visible at the point where …

Improve insertion location for "hoistable" instructions

---

source/core/slang-byte-encode-util.h
source/slang/slang-serialize-ir-types.h
source/slang/slang-serialize-ir.cpp

The number of IR instructions has expanded beyond 256, so 8 bits is no longer sufficient to represent all possible IR opcodes.
The `kIROpMeta_OpMask` value has been changed to 0x3FF and number of opcode bits has been changed to 10 previously.
This change modifies the IR encoding/decoding logic and use variable length integer encoding for opcodes to fix serialization errors.

Fix IR serialization to use variable length encoding for opcode.

---

source/slang/slang-visitor.h

Supresses `Unreachable code` warning in VS2017.

Fix VS2017 Warnings

---

source/slang/slang-ir-link.cpp
source/slang/slang-ir-lower-generics.cpp
source/slang/slang-ir-specialize-dispatch.cpp
source/slang/slang-ir-specialize-dynamic-associatedtype-lookup.cpp
tests/compute/dynamic-dispatch-12.slang
tests/compute/dynamic-dispatch-13.slang
tests/compute/dynamic-dispatch-14.slang

In previous PRs, we have already implemented a `switch` based dynamic dispatch without relying on pointers. This should allow all dynamic dispatch code to be supported for D3D/VK targets.
With PR #1612, the only remaining block to support `switch` based dynamic dispatch on D3D/VK is that the witness table and RTTI handles lower to `uint64_t`, which isn't supported by all platforms.
This PR makes all such handles lower to `uint2` instead, and adds the vector packing logic in places that are necessary.
One small issue with fxc is that if a `switch` statement contains only one `default` case, it sometimes complains that not all control paths return a value. To fix this, we omit the `switch` statement if there is only 1 case.
This PR also enables some dynamic dispatch tests on D3D/VK. Will …

Make witness and RTTI handles lower to `uint2`.

---

tests/compute/interface-shader-param-in-struct.slang
tests/compute/interface-shader-param.slang
tests/compute/interface-shader-param2.slang
tests/compute/interface-shader-param3.slang
tests/compute/interface-shader-param4.slang

Since we no longer emit `uint64_t` for RTTI/witness table IDs, `lower-generics` pass should now work with HLSL static specialization.
This PR re-enables the tests that were previously disabled in PR #1612.

Re-enable `interface-shader-param` tests.

---

slang.h

This was a serious problem that meant that some of our public API functions (exported from the DLL) had mangled C++ symbol names (which are not guaranteed to be portable across different compilers).
The fix here is the expedient one: just add `extern "C"` to the relevant functions. The simplicity has a cost, though, in that this change introduces a significant break in binary compatibility.
Source code should be compatible before/after this change, but it would be necessary to match an application and Slang shared library so that they agree on the mangled names of these symbols. We will need to treat this as a breaking release when this change goes out.
Note that because of the way that C++ mangled names were being used, we *already* have introduced breaking changes to the binary …

Fix mistake where some public API functions weren't extern "C"

---

source/slang/slang-ir-legalize-types.cpp

The refactor of type legalization in PR #1594 introduced a subtle problem where an IR instruction might be removed from the hierachy (perhaps because its parent was removed during legalization) but would still be on the work list. Legalization of such instructions is wasteful (since it would never impact the output), but it also creates a problem if we try to insert new legalized instructions next to such a removed instruction. The logic for inserting an instruction before/after another asserts that the sibling instruction must have a parent, and leads to a failure in debug builds and a potential crash in release builds.
This change adds a bit of defensive code to skip any instructions that appear to have been removed from the hierarchy (because they have no parent and are not the …

Fix a subtle bug introduced into type legalization

---

build/visual-studio/slang/slang.vcxproj
build/visual-studio/slang/slang.vcxproj.filters
source/slang/hlsl.meta.slang
source/slang/slang-capability-defs.h
source/slang/slang-capability.cpp
source/slang/slang-capability.h
source/slang/slang-compiler.h
source/slang/slang-emit-c-like.cpp
source/slang/slang-emit-c-like.h
source/slang/slang-emit.cpp
source/slang/slang-hlsl-intrinsic-set.cpp
source/slang/slang-ir-glsl-legalize.cpp
source/slang/slang-ir-inst-defs.h
source/slang/slang-ir-insts.h
source/slang/slang-ir-legalize-varying-params.cpp
source/slang/slang-ir-link.cpp
source/slang/slang-ir-specialize.cpp
source/slang/slang-ir.cpp
source/slang/slang-lower-to-ir.cpp
source/slang/slang.cpp

We already have cases in the stdlib where we mark declarations as being specific to certain targets, e.g.:
```
// My ordinary function to add two numbers.
// Works everywhere.
//
void myFunc(int a, int b) { return a + b; }
// On the "coolgpu" target, we can use a secret intrinsic
// that adds numbers even faster!
//
__specialized_for_target(coolgpu)
void myFunc(int a, int b) { return __secretIntrinsic(a, b); }
```
The existing logic for dealing with these modifiers (`__specialized_for_target` and `__target_intrinsic`) was almost entirely string-based. We would turn the chosen compilation target into a string, and then use that to try and search for the "best" definition of a function at a few steps:
* During IR linking, we always pick one definition of an `[import]`ed function, and that …

Add first steps toward a "capability" system

---

build/visual-studio/gfx/gfx.vcxproj
build/visual-studio/gfx/gfx.vcxproj.filters
premake5.lua
tests/compute/array-param.slang
tests/compute/entry-point-uniform-params.slang
tools/gfx/cuda/render-cuda.cpp
tools/gfx/cuda/render-cuda.h
tools/gfx/render.cpp
tools/render-test/render-test-main.cpp

This change adds a CUDA implementation of the `gfx::Renderer` interface, and routes CUDA tests with `-shaderobj` enabled through the standard gfx framework instead of through the `cuda-compute-util` functions.
The CUDA renderer provides only compute functionality, it does not implement any graphics pipeline features. It also only supports `ShaderObject` binding instead of the legacy `DescriptorSet` API. Samplers are not supported, but Texture and CombinedTextureSampler are supported.
This change enables two tests that is currently using this path: `array-param` which only uses global parameters, and `entry-point-uniform-params`, which uses global parameters and entry point parameters, and exercises sub-object binding via a `ConstantBuffer` parameter.

Implements CUDA renderer in gfx.

---

tools/gfx/cuda/render-cuda.cpp

- Remove unnecesary fields kept in `BindingRangeInfo`.
- `CUDARootShaderObject` stores uniform buffer in host memory so we no longer need the device->host copy before launching a kernel.

Cleanup CUDA renderer.

---

examples/heterogeneous-hello-world/shader.slang
source/slang/slang-emit-c-like.cpp
source/slang/slang-emit-c-like.h
source/slang/slang-emit-cpp.cpp
source/slang/slang-emit-cpp.h
source/slang/slang-emit-cuda.cpp
source/slang/slang-emit-cuda.h
source/slang/slang-emit.cpp

PR to fix issue #1638.  This change introduces a diagnostic sink to the
emitModule function, and updates all associated calls to that function.
Additionally, this commit updates the heterogeneous hello world example
to not need the entry and stage flags for simplicity.

Heterogeneous Flag Error Visibility

---

source/slang/slang-ir-glsl-legalize.cpp
tests/cross-compile/barycentrics.slang
tests/cross-compile/barycentrics.slang.glsl

This change allows for fragment shader varying inputs marked with the `SV_Barycentrics` semantic to be mapped to GLSL code using the `gl_BaryCoordNV` builtin variable (from he `GL_NV_fragment_shader_barycentric` extension).
This is the simplest possible change to get the functionality up and running, and it leaves out many things that could be desired in a more feature-complete version of the feature later:
* There is no support for alternative extensions that provide similar functionality. Selection of which extension to favor could eventually be based on the "capability" work that has been put in place.
* There is no attempt made to check that the input has the expected type (or to coerce it if it doesn't), so for now this is only going to be guaranteed to work for a `float3` input.
* …

Add basic GLSL support for SV_Barycentrics

---

source/slang/core.meta.slang
source/slang/slang-ast-modifier.h
source/slang/slang-emit-c-like.cpp
source/slang/slang-emit-c-like.h
source/slang/slang-emit-hlsl.cpp
source/slang/slang-emit-hlsl.h
source/slang/slang-ir-inst-defs.h
source/slang/slang-ir-insts.h
source/slang/slang-lower-to-ir.cpp

This adds the `[noinline]` attribute to the front-end, and passes it through when generating HLSL output.
Notes:
* This change doesn't include a test since the dxc version I have locally parses `[noinline]` but then generates DXIL that fails validation.
* This change doesn't include logic to handle `[noinline]` for other targets. Notably, SPIR-V has decorations that convey the same intention, but we don't yet take advantage of the GLSL extension(s) that would let us generate those decorations.
* By necesstiy, `[noinline]` is only a "strong suggestion" and not actually something the compiler can ever guarantee/enforce.

Add support for [noinline] attribute

---

source/slang/slang-options.cpp
tests/vkray/callable-caller.slang

This provides a stand-alone option distinct from `-profile` that can be used to add capabilities to a target. A test has been added to confirm that `-profile X -capability Y` works the same as `-profile X+Y`.
The intention is that this option could be used in applications that use the API to set up their target but then use the options-parsing logic to handle things like capabilities.
Note: that latter bit has not been confirmed, so it is possible that this approach does not actually suffice for hybrid API + options usage. That will need to be confirmed in follow-up work.

Add a -capability command-line option

---

slang.h
source/slang/slang-api.cpp
source/slang/slang-capability.cpp
source/slang/slang-capability.h

* Make invalid/unknown capability have a zero value (this aligns it better with the public API for `SlangProfileID`, so that the two can be merged down the line)
* Actually provide an implementation of `spFindCapability()` public API

Fill in some missing bits of capability API

---

tools/gfx-util/shader-cursor.cpp
tools/gfx-util/shader-cursor.h
tools/gfx/vulkan/render-vk.cpp
tools/render-test/render-test-main.cpp

This change removes the `ShaderCursor`'s dependency on `core`, so that it may be used by users who do not wish to use`core`.

Make  `ShaderCursor` no longer depend on core.

---

build/visual-studio/slang/slang.vcxproj
premake5.lua
slang.sln

This change also switches the build back to using prebuilt glslang binaries instead of always building from source.

Upgrade slang-binaries for glslang 11.1.0

---

source/core/slang-string.h
tools/gfx/d3d11/render-d3d11.cpp
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/render-graphics-common.cpp
tools/gfx/render.h
tools/gfx/vulkan/render-vk.cpp

This change contains two small (and temporary) improvements to `gfx`. Although these chagnes can become irrelavent in the future when we refactor the interface, they allow me to make progress on other pieces of work now.
Add `StructuredBuffer` support in `gfx`.
Allow `gfx` to be used without a window handle in d3d11/d3d12.

Small improvements to `gfx`.

---

source/slang/slang-reflection-api.cpp

If a shader parameter is a `StructuredBuffer<IExistential>`, the `resourceInfos` associated with it will contain 3 entries: one for the shader resource descriptor slot, one for `ExistentialTypeParam` and one for `ExistentialObjectParam`. The two existential entries doesn't affect descriptor set related reflection, so we update the reflection logic to be capable of handling parameters with more than one `resourceInfo`s.

Fix reflection to correctly report descriptor ranges of `StructureBuffer`s of existential types.

---

tools/gfx/d3d12/render-d3d12.cpp

Fix a bug in `DescriptorSet::setSampler` that is writing into the wrong descriptor table.

Fix D3D12 DescriptorSet::setSampler bug

---

source/slang/slang-ir-any-value-marshalling.cpp

This change makes the `marshal-any-value` pass to emit initialization logic to unused `anyValue` fields in synthesized `packAnyValue<T>` implementations to avoid fxc crash.

Initialize unused fields in packAnyValue

---

source/slang/slang.natvis

This allows the name string defined in an `IRNameHintDecoration`, `IRExportDecoration` or `IRImportDecoration` directly under the expand of an `IRInst` object if the inst contains such a decoration.

Make natvis to discover and display IRInst names more directly.

---

build/visual-studio/gfx/gfx.vcxproj
build/visual-studio/gfx/gfx.vcxproj.filters
examples/hello-world/main.cpp
examples/shader-toy/main.cpp
tools/gfx/cuda/render-cuda.cpp
tools/gfx/d3d11/render-d3d11.cpp
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/open-gl/render-gl.cpp
tools/gfx/render-graphics-common.cpp
tools/gfx/render-graphics-common.h
tools/gfx/render.h
tools/gfx/slang-context.h
tools/gfx/vulkan/render-vk.cpp
tools/render-test/render-test-main.cpp

This change makes `gfx::IRenderer` responsible for maintaining a slang `ISession` for shader reflection and compilation. This is a step necessary to allow `gfx` layer take control of shader compilation to properly support shader-object based specialization.
The `hello-world` and `shader-toy` examples have been modified to use the `ISession` from `IRenderer` instead of creating its own slang session.

Make `gfx::IRenderer` own a slang session.

---

source/slang/slang-emit-c-like.cpp
tests/pipeline/ray-tracing/ray-query-subroutine.slang
tests/pipeline/ray-tracing/ray-query-subroutine.slang.hlsl

The problem would manifest for any code that declared a DXR 1.1 `RayQuery` value, but then only used it as one location in their code.
The most common way for this to arise in user code was declaring a `RayQuery` and then handing it off to a helper/worker subroutine.
RayQuery<0> myRayQuery;
helperRoutine(myRayQuery, ...);
The root cause was in the emit logic, where the initialization of `myRayQuery` above (a `defaultConstruct` operation in our IR) was getting folded into its (only) use site.
This folding makes some sense, because the initialization of a ray query is not an operation with side effects, but doesn't work in practice because our way of handling default construction in HLSL output is by using a variable declaration.
The simple fix here is to ensure that `defaultConstruct` …

Fix issue when passing ray query to a subroutine

---

source/slang/slang-lower-to-ir.cpp

This change pertains to `static` variables in function scope (including things like methods, initializers, property accessors, etc.). Note that it does *not* have anything to do with global-scope `static` variables or with `static const` variables (whether inside a function or not).
The old code generation strategy had a lot of "clever" code to deal with the problem of a `static` variable inside a generic function (or inside a function inside a generic type, etc.). Basically, if you had input code like:
int myFunc<T>(int newVal) {
static int state = 0;
int result = state;
state = newVal;
return result;
}
The language semantics are that `myFunc<float3>` should have a different `state` variable than `myFunc<int2>`. The way that the existing codegen handled that was to generate the `state` …

Change how function-scope static variables lower to IR

---

docs/user-guide/00-introduction.md
docs/user-guide/03-conventional-features.md

This change adds a first draft of an Introduction chapter, along with a chapter about the "conventional" features of Slang (when compared to HLSL, GLSL, and C/C++).

Add more to User's Guide

---

source/slang/slang-reflection-api.cpp
tools/gfx/cuda/render-cuda.cpp
tools/gfx/render-graphics-common.cpp

The purpose of these changes is to make the `shader-object` example work correctly on CUDA.
Originally I had tried to add changes to the "flat" reflection information so that it introduced descriptor ranges to match the binding ranges it added for interface/existential-type fields. This approach helped the CUDA code that was using that information to try and compute uniform offsets for those fields, but it broke most of the other renderer back-ends. Instead, I removed the relevant asserts from `CUDAShaderObject::setObject()`.
Note taht there are leftover changes from my edits to the flat reflection information, around how it handles "leaf" fields that consume multiple resource kinds. I believe that those changes are, on balance, "more correct" now than they were before, so I decided to …

Fixes to get shader-object example working on CUDA

---

examples/shader-object/main.cpp
tools/gfx/cuda/render-cuda.cpp
tools/gfx/render-graphics-common.cpp
tools/gfx/render-graphics-common.h
tools/gfx/render.h
tools/gfx/renderer-shared.cpp
tools/gfx/renderer-shared.h
tools/render-test/render-test-main.cpp

This change kind of rolls together two different simplifications:
1. The `createShaderObject()` shouldn't really need to take an `IShaderObjectLayout` because it could just take the `slang::TypeLayoutReflection` instead and create the shader-object layout behind the scenes.
2. For that matter, it needn't take a `slang::TypeLayoutReflection` either, becaues it could just take a `slang::TypeReflection` and query the layout of that type behind the scenes.
The combination of these two changes means:
* `IShaderObjectLayout` is gone from the public API, as is `createShaderObjectLayout()`
* `createShaderObject()` directly takes a `slang::TypeReflection` and allocates a shader object of that type
The result is simpler and more streamlined application code.
Note that under the hood the …

Streamline shader object creation

---

source/slang/core.meta.slang
tests/pipeline/rasterization/fragment-shader-interlock.slang
tests/pipeline/rasterization/fragment-shader-interlock.slang.glsl

Both D3D "rasterizer ordered views" (ROVs) and GLSL "fragment shader interlock" (FSI) are aimed at the same basic use case: they allow for fragment shaders to contain operations that require mutual exclusion and/or deterinistics ordering between fragment shader invocations that affect the same framebuffer coordinates. The language-level exposure of the features varies greatly between the two API families, though:
* ROVs define an implicit ordering and mutual exclusion constraint: certain resoure parameters are marked as `RasterizerOrdered`, and reads/writes to these resources must be sequences *as if* fragment-shader invocations ran in sequential order for each pixel.
* FSI defines paired begin/end functions that mark a critical section of code. All memory operations in the critical …

Add basic support for fragment shader interlock (FSI)

---

source/slang/slang-parser.cpp
tests/parser/incomplete-member-decl.slang
tests/parser/incomplete-member-decl.slang.expected

The `AdvanceIfMatch()` method was introduced to the parser as a way to avoid infinite loops when parsing nested list structures (e.g., `()`-enclosed parameter lists). The basic idea is that it tries to detect if we have scanned "too far" looking for a closing token, and reports a match to whatever logic was doing the looping to break the statemate.
Unfortunately, the `TryRecoverBefore` logic was changed at some point so that it doesn't necessarily advance any tokens at all, because we generally don't want to skip over a `}` while searching for a `)`. As a result, we could still end up in an infinite loop where we didn't consume any additional tokens as part of recovery, but wouldn't bail out of the search for a match.
This change tries to introduce a slightly more systematic setup where …

Some ad hoc parser fixes

---

source/slang/hlsl.meta.slang
source/slang/slang-emit-c-like.cpp
tests/pipeline/rasterization/get-attribute-at-vertex.slang
tests/pipeline/rasterization/get-attribute-at-vertex.slang.hlsl

This operation was added along with the `SV_Barycentrics` system-value input, and allows for a `nointerpolation` varying input to a fragment shader to be fetched at a specific vertex index within the primitive that is causing the fragment shader to be invoked.
This change adds support for the new operations in the standard library, and also includes a test case to make sure that we emit it correctly when producing HLSL/DXIL.
This change also includes a small bug fix to our emission logic for function parameters so that we properly emit layout-related attributes for varying parameters declared directly on an entry point.
(Note that most attribute end up being declared in `struct` types in existing HLSL shaders, and our IR passes produce only global variables for attributes on GLSL; the …

Add support for GetAttributeAtVertex for D3D

---

source/slang/slang-preprocessor.cpp
tests/preprocessor/if-macro-token-paste.slang

The underlying problem here requires that we have an object-like macro with an expansion that starts with a non-identifier token:
```
```
Then we need a function-like macro that uses a token paste in a way that can expand to that object-like macro:
```
```
Finally, for the specific case a user ran into, we need to invoke that function-like macro in the context of a preprocessor conditional expression:
```
// ...
#error "unimplemented"
```
The way a problem manifest is that the preprocessor logic that handles conditional expressions tries to "peek" one token ahead and see what is coming, and while the peeking logic handles macro expansion it does *not* handle token pasting right now. That means that the peek operation sees `MY_FEATURE` and assumes that it is seeing an identifier in a …

Partial fix for macro expasnion of token pastes

---

tests/compute/dynamic-dispatch-12.slang
tools/gfx/cuda/render-cuda.cpp
tools/gfx/render-graphics-common.cpp
tools/gfx/renderer-shared.cpp
tools/gfx/renderer-shared.h

The big change here is in the `setObject()` implementations, where we now take write the witness table ID and data for the value being assigned in both the CUDA and graphics-API paths (it is possible the code could be shared...). The logic for deciding whether a value "fits" in the existential value payload should actually be correct here, since it uses the reflection data.
The other relevant change is that the logic for writing out the ordinary/uniform data for a shader object on the graphics-API path has been updated so that it only allocates the GPU buffer *after* it knows the specialized layout, and can thus allocate space for any extra parameter data that wasn't in the original layout but got added by specialization. There is some inactive code in place that tries to sketch how the …

Shader object specialization work-in-progress

---

source/core/slang-random-generator.cpp
source/slang/slang-capability-defs.h
source/slang/slang-compiler.cpp
source/slang/slang-emit.cpp
tests/spirv/spirv-version-option.slang
tests/spirv/spirv-version-option.slang.glsl

By default the Slang compiler policy is usually to produce output with the fewest dependencies possible. If input code can be encoded as SPIR-V 1.0, that is what we will use by default. The catch here is that in some cases later SPIR-V versions introduced improvements to the encoding that can affect performance (e.g., around large global arrays of constants), so that a user might explicitly want to require a newer SPIR-V version (restricting the driver versions their code can work on) in the hopes of seeing better performance.
This change uses the system of capabilities that was previously introduced so that an option like `-profile glsl_450+spirv_1_5` can be used to explicitly request a specific SPIR-V version. Consistent with the existing implementation, the requested version will be …

Add command-line control over SPIR-V version

---

source/slang/core.meta.slang
source/slang/hlsl.meta.slang
source/slang/slang-ast-modifier.h
source/slang/slang-emit-c-like.cpp
source/slang/slang-emit-c-like.h
source/slang/slang-emit-glsl.cpp
source/slang/slang-emit-glsl.h
source/slang/slang-emit-hlsl.cpp
source/slang/slang-ir-glsl-legalize.cpp
source/slang/slang-ir-insts.h
source/slang/slang-lower-to-ir.cpp
tests/pipeline/rasterization/get-attribute-at-vertex.slang
tests/pipeline/rasterization/get-attribute-at-vertex.slang.glsl

This change allows varying fragment shader inputs to be declared in a way that allows the `GetAttributeAtVertex` operation to compile to valid code for both D3D and GLSL/SPIR-V/Vulkan.
The key is that rather than just use ordinary `nointerpolation`-qualified inputs the code must declare these varying inputs with a new `pervertex` qualifier that marks them as *only* being usable with `GetAttributeAtVertex`. The `pervertex`-tagged inputs then translate to GLSL inputs using the `pervertexNV` qualifier
Note that this change does *not* include any enforcement of the requirements around how these qualifiers are used (and the compiler doesn't have enforcement for the existing operations like `EvaluateAttributeAtCentroid`). The underlying problem is that the inerpolation-mode qualifiers and …

Add GLSL/SPIR-V support got GetAttributeAtVertex

---

source/core/slang-shared-library.cpp
source/core/slang-shared-library.h
source/slang/slang-api.cpp

Makes slang cache the compiled stdlib during global session creation.
The cache file contains a timestamp of the `slang.dll/so` that creates the stdlib along with a serialization of the stdlib. The cache file is stored along side the slang shared library.
Upon global session creation, slang will look for the cache file and attempt to use it. The timestamp stored in the cache file will be compared against the timestamp of the current running `slang.dll/so` before actually using it.
Fixes #1655.

Cache stdlib when creating global session.

---

build/visual-studio/platform/platform.vcxproj
build/visual-studio/platform/platform.vcxproj.filters
examples/gpu-printing/gpu-printing.cpp
examples/hello-world/main.cpp
examples/shader-toy/main.cpp
premake5.lua
source/core/slang-downstream-compiler.cpp
source/core/slang-platform.cpp
source/slang/slang-check.cpp
tools/gfx/immediate-renderer-base.cpp
tools/gfx/render.cpp
tools/gfx/vulkan/render-vk.cpp
tools/platform/gui.cpp
tools/platform/linux/x11-key-code.cpp
tools/platform/linux/x11-window.cpp
tools/platform/placeholder/placeholder-window.cpp
tools/platform/window.h
tools/platform/windows/win-window.cpp

`platform` now supports creating windows on Linux via `Xlib`.
`gfx` now supports creating Vulkan devices on Linux.
Latest version of glslang uses `pthread`, therefore we need to ensure pthread is loaded before loading `libslang-glslang.so`.

Add Linux support to `platform` and `gfx`

---

slang-gfx.h
tools/gfx/cuda/render-cuda.cpp
tools/gfx/d3d11/render-d3d11.cpp
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/open-gl/render-gl.cpp
tools/gfx/vulkan/render-vk.cpp
tools/platform/gui.cpp
tools/platform/model.cpp
tools/render-test/shader-renderer-util.cpp

Before this change, initial data for a texture has been provided with the `ITextureResource::Data` type, where a call to `IDevice::createTexture()` would take zero or one `Data` and, if present, use it to initialize all the subresources of a texture.
The organization of `Data` was not actually quite how its own documentation comment described it (the implementations didn't agree with the comment), and while it aggressively factored out redundancies (e.g., only storing the stride for each mip level once, instead of once per subresource for large arrays), the result was that setting up a `Data` correcty was a bit confusing.
This change makes the initial data for a texture using a `SubresourceData` type that is almost identical to what D3D11 uses, so that developers are more likely to be …

Change representation of initial data for textures

---

build/visual-studio/gfx/gfx.vcxproj
build/visual-studio/gfx/gfx.vcxproj.filters
prelude/slang-cpp-types.h
premake5.lua
slang.h
source/slang/slang-compiler.h
source/slang/slang.cpp
tests/compute/dynamic-dispatch-11.slang
tests/compute/performance-profile.slang
tests/compute/unbounded-array-of-array-syntax.slang
tools/gfx/cpu/render-cpu.cpp
tools/gfx/cpu/render-cpu.h
tools/gfx/cuda/render-cuda.cpp
tools/gfx/render-graphics-common.cpp
tools/gfx/render.cpp
tools/gfx/renderer-shared.h
tools/render-test/cpu-compute-util.cpp
tools/render-test/render-test-main.cpp
tools/render-test/shader-renderer-util.h

This change adds a CPU back-end to `gfx` and ensures that most of our existing CPU tests pass when using it.
Detailed notes:
* Most of the CPU renderer implementation is copy-pasted from the CUDA case, so they share a lot of similar logic
* The main addition to the CPU renderer is a semi-complete implementation of host-memory textures. The logic here handles all the main shapes (Buffer, 1D, 2D, 3D, Cube) and all the currently-supported `Format`s that are sample-able as-is (no D24S8). The implementation is not intended to be fast, and it currently only does nearest-neighbor sampling, but otherwise it tries to avoid cutting too many corners and should be ar reasonable starting point for a more complete (but not performance-oriented) implementation.
* Refactored the CPU prelude `IRWTexture` …

Add a CPU renderer implementation

---

source/slang/slang-emit-glsl.cpp
tests/pipeline/ray-tracing/acceleration-structure-in-compute.slang
tests/pipeline/ray-tracing/acceleration-structure-in-compute.slang.glsl
tests/pipeline/ray-tracing/trace-ray-inline.slang
tests/pipeline/ray-tracing/trace-ray-inline.slang.glsl

The recent change that added support for the `GL_EXT_ray_query` extension made is so that a shader that declares a `RaytracingAccelerationStructure` as an input to a non-RT shader stage but then never *uses* it wouldn't enable any RT extension, resulting in a compilation failure in glslang.
This change reverts that behavior so that such shaders enable `GL_EXT_ray_tracing`, since that is the older of the two RT extensions that introduce `accelerationStructureEXT`. It is possible that we will need to revisit this decision based on which of the two extensions ends up being more broadly supported, but I think that right now it is fair to say that there exist drivers that support `GL_EXT_ray_tracing` but not `GL_EXT_ray_query`, so the former is the better default.

Fix handling of RT accelerations structures for non-RT stages

---

build/visual-studio/slang/slang.vcxproj
premake5.lua
slang.sln

Somehow the slang-glslang binaries we are currently using aren't the most up-to-date ones, so I am enabling building glslang from source so that we can produce new binaries.

Enable building glslang from source

---

examples/hello-world/main.cpp
examples/shader-object/main.cpp
examples/shader-toy/main.cpp
examples/shader-toy/shader-toy.slang
tools/gfx/cpu/render-cpu.cpp
tools/gfx/d3d/d3d-util.cpp
tools/gfx/d3d/d3d-util.h
tools/gfx/d3d11/render-d3d11.cpp
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/immediate-renderer-base.cpp
tools/gfx/immediate-renderer-base.h
tools/gfx/open-gl/render-gl.cpp
tools/gfx/render-graphics-common.cpp
tools/gfx/renderer-shared.cpp
tools/gfx/renderer-shared.h
tools/gfx/vulkan/render-vk.cpp

Refactored the shader-object implementation so that d3d11 and gl no longer uses `GraphicsCommonShaderObject` classes to implement shader-object API, so d3d11 and gl implementations are now free of descriptor-set related infrastructure.
Note that currently the implementation still requires `RootShaderObject` to be persistent and will crash if it is used as a transient object that gets released immediately after command buffer recording. Properly supporting transient root objects require systematic fix to the public interface and the implementations that are beyond the scope of this PR.

Remove `DescriptorSet` from D3D11 and GL devices.

---

examples/hello-world/main.cpp
examples/shader-object/main.cpp
examples/shader-toy/main.cpp
tools/gfx/d3d12/render-d3d12.cpp

This change reimplements D3D12 shader objects in the `gfx` layer,
so that it is no longer layered over the `DescriptorSet`
abstraction. The new implementation also takes advantage of
D3D12's flexibility to map a `space` and `register` binding to an
arbitrary descriptor address to facilitate a more efficient
binding algorithm.
In this implementation, each shader object
(representing an entry-point, a constant buffer or a parameter
block) maintains one descriptor table set (one table for each
descriptor heap type) that is used to hold all bindings for the
object, excluding bindings of sub-objects. For example, if the
global scope defines the following parameters:
```
struct CB
{
Texture2D texture;
SamplerState s;
};
ConstantBuffer<CB> cb;
RWStructuredBuffer<int> bufferOut;
```
Then we will …

`gfx` D3D12 shader objects rewrite.

---

examples/hello-world/main.cpp
examples/shader-object/main.cpp
examples/shader-toy/main.cpp
slang-gfx.h
source/slang/slang-reflection-api.cpp
tests/compute/entry-point-uniform-params.slang
tests/compute/parameter-block.slang
tests/disabled-tests.txt
tests/render/cross-compile-entry-point.slang
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/vulkan/render-vk.cpp

1. Null bindings no longer crashes.
2. No longer copies push constants to staging CPU buffer before setting it into command buffer. The entry-point shader object now directly sets it into command buffer upon `bindObject` call.
3. Improved vulkan implementation so that each shader object is responsible for creating descriptor sets on-demand.
4. Fixed slang reflection to correctly report `ParameterBlock` binding.
5. Re-enabled 3 tests that were previously disabled.

Improve Vulkan shader-objects implementation.

---

slang-gfx.h
source/core/slang-token-reader.h
tests/compute/array-existential-parameter.slang
tests/compute/cbuffer-legalize.slang
tests/compute/entry-point-uniform-params.slang
tests/compute/global-type-param-in-entrypoint.slang
tests/compute/interface-param-partial-specialize.slang
tests/disabled-tests.txt
tests/language-feature/shader-params/entry-point-uniform-params.slang
tools/gfx-util/shader-cursor.cpp
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/vulkan/render-vk.cpp
tools/render-test/render-test-main.cpp
tools/render-test/shader-input-layout.cpp
tools/render-test/shader-input-layout.h
tools/render-test/shader-renderer-util.cpp
tools/render-test/shader-renderer-util.h
tools/render-test/slang-support.cpp

The original goal of this change was to streamline the `TEST_INPUT` system by eliminating options that are no longer relevant once we have eliminated the non-shader-object execution paths. The result is more or less a re-implementation/refactor of the logic around how input is parsed and represented, that tries to set things up for a more general sytem going forward.
The main changes isthat the `ShaderInputLayout` no longer tracks a simple flat list of `ShaderInputLayoutEntry` (that is a kind of pseudo-union of the various buffer/texture/value cases), and it instead uses a hierarchical representation composed of `RefObject`-derived classes to represent "values."
There are several "simple" cases of values
* Textures
* Samplers
* Uniform/ordinary data (`uniform`)
* Buffers composed of …

Clean up render-test handling of input

---

source/core/slang-token-reader.h
tests/compute/array-existential-parameter.slang
tools/render-test/render-test-main.cpp
tools/render-test/shader-input-layout.cpp

This change allows the `TEST_INPUT` syntax used by `render-test` to support aggregate values with a single input line more easily.
The test writer can now use a syntax like:
```
//TEST_INPUT:set someVar = 3.0
```
Input lines that start with the `set` keyword will now use a simpler `dst = src` format (instead of `dst:name=src` as the existing syntax used). The right-hand side expression can include:
* Numeric literals, both integer and floating-point (currently only supporting 32-bit scalar types; we could fix this later)
* Arrays, consisting of zero or more comma-separated expressions inside `[]`
* Aggregates, consisting of zero or more comma-separated "fields" inside `{}`. A field can either be `name: <expr>` or just `<expr>`
* Objects, which can be written as either `new SomeType{ …

Add a streamlined syntax for TEST_INPUT lines

---

slang.h
source/slang/slang-reflection-api.cpp
source/slang/slang.cpp
tests/bugs/gh-357.slang
tests/compute/assoctype-generic-arg.slang
tests/compute/global-generic-value-param.slang
tests/compute/global-type-param-in-entrypoint.slang
tests/compute/global-type-param.slang
tests/compute/int-generic.slang
tests/compute/interface-assoc-type-param.slang
tests/compute/interface-func-param-in-struct.slang
tests/compute/interface-shader-param-in-struct.slang
tests/compute/interface-shader-param.slang
tests/compute/parameter-block.slang
tests/disabled-tests.txt
tools/gfx-util/shader-cursor.cpp
tools/gfx/d3d12/render-d3d12.cpp
tools/render-test/render-test-main.cpp
tools/render-test/shader-input-layout.cpp
tools/render-test/slang-support.cpp

This change originated as an attempt to re-enable a test case, but it has ended up disabling more tests (for good reasons) than it re-enables.
The main change here is a significant overhaul of the way that the D3D12 render path extracts information from the Slang reflection API to produce a root signature.
There were also some supporting fixes in the reflection information to make sure it returns what the D3D12 back-end needed.
The big picture here is that the D3D12 path now uses the descriptor ranges stored in the reflection data more or less directly.
It still needs to use register/space offset information queried via the "old" reflection API, but it only does so at the top level now, for the program and entry points themselves.
All other layout information is derived directly from what …

Refactor D3D12 renderer root signature creation

---

README.md

Introduction part of the README.md had 2 misspelled words: higest and estensible, fixed those

Fixed 2 typos on README.md

---

source/slang/slang-check-impl.h

In order to speed up compilation, the semantic checking step uses a cache for overload resolution in the case of an operator being applied to operations of basic scalar types and vectors/matrices thereof.
The logic for construct keys for that cache was defensive against the case of, e.g., `vector<int,N>` where the element count `N` of the vector was not a literal value but a generic parameter. For some reason it did not have equivalent safeguards for a case like `vector<T,2>` where the element type was not a basic type, and it would instead assume all vector/matrix types had basic types as their element type.
This change fixes the logic to make it properly defensive against this case.

Fix a bug in the "operator cache"

---

source/core/slang-file-system.h

Not sure if this call to `addRef` is intentional, but it is causing memory leaks.

Fix memory leak in `CacheFileSystem`

---

examples/model-viewer/main.cpp
examples/model-viewer/shaders.slang
slang.h
source/slang/slang-legalize-types.cpp
source/slang/slang-reflection-api.cpp
source/slang/slang-type-layout.h
tools/gfx/d3d11/render-d3d11.cpp
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/open-gl/render-gl.cpp
tools/gfx/renderer-shared.cpp
tools/gfx/renderer-shared.h
tools/gfx/vulkan/render-vk.cpp
tools/platform/windows/win-window.cpp

This change removes an erroneous special casing logic in `PseudoPtr` legalization that does the "if element type has not changed during legalization, then just return original type of this ptr type" logic. This is intended for array and ordinary pointer types but not so for pseudoPtr types because we need to legalize them away. This logic is there probably as a result of copy pasting from other legalization cases. 
Also adds `spReflectionTypeLayout_getSubObjectRangeSpaceOffset` function to return the space index for a sub object referenced through a `ParameterBlock` binding.
Also includes following fixes:
1. `gfx`: Make sure `InputLayout` and `FramebufferLayout` objects passed to create a `PipelineState` is hold alive by the pipeline state object, because when a pipeline gets specialized …

Various fixes to make `model-viewer` example almost working.

---

docs/_layouts/user-guide.html

When window width is less than 700, automatically hides the table of contents, and allow the user to open it with a button.

Improve user guide layout for narrow viewports

---

slang.h
source/slang/slang-reflection-api.cpp
tools/gfx/d3d11/render-d3d11.cpp
tools/gfx/vulkan/render-vk.cpp

This change applies to the case where we have a sub-object range with more than one object in it (so arrays of constant buffers, parameter blocks, or existentials). It is worth noting that we don't really seem to have any tests covering this case right now, so it is entirely possible that things are busted already, and/or that this change doesn't work the way I think it does.
When we go to actually bind the state from a sub-object range into the pipeline, we care about:
* The offset to where the first object should be written
* The "stride" between consecutive objects
We were already capturing the offset information from Slang reflection data, and the same was true for the part of the offset that pertains to "pending" ordinary data. For other cases, though, we were manually incrementing …

Clean up the way we stride over sub-object ranges for D3D11 and Vulkan

---

slang-gfx.h
tests/compute/dynamic-dispatch-14.slang
tools/gfx/debug-layer.cpp
tools/gfx/debug-layer.h
tools/gfx/renderer-shared.h
tools/render-test/render-test-main.cpp
tools/render-test/shader-input-layout.cpp
tools/render-test/shader-input-layout.h

The purpose of this change is to provide a way for the user to override default specialization behavior of shader objects in the `gfx` layer.
A new method, `setSpecializationArgs(const slang::SpecializationArg* args, uint32_t count)` is added to the `gfx::IShaderObject` interface, which sets the specialization arguments to use for the shader object. If the method is not called by the user, the `gfx` layer will automatically derive them.
This change also extended the `render-test` infrastructure to make use of this feature.
The `TEST_INPUT` syntax now supports specifying specialization overrides for shader-object values, such as the following:
```
//TEST_INPUT: set gCb1 = new StructuredBuffer<IInterface>{new MyImpl{1}} : specialization_args(__Dynamic);
RWStructuredBuffer<IInterface> gCb1; …
```

Allow overriding specialization args via `IShaderObject`.

---

slang-gfx.h
tests/compute/dynamic-dispatch-14.slang
tools/gfx-util/shader-cursor.h
tools/gfx/debug-layer.cpp
tools/gfx/debug-layer.h
tools/gfx/renderer-shared.h
tools/render-test/render-test-main.cpp
tools/render-test/shader-input-layout.cpp
tools/render-test/shader-input-layout.h

This PR changes the shader object's `setSpecializationArgs` implementation to operate on a sub-object range instead of on the parent shader object itself. This design preserves better modularity.
The `render_test` comment syntax is also updated so you user can write:
```
//TEST_INPUT: set gCb1 = dynamic new StructuredBuffer<IInterface>{new MyImpl{1}}
RWStructuredBuffer<IInterface> gCb1;
```
or
```
//TEST_INPUT: set gCb1 = specialize(__Dynamic) new StructuredBuffer<IInterface>{new MyImpl{1}}
RWStructuredBuffer<IInterface> gCb1;
```
This code sets the specialization arg on the `gCb1` object instead of on the `StructuredBuffer` objects.

Rework shader object specialization control interface.

---

source/core/slang-smart-pointer.h
source/slang/slang-reflection-api.cpp
source/slang/slang-type-layout.cpp
source/slang/slang-type-layout.h

This change fixes a cyclic reference in `ExtendedTypeLayout`.
The problematic reference is in `TypeLayout::m_extendedLayout::subObjectRange::varOffsetLayout::typeLayout`, which references back to the initial `TypeLayout` object in a `RefPtr`. The solution is to introduce a `TransformablePtr` that can be demoted into a weak pointer, and demote the `varOffsetLayout::typeLayout` into a weak pointer when creating the `varOffsetLayout`.

Fix cyclic reference in `ExtendedTypeLayout`.

---

tools/gfx/cpu/render-cpu.cpp
tools/gfx/cuda/render-cuda.cpp
tools/gfx/d3d11/render-d3d11.cpp
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/immediate-renderer-base.cpp
tools/gfx/immediate-renderer-base.h
tools/gfx/open-gl/render-gl.cpp
tools/gfx/slang-context.h
tools/gfx/vulkan/render-vk.cpp

Also: `[gfx]` nows sets define per-platform preprocessor macro when compiling shaders, this is needed to write platform-dependent shader code.

Fix D3D11 `uploadBufferResource`.

---

source/slang/slang-preprocessor.cpp
tests/preprocessor/bugs/pp-bug-1.slang
tests/preprocessor/bugs/pp-bug-1.slang.expected
tests/preprocessor/macros/macro-parens-from-expansion.slang
tests/preprocessor/macros/macro-parens-from-expansion.slang.expected

This bug manifested in both incorrect preprocessor output for certain complicated cases, and also (more importantly) a use-after-free issue.
One of the "clever" design choices in the Slang preprocessor implementation is that the set of "busy" macros during expansion is implicitly defined by a linked list of those invocations that are actively being read from as part of the input stack. This logic works very well for checking whether a macro name is busy before triggering expansion, and for computing what macros should be considered busy during expansion of an object-like macro.
The problem case here was with function-like macros where the preprocessor was re-using the same list of busy macros that had been fetched when reading the macro name, but doing so *after* all the macro argument …

Fix a bug in preprocessor "busy" logic

---

source/slang/slang-compiler.h
source/slang/slang-diagnostic-defs.h
source/slang/slang.cpp
tests/bugs/import-with-error.slang.expected
tests/diagnostics/recursive-import.slang.expected
tests/language-feature/modules/error-in-nested-import/a.slang
tests/language-feature/modules/error-in-nested-import/b.slang
tests/language-feature/modules/error-in-nested-import/c.slang
tests/language-feature/modules/error-in-nested-import/error-in-nested-import.slang
tests/language-feature/modules/error-in-nested-import/error-in-nested-import.slang.expected

When errors occur in nested `#include` files it is often helpful to have a "stack trace" / traceback of the `#include` chain that led from a root translation unit to the file with an error.
This change implements a similar feature for `import`s.
It is worth noting that `import`s don't really *require* this kind of compiler support the way `#include`s do because the intention is that the meaning of an `import`ed file does not depend on the order or nesting of `import`s. As such, when trying to *fix* an error in an `import`ed file, you usually don't care how it came to be `import`ed into your shaders.
The use case here is somebody adapting a large body of Slang code to use in a different codebase, such that they have certain `.slang` files they don't actually intend to have compile …

Include a "stack trace" with nested-import errors

---

slang-gfx.h
tools/gfx/command-writer.h
tools/gfx/cpu/render-cpu.cpp
tools/gfx/cuda/render-cuda.cpp
tools/gfx/d3d11/render-d3d11.cpp
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/debug-layer.cpp
tools/gfx/debug-layer.h
tools/gfx/immediate-renderer-base.cpp
tools/gfx/immediate-renderer-base.h
tools/gfx/open-gl/render-gl.cpp
tools/gfx/renderer-shared.cpp
tools/gfx/renderer-shared.h
tools/gfx/vulkan/render-vk.cpp
tools/gfx/vulkan/vk-api.h

This changes add an `IQueryPool` interface that is similar to Vulkan's `VkQueryPool` to allow querying GPU timestamps.
This feature can be used to obtain performance data.

Support timestamp queries in `gfx`.

---

source/slang/slang-ast-builder.cpp
source/slang/slang-ast-builder.h
source/slang/slang.cpp
tools/gfx/cpu/render-cpu.cpp

`Linkage::getContainerType` is introduced in #1851 to allow users to conveniently obtain a specialized `StructuredBuffer<T>` or `ParameterBlock<T>` types with a given element type.
The implementation was not complete in that it does not fill in the `declRef` field of the resulting `Type`. This can lead to crashes when the `declRef` is used, such as in `Type::getName()`. This change fixes this issue by properly looking up and fill in the declref.
Also includes a small fix to the cpu timestamp query implementation.

Properly fill `declref` in `Linkage::getContainerType`.

---

source/compiler-core/slang-lexer.cpp
source/compiler-core/slang-token-defs.h
source/slang/slang-diagnostic-defs.h
source/slang/slang-preprocessor.cpp
tests/preprocessor/macros/variadic-macro.slang
tests/preprocessor/macros/variadic-macro.slang.expected

This change adds support for variadic macros in the C-style
preprocessor, e.g.:
#define DEBUG(MSG, ...) print(__FILE__, __LINE__, MSG, __VA_ARGS__)
Similar to the gcc preprocessor, this feature supports both named
variadic macro parameters and unnamed ones (which then default to
`__VA_ARGS__`.
The implementation work is mostly straightforward, although there are a
few subtle design choices worth mentioning:
* A variadic macro is represented by it having a variadic *parameter*
that is part of the ordinary parameter list.
* Argument parsing does *not* detect whether the macro being invoked is
variadic and collect/combine arguments to form a single argument value
for the variadic parameter. This is motivated by the need for some
extensions to differentiate a variadic parameter receiving a …

Initial support for variadic macros

---

slang-gfx.h
tools/gfx/cpu/render-cpu.cpp
tools/gfx/cuda/render-cuda.cpp
tools/gfx/d3d11/render-d3d11.cpp
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/debug-layer.cpp
tools/gfx/debug-layer.h
tools/gfx/open-gl/render-gl.cpp
tools/gfx/vulkan/render-vk.cpp
tools/gfx/vulkan/vk-api.cpp
tools/gfx/vulkan/vk-api.h

Needed for ray tracing APIs.
D3D11 doesn't support this API, will return 0.
OpenGL support is possible via bindless extensions, but not currently implemented with this change, and will also return 0.

[gfx] Add `IBufferResource::getDeviceAddress()`.

---

slang-gfx.h
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/debug-layer.cpp
tools/gfx/debug-layer.h
tools/gfx/renderer-shared.cpp
tools/gfx/renderer-shared.h
tools/gfx/vulkan/render-vk.cpp

- Allow more flexible collection of shader stages in a shader program.
- Add `createRayTracingPipelineState` public interface. (no implementation).
- Fix a bug in vulkan initialization that causes a crash when vulkan is not available.

Minor refactor to gfx D3D12 implementation.

---

build/visual-studio/slang/slang.vcxproj
build/visual-studio/slang/slang.vcxproj.filters
source/slang/slang-emit.cpp
source/slang/slang-ir-insts.h
source/slang/slang-ir-specialize-arrays.cpp
source/slang/slang-ir-specialize-buffer-load-arg.cpp
source/slang/slang-ir-specialize-buffer-load-arg.h
source/slang/slang-ir-specialize-function-call.cpp
source/slang/slang-ir-specialize-function-call.h
source/slang/slang-ir-specialize-resources.cpp
source/slang/slang-lower-to-ir.cpp
tests/bugs/gh-841.slang.glsl
tests/bugs/vk-image-atomics.slang.glsl
tests/compute/unbounded-array-of-array-syntax.slang.glsl
tests/cross-compile/geometry-shader.slang.glsl
tests/pipeline/ray-tracing/trace-ray-inline.slang.glsl
tests/slang-extension/atomic-float-byte-address-buffer-cross.slang.glsl
tests/vkray/callable-caller.slang.glsl
tests/vkray/intersection.slang.glsl
tests/vkray/raygen.slang.glsl

SPIR-V is not an especially compact format, but some patterns in how Slang generates code and then runs it through `spirv-opt` lead to many redundant field-by-field copy operations being emitted. This change attempts to address some of the resulting bloat from the Slang side of things.
Note: experimentation shows that the bloat is less pronounced when running either *no* SPIR-V optimizations or *full* SPIR-V optimizations, so it is also likely that the bloat should be addressed by changing which `spirv-opt` passes the Slang compiler runs in default (`-O1`) builds. Such changes should come as a distinct pull request.
This change primarily does two things:
First, the code generation strategy for passing arguments to `out` and `inout` parameters has been changed. In the past, the compiler …

Work to mitigate SPIR-V bloat

---

source/slang/slang-emit.cpp
source/slang/slang-ir-specialize-resources.cpp

Slang and HLSL support opaque types (textures, buffers, samplers, etc.) as members of `struct`s, mutable local variables, function results, and `out`/`inout` parameters. GLSL and SPIR-V do not.
In order to translate Slang code over to GLSL/SPIR-V we use a variety of passes that seek to eliminate all of the above use cases and produce code that only uses opaque types in the limited ways that GLSL/SPIR-V allow. This change relates to the passes that deal with function results and `out`/`inout` parameters.
There are two basic changes here:
1. The `specializeResourceOutputs` pass was only dealing with resource (texture/buffer) types. This change updates it to process sampler types as well.
2. The sequencing of the passes made it possible that an opaque-typed local variable might be left …

Fix a few issues around opaque types as outputs

---

source/slang/slang-emit-c-like.cpp
source/slang/slang-mangle.cpp

This change is related to a case where a user saw a `/` character printed as part of a structure field name in output HLSL (which obviously broke downstream compilation).
The root cause in that case was that a module that was `import`ed was found via a file system directory path, and thus the module name that the Slang compiler formed included a `/`. Due to other factors the structure field was emitted based on its mangled name (missing name hint), and that meant the bare `/` escaped into the output.
That situation implies some other things maybe are questionable:
* Could we have avoided a `/` ending up in the module name to begin with? Maybe, but we kind of want to support non-ASCII characters in names in the long run.
* Could we have fixed whatever was causing the name hint to be …

Handle unexpected character in mangled names

---

slang.h
source/slang/hlsl.meta.slang
source/slang/slang-compiler.cpp
source/slang/slang-compiler.h
source/slang/slang-emit-base.cpp
source/slang/slang-emit-base.h
source/slang/slang-emit-c-like.cpp
source/slang/slang-emit-c-like.h
source/slang/slang-emit-spirv.cpp
source/slang/slang-ir-inst-defs.h
source/slang/slang-ir-spirv-legalize.cpp
source/slang/slang-ir-spirv-legalize.h
source/slang/slang-ir-spirv-snippet.cpp
source/slang/slang-ir-spirv-snippet.h
source/slang/slang-options.cpp
source/slang/slang.cpp
tests/hlsl-intrinsic/scalar-float.slang
tests/spirv/direct-spirv-compute-simple.slang
tests/spirv/direct-spirv-control-flow-2.slang
tests/spirv/direct-spirv-control-flow.slang
tools/gfx/vulkan/render-vk.cpp
tools/render-test/options.cpp
tools/render-test/options.h
tools/render-test/render-test-main.cpp
tools/render-test/slang-support.cpp

This change adds SPIRV-direct-emit intrinsics for extended instructions defined in `GLSL.core.450`.

Add GLSL450 intrinsics to SPIRV direct emit.

---

source/slang/slang-check-impl.h
source/slang/slang-mangle.cpp

* Fix mangling logic for the case where a symbol name contains characters that aren't permitted (this usually occurs when a module name consists of the actual path to the module). There were multiple early-out `if` cases that accidentally fell through to the fallback path, so that symbol names would end up being excessively long.
* Fix type conversion cost lookup cache, by allowing single-element vectors (e.g., `vector<float,1>`) and single row/column matrix types to be distinguished from types of lower rank. Previously, `float` and `float1` and `float1x1` would share a single cache entry, even though each (currently) has very different conversion rules.

Two small fixes.

---

source/slang/slang-ir-lower-generic-call.cpp
source/slang/slang-lower-to-ir.cpp
tests/compute/dynamic-dispatch-17.slang
tests/compute/dynamic-dispatch-17.slang.expected.txt

When generating dynamic dispatch code for an generic interface method whose function signature doesn't reference any generic parameters, the logic for computing the `IRType` of the generic method incorrectly omits the generic parameters, causing `lower-generics` to produce invalid code.
This change fixes this issue and includes a test case to cover the scenario.

Fix crash: dynamic dispatch of generic interface method.

---

source/slang/slang-compiler.cpp
source/slang/slang-compiler.h
source/slang/slang.cpp

This change fixes a bug that `spSetDumpIntermediates` is not effective when using the new `IComponentType` based compilation API. The new logic ensures the setting is conserved through `TargetRequest` from the `Linkage` backing the legacy `SlangCompileRequest` object.

Fix `spSetDumpIntermediates`.

---

tools/gfx/d3d12/render-d3d12.cpp

`TransientHeap::waitInfo` needs to hold a strong reference to `ID3DFence` to avoid crash when the user release the Fence before TransientHeap.

Fix a crash in gfx d3d TransientHeap implementation.

---

slang-gfx.h
tools/gfx/d3d12/render-d3d12.cpp

Changes:
- Added a new field `existingDeviceHandle` to `IDevice::Desc`, which is 0 by default to indicate that a device does not yet exist and will need to be created
- Modified `D3D12Device::initialize` to check if `desc.existingDeviceHandle` is 0. If not 0, then it stores the value in `m_device` instead of creating a new device through `_createDevice`
@csyonghe Here are the changes I made based on the conversation and notes from yesterday.

Allow D3D12Device to use an existing device handle

---

slang-gfx.h
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/vulkan/render-vk.cpp

Changes:
- Added static helpers for constructing `ExistingDeviceHandles`
- Added getter functions for retrieving device handles from `ExistingDeviceHandles` when they exist
- Changed `D3D12Device::initialize()` to utilize new getter functions instead of directly indexing into `existingDeviceHandles.values`
- Added support for existing device handles to `VkDevice::initialize()` and changed the dtor to no longer destroy the device and instance if they were passed in
@csyonghe Changes to the Vulkan end based on what I remember from our discussion, let me know if I missed something big.

Support for existing device/instance handles in Vulkan

---

tools/gfx-unit-test/gfx-test-util.h
tools/slang-test/test-reporter.h
tools/unit-test/slang-unit-test.cpp
tools/unit-test/slang-unit-test.h

Add NO_THROW and MCALL to unit test interfaces.
Properly implement SLANG_CHECK_ABORT to actually abort the unit test.

Improvements to the unit test framework.

---

.github/workflows/release-windows.yml

Aarch64 release build on github is now failing. Disabling it to enable us to make releases for x64 and x86 until this is fixed in the future.

Disable aarch64 build for releases.

---

build/visual-studio/slang/slang.vcxproj
build/visual-studio/slang/slang.vcxproj.filters
source/slang/slang-ir-entry-point-pass.cpp
source/slang/slang-ir-entry-point-pass.h
source/slang/slang-ir-entry-point-uniforms.cpp
source/slang/slang-ir-optix-entry-point-uniforms.cpp

Recent work that added support for translating DXR-style ray tracing shaders to work with OptiX seems to have accidentally applied its transformations even when compute shaders are translated for CUDA. As a result, compute entry points with `uniform` parameters at entry-point scope would be miscompiled to use OptiX calls that are not available for non-OptiX compiles.
This change fixes the relevant pass so that it correctly opts-out on compute entry points, and also unifies some pieces of code that were being shared between a few different IR passes but that had gotten copy-pasted for the OptiX case.
The fix has been confirmed by running relevant CUDA tests locally, but CUDA is still disabled in the default CI builds, so this change is not yet actively being tested to avoid further …

Fix a bug with CUDA entry-point params

---

tests/compute/half-texture-simple.slang
tests/hlsl-intrinsic/active-mask/switch-trivial-fallthrough.slang

First, we have a CUDA-only test that simply needed a format name to be changed to match the new conventions in `gfx`.
Second, we have one of the "active mask" tests that seems to produce different results locally for developers (under Vulkan) than it does on CI. This is almost certainly down to differences in GPUs and/or drivers. The inconsistency ultimately proves the point that I was trying to make when I wrote those tests - the "active mask" concept is effectively meaningless as exposed in D3D and Vulkan because it has not been specified in a way that allows programmers to reason about its value, and drivers have implemented wildly different interpretations of its supposed semantics for so long that there is no real hope of turning `WaveGetActiveMask()` into something that returns a …

Fix two test cases that were causing problems

---

slang-gfx.h
slang.h
tools/gfx/cuda/render-cuda.cpp
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/debug-layer.cpp
tools/gfx/debug-layer.h
tools/gfx/immediate-renderer-base.cpp
tools/gfx/renderer-shared.cpp
tools/gfx/renderer-shared.h
tools/gfx/vulkan/render-vk.cpp

This change updates the gfx interface around `IFence` and `RootShaderObject`.
1. Instead of having a `bindPipelineAndRootObject` for binding mutable root shader objects, we add a `copyFrom` method in `IShaderObject` so the user can do the usual `auto rootObj = bindPipeline(..);` followed by a `rootObj->copyFrom(existingMutableRootObject)`.
2. Change the `IFence` interface to reflect what is offered by VkTimelineSempahore instead of VkSemaphore, this provides a more convenient interface and a closer match to a d3d12 Fence.
3. Add `SLANG_E_TIME_OUT` return code for `waitForFences()` operation.
4. Change the `getNativeHandle` and `getSharedHandle` interface to use the new `InteropHandle` type.

Update gfx interface.

---

.gitignore
slang-gfx.h
tools/gfx/cpu/render-cpu.cpp
tools/gfx/cuda/render-cuda.cpp
tools/gfx/d3d11/render-d3d11.cpp
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/debug-layer.cpp
tools/gfx/debug-layer.h
tools/gfx/mutable-shader-object.h
tools/gfx/open-gl/render-gl.cpp
tools/gfx/renderer-shared.cpp
tools/gfx/renderer-shared.h
tools/gfx/vulkan/render-vk.cpp
tools/gfx/vulkan/vk-util.h

Add `IShaderObject::getSize`, `getRawData()` and `setConstantBufferOverride()` methods.
Add `IDevice::getTextureAllocationInfo()` method and its d3d12 and vulkan implementations.

gfx ShaderObject interface update, getTextureAllocationInfo()

---

slang-gfx.h
tools/gfx/cuda/render-cuda.cpp
tools/gfx/d3d/d3d-util.cpp
tools/gfx/d3d/d3d-util.h
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/debug-layer.cpp
tools/gfx/debug-layer.h
tools/gfx/immediate-renderer-base.cpp
tools/gfx/vulkan/render-vk.cpp
tools/render-test/render-test-main.cpp

Adds the API for:
* Specify `SubresourceRange` for resource view creation.
* `resolveResource` (MSAA texture)
* `copyTextureToBuffer` and `textureSubresourceBarrier`.
* Add `operator<` for `gfx::ShaderOffset` so it may be used in a `std::map`.

gfx: add coverage for more resource commands.

---

source/slang/slang-ir-lower-reinterpret.cpp

`reinterpret` lowering is currently skipped for generic functions, this is not intended.
This change removes the logic that skips the lowering logic.

Fix reinterpret lowering not done for generic functions.

---

examples/ray-tracing-pipeline/main.cpp
slang-gfx.h
source/slang/slang-ir-clone.cpp
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/vulkan/render-vk.cpp
tools/render-test/render-test-main.cpp

This change contains several fixes to issues that break shader-toy example.
1. Fix function specialization that breaks the invariant where all decorations appear before other insts in an `IRFunc`.
2. Properly set d3d12 color write mask when no blend desc is specified.
3. Fix Vulkan binding logic to not crash when a bound resource view is `nullptr`.

Fix shader-toy example.

---

tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/debug-layer.cpp
tools/gfx/vulkan/render-vk.cpp
tools/gfx/vulkan/vk-api.h

This change implements `clearResourceView` method on D3D12 and Vulkan.

gfx: Implement clearResourceView

---

examples/gpu-printing/main.cpp
examples/model-viewer/main.cpp
examples/ray-tracing-pipeline/main.cpp
examples/ray-tracing/main.cpp
examples/shader-object/main.cpp
examples/shader-toy/main.cpp
examples/triangle/main.cpp
slang-gfx.h
tools/gfx-unit-test/gfx-test-util.cpp
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/renderer-shared.cpp
tools/gfx/renderer-shared.h
tools/gfx/vulkan/render-vk.cpp
tools/gfx/vulkan/vk-util.cpp
tools/gfx/vulkan/vk-util.h
tools/render-test/render-test-main.cpp
tools/render-test/slang-support.cpp
tools/render-test/slang-support.h

`PipelineType` is used to create a `IShaderProgram`, but this is redundant since the slang `IComponentType` already contains info about what type of shader it is.

Remove `PipelineType` from gfx header.

---

build/visual-studio/gfx-unit-test-tool/gfx-unit-test-tool.vcxproj
build/visual-studio/gfx-unit-test-tool/gfx-unit-test-tool.vcxproj.filters
slang-gfx.h
tools/gfx-unit-test/draw-instanced-test.cpp
tools/gfx-unit-test/gfx-test-util.cpp
tools/gfx-unit-test/gfx-test-util.h
tools/gfx-unit-test/graphics-smoke.slang
tools/gfx-unit-test/shared-textures-tests.cpp
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/vulkan/render-vk.cpp
tools/gfx/vulkan/vk-api.h

Changes:
- Provided implementations for `drawInstanced`, `drawIndexedInstanced`, `drawIndirect`, and `drawIndexedIndirect` in both D3D12 and Vulkan
- Added a preliminary test for `drawInstanced` for D3D12 ONLY - The test doesn't actually contain any instancing yet, will be added along with the remaining tests
Note: This PR does NOT contain tests for the other three draw calls, nor does it contain functional Vulkan tests. Tests for the other three calls for D3D12 will be coming in a later PR, and Vulkan tests will be enabled once `readTextureResource` is implemented.

Implement instanced and indirect draw calls

---

slang-gfx.h
tools/gfx/d3d/d3d-util.cpp
tools/gfx/d3d/d3d-util.h
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/transient-resource-heap-base.h

Includes: `textureBarrier`, `copyTexture`, `uploadTextureData`, `copyTextureToBuffer`, and `textureSubresourceBarrier`.

gfx: Implement remaining resource commands on D3D12.

---

slang-gfx.h
tools/gfx/command-writer.h
tools/gfx/d3d/d3d-util.cpp
tools/gfx/d3d/d3d-util.h
tools/gfx/d3d11/render-d3d11.cpp
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/debug-layer.cpp
tools/gfx/debug-layer.h
tools/gfx/immediate-renderer-base.cpp
tools/gfx/immediate-renderer-base.h
tools/gfx/open-gl/render-gl.cpp
tools/gfx/transient-resource-heap-base.h
tools/gfx/vulkan/render-vk.cpp

This change cleans up the parameters of draw calls to use uint32_t to stick with the underlying APIs.
Also implements the AcclerationStructureCurrentSize query for d3d12, for vulkan this always returns 0 since it is not supported.

gfx: use uint32_t in draw calls and implement current size query.

---

build/visual-studio/gfx-unit-test-tool/gfx-unit-test-tool.vcxproj
build/visual-studio/gfx-unit-test-tool/gfx-unit-test-tool.vcxproj.filters
tools/gfx-unit-test/draw-instanced-test.cpp
tools/gfx-unit-test/gfx-test-util.cpp
tools/gfx-unit-test/gfx-test-util.h
tools/gfx-unit-test/graphics-smoke.slang
tools/gfx-unit-test/instanced-draw-tests.cpp
tools/gfx/d3d12/render-d3d12.cpp

Changes:
- Renamed draw-instanced-test.cpp to instanced-draw-tests.cpp and factored out all shared boilerplate code into a base test class
- Added tests for `drawInstanced()`, `drawIndexedInstanced()`, `drawIndirect()`, and `drawIndexedIndirect()`
- Moved the required command signatures for indirect draw calls into `D3D12Device` and moved initialization of these signatures into `D3D12Device::initialize()`
This PR is currently still missing the implementation of `readTextureResource()` for Vulkan, which is required for checking test results. All D3D12 tests should work correctly.

gfx: Add tests for instanced, indexed instanced, and indirect draw calls

---

tools/gfx/d3d12/render-d3d12.cpp

This change fixed a bug in `readTextureResource` that is causing the the texture resource being incorrectly released.

Fix random d3d12 crash related to readTextureResource().

---

examples/model-viewer/main.cpp
examples/ray-tracing-pipeline/main.cpp
examples/ray-tracing/main.cpp
examples/shader-toy/main.cpp
examples/triangle/main.cpp
slang-gfx.h
tools/gfx-unit-test/instanced-draw-tests.cpp
tools/gfx/command-writer.h
tools/gfx/cuda/render-cuda.cpp
tools/gfx/d3d11/render-d3d11.cpp
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/debug-layer.cpp
tools/gfx/debug-layer.h
tools/gfx/immediate-renderer-base.cpp
tools/gfx/immediate-renderer-base.h
tools/gfx/open-gl/render-gl.cpp
tools/gfx/vulkan/render-vk.cpp
tools/gfx/vulkan/vk-api.h
tools/platform/gui.cpp
tools/render-test/render-test-main.cpp

Changes:
- Fully implemented vertex buffer binding and input layouts for Vulkan - This comprises the bulk of the changes in this PR, which boil down to providing all vertex stride info when the `InputLayout` is created instead of being passed to `setVertexBuffers()` at call time because Vulkan requires that strides are known by the time pipeline states are created. To handle this, some elements of the current `InputElementDesc` were split off into a new `VertexStreamDesc` struct, and a new `Desc` struct was added under `IInputLayout` which contains both of these descs as well a count of both input elements and vertex streams. All other backends have had their `createInputLayout` and `setVertexBuffers` functions updated to account for these changes.
- Implemented `readTextureResource()` …

Draw call tests for Vulkan

---

source/compiler-core/slang-lexer.cpp

Hex escape issue affect all places where 'getStringLiteralTokenValue' are used.
Example:
test.slang
```
#line 1 "H\x65llo world"
#warning test
```
before:
```
slangc test.slang -target hlsl
H
```
after fix:
```
slangc test.slang -target hlsl
Hello world(1): warning 15901: #warning: test
#warning test
```

Fix hexadecimal escape is string literals

---

premake5.lua
source/compiler-core/slang-visual-studio-compiler-util.cpp
source/core/slang-writer.cpp
source/core/slang-writer.h
tools/slang-test/options.cpp
tools/slang-test/options.h
tools/slang-test/slang-test-main.cpp
tools/slang-test/test-context.cpp
tools/slang-test/test-context.h
tools/slang-test/test-reporter.cpp
tools/slang-test/test-reporter.h

Allows slang-test to start multiple instances of TestServer and dispatch tests to them in parallel.
Modifies `TestContext` to make most its methods thread-safe.
This significantly reduces the amount of testing time. Using 4 threads, the test time on team city reduced from 13 minutes to 5 minutes.
This change only affects TestServer spawn mode, others test spawn modes are unaffected and still runs in a single thread.
The caveat is that because tests are running in more separate processes, there is a chance that TeamCity would mistake the test report from one build configuration as from another build configuration that is concurrently running on the same physical machine. For example, if a machine is running tests for both x64 debug and x64 release, it may some time report 1-2 less tests in …

Enable running tests in parallel.

---

examples/ray-tracing-pipeline/main.cpp
slang-gfx.h
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/debug-layer.cpp
tools/gfx/debug-layer.h
tools/gfx/renderer-shared.cpp
tools/gfx/renderer-shared.h
tools/gfx/transient-resource-heap-base.h
tools/gfx/vulkan/render-vk.cpp

This change adds a new `IShaderTable` object to gfx, which allows the user to specify shader entry points in a shader binding table used in a DXR1.0 ray tracing pipeline. D3D12 implementation is included in this change, but Vulkan implemenetation is left empty.
This separates out the existing shader binding table logic in RayTracingPipelineState.

GFX: separated ShaderTable.

---

slang.h
source/slang/slang-compiler.cpp
source/slang/slang-compiler.h
source/slang/slang-ir-link.cpp
source/slang/slang.cpp

This change allows the user to specify a different name to use for an entry point in the resulting code.
Add a new `IEntryPoint::getRenamedEntryPoint(const char* newName, IEntryPoint** newEntryPoint)` method to return the user a new `IEntryPoint` object that represents the same entry point but with a name override.
When the user links the new entry point object into a `CompositeComponentType` that represents a program, the new name will be used in the generated downstream HLSL code.
This PR is mostly about plumbing the user provide info all the way to `linkIR()`, which then changes the `IREntryPointDecoration` on the entry point IR inst upon seeing a name override.

Add entry-point name override feature.

---

build/visual-studio/gfx-unit-test-tool/gfx-unit-test-tool.vcxproj
build/visual-studio/gfx-unit-test-tool/gfx-unit-test-tool.vcxproj.filters
slang-gfx.h
tools/gfx-unit-test/gfx-test-util.h
tools/gfx-unit-test/resolve-resource-shader.slang
tools/gfx-unit-test/resolve-resource-tests.cpp
tools/gfx/cuda/render-cuda.cpp
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/debug-layer.cpp
tools/gfx/debug-layer.h
tools/gfx/immediate-renderer-base.cpp
tools/gfx/vulkan/render-vk.cpp
tools/gfx/vulkan/vk-api.h

Changes:
- Added implementations for `resolveResource()` in both D3D12 and Vulkan backends
- Added a simple test that ensures basic functionality
- Fixed several functions in the Vulkan end that were hard setting sample count to 1, preventing multisampling from working entirely
@csyonghe

Add implementations for resolveResource() to D3D12 and Vulkan backends

---

tools/gfx/vulkan/render-vk.cpp

Changes:
- Numerous fields in the pipeline descs filled in inside `VKDevice::createGraphicsPipelineState()` now take their values where appropriate from the corresponding fields in the `GraphicsPipelineStateDesc` provided in the arguments instead of being hard-coded
- Small naming convention fix to `sampleCount` added alongside `resolveResource`
Note: There are a number of TODOs for some of the fields as either gfx does not currently support them or Vulkan and D3D12 treat them differently. These will be addressed at a later date.
@csyonghe

Set numerous fields in VKDevice::createGraphicsPipelineState using the information in GraphicsPipelineStateDesc

---

slang.h
source/slang/slang-compiler.cpp
source/slang/slang-compiler.h
source/slang/slang-lower-to-ir.cpp
source/slang/slang-parameter-binding.cpp
source/slang/slang.cpp

Changed the interface from `IEntryPoint::getRenamedEntryPoint` to `IComponentType::renameEntryPoint`.
The underlying implementation creates a `RenamedEntryPointComponentType` wrapper object around the base entry-point.
This new implementation allows the user to specify entry point renaming on an IComponentType that isn't just a `EntryPoint`, but also on `SpecializedComponentType` or `CompositeComponentType` as long as the component defines a single entry point.

Revise entrypoint renaming interface.

---

tools/gfx/vulkan/render-vk.cpp

Changes:
- Added a Vulkan-specific implementation of `getFormatSupportedResourceStates()`
@csyonghe There's no test for this yet, any ideas? Tess suggested maybe querying each format then creating a texture and a buffer using the returned resource states and then transition them between each state (and maybe doing something between transitions to ensure everything works as expected).

Added Vulkan implementation of getFormatSupportedResourceStates()

---

build/visual-studio/gfx-unit-test-tool/gfx-unit-test-tool.vcxproj
build/visual-studio/gfx-unit-test-tool/gfx-unit-test-tool.vcxproj.filters
slang-gfx.h
tools/gfx-unit-test/get-supported-resource-states-test.cpp
tools/gfx/vulkan/render-vk.cpp

Changes:
- Added a simple test for `getFormatSupportedResourceStates()` that gets the set of all supported resource states for a given format then creates an empty buffer and texture and transitions both resources through those states
- Modified `_transitionImageLayout` to determine access and pipeline stage flags for the source and destination layouts based on the image layout alone instead of having a large (incomplete) block of ifs
- Added `VkImageLayout` specific versions of `calcAccessFlags` and `calcPipelineStageFlags` and added the `VK_GOOGLE_surfaceless_query` extension to Vulkan device initialization
Eventually there should be a more complex test that actually does something relevant to the current resource state between state transitions.
@csyonghe

Added a simple test for getFormatSupportedResourceStates()

---

build/visual-studio/gfx-unit-test-tool/gfx-unit-test-tool.vcxproj
build/visual-studio/gfx-unit-test-tool/gfx-unit-test-tool.vcxproj.filters
build/visual-studio/gfx/gfx.vcxproj
build/visual-studio/gfx/gfx.vcxproj.filters
slang-gfx.h
source/slang/slang-emit.cpp
tests/pipeline/ray-tracing/trace-ray-inline.slang.glsl
tools/gfx-unit-test/clear-texture-test.cpp
tools/gfx-unit-test/format-unit-tests.cpp
tools/gfx-unit-test/get-buffer-resource-handle-test.cpp
tools/gfx-unit-test/get-supported-resource-states-test.cpp
tools/gfx-unit-test/sampler-array.cpp
tools/gfx-unit-test/sampler-array.slang
tools/gfx/command-encoder-com-forward.h
tools/gfx/cuda/render-cuda.cpp
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/debug-layer.cpp
tools/gfx/debug-layer.h
tools/gfx/immediate-renderer-base.cpp
tools/gfx/renderer-shared.h
tools/gfx/vulkan/render-vk.cpp
tools/gfx/vulkan/vk-api.h
tools/render-test/render-test-main.cpp

* Make `IRenderCommandEncoder`, `IComputeCommandEncoder` and `IRaytracingCommandEncoder` inherit from `IResourceCommandEncoder` and removed duplicated `barrier`, `writeTimestamp` commands.
* Various Vulkan bug fixes: primitive-topology dynamic state, null descriptors, texture copy, layered framebuffer, etc.
* Make Slang run `mandatoryInline` pass for `[__unsafeForceEarlyInline]` functions one more time after `lower-generics` pass.
* Add `beginDebugEvent` and `endDebugEvent` commands and implement them using PIX on D3D12, VK_EXT_debug_marker on Vulkan.

Various gfx fixes.

---

slang.h
source/slang/slang-api.cpp
source/slang/slang-compiler.h
source/slang/slang-emit-c-like.cpp
source/slang/slang-emit-c-like.h
source/slang/slang-emit-glsl.cpp
source/slang/slang-emit.cpp
source/slang/slang.cpp
tools/gfx/d3d12/render-d3d12.cpp

This change adds an option to `TargetRequest` that forces glsl emit to use `scalar` layout instead of `std430` layout for storage buffers.

Add target option to force `scalar` layout for storage buffers.

---

examples/ray-tracing-pipeline/main.cpp
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/renderer-shared.cpp
tools/gfx/renderer-shared.h
tools/gfx/vulkan/render-vk.cpp
tools/gfx/vulkan/vk-api.h
tools/gfx/vulkan/vk-util.cpp
tools/gfx/vulkan/vk-util.h

Changes:
- Added implementation for `dispatchRays()`, `bindPipeline()`, and `endEncoding()` and added the `ShaderTableImpl` class, which implements the inherited function `createDeviceBuffer()` - Combined with the implementation of `createRayTracingPipelineState()`, these allow the `ray-tracing-pipeline` example to successfully run.
- Changed `ShaderTableBase::m_entryPointNames` to `m_shaderGroupNames` to better reflect its contents
- Added an `extendedFeatures` check that adds Vulkan's ray tracing pipeline extension if supported and added code to get the ray tracing pipeline properties, which is saved to the new member variable `m_rtProperties` in `VulkanApi`
@csyonghe

Fully implement the ray tracing pipeline for Vulkan

---

tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/renderer-shared.h
tools/gfx/vulkan/render-vk.cpp
tools/gfx/vulkan/vk-api.h

Changes:
- Added implementations for `IFence::getSharedHandle()` for both Vulkan and D3D12
Note: These implementations are untested for the time being.
@csyonghe

Implement IFence::getSharedHandle() for Vulkan and D3D12

---

slang-gfx.h
tools/gfx-unit-test/nested-parameter-block.cpp
tools/gfx-unit-test/root-mutable-shader-object.cpp
tools/gfx-unit-test/root-shader-parameter.cpp
tools/gfx-unit-test/sampler-array.cpp
tools/gfx/cuda/render-cuda.cpp
tools/gfx/d3d12/descriptor-heap-d3d12.h
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/debug-layer.cpp
tools/gfx/debug-layer.h
tools/gfx/immediate-renderer-base.cpp
tools/gfx/renderer-shared.h
tools/gfx/simple-transient-resource-heap.h
tools/gfx/vulkan/render-vk.cpp

This change optimizes the performance of gfx d3d12 backend.
* Disables debug layer  on release configuration.
* Direct implementation of mutable shader objects by extending the existing d3d12 shader object implementation instead of wrapping a layer around it.
* Cache GPU descriptor sets.
* Changes the interface for using mutable shader objects to avoid an extra copy.

Optimize d3d12 mutable shader object implementation.

---

slang-gfx.h
tools/gfx/d3d/d3d-swapchain.h
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/renderer-shared.cpp
tools/gfx/renderer-shared.h
tools/gfx/vulkan/render-vk.cpp
tools/platform/gui.cpp

This change defers the shader compilation and actual pipeline state creation until it is needed by a draw call.
The reason for this is that creating a `MutableRootShaderObject` requires a `IShaderProgram`. If the user is creating a mutable root shader object, they will first need to create a `IShaderProgram`. Before this change, creating a `IShaderProgram` with a slang program that has 0 specialization arguments will immediately trigger downstream shader compilation. However there are cases where the user is creating MutableRootShaderObjects but never actually use them. Actively compiling the shaders is causing a slow down in user application's start up time. To address this issue, we always compile shaders and create pipeline state objects lazily until it is definitely needed.

gfx: defer downstream shader compilation until draw/dispatch.

---

slang-gfx.h
tools/gfx-unit-test/nested-parameter-block.cpp
tools/gfx/cuda/render-cuda.cpp
tools/gfx/d3d/d3d-swapchain.h
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/debug-layer.cpp
tools/gfx/debug-layer.h
tools/gfx/immediate-renderer-base.cpp
tools/gfx/renderer-shared.cpp
tools/gfx/renderer-shared.h
tools/gfx/transient-resource-heap-base.h
tools/gfx/vulkan/render-vk.cpp

* Remove the logic for waitable objects in d3d12 swapchain implementation.
* Fixed a frame fence syncing bug (signaling the wrong fence after present)
* Reset the command allocator for QueryHeap to prevent leaking
* Refactored `TransientResourceHeap` implementation to reuse the same logic for transient constant buffer and staging buffer allocation.
* Make D3D12 `TransientResourceHeap` implement `ID3D12TransientResourceHeap` interface that provides method for allocating descriptor tables on the currently bound GPU heap.
* Improve `textureBarrier` implementation to issue a single barrier when transitioning the entire resource instead of one barrier for each subresource.

gfx: d3d12 performance optimizations.

---

slang-gfx.h
tools/gfx/d3d/d3d-swapchain.h
tools/gfx/d3d11/render-d3d11.cpp
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/debug-layer.cpp
tools/gfx/debug-layer.h
tools/gfx/open-gl/render-gl.cpp
tools/gfx/vulkan/render-vk.cpp

Changes:
- Added `isOccluded()` and `setFullScreenMode()` to `ISwapchain`
- Added implementations for D3D12 (all others currently return `false`/`SLANG_FAIL`)
@csyonghe

Add isOccluded() and setFullScreenMode() to ISwapchain

---

slang-gfx.h
source/slang/slang-emit-glsl.cpp
source/slang/slang-parameter-binding.cpp
source/slang/slang-type-layout.cpp
source/slang/slang-type-layout.h
tools/gfx/d3d/d3d-util.cpp
tools/gfx/debug-layer.cpp
tools/gfx/debug-layer.h
tools/gfx/renderer-shared.cpp
tools/gfx/renderer-shared.h
tools/gfx/vulkan/render-vk.cpp
tools/render-test/render-test-main.cpp

This change makes Slang to use `scalar` constant buffer layout when `forceGLSLScalarBufferLayout` target flag is set.
Also updates the type reflection logic to respect this target flag.
Adds `createShaderObjectFromTypeLayout` method in gfx to make gfx shader object use the consistent type layout.

Use GLSL scalar layout for constant buffers.

---

slang-gfx.h
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/render.cpp
tools/gfx/vulkan/render-vk.cpp
tools/gfx/vulkan/render-vk.h
tools/gfx/vulkan/vk-device-queue.h
tools/gfx/vulkan/vk-module.h

Based on #2154, this change restructures render-vk.cpp to get rid of the nested class definition structure and move all class declarations to `render-vk.h` and all implementations to `render-vk.cpp`.
Reorders the definitions so that the functions for each type are all placed contiguously.
Renames `VKDevice` -> `vk::DeviceImpl`.

gfx: restructure render-vk.cpp

---

examples/example-base/example-base.cpp
slang-gfx.h
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/d3d12/render-d3d12.h
tools/gfx/debug-layer.cpp
tools/gfx/debug-layer.h
tools/gfx/renderer-shared.h
tools/render-test/render-test-main.cpp

This method allows `gfx` to know the user has finished using the resources in the transient heap for the current frame, so it can insert a fence signal operation.
Without this method, the implementation has to proactively signal a fence after every command buffer submit, which slightly reduces performance.

gfx: Add `ITransientResourceHeap::finish()`

---

tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/d3d12/render-d3d12.h

Use `ShortList` instead of `Array` for `m_waitHandles`.

Small fix in d3d12 transient heap.

---

source/slang/slang-compiler.cpp
source/slang/slang-compiler.h
source/slang/slang-diagnostic-defs.h
source/slang/slang-options.cpp

This change adds a `-depfile` command line option to `slangc` to save the dependency information, i.e. which source files does every output of the current compile request depend on. The deps are saved in a regular Makefile-type format, similar to e.g. `glslangValidator`.

Add -depfile option to save dependency info

---

slang-gfx.h
tools/gfx-unit-test/copy-texture-tests.cpp
tools/gfx/vulkan/render-vk.cpp

Changes:
- Added texture to texture copying tests that copy between differently sized textures and between different mip levels and array layers with different offsets and specific copy extents
- Added testing support for all non-compressed formats and all texture types other than TextureCube
- Significantly restructured `copy-texture-tests.cpp` to support testing different formats and texture types
This PR DOES NOT currently include tests for `TextureCube`s and tests for BC formats. These are commented in the code as a todo item and will be addressed in a future PR. I also originally had a test for copying from a texture to a buffer at an offset; however, I think it'll be better to put that in a separate file.
@csyonghe @tangent-vector

Add additional texture to texture copying tests

---

source/slang/slang-syntax.cpp
tests/diagnostics/mismatching-types.slang
tests/diagnostics/mismatching-types.slang.expected
tests/doc/doc.slang.expected

Improved the type printing function to include the generic substitutions and parent types.
See the new test `mismatching-types.slang` for examples.
Addresses the `resource.slang` example from https://github.com/shader-slang/slang/issues/2112

Improved type printing

---

source/slang/hlsl.meta.slang
tests/vkray/closesthit.slang
tests/vkray/closesthit.slang.glsl

It is confusing, but HLSL (and by extension Slang) and GLSL define these functions in opposite ways.
In HLSL, `InstanceID` is the user-provided index coming from the TLAS instance descriptor, and `InstanceIndex` is the autogenerated index. 
[DXR spec for ray queries](https://microsoft.github.io/DirectX-Specs/d3d/Raytracing.html#rayquery-committedinstanceindex)
[DXR spec for ray pipelines](https://microsoft.github.io/DirectX-Specs/d3d/Raytracing.html#instanceindex)
In GLSL, `InstanceId` is the autogenerated index, and `InstanceCustomIndex` is the user-provided index. 
[GLSL spec for ray queries](https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GLSL_EXT_ray_query.txt)
[Vulkan spec for ray pipelines](https://www.khronos.org/registry/vulkan/specs/1.2-khr-extensions/html/chap15.h …

Fixed the mapping of the ray tracing instance functions to GLSL

---

build/visual-studio/gfx-unit-test-tool/gfx-unit-test-tool.vcxproj
build/visual-studio/gfx-unit-test-tool/gfx-unit-test-tool.vcxproj.filters
slang-gfx.h
tools/gfx-unit-test/copy-texture-tests.cpp
tools/gfx-unit-test/gfx-test-texture-util.cpp
tools/gfx-unit-test/gfx-test-texture-util.h
tools/gfx-unit-test/gfx-test-util.cpp
tools/gfx-unit-test/texture-types-tests.cpp
tools/gfx-unit-test/trivial-copy-textures.slang
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/vulkan/render-vk.cpp

Changes:
- Added tests for 1D, 2D, and 3D textures for `ShaderResource`, `UnorderedAccess`, and `RenderTarget` views
- Small bugfixes in D3D12 and Vulkan where the depth value for 3D textures was not being handled correctly during framebuffer creation and texture readback
Note: These tests are not complete. Still needs to test buffers, texture cubes, and texture arrays with and without multisampling as well as the `DepthStencil` and `AccelerationStructure` views.
@csyonghe

Texture views/shapes tests part 1

---

source/slang/core.meta.slang
source/slang/hlsl.meta.slang
source/slang/slang-ast-modifier.h
source/slang/slang-check-modifier.cpp
source/slang/slang-emit-c-like.cpp
source/slang/slang-ir-insts.h
source/slang/slang-lower-to-ir.cpp
tests/vkray/callable-caller.slang.glsl

- Fixes the callable shader payload declaration to use `callableDataNV/EXT` instead of `rayPayloadNV/EXT`
- Adds an optional location parameter to the `__vulkanRayPayload` and `__vulkanCallablePayload` attributes to specify location explicitly for advanced use cases.

Callable shader fix and explicit payload locations for GLSL

---

build/visual-studio/gfx-unit-test-tool/gfx-unit-test-tool.vcxproj.filters
slang-gfx.h
tools/gfx-unit-test/copy-texture-tests.cpp
tools/gfx-unit-test/texture-types-tests.cpp
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/d3d12/render-d3d12.h
tools/gfx/renderer-shared.cpp
tools/gfx/renderer-shared.h
tools/gfx/vulkan/render-vk.cpp
tools/gfx/vulkan/render-vk.h

Changes:
- Added new typdefs `Size`, `Offset`, `GfxCount`, and `GfxIndex` to `slang-gfx.h` (distinctions for gfx made to avoid conflict with otherwise similarly named typedefs in Slang)
- Replaced numerous instances of `size_t` in `slang-gfx.h`, `render-d3d12.h/cpp`, `render-vk.h/cpp` and `renderer-shared.h/cpp` with `Size`/`Offset` where appropriate
- Fixed numerical conversion warnings in `texture-types-tests.cpp` and `copy-texture-tests.cpp`
@csyonghe @tangent-vector Checkpoint PR, mostly. Lots of renames to go through so the more eyes checking I haven't missed any size/offset `size_t`s, the better

GFX renaming work part 1

---

build/visual-studio/gfx-unit-test-tool/gfx-unit-test-tool.vcxproj.filters
build/visual-studio/slang-unit-test-tool/slang-unit-test-tool.vcxproj
build/visual-studio/slang-unit-test-tool/slang-unit-test-tool.vcxproj.filters
source/slang/slang-check-decl.cpp
source/slang/slang-check-impl.h
source/slang/slang-check.cpp
source/slang/slang-check.h
source/slang/slang-compiler.h
source/slang/slang.cpp
tools/slang-unit-test/unit-test-find-type-by-name.cpp
tools/slang-unit-test/unit-test-translation-unit-import.cpp

This changes makes translation units processed in a front end compile request visible to `import` decls in the later translation units in the same compile request.
This allows the user to mix generated sources and file sources in a same compile request, without having to output the generated source to file first.
The main body of this change is to propagate a list of additional modules to use as loaded modules from the `FrontEndCompileRequest` all the way to `Linkage::findOrImportModule()`.

Make translation units in the same CompileReq visible to `import`.

---

source/slang/slang-compiler.h
source/slang/slang.cpp
tools/slang-unit-test/unit-test-translation-unit-import.cpp

This PR allows the following case to work:
```
GeneratedModule
int f() {}
TestModule.slang
import GeneratedModule
int g() { return f(); }
MainModule.cs.slang
import TestModule;
..
```
Before this change, the transitive import via `TestModule.slang` does not work.

Made translation units visible to transitive `import`s.

---

premake5.lua

Changes:
- Added `flags { "FatalWarnings"}` under `tool "gfx"` to `premake5.lua`
@csyonghe

Treat warnings as errors in slang-gfx

---

source/slang/hlsl.meta.slang
tests/pipeline/ray-tracing/trace-ray-inline.slang
tests/pipeline/ray-tracing/trace-ray-inline.slang.glsl
tests/pipeline/ray-tracing/trace-ray-inline.slang.hlsl

The flags passed as `RayQuery<flags>` were ignored when generating GLSL code.
This change adds the necessary OR operation and improves the test to pass nonzero generic flags.
Relevant spec bit:
https://github.com/microsoft/DirectX-Specs/blob/master/d3d/Raytracing.md#rayquery 
> [RayQuery::TraceRayInline()](https://github.com/microsoft/DirectX-Specs/blob/master/d3d/Raytracing.md#rayquery-tracerayinline) also has a [RAY_FLAGS](https://github.com/microsoft/DirectX-Specs/blob/master/d3d/Raytracing.md#ray-flags) field which allows dynamic ray flags configuration - the template flags are OR'd with the dynamic flags during a raytrace.

Fixed RayQuery generic flags on GLSL

---

source/slang/slang-emit-c-like.cpp
source/slang/slang-ir-restructure.cpp
source/slang/slang-ir-restructure.h

As part of generating high-level-language code, we have a pass that
builds a data structure representing structured control-flow `Region`s
and their nesting relationship. That data structure is then used
when emitting control-flow statements for the body of a function.
There are `Region` subtypes coresponding to different kinds of control
flow constructs. Both the `IfElseRegion` and `SwitchRegion` subtypes
were implemented to store a reference to the branch condition direclty
in the `Region`. This turns out to be the root cause of the problem.
After the nested `Region` structure is constructed, we have an IR pass
that uses the region hierarchy to detect and fix problems where the
implicit "scoping" rules of SSA form are incompatible with the scoping
rules that will be in effect when those …

Fix the way IR "regions" store conditions

---

source/compiler-core/slang-include-system.h
source/core/slang-smart-pointer.h
source/slang/slang-check-shader.cpp
source/slang/slang-ir-deduplicate.cpp
source/slang/slang-ir-lower-generic-call.cpp
source/slang/slang-ir-witness-table-wrapper.cpp
source/slang/slang-parser.cpp

Hello,
As I tried to build this project with the default settings on my Mac with the latest version of Xcode (13.3.1), I got errors about unused variables and copy assignment operator needing to be explicit. Here are a excerpt:
```
../../../source/slang/slang-check-shader.cpp:1183:16: error: variable 'result' set but not used [-Werror,-Wunused-but-set-variable]
Result result = SLANG_OK;
^
In file included from ../../../source/slang/slang-compiler.cpp:13:
In file included from ../../../source/slang/slang-compiler.h:11:
../../../source/slang/../compiler-core/slang-include-system.h:14:5: error: definition of implicit copy assignment operator for 'SearchDirectory' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
SearchDirectory(SearchDirectory const& …
```

Fix errors when building with the latest Xcode

---

examples/example-base/example-base.cpp
slang-gfx.h
tools/gfx-unit-test/instanced-draw-tests.cpp
tools/gfx-unit-test/resolve-resource-tests.cpp
tools/gfx-unit-test/texture-types-tests.cpp
tools/gfx/d3d11/render-d3d11.cpp
tools/gfx/d3d12/render-d3d12.cpp
tools/gfx/d3d12/render-d3d12.h
tools/gfx/immediate-renderer-base.cpp
tools/gfx/open-gl/render-gl.cpp
tools/gfx/simple-render-pass-layout.h
tools/gfx/vulkan/render-vk.cpp
tools/gfx/vulkan/render-vk.h
tools/platform/gui.cpp
tools/render-test/render-test-main.cpp

Changes:
- Changed all uses of "attachment" in the context of render and depth stencil targets/attachments to "target"
Render/depth-stencil target and color/depth-stencil attachment are used interchangeably throughout the gfx header and implementation, so this PR changes all such instances to follow D3D12 naming convention.
@csyonghe

Consolidate naming for render/depth stencil targets/attachments

---

premake5.lua

Other than on Windows, we will go ahead and turn off warnings-as-errors
for the gfx project, to help clean up some of our CI build mess.

Turn off warnings-as-errors for gfx

---

premake5.lua
slang.h

Minor changes to allow compiling for aarch64 on MacOS (i.e., _Apple silicon_) using clang
- Modify the Apple OS detection logic to allow differentiating between IOS and MacOS when targeting arm.
- Specify `-Wno-unused-but-set-variable` for clang as well as gcc

Enable aarch64 build on MacOS

---

source/compiler-core/slang-fxc-compiler.cpp

When the FXC downstream compiler is used with invalid arguments, such as unsupported profile, Slang would silently ignore that error and report a successful compilation. The code blob would be empty, which is confusing.

Fixed FXC diagnostics

---

github_macos_build.sh
premake5.lua
source/core/slang-shared-library.cpp

- The embed-stdlib-generator project is created with
`kind = "StaticLib"` to allow the build to work, even though
the project doesn't actually create a library.
- Unlike some other platforms, MacOs `ar` emits an error if no
object files are listed to be added to an archive. This causes
enable-stdlib-generator to fail on MacOS.
- Changing the project's kind to `"SharedLib"` works around the issue.
Other values for `kind` do not seem to work around the issue.
- Add an optional flag to `generatorProject` to indicate that
`kind = "SharedLib"` should be used, rather than `"StaticLib"`
- Add MacOS fix for `SharedLibraryUtils::getSharedLibraryFileName()`.
- Enable embed stdlib in `github_macos_build.sh`

Work around MacOS compilation issue with embed stlib

---

build/visual-studio/gfx-unit-test-tool/gfx-unit-test-tool.vcxproj
build/visual-studio/gfx-unit-test-tool/gfx-unit-test-tool.vcxproj.filters
tools/gfx-unit-test/swap-chain-resize-test.cpp
tools/gfx-unit-test/swapchain-shader.slang

Changes:
- Added five frames of draw calls before and after the `swapchain->resize` operation to ensure the swapchain is usable both before and after resizing
@csyonghe

Extend swapchain resize test

---

build/visual-studio/slang/slang.vcxproj
build/visual-studio/slang/slang.vcxproj.filters
source/compiler-core/slang-language-server-protocol.cpp
source/compiler-core/slang-language-server-protocol.h
source/slang/slang-ast-decl.h
source/slang/slang-language-server-ast-lookup.cpp
source/slang/slang-language-server-document-symbols.cpp
source/slang/slang-language-server-document-symbols.h
source/slang/slang-language-server-semantic-tokens.cpp
source/slang/slang-language-server.cpp
source/slang/slang-language-server.h
source/slang/slang-parser.cpp
source/slang/slang-workspace-version.cpp

This change implements document symbol outline language server feature.
Also fixes the highlighting of extension decls. The target type of an `extension` can now be properly highlighted.

Language server: document symbols

---

source/slang/core.meta.slang
source/slang/slang-ast-modifier.h
source/slang/slang-ir-inst-defs.h
source/slang/slang-ir-insts.h
source/slang/slang-lower-to-ir.cpp

The decorator `[__differentiate_jvp]` does nothing at the moment.

Added a decorator to mark functions for forward-mode differentiation

---

source/slang/slang-check-decl.cpp
source/slang/slang-diagnostic-defs.h
tests/language-server/incomplete-inheritance.slang
tests/language-server/incomplete-inheritance.slang.expected.txt

An `unimplemented` diagnostic causes the type checker to abort by throwing an exception. When that happens the language server will not be able to provide any enhanced services that requires a checked AST.
This change turns two commonly encountered diagnostic into proper diagnostics to improve langauge server experience.

Define proper diagnostic item for two common "unimplemented" cases.

---

source/slang/slang-workspace-version.cpp

When defining a macro without value via configurations, the language server crashes.
This change fixes the crash.

Fix language server crash when processing predefind macros.

---

.github/workflows/release-macos.yml
build/visual-studio/slang/slang.vcxproj
build/visual-studio/slang/slang.vcxproj.filters
source/compiler-core/slang-language-server-protocol.cpp
source/compiler-core/slang-language-server-protocol.h
source/compiler-core/slang-lexer.cpp
source/core/slang-string.cpp
source/slang/slang-check-expr.cpp
source/slang/slang-language-server-auto-format.cpp
source/slang/slang-language-server-auto-format.h
source/slang/slang-language-server-inlay-hints.cpp
source/slang/slang-language-server-inlay-hints.h
source/slang/slang-language-server.cpp
source/slang/slang-language-server.h
source/slang/slang-parser.cpp
tests/language-server/member-completion-subscript.slang
tests/language-server/member-completion-subscript.slang.expected.txt
tools/slang-test/slang-test-main.cpp

- Add inlay hint feature that shows the parameter names for each call argument and auto deduced types for each `var` or `let` declaration.
- Fix type checking of JVPDiff operator to prevent crashing the language server
- Add signature help for higher order functions.
Result of inlay hints:

Language server fixes and improvements

---

source/slang/slang-emit-c-like.cpp
source/slang/slang-emit-cpp.cpp
source/slang/slang-ir-inst-defs.h
source/slang/slang-ir-insts.h
source/slang/slang-ir-marshal-native-call.cpp
source/slang/slang-ir.cpp
source/slang/slang-ir.h

This change implements marshalling between `ComPtr` and native pointers when making COM method calls.
- Add an `IRNativePtr` type to represent a native pointer of a ref-counted resource.
- Add `IRManagedPtrGetWriteRef`, `IRManagedPtrAttach`, `IRManagedPtrDetach` instructions.
- Add `IRGetNativePtr` instruction.

Native call marshalling for ComPtr parameters and return values.

---

build/visual-studio/slang/slang.vcxproj
build/visual-studio/slang/slang.vcxproj.filters
source/slang/slang-ast-expr.h
source/slang/slang-check-decl.cpp
source/slang/slang-check-expr.cpp
source/slang/slang-check-impl.h
source/slang/slang-check-overload.cpp
source/slang/slang-diagnostic-defs.h
source/slang/slang-emit-c-like.cpp
source/slang/slang-emit-c-like.h
source/slang/slang-emit-cpp.cpp
source/slang/slang-ir-inst-defs.h
source/slang/slang-ir-insts.h
source/slang/slang-ir-util.cpp
source/slang/slang-ir-util.h
source/slang/slang-ir.cpp
source/slang/slang-ir.h
source/slang/slang-lower-to-ir.cpp
source/slang/slang-parser.cpp
tests/cpu-program/class.slang
tests/cpu-program/class.slang.expected
tests/diagnostics/class-keyword.slang
tests/disabled-tests.txt
tools/gfx-unit-test/gfx-test-texture-util.cpp
tools/gfx-unit-test/ray-tracing-tests.cpp

This changes adds support for `class` types on host targets. `class` types are always reference counted (allocated on heap and referenced by a `RefPtr`).
This initial support relies on the `RefPtr` class defined in prelude to implement reference counting, instead of an explicit life time management in IR.
The current IR implementation doesn't represent class values as explicit pointers, instead they are just normal values with an `IRClassType` type. The emit logic will always emit `RefPtr<T>` when seeing a `IRClassType(T)`. This can be further optimized by emitting an `T*` on function parameters and use `RefPtr` only for variables and fields.
An `IRAllocObj` inst is added and emitted in a class's constructor body, which will cause the emit logic to emit the `new` keyword.
The `new` …

Support `class` types.

---

source/slang/slang-language-server-auto-format.cpp
source/slang/slang-language-server-auto-format.h
source/slang/slang-language-server-completion.cpp
source/slang/slang-language-server.cpp
source/slang/slang-language-server.h

This changes fixes several undesired behaviors reported by user.
Add option to prevent auto formatting to make any line break changes (default is not making line-break changes on auto-format).
Prevent formatting code (and therefore potentially changing the indent) after the cursor when pasting.
Fix auto indent adjustment when typing "{".
Prevent "." from commiting auto completion changes in an include path.
Fix auto complete suggestions after typing "../" in include path.

Language Server: Auto format bug fixes.

---

build/visual-studio/slang/slang.vcxproj
build/visual-studio/slang/slang.vcxproj.filters
examples/heterogeneous-hello-world/main.slang
source/slang/core.meta.slang
source/slang/slang-ast-expr.h
source/slang/slang-ast-support-types.cpp
source/slang/slang-ast-support-types.h
source/slang/slang-check-conversion.cpp
source/slang/slang-check-expr.cpp
source/slang/slang-check-impl.h
source/slang/slang-check-overload.cpp
source/slang/slang-emit-c-like.cpp
source/slang/slang-ir-inst-defs.h
source/slang/slang-ir-peephole.cpp
source/slang/slang-ir-util.cpp
source/slang/slang-ir-util.h
source/slang/slang-lower-to-ir.cpp
source/slang/slang-parser.cpp
tests/cpu-program/pointer-basics.slang
tests/cpu-program/pointer-basics.slang.expected

This PR adds parsing, checking and basic operators for pointer types.
Now it is valid to use `*` in c-style declarator to define pointer-typed variables.
Pointers can be compared, cast explicitly to and from uint64/int64 and implicitly to bool.
Pointers can be dereferenced with the `*` operator which results in a `RefType<T>` that can be "opened" to an l-value `T` at assignments and calls.
The `&` operator can be used on l-values to return a pointer.

Basic pointer usages.

---

source/slang/core.meta.slang
source/slang/slang-ast-support-types.h
source/slang/slang-check-expr.cpp
source/slang/slang-check-impl.h
source/slang/slang-check-overload.cpp
source/slang/slang-check-type.cpp
source/slang/slang-emit-c-like.cpp
source/slang/slang-lookup.cpp
tests/cpu-program/pointer-deref.slang
tests/cpu-program/pointer-deref.slang.expected

This PR makes it possible to use `.` operator on a pointer that implciitly dereferences the pointer to access the members.

Implicit pointer dereference when using member operator.

---

source/slang/slang-check-type.cpp
source/slang/slang-diagnostic-defs.h
source/slang/slang-emit.cpp
source/slang/slang-ir-generics-lowering-context.cpp
source/slang/slang-ir-generics-lowering-context.h
source/slang/slang-ir-insts.h
source/slang/slang-ir-lower-existential.cpp
source/slang/slang-ir-lower-generic-call.cpp
source/slang/slang-ir-lower-generic-function.cpp
source/slang/slang-ir-lower-generics.cpp
source/slang/slang-ir-lower-optional-type.cpp
source/slang/slang-ir-specialize-dynamic-associatedtype-lookup.cpp
source/slang/slang-ir-util.cpp
source/slang/slang-ir-util.h
source/slang/slang-ir-witness-table-wrapper.cpp
source/slang/slang-ir.cpp
tests/cpu-program/gfx-smoke.slang
tools/gfx/gfx.slang

By default, an `Optional<T>` lowers into a `struct` with a `T` field for the value and a `bool` field representing whether or not there is value.
For types that can be lowered into a pointer, such as `NativePtr`, `Ptr`, `ComPtr` or a `class`, we don't need to generate a struct. Instead, we can simply test if the lowered pointer is a `nullptr`.
This PR implements this optimization.
Also adds a compile time check to prevent forming direct pointers to managed types (e.g. classes or interfaces). These should be referred to with the `NativeRef` type which must be explicitly converted to managed type before use.

Make Optional<PointerType> lower to PointerType instead of a struct.

---

tools/gfx-unit-test/ray-tracing-tests.cpp
tools/gfx/vulkan/vk-command-encoder.h
tools/gfx/vulkan/vk-shader-table.cpp

Changes:
- Fixed math and alignment errors in Vulkan SBT creation resulting in all raygen shaders after the first being copied into the incorrect locations

Fix for Vulkan ray tracing test using a non-zero raygen shader index

---

source/core/slang-array.h
source/core/slang-short-list.h
source/slang/slang-api.cpp
source/slang/slang-ast-base.h
source/slang/slang-ast-builder.cpp
source/slang/slang-ast-builder.h
source/slang/slang-ast-print.cpp
source/slang/slang-ast-substitutions.cpp
source/slang/slang-ast-type.cpp
source/slang/slang-ast-type.h
source/slang/slang-ast-val.cpp
source/slang/slang-ast-val.h
source/slang/slang-check-conformance.cpp
source/slang/slang-check-constraint.cpp
source/slang/slang-check-conversion.cpp
source/slang/slang-check-decl.cpp
source/slang/slang-check-expr.cpp
source/slang/slang-check-impl.h
source/slang/slang-check-overload.cpp
source/slang/slang-check-shader.cpp
source/slang/slang-check-stmt.cpp
source/slang/slang-check-type.cpp
source/slang/slang-lookup.cpp
source/slang/slang-lower-to-ir.cpp
source/slang/slang-mangle.cpp
source/slang/slang-syntax.cpp
source/slang/slang-syntax.h
source/slang/slang.cpp

This change extends `ASTBuilder::getOrCreate` to handle more cases, and use it for creating type nodes, substitutions, witnesses, and int vals.
Also added a cache for lookups.

Deduplicate AST type nodes and cache lookup operations.

---

.gitignore
prelude/slang-cpp-prelude.h
slang-gfx.h
source/core/slang-smart-pointer.h
source/slang/core.meta.slang
source/slang/slang-ast-support-types.h
source/slang/slang-emit-c-like.cpp
source/slang/slang-emit-cpp.cpp
source/slang/slang-emit-cuda.cpp
source/slang/slang-ir-dll-import.cpp
source/slang/slang-ir-insts.h
source/slang/slang-ir-link.cpp
source/slang/slang-ir-lower-com-methods.cpp
source/slang/slang-ir-lower-existential.cpp
source/slang/slang-ir-lower-generic-function.cpp
source/slang/slang-ir-lower-optional-type.cpp
source/slang/slang-ir-marshal-native-call.cpp
source/slang/slang-ir-marshal-native-call.h
source/slang/slang-ir-peephole.cpp
source/slang/slang-ir-util.cpp
source/slang/slang-ir.cpp
source/slang/slang-lower-to-ir.cpp
tests/cpu-program/gfx-smoke.slang
tests/cpu-program/gfx-smoke.slang.expected
tests/language-feature/types/intptr.slang
tools/gfx/gfx.slang
tools/gfx/renderer-shared.cpp

This allows the gfx-smoke test, which calls gfx in slang, to run a simple compute kernel and print the result.
- Fix code gen issue related to inherited interface method calls.
- Fix slang-gfx.h for binary compatiblity
- Extend gfx-smoke test to run simple compute kernel.
- Allow `gfx::IDevice::createProgram2` to create program from string source in addition to from file.
- Fix marshalling of `out` interface parameters in COM methods.

Run simple compute kernel in gfx-smoke test.

---

slang-gfx.h
tools/gfx/d3d12/d3d12-command-buffer.h
tools/gfx/d3d12/d3d12-helper-functions.cpp

Also added `ICommandBufferD3D12::ensureInternalDescriptorHeapsBound()` for raw d3d api interop.

Fix d3d12 implementation of `uploadBufferData`.

---

source/slang/core.meta.slang
source/slang/hlsl.meta.slang
tests/cpu-program/class-com.slang
tests/cpu-program/class.slang
tests/cpu-program/cpu-hello-world.slang
tests/cpu-program/gfx-smoke.slang
tests/cpu-program/gfx-smoke.slang.expected
tests/cpu-program/pointer-basics.slang
tests/cpu-program/pointer-deref.slang

Now that `printf` is defined in stdlib, we can use them instead of custom-defined target intrinsic functions in our tests.

Use `printf` in tests.

---

source/slang/slang-ast-expr.h
source/slang/slang-ast-iterator.h
source/slang/slang-check-overload.cpp
source/slang/slang-language-server-ast-lookup.cpp
tests/bugs/nested-existential-dyndispatch.slang

PR #2404 introduced a regression that drops breadcrumbs when resolving a generic overload. This leads to a crash when lowering IR for a call to a generic member function due to missing `this` argument in a `call`.

Fix regression in check-overload.

---

slang-gfx.h
tools/gfx/d3d/d3d-util.cpp
tools/gfx/d3d11/d3d11-helper-functions.cpp
tools/gfx/d3d12/d3d12-device.cpp
tools/gfx/d3d12/d3d12-device.h
tools/gfx/d3d12/d3d12-pipeline-state.cpp
tools/gfx/d3d12/d3d12-shader-object-layout.cpp
tools/gfx/d3d12/d3d12-shader-object-layout.h
tools/gfx/d3d12/d3d12-shader-table.cpp
tools/gfx/renderer-shared.cpp
tools/gfx/vulkan/vk-helper-functions.cpp
tools/gfx/vulkan/vk-util.cpp

The main change is to use root signature v1.1 instead of v1.0 to take advantage of the default flags which allows more aggressive driver optimizations.

GFX: improve d3d12 performance.

---

source/slang/slang-ast-iterator.h
source/slang/slang-ast-stmt.h
source/slang/slang-check-impl.h
source/slang/slang-check-stmt.cpp
source/slang/slang-diagnostic-defs.h
source/slang/slang-language-server-ast-lookup.cpp
source/slang/slang-lower-to-ir.cpp
source/slang/slang-parser.cpp
tests/diagnostics/break-outside-loop.slang.expected
tests/diagnostics/continue-outside-loop.slang.expected
tests/diagnostics/token-line-continuation.slang.expected

This change adds the syntax for multi-level `break` statement.
A future IR pass will be implemented to lower the multi-level breaks out to ordinary breaks.

Add syntax for multi-level break.

---

source/slang/slang-emit.cpp
source/slang/slang-ir-eliminate-phis.cpp
source/slang/slang-ir-simplify-cfg.cpp
tests/experimental/liveness/liveness-7.slang
tests/pipeline/ray-tracing/trace-ray-inline.slang.glsl

- Simplify one-time loops into normal branching.
- Don't emit `store(xxx. undefined)`.
- DCE after final Phi elimination pass.

Small IR cleanups.

---

source/core/slang-digest.h
source/slang/slang-hash-utils.h
source/slang/slang.cpp
tools/gfx-unit-test/shader-cache-tests.cpp

Changes:
- Added a shader cache test for specialization args - This uses compute-smoke.slang and simply creates an add and a mul transformer, binds a transformer to the shader, and checks that changing the transformer type results in a cache miss.
- Small leftover cleanup change in `slang-digest.h`
Redo of the specialization args test PR. Rebase was reintroducing lines that were removed and not producing the clean commit history I was looking for.

Add specialization args test

---

slang-gfx.h
tools/gfx/d3d11/d3d11-device.cpp
tools/gfx/d3d12/d3d12-device.cpp
tools/gfx/gfx.slang
tools/gfx/open-gl/render-gl.cpp
tools/gfx/vulkan/vk-framebuffer.cpp

Providing an `optimalClearValue` but then clearing the texture with a different value triggers D3D12 validation layer warning. By allowing the user to opt out of optimal clear value, we can avoid this warning.

Make `optimalClearValue` optional in `ITextureResource::Desc`

---

tools/gfx-unit-test/shader-cache-tests.cpp
tools/gfx/persistent-shader-cache.cpp

Changes:
- Added several new checks to the cache eviction policy test - line count in saved cache files, existence of corresponding files for shaders currently in the cache and non-existence of files for shaders that aren't
- Added a check to `loadCacheFromFile()` to ensure only as many entries as are allowed in the cache are loaded

Cache eviction policy test refinement

---

source/slang/core.meta.slang
source/slang/slang-ast-decl.h
source/slang/slang-ast-dump.cpp
source/slang/slang-ast-modifier.h
source/slang/slang-ast-support-types.h
source/slang/slang-check-decl.cpp
source/slang/slang-check-expr.cpp
source/slang/slang-check-impl.h
source/slang/slang-check-type.cpp
source/slang/slang-emit-cpp.cpp
source/slang/slang-ir-dce.cpp
source/slang/slang-ir-diff-jvp.cpp
source/slang/slang-ir-inst-defs.h
source/slang/slang-ir-insts.h
source/slang/slang-ir-link.cpp
source/slang/slang-ir-util.cpp
source/slang/slang-ir-util.h
source/slang/slang-ir.cpp
source/slang/slang-ir.h
source/slang/slang-lower-to-ir.cpp
source/slang/slang-serialize-ast-type-info.h

This PR redesigns the checking logic around differential type conformances.
Previously, AST checking forms a `DifferentialTypeConformanceDictionary` node for each level of generic decl, including the top-level `Module`, and places differentiable types inside this dictionary node, which later lowers into an `IRDifferentiableTypeConformanceDictionary` inst so the auto diff pass can pick it up and lookup the differential type of a primal type.
Note that functions that are differentiable has either a `[ForwardDifferentiable]` or a `[ForwardDerivative]` attribute. We make them both subtypes of `DifferentialAttribute`. A `DifferentialAttribute` AST node provides us a natural place to hold differential witnesses needed by the differentiable function. When we check the body of an differential …

Rework differential conformance dictionary checking.

---

slang-gfx.h
tools/gfx/cuda/cuda-device.cpp
tools/gfx/cuda/cuda-helper-functions.cpp
tools/gfx/cuda/cuda-helper-functions.h
tools/gfx/d3d/d3d-util.cpp
tools/gfx/d3d/d3d-util.h
tools/gfx/d3d11/d3d11-device.cpp
tools/gfx/d3d11/d3d11-helper-functions.cpp
tools/gfx/d3d12/d3d12-device.cpp
tools/gfx/d3d12/d3d12-device.h
tools/gfx/d3d12/d3d12-helper-functions.cpp
tools/gfx/open-gl/render-gl.cpp
tools/gfx/vulkan/vk-device.cpp
tools/gfx/vulkan/vk-helper-functions.cpp
tools/gfx/vulkan/vk-helper-functions.h
tools/render-test/options.cpp
tools/render-test/options.h
tools/render-test/render-test-main.cpp

- Add `AdapterLUID` to hold locally unique identifier of GPU adapters.
- Return LUIDs when enumerating GPU adapters using `gfxGetAdapters()`.
- Allow specifying an LUID when creating a GPU device.
- Remove functionality to match adapter by name.
- Remove `adapter` option in `render-test`.

Add AdapterLUID to identify GPU adapters

---

source/slang/slang-check-conformance.cpp
source/slang/slang-ir-diff-jvp.cpp

- Delete the "auto conforming to IDifferentiable" logic in `isDeclaredSubtype`, which is no longer needed in the new type-system design.
- Remove `IRBuiilder*` parameters in several forward pass functions and use locally created `IRBuilder` instead to avoid having to explicitly save and restore `insertLoc`.

Small cleanups on forward differentiation.

---

source/slang-glslang/slang-glslang.cpp

As a separate PR to make the update slang-glslang dance work

Add mesh and amplification shaders to slang-glslang

---

build/visual-studio/slang/slang.vcxproj
build/visual-studio/slang/slang.vcxproj.filters
source/slang/slang-ast-decl.h
source/slang/slang-ast-expr.h
source/slang/slang-ast-iterator.h
source/slang/slang-ast-support-types.h
source/slang/slang-check-decl.cpp
source/slang/slang-check-expr.cpp
source/slang/slang-check-impl.h
source/slang/slang-diagnostic-defs.h
source/slang/slang-ir-check-differentiability.cpp
source/slang/slang-ir-check-differentiability.h
source/slang/slang-ir-diff-jvp.cpp
source/slang/slang-ir-diff-jvp.h
source/slang/slang-ir-inst-defs.h
source/slang/slang-ir-insts.h
source/slang/slang-ir-lower-error-handling.cpp
source/slang/slang-ir.cpp
source/slang/slang-language-server-ast-lookup.cpp
source/slang/slang-lower-to-ir.cpp
source/slang/slang-parser.cpp
source/slang/slang-serialize-misc-type-info.h
tests/autodiff/differential-method-synthesis.slang
tests/diagnostics/autodiff-data-flow.slang
tests/diagnostics/autodiff-data-flow.slang.expected
tests/diagnostics/autodiff.slang
tests/diagnostics/autodiff.slang.expected

- Add an IR validation pass to check for unintended call to non-differential functions (and losing derivatives).
- Add `no_diff` keyword to allow the user to clarify the intention and silence the diagnostic.

Data flow validation pass for diagnosing derivative loss.

---

tools/gfx-unit-test/shader-cache-specialization.slang
tools/gfx-unit-test/shader-cache-tests.cpp
tools/slang-test/test-reporter.cpp
tools/slang-test/test-reporter.h
tools/slang-unit-test/unit-test-lock-file.cpp
tools/slang-unit-test/unit-test-persistent-cache.cpp

- Make shader cache unit tests check the output buffer to validate the expected output.
- Add shader cache eviction test.
- Make `TestReporter` more thread-safe.
- Split `LockFile` tests.
- Disable multi-threaded tests on `aarch64` as they are currently failing when running from `test-server`.
- Cleanup.

Shader cache improvements

---

prelude/slang-cpp-types.h
source/slang/slang-emit-c-like.cpp
source/slang/slang-emit-cpp.cpp
source/slang/slang-emit-glsl.cpp
tests/bugs/matrix-reshape.slang
tests/bugs/matrix-reshape.slang.expected.txt

This fixes a regression introduced in the `construct` opcode cleanup PR.
Also adds the implementation for C++/CUDA path for matrix reshape.

Fix code generation for matrix reshape.

---

build/visual-studio/slang/slang.vcxproj
build/visual-studio/slang/slang.vcxproj.filters
source/slang/slang-ir-autodiff-fwd.cpp
source/slang/slang-ir-autodiff-fwd.h
source/slang/slang-ir-autodiff-rev.cpp
source/slang/slang-ir-autodiff-rev.h
source/slang/slang-ir-autodiff-transcriber-base.cpp
source/slang/slang-ir-autodiff-transcriber-base.h
source/slang/slang-ir-autodiff-unzip.cpp
source/slang/slang-ir-autodiff.cpp
source/slang/slang-ir-autodiff.h
source/slang/slang-ir-util.cpp
source/slang/slang-ir-util.h

This change further unifies the forward and backward auto diff passes to share more code in the transcriber class, and reorganizes the outer worklist processing loop to handle both forward and backward auto-diff transformations.
- Extract most shared logic in `ForwardDiffTranscriber` into `AutoDiffTranscriberBase`, that is served as the base class of `ForwardDiffTranscriber` and `BackwardDiffTranscriber`.
- Rename `transcribeInstBackward`  to `transposeInstBackward`.
- `transcribe` call in both forward and backward transcriber is now supposed to turn an inst into forward/backward differentiated inst. For most types (except function types), both forward and backward transcriber will behave the same. The forward transcriber is able to handle a wider range of insts, while the backward …

Further unify the autodiff passes.

---

.github/workflows/linux.yml
github_test.sh
source/slang/slang-ast-decl.h
source/slang/slang-ast-val.h
source/slang/slang-check-decl.cpp
source/slang/slang-ir-autodiff-fwd.cpp
source/slang/slang-ir-autodiff-fwd.h
source/slang/slang-ir-autodiff-rev.cpp
source/slang/slang-ir-autodiff-rev.h
source/slang/slang-ir-autodiff-transcriber-base.cpp
source/slang/slang-ir-autodiff-transcriber-base.h
source/slang/slang-ir-autodiff-unzip.cpp
source/slang/slang-ir-autodiff-unzip.h
source/slang/slang-ir-autodiff.cpp
source/slang/slang-ir-autodiff.h
source/slang/slang-ir-inst-defs.h
source/slang/slang-ir-insts.h
source/slang/slang-ir-specialize.cpp
source/slang/slang-ir-util.cpp
source/slang/slang-ir-util.h
source/slang/slang-ir.cpp
source/slang/slang-ir.h
source/slang/slang-lower-to-ir.cpp
source/slang/slang-mangle.cpp

The purpose of this change is to introduce two distinct IR ops to initiate backward differentiation: `IRBackwardDifferentiatePrimal` and `IRBackwardDifferentiatePropagate`, where the former produces the backward derivative primal function that contains the primal computations and outputs an intermediate value, and the later consumes the intermediate value and performs the backward propagation. The reason for introducing these changes is to allow us to handle recursive context save/restore for nested calls in a backward differentiable function, so that a `IRCall(callee)` can be transcribed into a call to `IRBackwardDifferentiatePrimal(callee)` in the primal part of the backward derivative func, and into a call to the `IRBackwardDifferentiatePropagate(callee)` in the propagate part of the …

Split bwd_diff op into separate ops for primal and propagate func.

---

source/slang/diff.meta.slang
source/slang/slang-ast-modifier.h
source/slang/slang-check-decl.cpp
source/slang/slang-check-modifier.cpp
source/slang/slang-diagnostic-defs.h
source/slang/slang-ir-inst-defs.h
source/slang/slang-ir-insts.h
source/slang/slang-lower-to-ir.cpp

This PR completes the front-end logic to allow user-provided backward derivative functions through `[BackwardDerivative]` and `[BackwardDerivativeOf]` attributes.
We currently only allow user defined full backward derivative functions instead of separate primal and propagate functions to simplify things. For now, we will automatically generate the trivial primal func (by calling the original func and writes nothing to intermediates) and the propagate func (by calling user provided derivative function). This is fine for most stdlib functions since they don't need to preserve context.
With these changes, the emitted IR will contain `[IRUserDefinedBackwardDerivativeDecoration]` on functions that has a user defined backward derivative implementation. Note that we are not reusing the existing …

Frontend work for `[BackwardDerivative]` and `[BackwardDerivativeOf]`.

---

source/slang/slang-check-decl.cpp
source/slang/slang-check-expr.cpp
source/slang/slang-check-impl.h
source/slang/slang-diagnostic-defs.h
source/slang/slang-ir-check-differentiability.cpp
tests/diagnostics/autodiff-data-flow-2.slang
tests/diagnostics/autodiff-data-flow-2.slang.expected
tests/diagnostics/autodiff-data-flow.slang.expected

This change adds a diagnostic when the user attempts to call a forward-differentiable function (but not backward differentiable) from a backward-differentiable function.

Add diagnostic for calling non-bwd-diff func from bwd-diff func.

---

slang-gfx.h
tools/gfx/d3d/d3d-util.cpp
tools/gfx/d3d/d3d-util.h
tools/gfx/debug-layer/debug-swap-chain.cpp
tools/gfx/gfx.slang
tools/gfx/render.cpp

- Add `gfxReportLiveObjects` API call which currently just calls the D3D `ReportLiveObjects` function. In the future this could also report gfx's internal objects.
- Turn gfx swapchain validation layer message from error into warning (otherwise we crash when running with NSight attached).

GFX report live objects

---

source/slang/slang-ir-autodiff-fwd.h
source/slang/slang-ir-autodiff-rev.h
source/slang/slang-ir-autodiff-transcriber-base.cpp
source/slang/slang-ir-autodiff-transcriber-base.h
source/slang/slang-ir-check-differentiability.cpp
source/slang/slang-ir-inst-defs.h
source/slang/slang-ir-insts.h
source/slang/slang-lower-to-ir.cpp

To support differentiating `LookupWitness` insts, we currently store the mapping of an interface requirement key to its derivative requirement key in an dictionary as a decoration on the interface type. This is unnecessary.
The simpler representation is to just reuse the existing `[ForwardDerivative]` decoration on the requirement key. This will make the representation consistent with how we are handling struct fields.
This change implements this cleanup and removes the `IRDifferentiableMethodRequirementDictionary` decoration.

Cleanup IR representation of interface member derivative.

---

build/visual-studio/gfx/gfx.vcxproj
examples/gpu-printing/kernels.slang
examples/gpu-printing/main.cpp
examples/gpu-printing/printing.slang
examples/hello-world/vulkan-api.cpp
premake5.lua
source/core/slang-string.h
tools/slang-generate/main.cpp

- Add support for ASAN (MSVC for now)
- Enable using `--enable-asan` option in premake
- Fix ASAN false positives when deleting `StringRepresentation` objects.
- Fix deep recursion in `slang-generate`.
- Fix `hello-world` and `gpu-printing` examples.
With this, all the examples pass when running debug build with ASAN enabled. Unfortunately when switching examples to use Vulkan, ASAN seems to break the loader. Needs more investigation.

Add ASAN support + fixes

---

docs/building.md
external/glslang-generated/README.md
github_build.sh
github_macos_build.sh
premake5.lua

According to the documentation, `gmake` has been deprecated by `gmake2` https://premake.github.io/docs/Using-Premake/#using-premake-to-generate-project-files
gmake2 has better dependency handling around our custom rules leading in fewer runs of slang-generate etc...
I've been using gmake2 without issue.

Use gmake2 as a premake target over gmake

---

source/slang/slang-check-expr.cpp
source/slang/slang-ir-autodiff-rev.cpp
source/slang/slang-ir-autodiff-transpose.h
tests/autodiff/reverse-inout-param-2.slang

This PR adds handling for `inout` non differential parameters so they be come an `in` parameter after backward diff.
This makes the semantics consistent with `out` non differential parameters, which are removed after transcription.

Patch transcription of `inout` non differentiable params.

---

tools/gfx/vulkan/vk-device.cpp

Although we could in principle write this explanatory message to stderr, that
would entangle this call with the layer search above for what is probably a
very unlikely possibility on any normal system.

Comment call to vkCreateInstance with a potential pitfall

---

source/slang/slang-ir-autodiff-transpose.h

it's redundant, and causes out-of-bounds accesses. The counters are enough to ensure correctness

AD: Remove the original loop condition upon inversion

---

source/slang/slang-ir-autodiff-rev.cpp
source/slang/slang-ir-autodiff-transcriber-base.cpp
source/slang/slang-ir-autodiff.h
tests/autodiff/backward-diff-check.slang

- Fixed issue with user-defined reverse-mode code still invoking AD
- removed special cases for float, double and half from the differential types logic

AD: More legacy type handling cleanup + user-defined reverse-mode fix

---

source/slang/diff.meta.slang
source/slang/slang-ast-modifier.h
source/slang/slang-check-impl.h
source/slang/slang-check-stmt.cpp
source/slang/slang-diagnostic-defs.h
source/slang/slang-ir-check-differentiability.cpp
source/slang/slang-ir-inst-defs.h
source/slang/slang-ir-util.cpp
source/slang/slang-ir-util.h
source/slang/slang-lower-to-ir.cpp
tests/autodiff/generic-impl-jvp.slang
tests/autodiff/reverse-loop.slang
tests/diagnostics/autodiff-data-flow.slang
tests/diagnostics/autodiff-data-flow.slang.expected
tests/diagnostics/autodiff.slang
tests/diagnostics/autodiff.slang.expected
tests/diagnostics/for-loop-warning.slang
tests/diagnostics/for-loop-warning.slang.expected

This PR adds a inference step when checking `for` loops to try to statically determine the maximum number of iterations for the loop and insert a `[MaxIters]` attribute on the loop if inference suceeds.
It also reports warnings along the way if it detects suspicious code like `for (int i = 0; i < 5; j++)`.

Add static for loop iteration inference.

---

source/slang/slang-ir-autodiff-cfg-norm.cpp
source/slang/slang-ir-autodiff-rev.h
source/slang/slang-ir-autodiff-transpose.h
source/slang/slang-ir-autodiff-unzip.cpp
source/slang/slang-ir-autodiff-unzip.h
tests/autodiff/reverse-control-flow-3.slang

Added logic to store most arbitrary temporary variables
The hoisting code is fairly messy now with all these cases. 
Next step is to restructure this and merge with the dominator tree approach.

Fixed hoisting of intermediate array & context vars

---

source/compiler-core/slang-artifact-representation-impl.cpp
source/compiler-core/slang-artifact-representation-impl.h
source/core/slang-io.cpp
source/core/slang-io.h
source/slang/slang.cpp

If the user has provided both a path and a source blob, we should use the user provided source blob instead of loading it from file. In this case we still need to preserve the path info, so we use the `SourceBlobWithPathInfoArtifactRepresentation` class to do that.

Add `SourceBlobWithPathInfoArtifactRepresentation`.

---

docs/user-guide/07-autodiff.md
source/slang/slang-ir-addr-inst-elimination.cpp
source/slang/slang-ir-autodiff-transcriber-base.cpp
source/slang/slang-ir-autodiff-unzip.cpp
source/slang/slang-ir-autodiff.cpp
source/slang/slang-ir-inst-defs.h
source/slang/slang-ir-insts.h
source/slang/slang-ir-peephole.cpp
source/slang/slang-ir-validate.cpp
source/slang/slang-ir.cpp
tests/autodiff/high-order-backward-diff-3.slang

This PR adds support for higher order differentiation of the `fwd_diff(bwd_diff(f))` pattern.
The main thing added here is to allow intermediate context types to be differentiated.
This means that after lowering intermediate context type to struct types, we need to generate witness tables for them.
The tricky part is to implement `dzero` and `dadd` methods for these types. For now we cut the corners by using `DefaultConstruct` as the implementation of `dzero` and a new `StructuralAdd` for `dadd`. This will result in inconsistent behavior with the rest of the system if the user is defining any non-trivial implementations for these methods. We may consider remove the `dadd` and `dzero` requirements from the `IDifferentiable` interface in the future, so we never need to worry about user …

Support `fwd_diff(bwd_diff(f))`.

---

source/slang/hlsl.meta.slang
source/slang/slang-capability-defs.h
source/slang/slang-capability.cpp
source/slang/slang-emit-glsl.cpp
source/slang/slang-emit-glsl.h
source/slang/slang-ir-glsl-legalize.cpp
source/slang/slang-options.cpp
tests/cross-compile/barycentrics-nv.slang
tests/cross-compile/barycentrics-nv.slang.glsl
tests/cross-compile/barycentrics.slang.glsl
tests/pipeline/rasterization/get-attribute-at-vertex-nv.slang
tests/pipeline/rasterization/get-attribute-at-vertex-nv.slang.glsl
tests/pipeline/rasterization/get-attribute-at-vertex-nv.slang.hlsl

Hey,
this is my first PR in here. I tried to follow conventions and change as little as possible. 
Using the capability system, you can keep the old behavior, but the default is to use the vendor-neutral GL_EXT_fragment_shader_barycentric extension.
I had to forward the `CodeGenContext` to the GLSL emitting functions in glsl-legalize, which is why there are more changes than I necessarily wanted.
Let me know what you think!

Support GL_EXT_fragment_shader_barycentric

---

slang.h
source/core/slang-type-text-util.cpp
source/slang/core.meta.slang
source/slang/slang-ast-modifier.h
source/slang/slang-compiler.h
source/slang/slang-ir-inst-defs.h
source/slang/slang-ir-insts.h
source/slang/slang-lower-to-ir.cpp
source/slang/slang-options.cpp
tests/autodiff/cuda-kernel-export.slang

We still need to integrate `nvcc` so we can invoke it to produce an actual `obj` file.

Add `[CudaDeviceExport]` to allow exporting CUDA device functions.

---

source/slang/core.meta.slang
source/slang/slang-ir-check-differentiability.cpp

This reimplements the part of assigning-to-non-diff-location check with its own data flow. The original implementation is hacky and could produce incorrect diagnostics in certain situations.

Rework differentiability dataflow check.

---

prelude/slang-cuda-prelude.h
source/slang/core.meta.slang
source/slang/slang-ast-expr.h
source/slang/slang-ast-modifier.h
source/slang/slang-check-expr.cpp
source/slang/slang-check-impl.h
source/slang/slang-emit-cpp.h
source/slang/slang-emit-cuda.cpp
source/slang/slang-emit-cuda.h
source/slang/slang-ir-inst-defs.h
source/slang/slang-ir-insts.h
source/slang/slang-ir.cpp
source/slang/slang-lower-to-ir.cpp
source/slang/slang-options.cpp
source/slang/slang-parser.cpp
tests/autodiff/cuda-kernel-export.slang

This change adds `[CudaHost]` and `[CudaKernel]` attributes for users to define cuda host and kernel functions.
Also adds a `__dispatch_kernel(func, thread_group_size, thread_count)(...)` syntax for dispatching kernels.

Add support for emitting cuda kernel and host functions.

---

docs/user-guide/07-autodiff.md
source/slang/slang-ast-modifier.h
source/slang/slang-check-decl.cpp
source/slang/slang-ir-autodiff-fwd.cpp
source/slang/slang-ir-autodiff-fwd.h
source/slang/slang-ir-autodiff-rev.cpp
source/slang/slang-lower-to-ir.cpp
tests/autodiff/treat-as-differentiable.slang
tests/autodiff/treat-as-differentiable.slang.expected.txt

This changes adds compiler support for using `[TreatAsDifferentiable]` decoration on a function to make it being treated as backward differentiable by the compiler, and causes the compiler to generate a trivial forward and backward derivative function that always return 0.

[TreatAsDifferentiable] functions.

---

source/core/slang-io.cpp
source/core/slang-io.h
source/slang/slang-artifact-output-util.cpp
tools/slang-lookup-generator/lookup-generator-main.cpp

This change makes slangc tool and lookup-generator tool to not write the output file if the content of it does not change.
This avoid unnecessary rebuilds and trivial git diffs from showing up.

Don't touch output file if content did not change.

---

source/slang/diff.meta.slang
source/slang/hlsl.meta.slang
source/slang/slang-emit-c-like.cpp
source/slang/slang-emit.cpp
source/slang/slang-ir-cleanup-void.cpp
source/slang/slang-ir-legalize-types.cpp
source/slang/slang-ir.cpp
source/slang/slang-legalize-types.h

- Add [__readNone] decorations to new intrinsics.
- [Disabled] Perform type legalization to get rid of empty types for Cpp and Cuda targets.
- Add `kIROp_Call` to void type clean up op-code whitelist, this prevents generation of invalid code from `return call(f)` where `f` returns `void`.
- Emit empty initializer list for `DefaultConstruct` on c++ and cuda.

Small fixes and cleanups on CUDA/CPP codegen.

---

prelude/slang-torch-prelude.h
source/slang/slang-emit-torch.cpp

Automatically convert tensor types before calling into the cuda kernel.

Convert tensor types in `make_tensor_view`.

---

source/core/slang-string.cpp

malloc was coming from StandardAllocator

Fix mismatched malloc/delete[] in toWString

---

source/core/unix/slang-unix-process.cpp

We create a pipe which the child closes on execv. If execv fails then the child
is able to tell us why through the pipe. If it closes before we hear anything,
then we know execv was successful.
also `s/exit/_exit`

Detect when calls to execv fail

---

prelude/slang-cuda-prelude.h
source/slang/slang-emit-torch.cpp
source/slang/slang-ir-insts.h
source/slang/slang-ir.cpp

Define vector version of atomicAdd in cuda prelude.
Automatically include the element vector size as  the last dimension when allocating a tensor.

Small fixes to TorchTensor.

---

source/core/slang-http.cpp

Previously we were always setting mimeType as "mimeType"

Correct http header construction

---

prelude/slang-torch-prelude.h
source/slang/slang-emit-torch.cpp
tools/gfx/cuda/cuda-command-queue.cpp

We used to query the shared memory size used by the kernel and use it as the argument in `cudaLaunchKernel`.
This is not the intended use of the `sharedMem` argument. It is meant to allocate additional bytes in the shared memory for dynamic allocation in the kernel. If the kernel just define shared memory objects statically, no additional bytes is required and we should always pass 0.

Set sharedMem argument to 0 when launching cuda kernel.

---

external/dxc/WinAdapter.h
external/dxc/dxcapi.h
premake5.lua
source/compiler-core/slang-dxc-compiler.cpp
source/core/slang-platform.cpp

This currently grabs the DXC headers from the system, rather than from external/dxc
We should make this consistent by either pulling in the Windows adapter from DXC into external/dxc or by making the Windows builds use <dxc/dxcapi.h>

Enable SLANG_ENABLE_DXIL_SUPPORT on non-Windows platforms

---

source/slang/core.meta.slang
source/slang/slang-diagnostic-defs.h
source/slang/slang-ir-use-uninitialized-out-param.cpp
tests/autodiff/bsdf/bsdf-auto-rev.slang
tests/compute/ray-tracing-inline.slang
tests/diagnostics/uninitialized-out.slang
tests/diagnostics/uninitialized-out.slang.expected

Also name uninitialized uses of out parameters

Add warning for returning without initializing out parameter

---

source/slang/slang-ir-autodiff-primal-hoist.cpp
source/slang/slang-ir-autodiff.cpp

- Remove obsolete assert in `extractPriamlFunc`.
- Make `findUniqueStoredVal` to ignore diff uses.

Small fixes to autodiff pass.

---

source/compiler-core/slang-doc-extractor.cpp
source/compiler-core/slang-doc-extractor.h
source/slang/core.meta.slang
source/slang/diff.meta.slang
source/slang/slang-ast-base.h
source/slang/slang-ast-dump.cpp
source/slang/slang-ast-modifier.h
source/slang/slang-ast-print.cpp
source/slang/slang-ast-support-types.h
source/slang/slang-check-modifier.cpp
source/slang/slang-doc-ast.cpp
source/slang/slang-doc-ast.h
source/slang/slang-language-server-ast-lookup.cpp
source/slang/slang-language-server.cpp
source/slang/slang.cpp

This allows intellisense to how documentation for stdlib decls.
Extends doc extract to work on attribute decls.

Embed stdlib documentation to AST.

---

source/slang/diff.meta.slang
source/slang/slang-ir-autodiff-transpose.h

- Fixed insertion point of type promotion in transposition pass
- Added `[BackwardDifferentiable]` to dot and cross builtin methods

Fix issue with out-of-order insts during type promotion when transposing code.

---

tools/gfx/d3d12/d3d12-helper-functions.cpp

My directx device was complaining that it expects either D3D12_SRV_DIMENSION_TEXTURE2DMS or D3D12_SRV_DIMENSION_TEXTURE2DMSARRAY when I tried to bind an MS texture as shader resource.
It looks like this case was not handled in the initSrvDesc() function, so I added it (works for me now).

fixed shader resource views for multisample textures

---

source/slang/slang-ast-support-types.h
source/slang/slang-check-conversion.cpp
source/slang/slang-check-impl.h
source/slang/slang-check-overload.cpp
source/slang/slang-stdlib.cpp
tests/compute/unbounded-array-of-array-syntax.slang.glsl
tests/compute/unbounded-array-of-array-syntax.slang.hlsl
tests/diagnostics/constexpr-error.slang.expected
tests/diagnostics/enum-implicit-conversion.slang.expected
tests/diagnostics/generic-invalid-type-specialization.slang.expected
tests/experimental/liveness/liveness.slang.expected

With this change, uint->int will have cost `kConversionCost_SameSizeUnsignedToSignedConversion` (250) instead of `kConversionCost_General` (900) so we no longer report warnings on them. This has been more annoying then helpful.
Our current logic does not report warnings on int->uint, which is even worse. So there is no reason to report warnings uint->int.
If we have
```
int f(int, int);
int f(uint, uint);
```
After this change, the compiler now prefers the `f(int, int)` overload if the argument types are `(uint, int)`, previously we will choose `f(uint, uint)`.
We need to make sure that a call to `f(uint, 3)` still picks the `uint` overload. To do this, we special case the coercion cost computation if the argument is an `IntLiterialExpr`. We also need to fix the cache for overload …

Be lenient on same-size unsigend->signed conversion.

---

source/slang/slang-diagnostic-defs.h
source/slang/slang-parser.cpp
tests/diagnostics/if-empty-body.slang
tests/diagnostics/if-empty-body.slang.expected

Warn on semicolon after `if`.

---

source/slang/slang-emit.cpp
source/slang/slang-ir-loop-unroll.cpp

If we have a loop bound on a generic integer value, the generic integer value may become an expression at global scope after specialization. We need to fold that global scope value before unrolling, otherwise we can never constant-fold the loop condition.

Apply SCCP on global scope before unrolling loops.

---

source/slang/hlsl.meta.slang
tests/cross-compile/non-uniform-indexing.slang

Ignores NonUniformResourceIndex for non uint/int types. Was tested with float, to make sure generic was taken over (say) coercing into integral, and that appeared to work as expected.
Should probably issue a warning when it is elided in this manner. Look to add in future PR.

Work around for NonUniformResourceIndex with non integral types.

---

build/visual-studio/slang/slang.vcxproj
build/visual-studio/slang/slang.vcxproj.filters
docs/gpu-feature/texture/footprint-queries.md
source/slang/hlsl.meta.slang
source/slang/slang-check-conversion.cpp
source/slang/slang-diagnostic-defs.h
source/slang/slang-emit.cpp
source/slang/slang-intrinsic-expand.cpp
source/slang/slang-ir-inst-defs.h
source/slang/slang-ir-insts.h
source/slang/slang-ir-lower-binding-query.cpp
source/slang/slang-ir-lower-binding-query.h
source/slang/slang-lower-to-ir.cpp
tests/gpu-feature/texture/query/footprint/nv-shader-texture-footprint-simple.slang
tests/gpu-feature/texture/query/footprint/nv-shader-texture-footprint.slang

This change adds operations to the Slang standard library that allow applications to query the texels that would be accessed by a texture sampling operation. These new operations are implementated for Vulkan via the `GL_NV_shader_texure_footprint` extension, and for D3D via NVAPI.
The main challenge in implementing this is that the NVAPI functions require the space/register of the texture and sampler being used for the query to be passed in as integers. In order to support this, the change adds new IR instructions that query the binding information of a resource, and a specialization pass that lowers those instructions by modifying the program to pass space/register information through the call chain.
The tests that have been added confirm that valid SPIR-V is being generated for this new …

Add support for texture footprint queries

---

docs/command-line-slangc-reference.md
source/slang/slang-hlsl-to-vulkan-layout-options.cpp
source/slang/slang-hlsl-to-vulkan-layout-options.h
source/slang/slang-options.cpp
source/slang/slang-parameter-binding.cpp
tests/bindings/hlsl-to-vulkan-shift.hlsl
tests/bindings/hlsl-to-vulkan-shift.hlsl.expected
tests/diagnostics/hlsl-to-vulkan-shift-diagnostic.hlsl

Fix for #2987
Problem was due to inappropriate use of b|t|u|s interpretation as should be using the D3D resource meanings.

Fix vk-shift-* mapping issue

---

source/slang/slang-emit-glsl.cpp
tests/bugs/vk-shift-uniform-issue.slang

In #3000 led to situations where DescriptorSlots were not being used for binding. Specifically when a shift is enabled for HLSL resource kind, the binding remains on the HLSL kind. This leads to HLSL like LayoutResourceKind in IR being HLSL even when doing GLSL emit.
Parts of the GLSL emit assumed DescriptorSlot is the resource kind used. 
The fix here was to in cases where the distinction could happen, enable looking up for the HLSL kind also.

Fix for vk-shift-* GLSL emit issue

---

source/slang/slang-emit-c-like.cpp
source/slang/slang-emit-c-like.h
source/slang/slang-emit-glsl.cpp
source/slang/slang-emit-glsl.h
source/slang/slang-ir-insts.h
source/slang/slang-ir.cpp
source/slang/slang-type-layout.h

In #3004 tries to fix an issue that came up with vk-shift-* can make GLSL emit see HLSL binding types. Moreover there can be a mixture of automatic 'vulkan' layout and shifted types. The change allows for treating multiple LayoutResourceKinds that are in effect the same, to be handled in a robust way.

Better handling of bindings with multiple resource kind "aliases" for GLSL emit

---

source/slang/slang-ast-expr.h
source/slang/slang-check-expr.cpp
source/slang/slang-ir-check-differentiability.cpp
source/slang/slang-ir-inst-defs.h
source/slang/slang-ir-insts.h
source/slang/slang-lower-to-ir.cpp
source/slang/slang-parser.cpp
tests/diagnostics/autodiff-data-flow-4.slang
tests/diagnostics/autodiff-data-flow-4.slang.expected

- Add logic & new decorations to disambiguate calls to differentiable and non-differentiable calls
(Made `TreatAsDifferentiableDecoration` a function-definiton decoration and introduced `DifferentiableCallDecoration` & `TreatCallAsDifferentiableDecoration` for call-sites.
- Add test

Fix data-flow analysis not propagating diff property through differentiable calls

---

build/visual-studio/slang/slang.vcxproj
build/visual-studio/slang/slang.vcxproj.filters
premake5.lua
source/slang/slang.natjmc

This allows Visual Studio debugger to skip over AST visitor dispatch functions and stop directly at the `visit*` functions when stepping into a `dispatch*` call.
Works with Visual Studio 17.6.

Add slang.natjmc.

---

source/slang/core.meta.slang
tests/cross-compile/glsl-texturegather.slang

The translation to GLSL is incomplete as intrinsics only exist for some combination of comparison and channel (just channel 0)
Closes https://github.com/shader-slang/slang/issues/3021

Add GatherCmp* for texture objects

---

source/slang/core.meta.slang
tests/cross-compile/glsl-calculatelevelofdetail.slang

Translates to textureQueryLod().x (with the Unclameped variant being returned in the .y component)
Closes https://github.com/shader-slang/slang/issues/3020

Add glsl intrinsics for CalculateLevelOfDetail

---

source/slang/slang-ast-builder.cpp
source/slang/slang-ast-builder.h
source/slang/slang-ast-type.h
source/slang/slang-check-decl.cpp
tests/bugs/vk-shift-uniform-issue.slang

Fixes #3007.
This change allows global variables to be decorated with [vk::push_constant].
The fix is when checking the global variable decl, if we find it has `push_constant` attribute but its type isn't a `ConstantBuffer`, we change its type to be a `ConstantBuffer<T>`.

Fix push constant on global variables.

---

tools/gfx/d3d12/d3d12-device.cpp

I added to gfx that a RenderTargetView can be created if the incoming type was TextureCube. This case was missing and resulted in an error.

Added D3D12 RenderTargetView TextureCube case

---

source/core/slang-token-reader.h
source/slang/slang-ir-spirv-snippet.cpp

To reduce the number of magic numbers floating around.
Also parses mask sums
Eventually we should replace this with a lookup table with every enum value in

Allow parsing some SPIR-V enums in intrinsics

---

source/slang/slang-ast-base.h
source/slang/slang-ast-builder.h
source/slang/slang-ast-decl-ref.cpp
source/slang/slang-ast-val.cpp
source/slang/slang-check-decl.cpp
source/slang/slang-ir-any-value-marshalling.cpp
source/slang/slang-serialize-ast-type-info.h
source/slang/slang-serialize-container.cpp
source/slang/slang-serialize-type-info.h
source/slang/slang-serialize.h
source/slang/slang-syntax.cpp
source/slang/slang.cpp

- Use SFINAE to override `SerializeTypeInfo<T*>` for certain derived types that works more robustly for value type members.
- Fix several missing calls to `resolve`.
- Concatenate all stdlib sources into a single module before compiling and serializing it so we don't have to deduplicate Vals within stdlibs upon deserialization.

Fix `Val` deduplication bug.

---

source/slang-glslang/slang-glslang.h

Required for memcpy (not sure why this has started being important, but it is the correct thing to do)

Add missing header in slang-glslang

---

source/slang/slang-emit-spirv.cpp
source/slang/slang-ir-insts.h
source/slang/slang-ir.cpp
source/slang/slang-ir.h

SPIR-V doesn't allow vector/sclar arithmetic ops so broadcast first
Also the various float/int casts

Casting and vector/scalar correct arithmetic ops for SPIR-V

---

source/slang/slang-emit-spirv.cpp

Types can depend on constants (for example fixed sized arrays)

Unify Type and Constant sections for SPIR-V

---

build/visual-studio/slang/slang.vcxproj
build/visual-studio/slang/slang.vcxproj.filters
source/slang/slang-diagnostic-defs.h
source/slang/slang-emit-spirv.cpp
source/slang/slang-spirv-val.cpp
source/slang/slang-spirv-val.h

This probably won't stay in this form forever (or could at least go behind a
flag), however it's very useful in development

Validate generated SPIR-V on output

---

source/slang/slang-capability-defs.h
source/slang/slang-lower-to-ir.cpp

They're never appropriate as they're not SPIR-V Opcodes
We could perhaps do with a "Textual" superclass for the existing ones?

Default target intrinsic should not apply to SPIR-V

---

source/slang/slang-check-impl.h
source/slang/slang-check-overload.cpp
source/slang/slang-diagnostic-defs.h
tests/bugs/mutating/mutating-call-in-loop-dce.slang
tests/pipeline/ray-tracing/ray-query-subroutine.slang

By default, function parameters in HLSL are mutable, but any changes to a parameter do not affect the values of the arguments after a call:
void f(int a)
{
a++; // allowed, but kind of useless
}
...
int b = 0;
f(b);
// b is still zero
Because the above behavior is a part of HLSL, we cannot easily diagnose such cases as errors without breaking backward compatibility with existing code.
This change makes it an error to invoke a `[mutating]` method on a function parameter, which cannot affect backward compatibility since the notion of `[mutating]` methods is not present in existing HLSL code:
struct Counter
{
int _state;
[mutating] void increment() { _state++; }
}
void f(Counter a)
{
a.increment(); // ERROR
}
...
Counter b = { 0 };
f(b);
// b is still zero
The compiler will also diagnose …

Add warning on mutation of function parameter

---

source/slang/hlsl.meta.slang
source/slang/slang-ir-glsl-legalize.cpp
source/slang/slang-mangle.cpp
tests/bugs/buffer-swizzle-store.slang
tests/bugs/buffer-swizzle-store.slang.expected.txt
tests/bugs/interlocked-add-uint-int.slang

Fixes #3071 
Fixes #3072 
Fixes #3073 
- Add `InterlockedAdd(__ref uint, int)` overload.
- Fix legalization of GLSL image store where an imageLoad should always return a 4-component vector.
- Add name mangling for modified types.

Various fixes in GLSL emit.

---

source/slang/hlsl.meta.slang
source/slang/slang-ast-type.h
source/slang/slang-emit-c-like.cpp
source/slang/slang-emit-glsl.cpp
source/slang/slang-emit-glsl.h
source/slang/slang-ir-inst-defs.h
source/slang/slang-ir.h
source/slang/slang-type-layout.cpp
tests/hlsl-intrinsic/const-buffer-pointer.slang

This change adds a `ConstBufferPointer` type that maps to a `buffer_reference` on Vulkan.
Usage:
```
struct MyStruct
{
float4 position;
float4x4 transform;
}
struct Globals
{
ConstBufferPointer<MyStruct> pStruct;
}
ConstantBuffer<Globals> gGlobals;
RWStructuredBuffer<uint> outputBuffer;
[numthreads(1,1,1)]
void main(int3 tid: SV_DispatchThreadID)
{
MyStruct s = gGlobals.pStruct.get();
outputBuffer[tid.x] = uint(s.position.x);
}
```

Add support for ConstBufferPointer on Vulkan.

---

source/slang/core.meta.slang
tests/bugs/gh-3085.slang
tests/bugs/texture-array-samplecmplevelzero.slang

Fix `Texture2D.Load()` with offset.

---

build/visual-studio/slang/slang.vcxproj
build/visual-studio/slang/slang.vcxproj.filters
source/slang/slang-emit-c-like.cpp
source/slang/slang-emit-spirv-ops-debug-info-ext.h
source/slang/slang-emit-spirv.cpp
source/slang/slang-ir-inst-defs.h
source/slang/slang-ir-insts.h
source/slang/slang-ir-link.cpp
source/slang/slang-ir.cpp
source/slang/slang-lower-to-ir.cpp
source/slang/slang.cpp
tests/bugs/spirv-debug-info.slang
tests/serialization/obfuscated-module-check-loc.slang
tests/serialization/obfuscated-module-check-loc.slang.1.expected
tests/serialization/obfuscated-module-check-loc.slang.3.expected

Add logic to emit OpDebugSource, OpDebugCompilationUnit, OpDebug and OpDebugLine in spirv-direct backend.

SPIRV: debug source and debug line.

---

tools/gfx/d3d12/d3d12-posix-synchapi.h

This was added to the dxvk header

Remove redundant define form synchapi emulation

---

source/slang/slang-ir-inline.cpp
source/slang/slang-ir-specialize-resources.cpp
tests/bugs/ray-query-in-generic.slang
tests/hlsl-intrinsic/shader-execution-reordering/hit-object-make-hit.slang.1.expected
tests/hlsl-intrinsic/shader-execution-reordering/hit-object-output.slang.1.expected
tests/hlsl-intrinsic/shader-execution-reordering/hit-object-reorder-thread.slang.1.expected
tests/hlsl-intrinsic/shader-execution-reordering/hit-object-trace-motion-ray.slang.1.expected
tests/hlsl-intrinsic/shader-execution-reordering/hit-object-trace-ray.slang.1.expected

Fixes #3141.
Reverts the attempt to specialize functions with RayQuery/HitObject parameters in PR #2929, because specialization introduces new copies of these objects that can't be eliminated. 
We have to resort to inlining them for now.

Inline all RayQuery/HitObject typed functions when targeting GLSL.
