shader-slang/slang

- slang.h
- source/slang/check.cpp
- source/slang/compiler.cpp
- source/slang/compiler.h
- source/slang/emit.cpp
- source/slang/lexer.cpp
- source/slang/parser.cpp
- source/slang/slang-stdlib.cpp
- source/slang/slang.cpp
- source/slang/syntax-visitors.h
- source/slang/syntax.cpp
- source/slang/syntax.h
- tests/render/cross-compile0.hlsl
- tests/render/cross-compile0.slang
- tools/render-test/main.cpp
- tools/render-test/options.cpp
- tools/render-test/options.h
- tools/render-test/render-gl.cpp
- tools/render-test/slang-support.cpp
- tools/render-test/slang-support.h
- tools/slang-test/main.cpp
This set of changes is all about adding a first end-to-end test case for the core cross-compilation appraoch.
Note that this is dealing with cross-compilation of *library* code first. Cross-compilation of entry points is a desirable goal in the long term, but actually isn't something our current customer (Falcor) needs right away.
> Cross compilation

- source/slang/preprocessor.cpp
The basic underlying problem here is that the preprocessor tries to linger at the end of an input stream until it is sure it is time to advance.
An input stream can include raw input files, or the expansion of a macro or macro argument.
This was originally done to deal with not getting good end-of-line tokens when in directives (that issue has been fixed), but it is now a legacy issue that should probably be removed (but I am wary of making such a sweeping change).
The problem that arises is that some code depends on what the actual input stream is (e.g., when turning conditionals on/off), and so we need to be careful.
The bugs that this change affects arise when a `#if` or `#elseif` conditional expression *ends* with a macro expansion:
#define FOO 2
#if 2 == FOO
...
#endif
When we try to …
> Fixes for preprocessor conditionals that use macros

- source/slang/emit.cpp
This is all work on making sure we emit better `#line` directives so that we can get good error messages from downstream compilers when in "rewriter" mode.
> Line directives

- source/slang/check.cpp
- source/slang/emit.cpp
- source/slang/parser.cpp
A few fixes needed by Falcor shader library code.
> Falcor work

- source/slang/check.cpp
- source/slang/emit.cpp
- source/slang/lookup.cpp
- source/slang/lookup.h
- source/slang/parser.cpp
- source/slang/slang-stdlib.cpp
- source/slang/syntax.h
This is all a bunch of work to add missing library functionality needed by Falcor workloads.
> Standard library additions + supporting features

- source/slang/compiler.h
- source/slang/parameter-binding.cpp
- source/slang/slang.cpp
- source/slang/type-layout.cpp
- tests/reflection/reflect-imported-code.hlsl
- tests/reflection/reflect-imported-code.hlsl.expected
- tests/reflection/reflect-imported-code.slang
- tools/slang-test/main.cpp
Something fishy is going on when this change gets tested on AppVeyor, and I need to figure out how to debug the failure (which I can't reproduce locally)
> Reflect imported code

- source/slang/compiler.cpp
- source/slang/emit.cpp
- source/slang/lower.cpp
- source/slang/modifier-defs.h
- source/slang/preprocessor.cpp
- source/slang/slang-stdlib.cpp
- source/slang/syntax.cpp
- source/slang/syntax.h
- source/slang/type-defs.h
- source/slang/val-defs.h
- tests/rewriter/resources-in-structs.glsl
- tests/rewriter/resources-in-structs.slang
This is the initial work on supporting resources-in-structs when lowering to GLSL. There is certainly more that needs to be done, but this gets an initial test case passing.
Re-creating pull request because AppVeyor seems to have gotten confused.
> Resources in structs

- slang.h
- source/slang/compiler.cpp
- source/slang/emit.cpp
- source/slang/profile-defs.h
- source/slang/profile.h
- source/slang/slang-stdlib.cpp
- source/slang/slang.cpp
Working through the easy items in the issue list, and trying to knock things down.
> Various bug fixes

- source/slang/emit.cpp
- source/slang/lower.cpp
- source/slang/slang-stdlib.cpp
- source/slang/syntax.h
These are various fixes motivated by work trying to get the Falcor `Shadows` sample working with cross-compilation. With these changes shader compilation completes, but then we crash inside Falcor. I'd like to hand this off to somebody else to debug the next step.
> Falcor shadows fixes

- source/slang/emit.cpp
- source/slang/slang-stdlib.cpp
These are Slang fixes needed to get the gaussian blur kernel in Falcor working.
> Gaussian blur fixes

- source/slang/emit.cpp
- source/slang/ir-inst-defs.h
- source/slang/ir.cpp
- source/slang/ir.h
- source/slang/lower-to-ir.cpp
- tests/bugs/gh-103.slang
- Add support for matrix types in IR/codegen
- Add support for basic indexing operations in IR/codegen
> Get another test working with IR codedgen

- docs/design/interfaces.md
This covers interfaces, generics, and associated types - hopefully with enough detail that we can start writing up example programs that we believe should compile.
> Add an initial design document on interfaces

- .travis.yml
- Makefile
- tools/slang-test/main.cpp
- tools/slang-test/os.cpp
- tools/slang-test/os.h
Our CI builds are sometimes hanging on Travis, and I suspect it might be something to do with how we are waiting for subprocesses to complete. I'm trying to following the manpage for the `wait()` and `waitpid()` calls a bit better here.
> Attempt to fix subprocess handling for Linux

- source/slang/check.cpp
- source/slang/core.meta.slang
- source/slang/core.meta.slang.h
- source/slang/lookup.cpp
- source/slang/lower-to-ir.cpp
- source/slang/lower.cpp
- tests/bugs/array-size-static-const.hlsl
- tests/bugs/empty.slang
- tests/bugs/implicit-conversion-binary-op.hlsl
- tests/bugs/import-overload-error.hlsl
- tests/bugs/import-overload-error.slang
- tests/bugs/uav-write-index.hlsl
- tests/bugs/vec-init-list.hlsl
This is a grab bag of bug fixes for issues encountered by Slang users.
> Bug fixing

- source/slang/emit.cpp
- source/slang/hlsl.meta.slang
- source/slang/hlsl.meta.slang.h
- tests/bugs/do-loop.hlsl
- tests/hlsl/simple/allow-uav-conditional.hlsl
These are some more bug fixes based on errors encountered by users.
> Do loop fix

- tools/slang-generate/main.cpp
This changes logic of slang-generate to detect whether the newly generated .h file is different from the existing file, and update the existing file only when the actual content has changed. This helps prevent visual studio from repetitively rebuilding the slang project due to the header file being updated on every build.
> Don't update generated .h file if its not changed.

- source/slang/emit.cpp
There was a bug that arose in the context of Falcor, because:
- Slang uses `sprintf` to format floating-point values when outputting HLSL/GLSL source
- Falcor (or a library it uses) does the equivalent of `setlocale(LC_ALL, "")` to set the global locale for the process based on the user's environment variables
This led to a floating-point literal of `0.5` getting printed as `0,5f`, with a comma for the decimal point. This then gets consumed by `glslang` which (luckily for us) complains that `5f` is not a valid floating-point literal in their language (since it has neither decimal point nor exponent).
The most expedient fix in this case was to switch from using C `sprintf` for formatting floating-point numbers over to using the C++ `<stdio>` implementation, which allows the locale to be …
> Fix floating-point literal emit to be locale-independent.

- source/slang/check.cpp
- source/slang/ir.cpp
- source/slang/lower-to-ir.cpp
These seem to be just enough fixes (and hacks) to get a generic extension through codegen.
> Generic extension fixes

- slang.h
- source/slang/check.cpp
- source/slang/core.meta.slang
- source/slang/core.meta.slang.h
- source/slang/emit.cpp
- source/slang/hlsl.meta.slang
- source/slang/hlsl.meta.slang.h
- source/slang/ir-inst-defs.h
- source/slang/ir-ssa.cpp
- source/slang/ir.cpp
- source/slang/slang.cpp
- source/slang/syntax.cpp
- source/slang/vm.cpp
- tests/ir/loop.slang.expected
This is a bunch of smaller changes that I ran into while getting some of the simpler Falcor examples up and running with the new IR-only Slang.
> Falcor fixes

- slang.h
- source/slang/reflection.cpp
- tests/reflection/shared-modifier.hlsl
- tests/reflection/shared-modifier.hlsl.expected
- tools/slang-reflection-test/main.cpp
The main change being merged here is #436 for the `shared` modifier, but it looks like previous features have been cherry-picked and rebased on the master branch, so that this merge commit picks up all the other changes, even if they've already been applied to the master branch.
> Merge from v0.9.15

- tests/render/render0.hlsl
- tools/render-test/render-d3d12.cpp
Problem was around when the ID3D12CommandList was Reset, it required to be rebound with render target rendering state.
> Dx12 Render test working.

- source/slang/lower-to-ir.cpp
> Fixes `ValLoweringVisitor::visitNamedExpressionType` issue 

- source/slang/emit.cpp
When outputting a vector type with a size of 1 in GLSL, it needs to be output as the underlying type. For example vector<float,1> should be output as float in GLSL.
> Fix for issue 571 - vector<Type,1> should be output as 'Type' on glsl.

- source/slang/lower-to-ir.cpp
The problem here arose when a complicated l-value was formed like:
```hlsl
struct Foo { float4 a; }
RWStructuredBuffer<Foo> gBuffer;
gBuffer[index].a.xz += whatever;
```
In this case the `gBuffer[index].a.xz` expression is a complex l-value in multiple ways:
* The `gBuffer[index]` subscript could be routed to either a `get` accessor or a `ref` accessor (and maybe also a `set` accessor if we add one to the stdlib definition), and we defer the choice  of which to call until as late as possible in codegen today.
* The `_.a` part then becomes a "bound member acess" because we can't actually produce a direct pointer until we've resolved how to implement the subscript operation.
* The `_.xz` part becomes a "swizzled l-value" because there is *no* way to materialize it as a pointer to contiguous …
> Fix some issues around codegen for l-values and assignment

- source/slang/emit.cpp
There was some logic called `maybeEmitGLSLFlatModifier()` that was supposed to emit an implicit `flat` modifier for any varying shader parameter with an integer type that wasn't qualified as `nointerpolation` in the input HLSL/Slang (where `nointerpolation` is the equivalent of `flat`).
This wasn't being triggered because I apparently added code to only emit the implicit modifier if there was no explicit one, but then I had this code:
```c++
bool anyModifiers = false;
anyModifiers = true;
...
if(!anyModifiers && ...) { maybeEmitGLSLFlatModifier(); }
```
Unsurprisingly, the `anyModifiers = true` line meant that things never actually triggered. Once I fixed that issue the next problem that arose was that the `maybeEmitGLSLFlatModifier()` logic was being applied to *any* varying integer …
> Fix implicit flat interpolation for GLSL output

- source/slang/ir-insts.h
Remove IRDeclRef as recommended in comments for PR #635 as no longer used/needed.
> Remove IRDeclRef 

- source/core/hash.h
- source/core/slang-string.h
- source/slang/bytecode.cpp
- source/slang/emit.cpp
- source/slang/ir-inst-defs.h
- source/slang/ir-insts.h
- source/slang/ir.cpp
- source/slang/ir.h
- source/slang/lower-to-ir.cpp
- tests/ir/string-literal.slang
- tests/ir/string-literal.slang.expected
* Added support for strings in IR with IRStringLit - with storage o chars after it
* Added kIRDecorationOp_Transitory - can be used for detecting instructions constructed on stack
* Made IRConstant hashing work off type
> Support for IRStringLit

- source/slang/emit.cpp
- source/slang/ir-insts.h
- source/slang/ir-serialize.cpp
- source/slang/ir.cpp
- source/slang/ir.h
- source/slang/lower-to-ir.cpp
This merges and updates the fixes made in `v0.10.36` (PR #685) into the main development branch.
> Vulkan implicit sampler fixups

- source/slang/emit.cpp
- tests/bugs/vk-structured-buffer-binding.hlsl
- tests/bugs/vk-structured-buffer-binding.hlsl.expected
- tests/vkray/closesthit.slang.glsl
* Added fix for bug in outputting vk::binding results on structured buffer
* Added test
* Fixed test, that made output vary because of binding
> Bug fix - vk::binding on structured buffers

- tools/gfx/render-vk.cpp
The VK renderer, impl of DescriptorSet was not keeping objects set on it in scope. The following code might be somewhat overkill - but could be used on any impl with minor changes once wrapped into a class. 
Currently other impls have their own way of keeping resources in scope - seemingly taking into account specifics of the target.
> Keep resources in scope for Vk in DescriptorSet.

- slang.h
- source/slang/compiler.cpp
- source/slang/compiler.h
- source/slang/slang.cpp
- tools/slang-test/main.cpp
* Renamed  spSessionHasCompileTargetSupport to spSessionCheckCompileTargetSupport.
* Improved return codes from spSessionCheckCompileTargetSupport
> Small improvements from review of feature/early-depth-stencil review

- source/slang/diagnostic-defs.h
- source/slang/parameter-binding.cpp
- source/slang/type-layout.h
- tests/diagnostics/single-shader-record.slang.expected
* Use LayoutResourceKind for calcing total num regs used
* Made diagnostic message more compliant + fixed test output
* Typo fixes
> [[vk::shader_record]] review

- source/slang/diagnostic-defs.h
- source/slang/emit.cpp
- source/slang/lower-to-ir.cpp
- tests/diagnostics/undefined-in-preprocessor-conditional.slang.expected
* Fix some comment typos
* Fix typo in diagnostic message
> Fix typos in diagnostic message and comments

- source/slang/ir-glsl-legalize.cpp
Good morning.
I just added support for using gl_PointSize by using the SV_PointSize semantic.
This is my first contribution, any feedback is appreciated.
> Add support for SV_PointSize semantic for glsl

- source/slang/compiler.h
- source/slang/diagnostics.h
* Make sure sourceManager is initialized on DiagnosticSink.
* Typo fix
> Trivial fix - to make sure sourceManager in DiagnosticSink is initialized

- source/slang/emit.cpp
- tests/bugs/vk-structured-buffer-load.hlsl
- tests/bugs/vk-structured-buffer-load.hlsl.glsl
* These operations need to be converted to logical And & Or for scalars
* TODO: handle the bvec case by converting them to uvec
> Fix bitwise And & Or for scalar bool

- source/slang/ir-glsl-legalize.cpp
Attempt to improve the glsl handling of hlsl semantics by taking into account the underlying glsl type.
> Improve handling of types of semantics in glsl

- source/core/slang-io.cpp
- source/core/slang-io.h
- source/core/slang-platform.cpp
- source/core/slang-platform.h
- source/core/slang-shared-library.cpp
- tools/slang-test/slang-test-main.cpp
- tools/slang-test/test-context.cpp
* Added Path::combineBuilder, so as two sub paths can be combined into a StringBuilder
* Renamed and improved comments on SharedLibrary
> Small SharedLibrary/Path improvements

- tools/slang-test/slang-test-main.cpp
We already have test cases that compare `slangc` and `fxc` output (in DXBC assembly). This change adds an option to do the same basic thing for `slangc` and `dxc` (comparing DXIL output).
This isn't being enabled for any of our regression tests right now. It is mostly just a useful feature to have when reproducing customer issues that relate to DXIL output in cases where `dxc` can produce a baseline to compare against to isolate the problem.
> Allow slang-vs-dxc output comparison tets

- source/slang/slang-emit-glsl.cpp
- source/slang/slang-emit-hlsl.cpp
- source/slang/slang-ir-glsl-legalize.cpp
- source/slang/slang-ir-inst-defs.h
- source/slang/slang-ir-insts.h
- source/slang/slang-lower-to-ir.cpp
* GeometryPrimitiveTypeDecoration -> GeometryInputPrimitiveTypeDecoration (to try and closer match meaning and the Modifier name)
* Remove a small problem around definition of IRGeometryPrimitiveTypeDecoration
* Fix comment around IRStreamOutputTypeDecoration
> Fixed from Review of Entry Point decoration #1068

- source/core/slang-riff.cpp
- source/core/slang-riff.h
- source/slang/slang-state-serialize.cpp
- source/slang/slang-state-serialize.h
* Added semantic versioning and hashing test on repro data.
* Added RiffSemanticVersion type
> Version information on repro binary format.

- source/slang/slang-emit-c-like.cpp
- source/slang/slang-emit-c-like.h
- source/slang/slang-emit-hlsl.cpp
These were meant to be merged into #1084, but I failed to push the changes to the server.
> Address review comments on IR layout PR

- prelude/slang-cuda-prelude.h
- source/core/slang-test-tool-util.cpp
- source/slang/slang-emit-cpp.cpp
- source/slang/slang-emit-cpp.h
- source/slang/slang-emit-cuda.cpp
- source/slang/slang-emit-cuda.h
There's lots missing/wrong here, but a slang source file is producing cuda source that nvrtc can compile. 
* Added prelude for cuda
* Added HLSL intrinsic function generation
* Derive CUDA emit impl from C++
> Initial simple slang source -> CUDA compiles

- tools/render-test/bind-location.cpp
On looking into this problem, and debugging, when the buffers 'signs' or 'stuff' is set the amount of values is way larger than the constant buffer. You could argue that the test data is wrong, and this should fail/assert, but here I've made the setUniform function check when writing data and if there is too much data set, the extra data is just ignored.
I was only able to repeat the crash with a win32 build - either way memory was trampled. 
Tim observes:
"The right fix here is to fix up the test case to not pass in data that assumes GPU layout/size, but at that point we really should be transitioning to using the BindPoint abstraction (or some refinement of it) for everything."
This is a bit of a hack (perhaps understatement) it's true. The actual mechanism is a hack, that is only …
> Fix for crash in entry-point-uniform-params.slang

- README.md
- docs/cuda-target.md
- source/slang/hlsl.meta.slang
* Small improvements to CUDA documentation.
* Discussion of Wave intrinsics on CUDA
* Added CUDA target guide to README.md
> Improve CUDA Wave intrinsics documentation.

- source/core/slang-gcc-compiler-util.cpp
- tools/slang-test/slang-test-main.cpp
Improve diagnostic parsing from GCC.
Enable x86_64 CPU tests on TC.
> Improvements to GCC diagnostic parsing.

- source/slang/slang-ast-builder.cpp
- source/slang/slang-compiler.h
- source/slang/slang.cpp
* Fix bug with create being called on null ASTBuilder
* Added ASTBuilder to Module, and construction from it
> Small improvements around ASTBuilder

- source/slang/slang-check-shader.cpp
- tools/slang-test/slang-test.vcxproj
- tools/slang-test/slang-test.vcxproj.filters
- tools/slang-test/test-reporter.h
- tools/slang-test/unit-test-find-type-by-name.cpp
> Fix FindTypeByName reflection API not finding stdlib types.

- source/slang/slang-lower-to-ir.cpp
This change generalizes `lowerSimpleIntrinsicType` to lower all generic arguments of a `DeclRefType` into operands of the resulting IR type. By doing so, we are able to remove the special handling logic in `ValLoweringVisitor::visitPtrType`. In the future we can further cleanup the code handling `elementType`s of resource types.
> Generalize lowerSimpleIntrinsicType to include generic arguments

- source/slang-glslang/slang-glslang.cpp
Glslang texel offset bug fix #1485
> Slang binaries including #1485 fix

- source/slang/slang-ir-legalize-types.cpp
The existing type legalization logic worked as a single preorder pass over the IR tree. This could create problems in cases where an instruction might be processed before one of its operands (e.g., a function that references a global shader parameter is processed before that parameter).
This change makes it so that type legalization uses a work list, and only adds instructions to the work list once their parent, type, and operands have been processed. As a result, we should be able to guarantee that an instruction will only be processed once all of its operands have been.
One wrinkle here is that in the current IR it is possible to end up with a cycle of uses for global-scope instructions, specifically around interface types and their list of requirements. This change includes a …
> Refactor the flow of type legalization

- source/slang/slang-ir-glsl-legalize.cpp
- tests/pipeline/rasterization/conservative-rasterization/inner-coverage.slang
- tests/pipeline/rasterization/conservative-rasterization/inner-coverage.slang.glsl
This was a fairly straightforward addition once I found the correct GLSL extension spec to use.
> Add GLSL support for SV_InnerCoverage

- tools/gfx/cpu/render-cpu.cpp
Get rid of warnings from clang.
> Cleanup CPU renderer.

- docs/_layouts/user-guide.html
Fix a nuanced layout bug when the user resizes window from narrow view to wide view.
> Fix user-guide layout bug

- source/slang/slang-ir.cpp
- source/slang/slang-type-layout.cpp
- source/slang/slang.natvis
And rename debug symbols for navis.
> Fix CUDA vector layout logic.

- .github/workflows/verify-solution-file.yml
- build/visual-studio/compiler-core/compiler-core.vcxproj
- build/visual-studio/core/core.vcxproj
- build/visual-studio/cpu-hello-world/cpu-hello-world.vcxproj
- build/visual-studio/example-base/example-base.vcxproj
- build/visual-studio/gfx-util/gfx-util.vcxproj
- build/visual-studio/gfx/gfx.vcxproj
- build/visual-studio/gpu-printing/gpu-printing.vcxproj
- build/visual-studio/hello-world/hello-world.vcxproj
- build/visual-studio/lz4/lz4.vcxproj
- build/visual-studio/miniz/miniz.vcxproj
- build/visual-studio/model-viewer/model-viewer.vcxproj
- build/visual-studio/platform/platform.vcxproj
- build/visual-studio/render-test-tool/render-test-tool.vcxproj
- build/visual-studio/run-generators/run-generators.vcxproj
- build/visual-studio/shader-object/shader-object.vcxproj
- build/visual-studio/shader-toy/shader-toy.vcxproj
- build/visual-studio/slang-cpp-extractor/slang-cpp-extractor.vcxproj
- build/visual-studio/slang-embed/slang-embed.vcxproj
- build/visual-studio/slang-generate/slang-generate.vcxproj
- build/visual-studio/slang-reflection-test-tool/slang-reflection-test-tool.vcxproj
- build/visual-studio/slang-test/slang-test.vcxproj
- build/visual-studio/slang/slang.vcxproj
- build/visual-studio/slangc/slangc.vcxproj
- build/visual-studio/triangle/triangle.vcxproj
- slang.sln
To match with Github CI setups.
> Change default VS version to 2017.

- source/slang/slang.cpp
> Fix AbortCompilationException leaking through loadModule API.

- slang.h
- source/slang/slang-compiler.h
- source/slang/slang.cpp
This allows the user to load a module from source.
> Add ISession::loadModuleFromSource.

- .github/workflows/release-windows.yml
- .gitignore
- premake5.lua
- source/compiler-core/windows/slang-win-visual-studio-util.cpp
- tools/gfx/open-gl/render-gl.cpp
- tools/platform/windows/win-window.cpp
Fixes to build windows/aarch64 binaries on github.
> Fix GitHub release

- slang-gfx.h
- tools/gfx/cuda/render-cuda.cpp
- tools/gfx/d3d12/render-d3d12.cpp
- tools/gfx/debug-layer.cpp
- tools/gfx/debug-layer.h
- tools/gfx/immediate-renderer-base.cpp
- tools/gfx/vulkan/render-vk.cpp
- Added resource barrier API to `IResourceCommandEncoder`
- Implemented in VK, stubbed in other implementations
No integration in this PR. Test coming in another PR, or can be added here if requested.
> VK Resource Barrier

- source/slang/slang-emit-glsl.cpp
> Add 8/16/64 bit int/uint texture format support in glsl shaders

- slang-gfx.h
- source/core/slang-math.h
- tools/gfx/cuda/render-cuda.cpp
- tools/gfx/d3d12/render-d3d12.cpp
- tools/gfx/debug-layer.cpp
- tools/gfx/debug-layer.h
- tools/gfx/immediate-renderer-base.cpp
- tools/gfx/vulkan/render-vk.cpp
Fixes to code review comments in #2054
> Fixes to `uploadTextureData`.

- slang-gfx.h
- tools/gfx/d3d/d3d-util.cpp
- tools/gfx/d3d/d3d-util.h
- tools/gfx/d3d12/render-d3d12.cpp
* Fix binding null resource views in d3d12.
* Fix array render target view creation.
* Add support for more primitive topologies.
> Fixes to GFX.

- slang-gfx.h
- tools/gfx/d3d12/render-d3d12.cpp
- tools/gfx/renderer-shared.cpp
- tools/gfx/renderer-shared.h
This allows the user application to intercept API calls to create pipeline states. This feature can be used to integrate NVAPI in the user application.
> GFX: Add API interception mechanism for pipeline creation.

- tools/gfx/vulkan/render-vk.cpp
- tools/gfx/vulkan/vk-api.h
Changes:
- Added Vulkan-specific implementation for `createRayTracingPipelineState()`
@csyonghe No test for this right now either beyond running on existing tests.
> Added Vulkan implementation for createRayTracingPipelineState()

- slang-gfx.h
- tools/gfx/cuda/render-cuda.cpp
- tools/gfx/d3d12/render-d3d12.cpp
- tools/gfx/debug-layer.cpp
- tools/gfx/debug-layer.h
- tools/gfx/immediate-renderer-base.cpp
- tools/gfx/renderer-shared.h
- tools/gfx/vulkan/render-vk.cpp
- tools/gfx/vulkan/vk-api.h
This allows resolving query results from GPU.
> gfx: Add `resolveQuery` command.

- build/visual-studio/gfx-unit-test-tool/gfx-unit-test-tool.vcxproj
- build/visual-studio/gfx-unit-test-tool/gfx-unit-test-tool.vcxproj.filters
- tools/gfx-unit-test/clear-texture-test.cpp
- tools/gfx/d3d/d3d-swapchain.h
- tools/gfx/resource-desc-utils.cpp
- tools/gfx/resource-desc-utils.h
- tools/gfx/vulkan/render-vk.cpp
- tools/gfx/vulkan/vk-api.h
- tools/gfx/vulkan/vk-util.cpp
Various fixes to Vulkan device implementation.
> gfx: Various Vulkan fixes.

- source/slang/slang-ir-sccp.cpp
The SCCP optimization pass was recently updated to include some actual
constant folding, but the case for handling `kIROp_Construct` is
mistakenly assuming that any `construct` instruction of a basic
scalar type *must* have exaclty one operand. We have multiple places
in the code that form zero-argument `construct` instructions with
the understanding that these will represent "default" values, and if
one of those ends up in SCCP it causes a crash.
This change adds simple logic to make the folding more robust by
checking the operand count of `construct` instructions before
processing them, and it also adds the logic to fold the zero-operand
case, since that should be a simple one.
> Fix folding of no-arg constructs in SCCP pass

- build/visual-studio/core/core.vcxproj
- build/visual-studio/core/core.vcxproj.filters
- build/visual-studio/slang-rt/slang-rt.vcxproj
- build/visual-studio/slang-rt/slang-rt.vcxproj.filters
- source/core/slang-range.h
- source/slang/slang-ast-print.cpp
- source/slang/slang-ast-print.h
- source/slang/slang-language-server-semantic-tokens.cpp
- source/slang/slang-language-server-semantic-tokens.h
- source/slang/slang-language-server.cpp
- source/slang/slang-workspace-version.cpp
- source/slang/slang-workspace-version.h
Fixing review comments from PR #2264
> Code review fixes for language server.

- source/slang/slang-ir-any-value-marshalling.cpp
- source/slang/slang-ir-specialize-dispatch.cpp
- source/slang/slang-ir-specialize-dynamic-associatedtype-lookup.cpp
+ Include indirectly referenced witness table in dynamic dispatch.
> Fix matrix packing/unpacking logic.

- source/core/slang-byte-encode-util.cpp
This prevents memory tools like gflags causing an exception on the out of bound access.
Given every value is at least one byte, only up to the 3rd-last value is safe, in the case of numBytesRemaining == 2 (the minimum), since it must be followed by at least 2 more bytes (1 for each remaining item).
> Prevent out of bounds access by unaligned access in decodeLiteUInt32

- source/slang/slang-ir-glsl-legalize.cpp
- source/slang/slang-language-server-completion.cpp
- tests/cross-compile/multiview.slang
- tests/cross-compile/multiview.slang.glsl
closes https://github.com/shader-slang/slang/issues/2410
> Add support for SV_ViewID

- github_test.sh
- premake5.lua
- slang.h
- source/slang/slang-ir-diff-jvp.cpp
- source/slang/slang-legalize-types.h
- tools/gfx-unit-test/shader-cache-tests.cpp
Nothing too controversial I hope
> Squash warnings

- docs/design/autodiff.md
Initial version of the reverse-mode design doc.
> Added autodiff design doc

- source/slang/diff.meta.slang
- tests/autodiff/matrix-arithmetic-fwd.slang
This simplifies the syntax to create a `DifferentialPair`.
> Add `diffPair` stdlib function.

- tools/gfx-unit-test/swap-chain-resize-test.cpp
> Fix validation errors (and hang) in swapchain resize test

- premake5.lua
Fix the one space shift in the indentation of `premake5.lua`. Not sure this is something you are interested in, but it screws my editor anytime I try to change things in that file.
> Format premake5.lua

- premake5.lua
> Correct indentation in premake lua

- source/slang/slang-ir-legalize-types.cpp
Run type legalization in a loop until no more changes can be made.
> Fix type legalization pass.

- source/slang/slang-check-stmt.cpp
- source/slang/slang-diagnostic-defs.h
- tests/diagnostics/dangling-comparison.slang
- tests/diagnostics/dangling-comparison.slang.expected
> Warn on dangling comparison operator.

- .github/workflows/linux.yml
- .github/workflows/release-linux.yml
- tools/slang-unit-test/unit-test-persistent-cache.cpp
> Downgrade github runner to 20.04

- .gitignore
- slang.h
- source/core/slang-platform.cpp
- tools/gfx/d3d/d3d-util.cpp
- tools/gfx/d3d/d3d-util.h
- tools/gfx/d3d11/d3d11-device.cpp
- tools/gfx/d3d11/d3d11-query.cpp
- tools/gfx/d3d12/d3d12-device.cpp
- tools/gfx/render.cpp
The last set of "uncontroversial" changes.
> Changes for vkd3d proton

- source/slang/slang-ir-autodiff-cfg-norm.cpp
- source/slang/slang-ir-autodiff-primal-hoist.cpp
- source/slang/slang-ir-autodiff-primal-hoist.h
- source/slang/slang-ir-autodiff-region.h
- source/slang/slang-ir-autodiff-rev.cpp
- source/slang/slang-ir-autodiff-transpose.h
- source/slang/slang-ir-autodiff-unzip.cpp
- source/slang/slang-ir-autodiff-unzip.h
- source/slang/slang-ir-autodiff.cpp
- source/slang/slang-ir-autodiff.h
- source/slang/slang-ir-dce.cpp
- source/slang/slang-ir-inst-defs.h
- source/slang/slang-ir-insts.h
- source/slang/slang-ir-loop-unroll.cpp
- source/slang/slang-ir-redundancy-removal.cpp
- source/slang/slang-ir-util.cpp
- source/slang/slang-ir-util.h
- source/slang/slang-ir.cpp
This change refactors the checkpoint/availability pass to take place after transposition.
> Refactor checkpointing policy and availability pass.

- external/stb/stb_image.h
- external/stb/stb_image_resize.h
- external/stb/stb_image_write.h
- slang.h
- source/core/slang-allocator.h
- source/core/slang-chunked-list.h
- source/core/slang-crypto.h
- source/core/slang-memory-arena.h
- source/slang/slang-ir.cpp
- source/slang/slang-ir.h
- source/slang/slang-serialize-ir.cpp
Change code which will become deprecated with c++20, still compiles with c++17 by default
> Bump glm and stb + small neatenings

- build/visual-studio/gfx/gfx.vcxproj
- build/visual-studio/gfx/gfx.vcxproj.filters
- premake5.lua
- slang.h
- source/compiler-core/slang-fxc-compiler.cpp
- source/core/slang-render-api-util.cpp
- tools/gfx-unit-test/copy-texture-tests.cpp
- tools/gfx/d3d/d3d-util.cpp
- tools/gfx/d3d11/d3d11-device.cpp
- tools/gfx/d3d12/d3d12-base.h
- tools/gfx/d3d12/d3d12-buffer.cpp
- tools/gfx/d3d12/d3d12-fence.cpp
- tools/gfx/d3d12/d3d12-posix-synchapi.cpp
- tools/gfx/d3d12/d3d12-posix-synchapi.h
- tools/gfx/d3d12/d3d12-texture.cpp
There are a couple of failing tests, however it's overall working well enough to be useful to a motivated Linux user.
It currently relies on vkd3d and dxvk being made available externally in the build environment.
Disabled by default obviously.
> vkd3d and dxvk integration

- source/slang/slang-check-decl.cpp
Fixes issues that prevent code completion and hover info from working on attribute arguments.
> Improve intellisense for attribute arguments.

- source/slang/core.meta.slang
- source/slang/slang-ast-support-types.cpp
- source/slang/slang-parser.cpp
Add `bwd_diff`, `fwd_diff` and `[Differentiable(n)]`.
> Add finalized keywords for autodiff.

- source/slang/slang-diagnostic-defs.h
- source/slang/slang-ir-autodiff-rev.cpp
- source/slang/slang-ir-legalize-types.cpp
- source/slang/slang-ir-single-return.cpp
- source/slang/slang-ir-single-return.h
- tests/diagnostics/unbound-loop.slang
Fixes #2901 
Also added a diagnostic on functions that never returns before trying to differentiate it.
Fixes #2900
> Fix bug in legalizeFuncType that leads to invalid IR.

- source/slang/slang-emit.cpp
- source/slang/slang-ir-autodiff-fwd.cpp
- source/slang/slang-ir-sccp.cpp
- source/slang/slang-ir-sccp.h
- source/slang/slang-ir-ssa-simplification.cpp
- source/slang/slang-ir-ssa-simplification.h
- source/slang/slang-lower-to-ir.cpp
- tests/diagnostics/sccp-div-by-zero.slang
> Fix div-by-zero error during sccp.

- build/visual-studio/slang/slang.vcxproj
- build/visual-studio/slang/slang.vcxproj.filters
- source/slang/slang-container-pool.h
- source/slang/slang-emit-c-like.cpp
- source/slang/slang-ir-address-analysis.cpp
- source/slang/slang-ir-augment-make-existential.cpp
- source/slang/slang-ir-check-differentiability.cpp
- source/slang/slang-ir-cleanup-void.cpp
- source/slang/slang-ir-constexpr.cpp
- source/slang/slang-ir-dce.cpp
- source/slang/slang-ir-deduplicate.cpp
- source/slang/slang-ir-generics-lowering-context.h
- source/slang/slang-ir-init-local-var.cpp
- source/slang/slang-ir-inst-pass-base.h
- source/slang/slang-ir-legalize-types.cpp
- source/slang/slang-ir-lower-binding-query.cpp
- source/slang/slang-ir-lower-error-handling.cpp
- source/slang/slang-ir-lower-generics.cpp
- source/slang/slang-ir-lower-optional-type.cpp
- source/slang/slang-ir-lower-result-type.cpp
- source/slang/slang-ir-lower-tuple-types.cpp
- source/slang/slang-ir-lower-witness-lookup.cpp
- source/slang/slang-ir-redundancy-removal.cpp
- source/slang/slang-ir-simplify-for-emit.cpp
- source/slang/slang-ir-specialize.cpp
- source/slang/slang-ir-ssa-register-allocate.cpp
- source/slang/slang-ir.h
- source/slang/slang-lower-to-ir.cpp
This further improves backend perf by 10%.
> Pool inst worklists and hashsets to avoid rehashing.

- prelude/slang-torch-prelude.h
A way around the bug with casting of torch tensors using `.to()` where the first cast is successful, but subsequent transfers appear to fail and return the first tensor causing really odd bugs.
This PR replaces the casting with an error message instead. This asks the user to use `.cuda()` and `.dtype(torch.float)` from the Python side instead of performing it implicitly (which can also cause unintended memory allocations)
Tests for the bug are available at: **https://github.com/shader-slang/slang-python/blob/aa74c0a6a540969b720c834b73b999e6ee690a9a/tests/test.py#L21C16-L21C16**
(they are currently skipped)
> Torch target: Avoid implicit casts or device transfers on torch tensors

- source/slang/hlsl.meta.slang
> Remove [__readNone] on clip.

- source/slang/slang-emit-glsl.cpp
- source/slang/slang-parameter-binding.cpp
- tests/bindings/hlsl-to-vulkan-shift-bshift-global.slang
- tests/bindings/hlsl-to-vulkan-shift-rw-structured.hlsl
- tests/bugs/vk-shift-uniform-issue.slang
This is a partial fix to issue #3032.
> Fix -fvk-u-shift not applying to global constant buffer.

- source/slang/slang-ir-any-value-marshalling.cpp
This should not be returning UInt, it should be a pointer type
> Correct return type for emitFieldAddress

- source/slang/slang-emit-spirv.cpp
No sensible way to continue here
> Fail on an unhandled spv operand

- source/slang/slang-diagnostic-defs.h
- source/slang/slang-emit-spirv.cpp
- source/slang/slang-ir-spirv-legalize.cpp
- source/slang/slang-ir-spirv-legalize.h
- source/slang/slang-ir-spirv-snippet.cpp
- source/slang/slang-ir-util.cpp
- source/slang/slang-ir-util.h
Plus some more/clearer asserts
> Diagnostic improvements for direct spirv

- build/visual-studio/compiler-core/compiler-core.vcxproj
- build/visual-studio/compiler-core/compiler-core.vcxproj.filters
- slang.h
- source/compiler-core/slang-downstream-compiler-util.cpp
- source/compiler-core/slang-spirv-dis-compiler.cpp
- source/compiler-core/slang-spirv-dis-compiler.h
- source/core/slang-type-text-util.cpp
- source/slang/slang-compiler.cpp
- source/slang/slang-compiler.h
- tests/diagnostics/command-line/x-arg-tool-unknown.slang.expected
Just the most basic working implementation at the moment
> Add spirv-dis as a downstream compiler

- source/slang/slang-check-expr.cpp
- tests/bugs/gh-3086.slang
- tools/slang-unit-test/unit-test-lock-file.cpp
> Allow member lookup through modified type.

- source/slang/hlsl.meta.slang
> Add scalar version of `distance`.

- source/compiler-core/slang-diagnostic-sink.cpp
- source/compiler-core/slang-diagnostic-sink.h
- source/slang/slang-parameter-binding.cpp
- tests/bugs/warn-39001-disable.slang
> Fix a bug that warning 39001 can't be fully disabled.

- tools/gfx/d3d12/d3d12-posix-synchapi.cpp
This can happen if vkd3d-proton triggered a VK_DEVICE_LOST for example.
Platform limitations preclude a totally faithful emulation anyway.
> Bail out of infinite timeouts in our posix synchapi emulation

- source/slang/hlsl.meta.slang
- source/slang/slang-spirv-val.cpp
And place the error message at the bottom to minimize scrolling
> color spirv-val output

- deps/target-deps.json
- source/slang/slang-stdlib-textures.cpp
- tests/expected-failure.txt
- tests/hlsl-intrinsic/texture-lod-shadow.slang
> Update prebuilt glslang binaries

- examples/hello-world/main.cpp
- examples/hello-world/vulkan-api.cpp
- source/slang/slang-ir-glsl-legalize.cpp
- source/slang/slang-ir-insts.h
- tests/spirv/direct-spirv-emit.slang.expected
- tools/gfx/vulkan/vk-shader-program.cpp
> Use direct spirv in hello-world example.

- source/slang/diff.meta.slang
> Remove `[NoSideEffect]` from `DiffTensorView.store()`

- deps/target-deps.json
- docs/stdlib-doc.md
- prelude/slang-cpp-scalar-intrinsics.h
- prelude/slang-cuda-prelude.h
- source/slang/hlsl.meta.slang
- tests/bugs/frexp-double.slang
- tests/bugs/frexp.slang
Fixes https://github.com/shader-slang/slang/issues/3282
> Make the exponent return value from frexp int

- source/slang/hlsl.meta.slang
- source/slang/slang-emit-spirv.cpp
> Several spirv intrinsics and small fix

- source/slang/slang-ir-peephole.cpp
Fixes https://github.com/shader-slang/slang/issues/3323
> Fix Phi simplification bug

- source/slang/hlsl.meta.slang
- tests/spirv/fwidth.slang
> Fix spirv intrinsics for partial derivatives.

- source/slang/slang-ast-print.cpp
- source/slang/slang-check-decl.cpp
- source/slang/slang-language-server.cpp
- tests/language-server/incomplete-custom-derivative.slang
- tools/slang-test/slang-test-main.cpp
Fix language server crash when checking custom derivative attributes.
Fix failed signature help.
> Misc language server fixes.

- source/slang/slang-check-decl.cpp
- source/slang/slang-check-shader.cpp
- source/slang/slang-lower-to-ir.cpp
- source/slang/slang.cpp
- tests/language-feature/modules/import-in-include/a.slang
- tests/language-feature/modules/import-in-include/b.slang
- tests/language-feature/modules/import-in-include/c.slang
- tests/language-feature/modules/import-in-include/helper.slang
> Handle import, entrypoint and global params in included files.

- source/compiler-core/slang-diagnostic-sink.h
- source/slang/hlsl.meta.slang
- source/slang/slang-ast-modifier.cpp
- source/slang/slang-ast-modifier.h
- source/slang/slang-check-modifier.cpp
- source/slang/slang-diagnostic-defs.h
- source/slang/slang-parser.cpp
- tests/diagnostics/modifier-check.slang
- tests/nv-extensions/nv-ray-tracing-motion-blur.slang
- tests/vkray/raygen.slang
> Add check for invalid use of modifiers.

- source/slang/hlsl.meta.slang
- source/slang/slang-emit-spirv.cpp
- tests/hlsl-intrinsic/const-buffer-pointer.slang
> Add spirv intrinsics for `ConstBufferPointer`.

- source/slang/slang-emit-c-like.cpp
- source/slang/slang-emit.cpp
- source/slang/slang-ir-explicit-global-init.cpp
- source/slang/slang-lower-to-ir.cpp
- tests/bugs/gh-2959.slang
- tests/bugs/gh-3408.slang
> Fix GLSL static initialization bug.

- source/slang/slang-emit.cpp
Looks like `#3327` left in some debugging code.
> Comment out some debug code

- build/visual-studio/slang/slang.vcxproj
- build/visual-studio/slang/slang.vcxproj.filters
- source/slang/core.meta.slang
- source/slang/slang-ast-modifier.h
- source/slang/slang-ast-type.h
- source/slang/slang-check-decl.cpp
- source/slang/slang-check-expr.cpp
- source/slang/slang-check-modifier.cpp
- source/slang/slang-diagnostic-defs.h
- source/slang/slang-emit.cpp
- source/slang/slang-ir-inst-defs.h
- source/slang/slang-ir-insts.h
- source/slang/slang-ir-lower-glsl-ssbo-types.cpp
- source/slang/slang-ir-lower-glsl-ssbo-types.h
- source/slang/slang-ir.cpp
- source/slang/slang-ir.h
- source/slang/slang-lower-to-ir.cpp
- source/slang/slang-parser.cpp
- source/slang/slang-stdlib.cpp
- source/slang/slang-type-layout.cpp
- tests/glsl/ssbo-2.slang
- tests/glsl/ssbo.slang
One small todo is to move the lowering later in the pipeline, at the moment this hits a validation bug for the non-array case.
Documentation too
> GLSL SSBO Support

- tests/compute/groupshared-init.slang
We can close https://github.com/shader-slang/slang/issues/2964 which got fixed sometime
> Add test for glsl groupshared init

- source/slang/slang-ir-propagate-func-properties.cpp
- tests/bugs/gh-3429.slang
> Fix funcs w/ buffer load being treated as readnone.

- source/slang/slang-ast-modifier.h
- source/slang/slang-check-modifier.cpp
- source/slang/slang-ir-insts.h
- source/slang/slang-ir.cpp
- source/slang/slang-lower-to-ir.cpp
- source/slang/slang-parser.cpp
- tests/glsl/compute-shader-layout.slang
Closes https://github.com/shader-slang/slang/issues/3523
> Correctly apply glsl local size layout to entry points during lowering

- source/slang/hlsl.meta.slang
- source/slang/slang-ir-use-uninitialized-out-param.cpp
- source/slang/slang-parser.cpp
- source/slang/slang.cpp
- tests/hlsl-intrinsic/byte-address-buffer/byte-address-half-atomics.slang
- tests/hlsl-intrinsic/texture/float-atomics.slang
- tests/language-feature/spirv-asm/too-many-operands.slang
Also fixes warnings in existing stdlib, add debug assertion to prevent future warnings.
Fixes #2926.
> FP16 atomics for RWByteAddresBuffer, fp32 atomics for images.

- source/slang/slang-emit-spirv.cpp
- source/slang/slang-ir-specialize-resources.cpp
- source/slang/slang-ir-specialize-resources.h
- tests/spirv/array-param-gep.slang
> Fix spirv emit that leads to pathological downstream time.

- source/slang/core.meta.slang
- source/slang/hlsl.meta.slang
- source/slang/slang-ast-modifier.h
- source/slang/slang-check-modifier.cpp
- source/slang/slang-emit-glsl.cpp
- source/slang/slang-ir-lower-glsl-ssbo-types.cpp
- source/slang/slang-ir.h
- source/slang/slang-lower-to-ir.cpp
- source/slang/slang-parser.cpp
- source/slang/slang-parser.h
- source/slang/slang-preprocessor.cpp
- source/slang/slang-preprocessor.h
- source/slang/slang.cpp
- tests/glsl/ssbo-scalar.slang
+ Automatic GLSL module recognition.
Fixes #3535.
Fixes #3369.
> Unify GLSL and HLSL buffer block parsing.

- .github/workflows/macos.yml
- .github/workflows/release-macos.yml
- github_macos_build.sh
> deploy slang-glslang with macos releases

- source/slang/slang-ir-glsl-legalize.cpp
- source/slang/slang-lower-to-ir.cpp
- tests/language-feature/generics/generic-static-const.slang
> Fix lowering of static consts in a generic function.

- .github/workflows/release-linux-arm64.yml
- github_build.sh
- Add release package build for linux aarch64
- Enable libslang-glslang build under linux aarch64
- Remove the slang-llvm under linux aarch64 build
> Add release package build for linux aarch64

- examples/platform-test/main.cpp
- slang.h
- source/compiler-core/slang-source-loc.h
- source/slang/slang-api.cpp
- source/slang/slang-check-decl.cpp
- source/slang/slang-check-modifier.cpp
- source/slang/slang-check-shader.cpp
- source/slang/slang-compiler.cpp
- source/slang/slang-compiler.h
- source/slang/slang-ir-link.cpp
- source/slang/slang-module-library.cpp
- source/slang/slang-module-library.h
- source/slang/slang-options.cpp
- source/slang/slang-serialize-container.cpp
- source/slang/slang-serialize-container.h
- source/slang/slang-serialize-factory.cpp
- source/slang/slang.cpp
- tests/serialization/extern/extern-test.slang
- tests/serialization/extern/module-a.slang
- tests/serialization/extern/module-b.slang
- tests/serialization/obfuscated-loc-module.slang
- tests/serialization/obfuscated-module-check-loc.slang
- tests/serialization/obfuscated-serialized-module-shared.slang
- tests/serialization/obfuscated-serialized-module-test.slang
- tests/serialization/obfuscated-serialized-module.slang
- tests/serialization/serialized-module-shared.slang
- tests/serialization/serialized-module-test.slang
- tests/serialization/serialized-module.slang
- tools/render-test/slang-support.cpp
- tools/slang-test/slangc-tool.cpp
> Add slangc interface to compile and use ir modules.

- .github/github_test.sh
- .github/workflows/linux-arm64.yml
- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/windows.yml
- source/slang/core.meta.slang
- source/slang/slang-emit-spirv.cpp
- source/slang/slang-parser.cpp
- tests/spirv/multi-entry-point-input-var.slang
- tests/spirv/unknown-opcode.slang
Fixes #3613.
Fixes #3515.
Fixes #3155.
Also fixes #3619.
> SPIRV Fixes.

- README.md
- docs/user-guide/08-compiling.md
- docs/user-guide/10-link-time-specialization.md
> Add documentation for debugging.

- source/slang/slang-ir-spirv-legalize.cpp
- tests/spirv/pointer-array.slang
> Fix SPIRV pointer codegen.

- .github/workflows/falcor-test.yml
- source/slang/slang-emit-spirv.cpp
- tests/spirv/pointer-bug-2.slang
> [SPIRV] Fix pointer lowering bug.

- tests/hlsl-intrinsic/ray-tracing/ray-query-intrinsics.slang
For https://github.com/shader-slang/slang/issues/3493
> Add ray query intrinsic test

- source/slang/slang-emit-spirv.cpp
- source/slang/slang-ir-glsl-legalize.cpp
- source/slang/slang-ir-spirv-legalize.cpp
- tests/cross-compile/sv-coverage.slang
- tests/spirv/flat-builtin.slang
- tests/spirv/primitive-id.slang
Fixes #3719.
Fixes #3714.
Fixes #3699.
> [SPIRV] fix code gen for `SV_Coverage`.

- docs/user-guide/08-compiling.md
- docs/user-guide/a1-05-uniformity.md
- docs/user-guide/a1-special-topics.md
- docs/user-guide/toc.html
- source/slang/slang-diagnostic-defs.h
- source/slang/slang-ir-uniformity.cpp
- tests/language-feature/dynamic-uniform/dynamic-uniform-1.slang
> Add documentation for uniformity analysis + small fix.

- source/slang/slang-check-expr.cpp
- tests/bugs/gh-3727.slang
> Fix crash when trying to constant fold non-existent call.

- source/slang/slang-emit-glsl.cpp
- source/slang/slang-emit-spirv.cpp
- tests/spirv/shading-rate.slang
> Fix spirv builtin for `SV_ShadingRate`.

- source/slang/slang-emit-cpp.cpp
> Support emitting generic target_intrinsic type.

- source/slang/diff.meta.slang
> Fix derivative implementation of `clamp`.

- build/visual-studio/slang-unit-test-tool/slang-unit-test-tool.vcxproj
- build/visual-studio/slang-unit-test-tool/slang-unit-test-tool.vcxproj.filters
- source/slang/slang-check-expr.cpp
- source/slang/slang-check-type.cpp
- source/slang/slang-diagnostic-defs.h
- source/slang/slang-ir-lower-buffer-element-type.cpp
- source/slang/slang-ir-lower-buffer-element-type.h
- source/slang/slang-ir-spirv-legalize.cpp
- source/slang/slang.cpp
- tests/front-end/typedef-matrix.slang
- tests/spirv/buffer-pointer-matrix-layout.slang
- tests/spirv/pointer-bug.slang
- tests/spirv/pointer.slang
- tools/slang-unit-test/unit-test-default-matrix-layout.cpp
> Fix `sessionDesc.defaultMatrixLayoutMode` being ineffective.

- source/slang/slang-check-decl.cpp
- source/slang/slang-check-impl.h
- tools/gfx-unit-test/link-time-type.cpp
> Add wrapper type synthesis logic for constructors.

- source/slang/slang-check-shader.cpp
- source/slang/slang-ir-specialize.cpp
> Fix crash when specializing generic entry points.

- CMakeLists.txt
- cmake/SlangTarget.cmake
Address CMake issues with linking against frameworks on MacOS
> CMake fixes for MacOS

- docs/user-guide/a1-04-interop.md
> Add cautionary desclaimers on interop mechanisms.

- source/slang/slang-ir-spirv-legalize.cpp
- source/slang/slang-ir-translate-glsl-global-var.cpp
> Fix lowering of glsl builtin globals.

- source/slang/slang-check-conformance.cpp
- source/slang/slang-check-decl.cpp
- source/slang/slang-check-impl.h
- source/slang/slang-diagnostic-defs.h
- tests/diagnostics/invalid-constraint.slang
> Add diagnostic on invalid type constraint.

- docs/user-guide/02-conventional-features.md
- source/slang/core.meta.slang
- source/slang/slang-ast-modifier.h
- source/slang/slang-check-modifier.cpp
- source/slang/slang-lookup.cpp
- tests/language-feature/enums/unscoped-enum.slang
> Support unscoped enums.

- build/visual-studio/slang/slang.vcxproj
- build/visual-studio/slang/slang.vcxproj.filters
- source/slang/slang-diagnostic-defs.h
- source/slang/slang-ir-check-recursive-type.cpp
- source/slang/slang-ir-check-recursive-type.h
- source/slang/slang-lower-to-ir.cpp
- tests/bugs/cyclic-type.slang
> Check for cylic types.

- source/slang/slang-emit.cpp
- tests/bugs/cyclic-type-2.slang
> Check cyclic types after specialization.

- source/slang/slang-ir-lower-buffer-element-type.cpp
- tests/bugs/gh-3795.slang
> Fix regression on pointer address space handling.

- source/slang/slang-ast-type.cpp
- tests/bugs/gh-3792.slang
> Fix type checking for constructors in generic interfaces.

- source/slang/slang-parser.cpp
- tests/bugs/gh-3802.slang
> Fix namespace parsing.

- source/slang/slang-ir-glsl-legalize.cpp
- source/slang/slang-ir-specialize-resources.cpp
- tests/spirv/geometry-shader-sub-func.slang
> Fix spirv generation for using output stream in a function.

- source/slang/slang-check-inheritance.cpp
- source/slang/slang-diagnostic-defs.h
- tests/bugs/gh-3808.slang
> Diagnose cyclic references in inheritance graph.

- slang.h
- source/slang/slang-check-decl.cpp
- source/slang/slang-emit-hlsl.cpp
- source/slang/slang-emit-hlsl.h
- source/slang/slang-ir-inst-defs.h
- source/slang/slang-ir-insts.h
- source/slang/slang-lower-to-ir.cpp
- source/slang/slang-options.cpp
- source/slang/slang-parser.cpp
- tests/bindings/array-of-struct-of-resource.hlsl
- tests/bindings/binding0.hlsl
- tests/bindings/binding1.hlsl
- tests/bindings/explicit-binding.hlsl
- tests/bindings/multi-file.hlsl
- tests/bindings/parameter-blocks.slang
- tests/bindings/resources-in-cbuffer.hlsl
- tests/bindings/targets-and-uavs-structure.hlsl
- tests/bindings/targets-and-uavs.hlsl
- tests/bugs/gh-103.slang
- tests/bugs/gh-333.slang
- tests/bugs/gh-666.slang
- tests/bugs/split-nested-types.hlsl
- tests/hlsl/simple/allow-uav-conditional.hlsl
- tests/hlsl/simple/compute-numthreads.hlsl
- tests/hlsl/simple/implicit_conversion.hlsl
- tests/hlsl/simple/literal-typing.hlsl
- tests/hlsl/simple/rw-texture.hlsl
- tests/language-feature/no-hlsl-binding.slang
- tests/language-feature/no-mangle.slang
- tests/rewriter/varying-struct.vert
> Make `-no-mangle` option work, add `-no-hlsl-binding`.

- source/slang/slang-check-decl.cpp
- source/slang/slang-check-impl.h
- source/slang/slang-check-modifier.cpp
- source/slang/slang-check-stmt.cpp
- source/slang/slang-lookup.cpp
- source/slang/slang-parser.cpp
- tests/language-feature/anonymous-struct.slang
> Allow anonymous struct.

- source/slang/slang-emit-spirv.cpp
- tests/spirv/depth-replacing-none.slang
> Fix the erroneous logic of determining whether or not to emit DepthReplacing.

- source/slang/hlsl.meta.slang
- tests/spirv/barrier.slang
> Update glsl intrinsic for GroupMemoryBarrierWithGroupSync

- source/slang/slang-emit-spirv.cpp
- tests/pipeline/rasterization/mesh/mesh-PerPrimitiveEXT.slang
> Add decoration PerPrimitiveEXT for all OutputPrimitives members for mesh shaders

- source/slang/slang-type-layout.cpp
- tests/hlsl/append-structured-buffer.slang
The current logic double counts the counter resource.
Fixes #3923.
> Fix typelayout for append/consume structured buffers.

- source/slang/slang-check-shader.cpp
> Fix another bug in entrypoint specialization arg synthesis.

- source/slang/slang-preprocessor.cpp
- tests/preprocessor/line-macro.slang
> Fix micro expansion issue for __LINE__.

- source/slang/glsl.meta.slang
- source/slang/hlsl.meta.slang
- tests/glsl-intrinsic/intrinsic-basic.slang
Fixes #4051
This commit implements SPIR-V target for GLSL functions. It also fixes a few problesm of GLSL targetting implemention too.
> Implement SPIR-V target for GLSL functions

- source/slang/slang-emit-spirv.cpp
- tests/bugs/gh-4111.slang
> Make sure pointer local vars have `AliasedPointer` decoration.

- tests/metal/texture-binding-index.slang
This commit adds a test case that check the texture binding index for the combined textures and not-combined textures. It also tests the binding index that is explicitly specified.
> Test binding index for combined and not-combined textures

- docs/user-guide/08-compiling.md
I think the sentence was saying the opposite of what it meant!
> Fix confusion in Translation Units doc

- docs/user-guide/03-convenience-features.md
- tests/spirv/pointer-from-user-guide.slang
Closes #4243
Update document regarding pointer.
And also add an actual test case from the User Guide example.
> Update document regarding pointer

- docs/user-guide/08-compiling.md
Fixed as I was testing release `v2024.1.17` (latest)
> Various issues in code snippets

- examples/hello-world/main.cpp
Changed profile string from `glsl_440` to `spirv_1_5` per request in pr#4268.
> Fixed profile string per request in pr#4268

- source/slang/hlsl.meta.slang
- tests/hlsl/texture-mips-operator.slang
> Support HLSL `.mips` syntax.

- tools/gfx/metal/metal-command-encoder.cpp
- tools/gfx/metal/metal-device.cpp
- tools/gfx/metal/metal-fence.cpp
- tools/gfx/metal/metal-helper-functions.h
- tools/gfx/metal/metal-pipeline-state.cpp
- tools/gfx/metal/metal-resource-views.cpp
- fix binding resources in graphics passes
- fix binding vertex buffers
- implement `Device::readTextureResource`
- cleanup
> [gfx] Metal improvements

- source/slang/slang-emit-c-like.cpp
- tests/compute/static-const-array.slang
- tests/compute/static-const-matrix-array.slang
- tests/compute/static-const-vector-array.slang
> [Metal] Fix global constant array emit.

- source/slang/glsl.meta.slang
> Fixed gl_LocalInvocationIndex being uvec3 instead of uint

- source/slang/hlsl.meta.slang
- tests/bugs/gh-4414.slang
> Disambiguate int type matrix multiply

- docs/proposals/README.md
Bug: 4511
Author: Shannon Woods
>     Add clearer information about how to submit a proposal document.

- source/slang/glsl.meta.slang
- tests/spirv/texture-query-lod.slang
Fixes #4357 
Add a test to check that the capability is indeed in the generated code.
> Supply SPIRV capability for textureQueryLod

- .github/workflows/macos.yml
- .github/workflows/release-macos.yml
- .github/workflows/release-windows.yml
- .github/workflows/windows.yml
Add README.md and LICENSE to binary windows and macos packages.
Fixes issue https://github.com/shader-slang/slang/issues/4117
> Add README.md and LICENSE to binary windows and macos packages

- source/slang/hlsl.meta.slang
- tests/bugs/gh-4533.slang
Closes #4533
Fixes part of #4531
> Add specializations for 1 vectors in functions using the $N glsl intrinsic placement

- source/compiler-core/slang-lexer.cpp
- tests/hlsl-intrinsic/scalar-swizzling.slang
> Fix Lexer to recognize swizzling on an integer scalar value

- .github/workflows/release-linux-glibc-2-17.yml
> Change to use cmake in centos7 build

- CONTRIBUTION.md
The path to slang-test.exe has been changed recently and it needs to be updated on the document.
> Update CONTRIBUTION.md for path to slang-test.exe

- docs/user-guide/09-targets.md
- docs/user-guide/toc.html
Related to an issue #4262
The description of "Parameter passing" part for Metal is related to PR #4022.
> Add Metal to user-guide/09-targets.md

- prelude/slang-cuda-prelude.h
> Add missing make_bool intrinsics in cuda prelude.

- source/slang/core.meta.slang
- tests/language-feature/enums/implicit-cast-to-bool.slang
> Allow implicitly casting enum types to bool.

- .github/workflows/ci.yml
- .github/workflows/compile-regression-test.yml
- .github/workflows/ensure-pr-label.yml
- .github/workflows/falcor-compiler-perf-test.yml
- .github/workflows/falcor-test.yml
- .github/workflows/release.yml
> Don't trigger CI on doc changes.

- source/slang/slang-ir-specialize.cpp
- tools/slang-unit-test/unit-test-generic-interface-conformance.cpp
> FIx issue with specializing witness tables

- docs/proposals/008-tuples.md
> Design proposal for Tuple types.

- source/core/slang-io.cpp
- source/slang/slang-ir-specialize-function-call.cpp
Implement Path::createDirectoryRecursive with existing Path::createDirectory that uses system call instead of c++ standard lib.
> Implement Path::createDirectoryRecursive

- source/slang/slang-ir-metal-legalize.cpp
Fixing Metal semantic for primitive_id
> Metal: Fix metal primitive_id semantic

- .github/workflows/benchmark.yml
- .github/workflows/push-benchmark-results.yml
> Push benchmark results to a viewable page

- .github/workflows/push-benchmark-results.yml
- tools/benchmark/compile.py
Also fixes the machine used for running so that the benchmark results will have reduced variance.
> Remove unused package in primary benchmark script

- source/slang/core.meta.slang
- tests/bugs/gh-5026.slang
> Fix generic IInteger `mod` implementation.

- source/slang/slang-ir-use-uninitialized-values.cpp
- tests/diagnostics/uninitialized-struct-from-constructor.slang
> Fix compilation warning with uninitialized struct use in constructors

- docs/proposals/002-type-equality-constraints.md
This proposal builds on the other proposal for `where` clauses.
> Add proposal for equality constraints

- .github/actions/common-setup/action.yml
SCCACHE_IGNORE_SERVER_IO_ERROR=1
Closes https://github.com/shader-slang/slang/issues/5163
> Add fallback flag for sccache

- source/slang/slang-lower-to-ir.cpp
Fix the lowering bug that can lead to IR validation assert on debug builds.
> Fix target switch lowering bug.

- .github/actions/common-setup/action.yml
Hopefully alleviates https://github.com/shader-slang/slang/issues/5163
> Switch sccache action to Mozilla-Actions version

- source/slang/slang-ir.cpp
- source/slang/slang-parser.cpp
The type of `sizeof` has to be int not uint.
> Fix the broken CI

- source/slang/slang-check-decl.cpp
- source/slang/slang-diagnostic-defs.h
- source/slang/slang-ir-insts.h
- source/slang/slang-ir-lower-buffer-element-type.cpp
- source/slang/slang-ir-specialize-address-space.cpp
- source/slang/slang-ir.cpp
- tests/bugs/gh-3825.slang
- tests/spirv/ptr-unsized-array.slang
> Fix spirv lowering logic around pointer to unsized array.

- source/slang/slang-check-expr.cpp
- source/slang/slang-check-impl.h
- tests/language-feature/constants/static-array-indexing.slang
> Support constant folding for static array access.

- source/slang/slang-doc-markdown-writer.cpp
and fix associated type doc generation logic.
> Fix links in stdlib reference category landing page.

- source/slang-stdlib/CMakeLists.txt
Fixes https://github.com/shader-slang/slang/issues/5270
> Fix race condition for building stdlib headers

- CMakeLists.txt
- docs/building.md
- external/CMakeLists.txt
> Lower minimum CMake version to 3.22

- source/slang/slang-check-inheritance.cpp
- tests/bugs/gh-5140.slang
- tests/fcpw/LICENSE
- tests/fcpw/aggregate.slang
- tests/fcpw/bounding-volumes.slang
- tests/fcpw/bvh-node.slang
- tests/fcpw/bvh-refit.cs.slang
- tests/fcpw/bvh-traversal.cs.slang
- tests/fcpw/bvh.slang
- tests/fcpw/fcpw.slang
- tests/fcpw/geometry.slang
- tests/fcpw/interaction.slang
- tests/fcpw/math-constants.slang
- tests/fcpw/ray.slang
- tests/fcpw/transform.slang
- tools/slang-unit-test/unit-test-fcpw-compile.cpp
Add fcpw library to test suite.
Closes #5140.
> Fix type checking on generic extensions.

- source/slang/slang-emit-spirv.cpp
- tests/bugs/gh-3601.slang
- tests/spirv/pointer.slang
> Remove use of Variable Pointer capability.

- source/slang/hlsl.meta.slang
> Document derivative core module functions

- source/slang/core.meta.slang
- source/slang/hlsl.meta.slang
Closes https://github.com/shader-slang/slang/issues/5304
> Document the interfaces in the core module

- source/slang/slang-check-decl.cpp
- tests/language-server/robustness-8.slang
> Fix language server crash.

- source/slang/slang.cpp
> Fix incorrect debug assert in `getLanguagePrelude`.

- .github/workflows/format.yml
- .github/workflows/slash-command-dispatch.yml
- extras/formatting.sh
Comment on a PR with /format
Closes #5390
> Actions workflow to format code on command

- CMakeLists.txt
- cmake/FetchedSharedLibrary.cmake
- cmake/GitHubRelease.cmake
- cmake/Glob.cmake
- cmake/LLVM.cmake
- cmake/SlangTarget.cmake
- external/CMakeLists.txt
- prelude/CMakeLists.txt
- source/core/CMakeLists.txt
- source/slang-core-module/CMakeLists.txt
- source/slang-glslang/CMakeLists.txt
- source/slang-rt/CMakeLists.txt
- source/slang-wasm/CMakeLists.txt
- source/slang/CMakeLists.txt
- tools/CMakeLists.txt
> format cmake files

- .github/actions/format-setup/action.yml
- .github/workflows/benchmark.yml
- .github/workflows/ci.yml
- .github/workflows/compile-regression-test.yml
- .github/workflows/ensure-pr-label.yml
- .github/workflows/falcor-compiler-perf-test.yml
- .github/workflows/falcor-test.yml
- .github/workflows/push-benchmark-results.yml
- .github/workflows/release-linux-glibc-2-17.yml
- .github/workflows/release.yml
- .github/workflows/slash-command-dispatch.yml
- .github/workflows/vk-gl-cts-nightly.yml
- CMakePresets.json
- docs/scripts/release-note.sh
- external/build-llvm.sh
- external/bump-glslang.sh
- extras/formatting.sh
- extras/macos-notarize.json
- extras/macos-sign.json
Might as well,,,
uses prettier and shfmt
https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
and https://marketplace.visualstudio.com/items?itemName=mkhl.shfmt might be helpoful
> format yaml and json

- source/slang/slang-check-decl.cpp
- source/slang/slang-check-expr.cpp
- tests/language-feature/enums/enum-in-binding.slang
> Allow enum cases to be used in attribute arguments.

- source/slang/slang-ir-wgsl-legalize.cpp
- tests/compute/texture-simpler.slang
> Fix system semantics of SV_GroupIndex

- prelude/slang-cuda-prelude.h
- tests/cuda/make-matrix.slang
Fixes slang-torch issue [#21](https://github.com/shader-slang/slang-torch/issues/21).
> Fix CUDA prelude for makeMatrix

- .github/workflows/slash-command-dispatch.yml
Noticed it wasn't working for non-write access people
> lower permission level for format dispatch

- tools/render-test/render-test-main.cpp
Update slang-rhi to the latest version that includes a huge refactoring regarding command encoding.
The next step will be refactoring shader object handling.
> [slang-rhi] refactor command encoding

- docs/proposals/012-language-version-directive.md
This feature has been discussed within the Slang team, but has not previously been written up and shared.
> Proposal for a language version directive.

- docs/user-guide/02-conventional-features.md
> Fixed typo of type in user docs

- .github/workflows/benchmark.yml
- .github/workflows/ci.yml
- .github/workflows/compile-regression-test.yml
- .github/workflows/ensure-pr-label.yml
- .github/workflows/falcor-compiler-perf-test.yml
- .github/workflows/falcor-test.yml
- .github/workflows/push-benchmark-results.yml
- .github/workflows/release.yml
Recently we renamed a few files and directories and they should be reflected on the workflow YAML files.
- LICENCE is a typo of LICENSE.
- We recently created a new "LICENSES/"
- CONTRIBUTION.md was renamed to CONTRIBUTING.md
Closes #5686
> Update workflow YML files for renamed files

- cmake/FetchedSharedLibrary.cmake
Closes https://github.com/shader-slang/slang/issues/5706 and https://github.com/shader-slang/slang/issues/5657
> fetch and extract prebuilt deps lazily

- .github/workflows/ci.yml
I thought of this simple way of solving this issue, no need for any complex parent job or anything
> Run a do-nothing CI job for documentation changes

- source/slang/slang-ir-vk-invert-y.cpp
- tests/spirv/mesh-shader-invert-y.slang
> Make fvk-invert-y work on mesh shader ouptuts.

- .github/workflows/release-linux-glibc-2-17.yml
missed a file here https://github.com/shader-slang/slang/pull/5763
> Set prerelease and draft correctly for centos releases

- .github/workflows/release.yml
- CMakeLists.txt
- CMakePresets.json
- cmake/CompilerFlags.cmake
- cmake/SlangTarget.cmake
- docs/building.md
Work towards https://github.com/shader-slang/slang/issues/5724
> Split debug info for all targets

- source/slang/hlsl.meta.slang
- tests/spirv/sampler-shadow.slang
Closes [#5577](https://github.com/shader-slang/slang/issues/5577).
> Add Sampler*Shadow type aliases.

- source/slang/slang-lower-to-ir.cpp
- tests/diagnostics/recursive-type.slang
> Fix crash on recursive types.

- source/slang/slang-check-decl.cpp
- source/slang/slang-check-expr.cpp
- source/slang/slang-check-impl.h
- source/slang/slang-check-type.cpp
- source/slang/slang-check.h
- source/slang/slang-ir-lower-buffer-element-type.cpp
- tests/bugs/gh-3825.slang
- tests/spirv/existential-ptr.slang
- tests/spirv/ptr-member-func.slang
- tests/spirv/ptr-unsized-array-3.slang
- tests/spirv/ptr-unsized-array-4.slang
- tools/render-test/render-test-main.cpp
Closes [#5677](https://github.com/shader-slang/slang/issues/5677).
> Allow pointers to existential values.

- source/slang/slang-parser.cpp
- tests/language-feature/modules/typealias/lib.slang
- tests/language-feature/modules/typealias/main.slang
> Fix parsing logic of for loops' initial statement.

- source/core/slang-string-util.cpp
- source/slang/slang.cpp
- tests/language-feature/modules/gh-5799/Common/Common.slang
- tests/language-feature/modules/gh-5799/Common/Test.slang
- tests/language-feature/modules/gh-5799/HelloTriangleFS.slang
- tests/language-feature/modules/gh-5799/Scene/Scene.slang
- tools/slang-test/slang-test-main.cpp
> Fix a crash when search for files.

- source/slang/slang-check-decl.cpp
- tests/bugs/dynamic-interface-property.slang
> Create scope for synthesized property decl.

- CONTRIBUTING.md
This commit adds more detailed explanations on the PR process.
It also fixed a few typos and grammar mistakes identified by LLM.
Closes https://github.com/shader-slang/slang/issues/5730
> Add more details on PR process to CONTRIBUTING.md

- tools/gfx/vulkan/vk-device.cpp
The 'samplerInfo.magFilter' should match the 'desc.magFilter'.
> A small mistake.

- cmake/CompilerFlags.cmake
Hide some more symbols
affects https://github.com/shader-slang/slang/issues/5820 slightly
> Reduce export size with gcc

- include/slang.h
- source/compiler-core/windows/slang-win-visual-studio-util.cpp
- source/core/slang-allocator.h
- source/core/slang-platform.cpp
- source/core/slang-secure-crt.h
Partially sorts https://github.com/shader-slang/slang/issues/5843
> Correctly distinguish between windows and MSVC

- .github/workflows/check-toc.yml
- .github/workflows/regenerate-toc.yml
Closes https://github.com/shader-slang/slang/issues/5876
> install mono for toc generation

- source/slang/slang-emit-metal.cpp
- tests/metal/matrix-negate.slang
> Support matrix negation in metal backend.

- examples/reflection-api/README.md
- examples/reflection-api/main.cpp
- source/compiler-core/slang-artifact-associated-impl.h
- source/slang/slang-ir-metadata.cpp
- tools/slang-unit-test/unit-test-parameter-usage-reflection.cpp
> Fix metadata of register space and varying params.

- source/slang/slang-parser.cpp
- tests/diagnostics/invalid-namespace-nesting.slang
> Check decl nesting for namespaces.

- source/slang/slang-ir-loop-unroll.cpp
- tests/ir/loop-unroll-3.slang
> Fix crash during loop unrolling.

- source/slang/slang-check-decl.cpp
- source/slang/slang-syntax.cpp
- tests/autodiff/subscript.slang
> Check subscript/property accessor for differentiability.

- examples/wgpu-html5/README.md
- examples/wgpu-html5/build.py
- examples/wgpu-html5/example.js
- examples/wgpu-html5/index.html
- examples/wgpu-html5/shader.slang
- Add a simple example of using WebGPU and Slang together
https://github.com/shader-slang/slang/issues/5656
> Add a basic WebGPU example

- source/slang/slang-check-impl.h
- source/slang/slang-check-inheritance.cpp
- source/slang/slang-ir-legalize-types.cpp
- source/slang/slang-syntax.cpp
- tests/language-feature/interfaces/gh-5900.slang
> Fix `getInheritanceInfo` for `ExtractExistentialType`.

- source/compiler-core/slang-nvrtc-compiler.cpp
> update slang-rhi + fix nvrtc options

- source/slang/slang-ir-legalize-varying-params.cpp
- tests/cuda/optix-hit-attributes.slang
> Fix optix varying legalization.

- source/slang/slang-lower-to-ir.cpp
- tests/autodiff/generic-accessors.slang
Fixes: https://github.com/shader-slang/slang/issues/6117
> Fix interface requirement lowering for generic accessors

- source/slang/slang-ast-support-types.h
- source/slang/slang-check-decl.cpp
- source/slang/slang-diagnostic-defs.h
- source/slang/slang-syntax.cpp
- tests/diagnostics/generic-value-parameter-must-have-type.slang
> Improve error message on generic value parameters decls

- source/slang/slang-check-decl.cpp
- source/slang/slang-check-shader.cpp
- source/slang/slang-ir-translate-glsl-global-var.cpp
- source/slang/slang-lower-to-ir.cpp
- source/slang/slang-parameter-binding.cpp
- tests/glsl/in-layout.slang
> Properly plumbing layout for global varyings.

- CMakeLists.txt
- include/slang.h
- source/slang-glsl-module/CMakeLists.txt
- source/slang-glsl-module/slang-embedded-glsl-module.cpp
- source/slang-record-replay/util/emum-to-string.h
- source/slang/slang-api.cpp
- source/slang/slang-options.cpp
- source/slangc/CMakeLists.txt
> Distribute slang-glsl-module.bin in release packages.

- .github/workflows/release.yml
- CMakeLists.txt
- include/slang.h
- source/slang-glsl-module/CMakeLists.txt
- source/slang-glsl-module/slang-embedded-glsl-module.cpp
- source/slang-record-replay/util/emum-to-string.h
- source/slang/slang-api.cpp
- source/slang/slang-options.cpp
- source/slangc/CMakeLists.txt
> Include slang-glsl-module.dll in releases, for precompiled glsl module.

- source/slang/slang-parser.cpp
- tests/front-end/generic-disambiguate-module.slang
- tests/front-end/generic-disambiguate.slang
> Fix parsing of nested generic app.

- tools/CMakeLists.txt
Closes https://github.com/shader-slang/slang/issues/6144
> Correct NVAPI include

- .github/workflows/vk-gl-cts-nightly.yml
Closes https://github.com/shader-slang/slang/issues/6245
> Use 0.0.7 version of VK-GL-CTS-for-Slang on nightly CTS CI

- .github/workflows/falcor-test.yml
This is a follow-up to PR #6058, where we switched to Falcor-new now we will switch back to Falcor.
> Switch back to Falcor

- docs/proposals/020-stage-switch.md
- source/slang/glsl.meta.slang
- source/slang/slang-ast-stmt.h
- source/slang/slang-capability.cpp
- source/slang/slang-capability.h
- source/slang/slang-check-decl.cpp
- source/slang/slang-check-stmt.cpp
- source/slang/slang-diagnostic-defs.h
- source/slang/slang-emit.cpp
- source/slang/slang-ir-autodiff-fwd.cpp
- source/slang/slang-ir-inst-defs.h
- source/slang/slang-ir-insts.h
- source/slang/slang-ir-specialize-stage-switch.cpp
- source/slang/slang-ir-specialize-stage-switch.h
- source/slang/slang-ir.cpp
- source/slang/slang-lower-to-ir.cpp
- source/slang/slang-parser.cpp
- tests/language-feature/stage-switch.slang
- tests/spirv/primitive-id-2.slang
Closes #6007.
Closes #6270.
Fixes #3354.
> Support stage_switch.

- CMakePresets.json
- source/slang/slang-reflection-api.cpp
- source/slang/slang.cpp
- tools/slang-unit-test/unit-test-function-reflection.cpp
> Reflection Fixes.

- tools/gfx/metal/metal-device.cpp
- tools/gfx/metal/metal-fence.cpp
- tools/gfx/metal/metal-fence.h
- tools/gfx/metal/metal-shader-object.cpp
- implement waitForFences for metal backend
- fix a bug that it misses clear the entryPoints when initializing RootShaderObject
> Fix metal issue

- source/slang/slang-preprocessor.cpp
Handle case where VA_ARGS is empty.
> slang: Fix empty VARARGS issue(#6332)

- source/slang/hlsl.meta.slang
Closes https://github.com/shader-slang/slang/issues/6389
> Add two DXC implementation for CoopVec

- source/slang/slang-ir-legalize-types.cpp
Closes https://github.com/shader-slang/slang/issues/5751
> Fix loading empty structs from structured buffers

- source/slang/slang-check-decl.cpp
- source/slang/slang-emit-spirv.cpp
- tests/bugs/gh-6380-atomic-in-struct.slang
> Fix regression when using Atomic<T> in struct.

- source/slang/slang-compiler-options.cpp
This helps to address issue #4760.
> Fix option set serialization bug

- tools/gfx-unit-test/link-time-type-layout-cache.cpp
Closes https://github.com/shader-slang/slang/issues/6558
> test for link type layout caching

- source/slang/slang-diagnostic-defs.h
- source/slang/slang-emit.cpp
- tests/compute/integer-matrix-diagnostic.slang
- tests/compute/integer-vector-diagnostic.slang
- tests/compute/matrix-layout.hlsl
- Add the diagnostic messages, and code to emit them
- Add some tests
This helps to address issue https://github.com/shader-slang/slang/issues/6183.
> Add error diagnostic vectors and matrices with disallowed element types

- .github/workflows/ci.yml
Closes https://github.com/shader-slang/slang/issues/6727
> Fix the broken workflow for linux/release/gcc/wasm

- source/slang/slang-check-decl.cpp
- source/slang/slang-diagnostic-defs.h
- tests/modules/extension-warning.slang
- tests/modules/implementing-with-ext.slang
Closes https://github.com/shader-slang/slang/issues/5995
> warn when the user puts a file extension in an implementing directive

- tools/benchmark/compile.py
This commit resolves two issues in the benchmark script:
1. Fixed nested f-string syntax error that was causing CI failures (fixes #6772)
2. Fixed key access error handling for timing dictionary
The nested f-string was causing a syntax error in CI, and the proper fix is to create the key variable separately before using it. Also improved error handling for cases where compilation fails and timing data might be missing.
Fixes: #6772
> Fix benchmark/compile.py nested f-string and deprecated constant issues

- source/slang/slang-reflection-json.cpp
- tests/reflection/attribute.slang
- tests/reflection/attribute.slang.expected
Fixes #6794
Also fixes json formatting for user attributes.
> Fix User Attribute string reflection

- .github/workflows/ci.yml
- .github/workflows/release.yml
- source/slang/slang-check-decl.cpp
- source/slang/slang-check-inheritance.cpp
close https://github.com/shader-slang/slang/issues/6824
> Use the latest Ubuntu version not specific old version

- source/slang/slang-ir-glsl-legalize.cpp
- tests/spirv/sv_instance.slang
Closes #6847. A require glsl460 is missing.
> Fix SV_InstanceID for emit-spirv-via-glsl path

- source/slang/slang-emit-glsl.cpp
- source/slang/slang-emit-spirv.cpp
- tests/wgsl/write-only-texture.slang
> Emit SPIRV NonReadable decoration for WTexture*

- source/slang/slang-capabilities.capdef
- source/slang/slang-emit-hlsl.cpp
- tests/compute/logic-no-short-circuit-evaluation.slang
Closes https://github.com/shader-slang/slang/issues/6968
> Add a new capability hlsl_2018 that avoid using select/and/or

- source/slang/glsl.meta.slang
- source/slang/hlsl.meta.slang
- source/slang/slang-ir-extract-value-from-type.cpp
- tests/glsl/interger_pack.slang
Add unpack8, unpack16 and pack32 intrinsics to glsl.
Close #6949.
Also fix the issue in lowering `bitcast`.
close #7007.
> Add interger pack/unpack intrinsic to glsl

- source/slang/slang-ir-spirv-legalize.cpp
- tests/language-feature/bitfield/bitfield-insert-extract-non32bit.slang
> Ensure to emit 32-bit type for bitfield operations for SPIRV

- source/slang/slang-emit-cpp.cpp
- tests/cuda/compile-to-cuda.slang
> Fix RWStructuredBuffer emission

- CMakeLists.txt
- tools/CMakeLists.txt
- tools/slang-fiddle/slang-fiddle-lua.cpp
Update the build to allow setting user-specific path for the external module lua.
> Update build to allow setting external lua path

- source/slang/diff.meta.slang
- source/slang/hlsl.meta.slang
- tests/autodiff-dstdlib/dstdlib-inverse-hyperbolic.slang
Adds derivatives for `asinh`, `acosh` and `atanh`. They are defined [here](https://en.wikipedia.org/wiki/Inverse_hyperbolic_functions#Derivatives).
> Add inverse hyperbolic derivatives

- source/slang/slang-check-decl.cpp
- source/slang/slang-diagnostic-defs.h
- tests/diagnostics/inheritance-1.slang
- tests/diagnostics/inheritance-2.slang
- tests/hlsl-intrinsic/size-of/align-of.slang
- tests/hlsl-intrinsic/size-of/size-of.slang
- tests/initializer-list/struct-inherit.slang
- tests/language-feature/inheritance/derived-struct-init-list.slang
- tests/language-feature/inheritance/struct-inherit-interface-requirement.slang
- tests/language-feature/inheritance/struct-inheritance-imported.slang
- tests/language-feature/inheritance/struct-inheritance.slang
- tests/language-feature/initializer-lists/inheritance-generic.slang
- tests/language-feature/struct-field-initializers/struct-field-initializer-extension-inheritance.slang
- tests/language-feature/struct-field-initializers/struct-field-initializer-extension.slang
- tests/language-feature/struct-field-initializers/struct-field-initializer-inherited-chain.slang
- tests/language-feature/struct-field-initializers/struct-field-initializer-init-inheritance-write-to-same.slang
- tests/language-feature/struct-field-initializers/struct-field-initializer-static.slang
> Diagnose on use of struct inheritance.

- .github/workflows/ci.yml
Related to
- https://github.com/shader-slang/slang/issues/5054
- https://github.com/shader-slang/slang/issues/7026
> Print CUDA version on CI servers

- source/slang/slang-ir-autodiff-cfg-norm.cpp
close #4187.
This PR makes some cleanup on the variable name.
During CFG normalization, we introduce a variable to replace the `break`, but the variable indicates that we should continue running the loop if it's `true`, and break the loop if it's `false`.
Previously we named this variable as 'breakVar', which is opposite to its purpose. So rename it to `keepRunning`.
> AD cleanup for 'break' replacement

- source/core/slang-signal.cpp
- source/slang/slang-ir.h
- source/slang/slang-serialize-ast.cpp
- source/slang/slang-serialize-container.cpp
- source/slang/slang-serialize-container.h
- source/slang/slang-serialize-ir-types.h
- source/slang/slang-serialize-ir.cpp
- source/slang/slang-serialize-ir.h
- source/slang/slang-serialize-source-loc.h
- source/slang/slang-serialize-types.h
- source/slang/slang.cpp
Closes https://github.com/shader-slang/slang/issues/7186
Closes https://github.com/shader-slang/slang/issues/7187 
Closes https://github.com/shader-slang/slang/issues/7188
> Use fossil for IR serialization

- docs/command-line-slangc-reference.md
- source/slang/slang-options.cpp
> Fix `slangc --help` text for `-reflection-json`

- examples/example-base/example-base.cpp
Fixes: https://github.com/shader-slang/slang/issues/4773
> Configure the surface with right format

- source/slang/slang-ir-metal-legalize.cpp
- tests/metal/texture-store-vector.slang
Fixes: https://github.com/shader-slang/slang/issues/7199
> Fix metal segfault by check vectorValue before accessing

- docs/design/ir-instruction-definition.md
- source/slang/slang-ir-insts.lua
Closes https://github.com/shader-slang/slang/issues/7193
> Document IR changes

- examples/example-base/example-base.cpp
- examples/example-base/example-base.h
- examples/example-base/test-base.cpp
- examples/example-base/test-base.h
- examples/model-viewer/main.cpp
- examples/platform-test/main.cpp
- examples/ray-tracing-pipeline/main.cpp
- examples/ray-tracing/main.cpp
- examples/shader-toy/main.cpp
- examples/triangle/main.cpp
Add -h/--help flag to show usage information.
Add -api flag to select rendering API.
> Add command-line arguments to examples

- tests/metal/metal-pointer-uniform.slang
Adding a test for:
- https://github.com/shader-slang/slang/issues/7623
The issue was already resolved by another PR
- https://github.com/shader-slang/slang/pull/7759
> Add test for Metal pointer uniform parameter

- source/slang/slang-diagnostic-defs.h
- source/slang/slang-emit.cpp
- source/slang/slang-ir-detect-uninitialized-resources.cpp
- source/slang/slang-ir-detect-uninitialized-resources.h
- tests/diagnostics/uninitialized-resource-field.slang
Closes https://github.com/shader-slang/slang/issues/3386
> Detect uses of uninitialized resource fields

- .github/workflows/ci.yml
Disabling the debug-layers until resolving the issue
- https://github.com/shader-slang/slang/issues/7965
> Disable debug-layers temporarlily on CI

- tests/compute/assoctype-nested-lookup.slang
- tests/compute/byte-address-buffer-align-error.slang
- tests/compute/dynamic-dispatch-15.slang
- tests/compute/dynamic-dispatch-16.slang
- tests/compute/dynamic-dispatch-17.slang
- tests/compute/dynamic-dispatch-18.slang
- tests/compute/dynamic-dispatch-19.slang
- tests/compute/nested-assoc-types.slang
- tests/compute/pack-any-value-8bit.slang
- tests/compute/spirv-multisampled-array-texel-pointer-atomic.slang
- tests/compute/write-structured-buffer-field.slang
Enable those what are passing already
> Enable compute/ dir which passes

- source/slang/slang-core-module-textures.cpp
- tests/cross-compile/vk-sampler-getdimension.slang
Closes https://github.com/shader-slang/slang/issues/8025
> Fix GetDimensions to use mipLevel for SPIRV

- source/compiler-core/slang-artifact-associated-impl.h
- source/slang/slang-ir-lower-dynamic-resource-heap.cpp
- tests/spirv/descriptor-heap-space.slang
> Fix unused space discovery for bindless heap.

- source/slang/slang-check-decl.cpp
- source/slang/slang-check-impl.h
- source/slang/slang-diagnostic-defs.h
- tests/diagnostics/array-parameterblock.slang
Closes https://github.com/shader-slang/slang/issues/5750
> Diagnose on array of parameterblock instead of asserting

- .github/workflows/ci.yml
Fixes https://github.com/shader-slang/slang/issues/8098
> Be conservative for checking if PR is doc changes only

- tools/gfx/cuda/cuda-device.cpp
- tools/gfx/cuda/cuda-helper-functions.h
Update cuda context creation to support both cuda 12 and cuda 13.
> Update cuda context creation to support cuda 13

- source/slang/slang-ast-base.h
- source/slang/slang-check-decl.cpp
- source/slang/slang-check-impl.h
- source/slang/slang-diagnostic-defs.h
- source/slang/slang-emit.cpp
- source/slang/slang-ir-validate.cpp
- source/slang/slang-ir-validate.h
- source/slang/slang-ir.cpp
- source/slang/slang-ir.h
- tests/diagnostics/recursive-type.slang
- tests/diagnostics/structuredbuffer-resource-static.slang
- tests/diagnostics/structuredbuffer-resource-struct-array.slang
- tests/diagnostics/structuredbuffer-resource-struct-recursive-mutual.slang
- tests/diagnostics/structuredbuffer-resource-struct-recursive.slang
- tests/diagnostics/structuredbuffer-resource-struct.slang
- tests/diagnostics/structuredbuffer-resource.slang
closes https://github.com/shader-slang/slang/issues/3313
> Diagnose on structured buffers containing resources

- .github/workflows/vk-gl-cts-nightly.yml
- Enable ccache in slang bulid for CTS test
- Allow manual CI dispatch
> Enable ccache in slang bulid for CTS test

- docs/update_spirv.md
It turned out that SPIRV-Headers update has to be done after building SPIRV-Tools
> Revise SPIRV-Headers update instructions in documentation

- .github/workflows/ci-slang-test.yml
Related to https://github.com/shader-slang/slang/issues/8497
> Reduce the maxprocesses to 3 for slangpy test
